### ISSUE TITLE
Remove Email Identification?

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#1000]
Its currently not working on the windows installer and thus should be removed?

**Comment by PicassoCT** [comment]
Im super confused right now.
I downloaded the source- and found email registration to be removed.
springdev\springlobby\springlobby\src\gui\connectwindow.cpp

```

	// Register page
	wxBoxSizer* m_register_sizer = new wxBoxSizer( wxVERTICAL );

	wxBoxSizer* m_regnick_sizer = new wxBoxSizer( wxHORIZONTAL );

	m_regnick_lbl = new wxStaticText( m_register_tab, wxID_ANY, _("Nickname"), wxDefaultPosition, wxDefaultSize, 0 );
	m_regnick_sizer->Add( m_regnick_lbl, 1, wxALL | wxALIGN_CENTER_VERTICAL, 4 );

	m_regnick_text = new wxTextCtrl( m_register_tab, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );
	m_regnick_sizer->Add( m_regnick_text, 1, wxALL, 4 );

	m_register_sizer->Add( m_regnick_sizer, 0, wxEXPAND, 4 );

	m_regpass_sep = new wxStaticLine( m_register_tab, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL );
	m_register_sizer->Add( m_regpass_sep, 0, wxALL|wxEXPAND, 4 );

	wxBoxSizer* m_regpass1_sizer = new wxBoxSizer( wxHORIZONTAL );

	m_regpass1_lbl = new wxStaticText( m_register_tab, wxID_ANY, _("Password"), wxDefaultPosition, wxDefaultSize, 0 );
	m_regpass1_sizer->Add( m_regpass1_lbl, 1, wxALL | wxALIGN_CENTER_VERTICAL, 4 );

	m_regpass1_text = new wxTextCtrl( m_register_tab, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD );
	m_regpass1_sizer->Add( m_regpass1_text, 1, wxALL, 4 );

	m_register_sizer->Add( m_regpass1_sizer, 0, wxEXPAND, 4 );

	wxBoxSizer* m_regpass1_sizer1 = new wxBoxSizer( wxHORIZONTAL );
```

I then checked the install. Which had in the help-> about the version 2.70
I then uninstalld manually what was registered as 2.73.
Now its Registered as 2.73. But still shows the email login even though its not in the source? Is the prepackaged build 2.73 outdated?
The problem is, i recommend springlobby to the few who want tot test my game. The login has to work :D (Panicked Pica Noises)

**Comment by abma** [comment]
so, now i'm confused whats this ticket about?

the controls of the connectwindow are created there:

https://github.com/springlobby/springlobby/blob/master/src/gui/wxfb/generated/ConnectWindowBase.cpp

**Comment by PicassoCT** [comment]
I tried to reproduce  a problem from a friend that couldn't sign in. He never received the email when registrating. Merry X-Mass by the way :D

**Comment by PicassoCT** [comment]
Due to them being on windows, i have no idea were springlobby logs its problems on that platform.

**Comment by PicassoCT** [comment]
I tryied to run it with with springlobby.exe -l5 to print out the log to console on windows. Nothing comes out

**Comment by PicassoCT** [comment]
So i watched my friend trying to run MOSAIC today via springlobby.

He is on Win10. Springlobby was the most recent version. 
The Lobby did not start downloading engine, map or game.

Friend installed the spring engine manually. It did not work initially. He got it working by continously joining other servers.
Lots of curl erorrs.

**Comment by PicassoCT** [comment]
So it turns out, it fails for some "temporary email providers".. silently..
