### ISSUE TITLE
not all translations are used

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#111]
idk why, for example 

Server->Connect:

"Note: If you do not have an account, you\n can register one for free on the\n\"Register\" tab."

isn't translated:

http://springrts.fr/telechargements/les-clients-de-jeu/spring-lobby/
https://github.com/springlobby/springlobby/blob/master/src/connectwindow.cpp#L85

**Comment by Usaga** [comment]
This is not a bug, sometimes it was because of using _T() instead of _() in sources, sometimes because of "FUZZY" mark at phrases to be translated in *.po files... Think this issue may be closed.

**Comment by specing** [comment]
Abma is this fixed now? Most translations seem to work now.

**Comment by abma** [comment]
yep, all translations should work again. a lot of them got lost / were invalid...
