### ISSUE TITLE
add error some message when file to download can't be found / dl failed

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#125]
We wanted to test spring but me(decay) and kixu - faced issues.

1) We selected battle with this version and pressed "join" and we selected "yes, download engine" in modal window - nothing happened

2) We downloaded that engine using "search" in download tab

3) Still can't join battle after download finished

4) There are no "95.0.1-115" engine in engines list (on preferences)

5) If we set manually path to engine in preferences - lobby crashes

**Comment by abma** [comment]
is fixed/implemented...
