### ISSUE TITLE
Same game shown as sync and unsync (depending on selected default engine?)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#152]
See screenshot:
Two rooms with same mod, yet one is shown as unsync while the other is not.

I was in battleroom and joined midgame as spectator - everything worked.
After game ended, it showed me in battleroom as unsync: Does not make sense since I had just sucessfully watched the game.

Changing the default engine to 96 from 95 made it show as sync in battleroom.

1) It seems default-entry is used for sync checking, instead of what engine the room really uses?

2) There should be 3 sync rows in battle list: game, map, engine

![bla](https://f.cloud.github.com/assets/3044855/1896334/c2abbd46-7b96-11e3-981b-37035d87e020.png)

**Comment by abma** [comment]
should be fixed in current dev version of spring. there it doesn't check if hash matches it only checks if map is present. (using a different unitsync version can change the hash)
