### ISSUE TITLE
No more horizontal scrollbars when resizing!

### ISSUE THREAD

**Issue by ForbodingAngel** [springlobby/springlobby#159]
The lobby needs to resize itself gracefully if at all possible. I realize that this is a murky request, but I trust that you understand what I mean.

If I go from fullscreen to windowed, the chat list might get a horizontal scrollbar, regardless of the fact that there is plenty of space on the chat area where it could have expanded.

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/abd28b1f8c096c9133929ac4c93ab2d30f09a2d1
