### ISSUE TITLE
Add a simple method for gamedevs to add a channel to be joined automatically (and possibly battle filter)

### ISSUE THREAD

**Issue by ForbodingAngel** [springlobby/springlobby#162]
Preferably not a springlobby conf. Just something super simple. Join this channel (on top of the default ones), and optionally, only show battles of this game.

The idea being to distribute springlobby as a standalone app and just do minor tailoring in order to make it easy for newbies who are looking for a specific game.

I dunno, maybe springlobby.conf is the only nice way to do it. If that is the case, perhaps add an example conf (allowing channel/battle filtering) to the archive for gamedevs to use as a template? Preferably not including anything that would screw with default, and easily changeable by the end user.

**Comment by specing** [comment]
Game bundles -> #818
