### ISSUE TITLE
Exceptions on WX-3.0.0 + OS X 10.9.2

### ISSUE THREAD

**Issue by spitfire** [springlobby/springlobby#207]
As mentioned in https://github.com/springlobby/springlobby/issues/206 with commit 6c223ac I get 2 exceptions before app crashes - I can "bypass them"

1st warning/stacktrace

../src/osx/imaglist.cpp(152): assert "Assert failure" failed in GetIcon(): cannot convert from bitmap to icon
Collecting stack trace information, please wait... --
Warning: /usr/bin/atos is moving and will be removed from a future OS X release.
It is now available in the Xcode developer tools to be invoked via: `xcrun atos`
To silence this warning, pass the '-d' command-line flag to this tool.
 --
Process 16249 stopped
* thread #1: tid = 0xc983, 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
    frame #0: 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10
libsystem_kernel.dylib`__kill + 10:
-> 0x7fff98cc4292:  jae    0x7fff98cc429c            ; __kill + 20
   0x7fff98cc4294:  movq   %rax, %rdi
   0x7fff98cc4297:  jmpq   0x7fff98cc1175            ; cerror_nocancel
   0x7fff98cc429c:  ret
(lldb) bt
* thread #1: tid = 0xc983, 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
  * frame #0: 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10
    frame #1: 0x00000001013e6aa8 libwx_osx_cocoau_core-3.0.dylib`wxGUIAppTraitsBase::ShowAssertDialog(wxString const&) + 300
    frame #2: 0x000000010186062c libwx_baseu-3.0.dylib`ShowAssertDialog(wxString const&, int, wxString const&, wxString const&, wxString const&, wxAppTraits*) + 648
    frame #3: 0x00000001018602c8 libwx_baseu-3.0.dylib`wxAppConsoleBase::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) + 264
    frame #4: 0x0000000101860ebb libwx_baseu-3.0.dylib`wxDefaultAssertHandler(wxString const&, int, wxString const&, wxString const&, wxString const&) + 268
    frame #5: 0x000000010185ee16 libwx_baseu-3.0.dylib`wxOnAssert(char const*, int, char const*, char const*, wchar_t const*) + 160
    frame #6: 0x0000000101332c66 libwx_osx_cocoau_core-3.0.dylib`wxImageList::GetIcon(int) const + 162
    frame #7: 0x000000010027c89a springlobby`MainWindow(this=0x0000000104030a00) + 554 at mainwindow.cpp:127
    frame #8: 0x000000010027c665 springlobby`MainWindow(this=0x0000000104030a00) + 21 at mainwindow.cpp:230
    frame #9: 0x0000000100372222 springlobby`Ui(this=0x0000000109d64a20) + 258 at ui.cpp:94
    frame #10: 0x0000000100372115 springlobby`Ui(this=0x0000000109d64a20) + 21 at ui.cpp:100
    frame #11: 0x000000010037fc7b springlobby`GlobalObjectHolder(this=0x000000010090ebb8, (null)=<unavailable>) + 251 at globalsmanager.h:70
    frame #12: 0x000000010037f4e5 springlobby`GlobalObjectHolder(this=0x000000010090ebb8, (null)=<unavailable>) + 21 at globalsmanager.h:74
    frame #13: 0x000000010037205b springlobby`ui() + 251 at ui.cpp:79
    frame #14: 0x0000000100142974 springlobby`NotificationManager(this=0x00000001022d8c70) + 132 at notificationmanager.cpp:44
    frame #15: 0x00000001001428e5 springlobby`NotificationManager(this=0x00000001022d8c70) + 21 at notificationmanager.cpp:50
    frame #16: 0x00000001001450db springlobby`GlobalObjectHolder(this=0x000000010090c388, (null)=<unavailable>) + 251 at globalsmanager.h:70
    frame #17: 0x0000000100143cb5 springlobby`GlobalObjectHolder(this=0x000000010090c388, (null)=<unavailable>) + 21 at globalsmanager.h:74
    frame #18: 0x000000010014282c springlobby`notificationManager() + 188 at notificationmanager.cpp:38
    frame #19: 0x0000000100339f9c springlobby`SpringLobbyApp::OnInit(this=0x000000010209d090) + 2572 at springlobbyapp.cpp:158
    frame #20: 0x000000010132ea23 libwx_osx_cocoau_core-3.0.dylib`wxApp::CallOnInit() + 65
    frame #21: 0x00000001018bf166 libwx_baseu-3.0.dylib`wxEntry(int&, wchar_t**) + 47
    frame #22: 0x00000001003393a6 springlobby`main(argc=1, argv=0x00007fff5fbffb68) + 38 at springlobbyapp.cpp:63

2nd warning/backtrace

../src/common/iconbndl.cpp(293): assert "icon.IsOk()" failed in AddIcon(): invalid icon
Collecting stack trace information, please wait... --
Warning: /usr/bin/atos is moving and will be removed from a future OS X release.
It is now available in the Xcode developer tools to be invoked via: `xcrun atos`
To silence this warning, pass the '-d' command-line flag to this tool.
 --
Process 16266 stopped
* thread #1: tid = 0xcd81, 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
    frame #0: 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10
libsystem_kernel.dylib`__kill + 10:
-> 0x7fff98cc4292:  jae    0x7fff98cc429c            ; __kill + 20
   0x7fff98cc4294:  movq   %rax, %rdi
   0x7fff98cc4297:  jmpq   0x7fff98cc1175            ; cerror_nocancel
   0x7fff98cc429c:  ret
(lldb) bt
* thread #1: tid = 0xcd81, 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
  * frame #0: 0x00007fff98cc4292 libsystem_kernel.dylib`__kill + 10
    frame #1: 0x00000001013e6aa8 libwx_osx_cocoau_core-3.0.dylib`wxGUIAppTraitsBase::ShowAssertDialog(wxString const&) + 300
    frame #2: 0x000000010186062c libwx_baseu-3.0.dylib`ShowAssertDialog(wxString const&, int, wxString const&, wxString const&, wxString const&, wxAppTraits*) + 648
    frame #3: 0x00000001018602c8 libwx_baseu-3.0.dylib`wxAppConsoleBase::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) + 264
    frame #4: 0x0000000101860ebb libwx_baseu-3.0.dylib`wxDefaultAssertHandler(wxString const&, int, wxString const&, wxString const&, wxString const&) + 268
    frame #5: 0x000000010185ee16 libwx_baseu-3.0.dylib`wxOnAssert(char const*, int, char const*, char const*, wchar_t const*) + 160
    frame #6: 0x0000000101442156 libwx_osx_cocoau_core-3.0.dylib`wxIconBundle::AddIcon(wxIcon const&) + 234
    frame #7: 0x000000010144203e libwx_osx_cocoau_core-3.0.dylib`wxIconBundle::wxIconBundle(wxIcon const&) + 40
    frame #8: 0x000000010027c8b2 springlobby`MainWindow(this=0x0000000104009200) + 578 at mainwindow.cpp:127
    frame #9: 0x000000010027c665 springlobby`MainWindow(this=0x0000000104009200) + 21 at mainwindow.cpp:230
    frame #10: 0x0000000100372222 springlobby`Ui(this=0x00000001024a2690) + 258 at ui.cpp:94
    frame #11: 0x0000000100372115 springlobby`Ui(this=0x00000001024a2690) + 21 at ui.cpp:100
    frame #12: 0x000000010037fc7b springlobby`GlobalObjectHolder(this=0x000000010090ebb8, (null)=<unavailable>) + 251 at globalsmanager.h:70
    frame #13: 0x000000010037f4e5 springlobby`GlobalObjectHolder(this=0x000000010090ebb8, (null)=<unavailable>) + 21 at globalsmanager.h:74
    frame #14: 0x000000010037205b springlobby`ui() + 251 at ui.cpp:79
    frame #15: 0x0000000100142974 springlobby`NotificationManager(this=0x00000001024a1990) + 132 at notificationmanager.cpp:44
    frame #16: 0x00000001001428e5 springlobby`NotificationManager(this=0x00000001024a1990) + 21 at notificationmanager.cpp:50
    frame #17: 0x00000001001450db springlobby`GlobalObjectHolder(this=0x000000010090c388, (null)=<unavailable>) + 251 at globalsmanager.h:70
    frame #18: 0x0000000100143cb5 springlobby`GlobalObjectHolder(this=0x000000010090c388, (null)=<unavailable>) + 21 at globalsmanager.h:74
    frame #19: 0x000000010014282c springlobby`notificationManager() + 188 at notificationmanager.cpp:38
    frame #20: 0x0000000100339f9c springlobby`SpringLobbyApp::OnInit(this=0x000000010209b690) + 2572 at springlobbyapp.cpp:158
    frame #21: 0x000000010132ea23 libwx_osx_cocoau_core-3.0.dylib`wxApp::CallOnInit() + 65
    frame #22: 0x00000001018bf166 libwx_baseu-3.0.dylib`wxEntry(int&, wchar_t**) + 47
    frame #23: 0x00000001003393a6 springlobby`main(argc=1, argv=0x00007fff5fbffb68) + 38 at springlobbyapp.cpp:63

**Comment by abma** [comment]
please test again with 0.214+
