### ISSUE TITLE
cancel/ok button missing in channel-list & spring settings

### ISSUE THREAD

**Issue by renemilk** [springlobby/springlobby#23]
This has a lengthy discussion and images...
http://projects.springlobby.info/issues/1677

other reported stuff is imo its a problem of the desktop/windowmanager system (=won't fix)

**Comment by renemilk** [comment]
closing this since referenced discussion is gone

**Comment by abma** [comment]
without discussion i see this is still an issue, all "popup" dialogs should have a button :-)

**Comment by specing** [comment]
Why are they gone? Where are they gone?

**Comment by abma** [comment]
the old issues / bug tracker was deleted

**Comment by specing** [comment]
Why was it not saved anywhere? Why was it deleted?

**Comment by abma** [comment]
this is no chat

**Comment by abma** [comment]
#877
