### ISSUE TITLE
show download status / error when update is downloaded

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#250]
1) When updating via "check for new version" menu, the lobby broke:
There was two message boxes:
"Invalid zip file [ok]"
and
"springlobby_updater.exe nicht gefunden" (=not found)
File springlobby_updater.exe exists.

then the lobby closed.

2) After first  restart got this "message":
![sl warning](https://cloud.githubusercontent.com/assets/3044855/3538947/3de2893c-0836-11e4-935a-6cdc72590ba5.jpg)

3) After new restarts the lobby seemed to work okay but:
Clicking [ok] in dialog "Your version is 01.955, current is 0.196. update?" would now simply do nothing.

4) Suddendly a small window with progress bar come up for 2 seconds, then lobby did this:
![sl error 0195 to 0196](https://cloud.githubusercontent.com/assets/3044855/3538918/efe75a3c-0835-11e4-9c49-0908960f1006.jpg)
(this time only "warning" not "error" as in prev picture)
and closed

5) After restart the lobby is now supposedly at v0.196
But problem is that none of the error messages were really helpful.
(edited typo: not->now)

**Comment by abma** [comment]
status is now shown
