### ISSUE TITLE
Some replay list features

### ISSUE THREAD

**Issue by MajBoredom** [springlobby/springlobby#269]
I'd like to add some enhanced query / filter options to the replays panel. For example, I think I could construct a fairly lightweight but open-ended query interface that would let you create queries like:

"replays of games that I played in"
"replays of games that I played against Foo"
"replays of games that I played on same allyteam as Bar"
"replays of games that I won against Fub"

...etc.

The only caveat is that I'd like to use a lightweight embedded database like sqlite to build the index. The index file would sit in the demos/ directory with the replay files themselves. It is a very lightweight file-based database, however it does mean adding another dependency to the project. So I wanted to raise the issue here and talk about it before trying anything.

Of course, I would also look at fixing the replay list beforehand.

**Comment by abma** [comment]
i don't see this happen...
