### ISSUE TITLE
reenable sound support on windows / wait for alure to be fixed

### ISSUE THREAD

**Issue by renemilk** [springlobby/springlobby#27]
alure 1.2 crashes:
http://paste.springfiles.com/view/c989d189

wait until alure is fixed upstream and reenable it:

(revert https://github.com/abma/springlobby/commit/83380bc1124fa8af4cde10a8fe31d4d1c00899a2 )

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/6ef22f48e54d9def828f9bdcdad941f9c7ad2070
