### ISSUE TITLE
Springlobby doesn't show an error when download dir isn't writeable

### ISSUE THREAD

**Issue by springjools** [springlobby/springlobby#283]
When I try to join a battle where I don't have the map or the gmae, SL ask me to download them. But the download finishes instantly and SL asks me the same question again. Here is a picture:

![sl1](https://cloud.githubusercontent.com/assets/5911982/4272025/653ba3ba-3cde-11e4-84cf-bf49469ab833.png)

Here is the output from System Info:

![sl2](https://cloud.githubusercontent.com/assets/5911982/4272067/bc6ac4ae-3cde-11e4-9485-d56242b57a68.png)

It's probably due to incorrect download dir. How do set it to a correct one?

**Comment by abma** [comment]
please test again with 0.214+ it should show an error now (if not, its now very easy to solve)
