### ISSUE TITLE
associate .sdf files with springlobby?

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#298]
Spring 97 changelog:
"don't associate .sdf with spring.exe any more"

Maybe .sdf files could now be associated with lobbies, for ex. SL
On doubleclicking the .sdf file the lobby would then download all files nessecary to watch the reply and play it.

At the moment players have to either move downloaded .sdf files into their demos\ folder or manually select the correct spring version. (via drag&drop "Open file with program.." dialog), both is not userfriendly.

**Comment by abma** [comment]
i don't see anyone implementing this:

- requires an installer
- requires file association
- requires support for command line parameter of .sdf
