### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#303]
errors should be visible somehow in gui and not console only.

especially unitsync / write errors

see #300 #299 #125 for example

**Comment by Usaga** [comment]
How about to replace <wx/log.h> with your own wxLogError and wxLogWarning (and so on) implementation? It will give ability to show errors to user with GUI dialogs

**Comment by abma** [comment]
the code to do so is basicly there.

https://github.com/springlobby/springlobby/blob/master/src/log.cpp#L50

it just needs some love :-)

**Comment by Usaga** [comment]
Hmm. I don`t get it. After some superficially studying wxLogXXX functions I understood they show messages directly to user with GUI boxes by default. But this is not what you want? Or you meant not all errors are been catching this way?

**Comment by abma** [comment]
(atm?!) to many errors happens, if this is enabled user would be annoyed about clicking ok to accept things he can't change.

imo there should be a setting which allows to enable this gui dialog to see all recent errors/warnings/messages for debugging.

**Comment by Usaga** [comment]
Holy Horns! I just activated displaying error... There is really a lot of them. But there is much more of simple log messages (user xxx added, password accepted and so on) then errors. Is it really so necessary to have so much? And may be it is worth to comment out most of them(and errors too) leaving only most critical ones, then just ignore it all and build another logging subsystem that will do just the same work?..

**Comment by abma** [comment]
wxLog() allows to filter messages by category, etc imo this should be used. also some log levels used are in many cases wrong (i.e. debug uses error, etcetc)

**Comment by Usaga** [comment]
So it looks like the best way to do it is to add new menu item in springlobby`s main menu that will raise logwindow with information redirected from wxLogXXX except wxLogError and wxFatalError that will be shown to user directly. What do you think?

**Comment by abma** [comment]
seems i forgot to respond. as it works great, thanks a lot! :)
