### ISSUE TITLE
OSX: crash when joining a battle in  boost::filesystem::path::operator/=

### ISSUE THREAD

**Issue by moobyfr** [springlobby/springlobby#310]
while trying to join a battle, (having the game, but not the map for the moment), answering yes for downloading the map, SL crash.
the log says:
21:34:20: Error: /Volumes/Stockage/Users/e.blindauer/tmp/moobyfr/springlobby/src/lsl/src/lslunitsync/unitsync.cpp -- 468: Balanced Annihilation V8.06: cannot find image SidePics/arm.png

I verified in BA archive, I have arm.png map, but in the directory ./luaui/images/arm.png only

**Comment by abma** [comment]
did the most recent commit(s) fix this crash?

**Comment by moobyfr** [comment]
the recent commits didn't fix the issue.

If I remove the ba-v8.06.sdz from the directory games/ and if I join a battle, moving the file back permit to join as spec the game

**Comment by abma** [comment]
>  the functions fails on std::FILE *file = fmemopen( (void*)data, size, "rb" );

whats the output of
print data
print size
?

i need your help here, i can't reproduce it + i have no idea why it crashes there...

**Comment by moobyfr** [comment]
(lldb) p data
(LSL::Util::uninitialized_array<char>) $4 = (elems = "BM8\x03")
(lldb) p size
(size_t) $5 = 824
