### ISSUE TITLE
add encryption support

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#314]
libcrypto seems useable for that.

https://www.openssl.org/docs/crypto/crypto.html

example client in python:

https://github.com/spring/uberserver/blob/master/TestLobbyClient.py

**Comment by abma** [comment]
related feature requests:
http://springrts.com/mantis/view.php?id=4647
https://github.com/cleanrock/flobby/issues/16

**Comment by Usaga** [comment]
Does it really needed?

**Comment by abma** [comment]
yep!

**Comment by abma** [comment]
uberserver now supports STARTTLS

(this change atm is only applied to the development server at lobby.springrts.com:7000)

**Comment by specing** [comment]
You seem to have a new bug open for this @abma

**Comment by abma** [comment]
yep, see #784
