### ISSUE TITLE
OSX - Selecting Spring.app in SpringLobby

### ISSUE THREAD

**Issue by darklord42** [springlobby/springlobby#316]
Given that App bundles are just glorified directories.  Is there anything we can do to restore selecting an app bundle as Spring executable and UnitSync library?  Or better yet, infer the true location of both by selecting anything labeled Spring * .app as Add New.
the actual executable will always be
./Spring * .app/Contents/MacOS/spring
and the UnitSync lib will always be
./Spring * .app/Contents/MacOS/libunitsync.dylib

**Comment by abma** [comment]
doesn't this partly work already?

made a fix recently:
https://github.com/springlobby/springlobby/commit/745862b68552403e4a8f513b948534372caafcbd

selecting .app would be missing then.

**Comment by darklord42** [comment]
Well it works if you manually add to the springlobby.cfg:
[Spring/Paths]
[Spring/Paths/version]
SpringBinPath=/path/Spring.app/Contents/MacOS/spring
UnitSyncPath=/path/Spring.app/Contents/MacOS/libunitsync.dylib
SpringBundlePath=/path/Spring.app

But .apps are greyed out under the Add New menu.  Spring Executable can only select the app and not the executable, and finally UnitSync Browse can't open the Spring.app to get at the libunitsync.dylib

**Comment by abma** [comment]
fixed by https://github.com/springlobby/springlobby/pull/322
