### ISSUE TITLE
springlobby ppa is VERY outdated

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#321]
need help to update, idk how to do :-|

where is the existing code/script?

**Comment by baracoder** [comment]
Uff, long time ago...

I had added the dpkg code to the ubuntu branch. Usualy it should be enough to merge master into it and start the build.

**Comment by abma** [comment]
meh, i gave up :-|

at least someone at debian seems to update springlobby, so there will be updates in newer ubuntu versions:

https://launchpad.net/ubuntu/+source/springlobby/0.201-1

**Comment by abma** [comment]
maybe if someone else continues this:
todo is sth. like this

update this branch by merging 0.201 (or the current release)
https://github.com/springlobby/springlobby/commits/ubuntu

upload with tools/ppa_release.sh

(+ fix all errors occuring)

also all changes outside of debian/ should be merged back into the master branch else it will give a lot of merge errors next time it will be updated.

**Comment by apoleon** [comment]
Hi,

I am the Debian maintainer for springlobby. If you really want to distribute springlobby with a PPA, then I suggest to download the official Debian sources with apt-get source springlobby and upload them with dput to your PPA. Of course I recommend to use the official version... :>

**Comment by abma** [comment]
i don't want to distribute with a ppa, but the springlobby version shipped with current ubuntu / debian is very old and contains a lot of bugs which are already fixed in current version... thanks for the hint, will give it a try.

**Comment by abma** [comment]
thanks to renemilk the ppa is up to date!
