### ISSUE TITLE
linking errors on ALT Linux 7.0

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#327]
Linking CXX executable springlobby
/usr/bin/ld: CMakeFiles/springlobby.dir/gui/notificationmanager.cpp.o: undefined reference to symbol 'g_type_check_instance_cast'
/usr/bin/ld: note: 'g_type_check_instance_cast' is defined in DSO /usr/lib64/libgobject-2.0.so.0 so try adding it to the linker command line
/usr/lib64/libgobject-2.0.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [src/springlobby] Error 1
make[1]: *** [src/CMakeFiles/springlobby.dir/all] Error 2
make: *** [all] Error 2

It could not find gobject-2.0 lib, so I've changed src/CMakeLists.txt:

diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 8dc036b..0835745 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -357,7 +357,7 @@ TARGET_LINK_LIBRARIES(springlobby lsl-utils lsl-unitsync pr-downloader_static js
 #add_dependencies(springlobby version)
 IF(UNIX)
        FIND_PACKAGE(X11 REQUIRED)
-       TARGET_LINK_LIBRARIES(springlobby ${X11_X11_LIB})
+       TARGET_LINK_LIBRARIES(springlobby ${X11_X11_LIB} gobject-2.0) 
 ENDIF(UNIX)
 
 ENABLE_TESTING()

And it worked.
I have ALT Linux 7.0 (http://www.altlinux.com/) operating system.

**Comment by abma** [comment]
what does 
$ pkg-config --libs x11

output?

**Comment by jet-bird** [comment]
-lX11

**Comment by jet-bird** [comment]
Hm.. what does that command on your machine?

**Comment by abma** [comment]
the same. ahh, maybe this, whats the output of this:

pkg-config --libs libnotify

**Comment by jet-bird** [comment]
```
-lnotify
```

**Comment by abma** [comment]
does it compile with OPTION_NOTIFY disabled?

**Comment by jet-bird** [comment]
no, it doesn't

**Comment by jet-bird** [comment]
Could you tell me something more about this bug so I could contact with ALT Linux developers? Why not to link to gobject-2.0 explicitly, for example:
```
FIND_PACKAGE(GTK2 REQUIRED)
TARGET_LINK_LIBRARIES(springlobby ${X11_X11_LIB} ${GTK2_LIBRARIES}) 
```
?

**Comment by abma** [comment]
because springlobby doesn't directly use gobject-2.0. its a dependency which is pulled in by an external lib and it should be then autodetected by pkg / cmake.

on ubuntu its not needed to link to GTK2/gobject-2.0

whats the output (when successfully linked) of

LC_ALL=C readelf -d springlobby |grep Shared

?

here its http://pastebin.com/Eq2vDf3c

**Comment by jet-bird** [comment]
http://pastebin.com/1d1SzwJi

**Comment by jet-bird** [comment]
Maybe this is not a bug, but a new feature?
http://fedoraproject.org/wiki/Features/ChangeInImplicitDSOLinking
I think it can be related to the problem.
My version of linker is
```GNU ld version 2.23.51.0.1-alt2 20120806```

**Comment by abma** [comment]
> does it compile with OPTION_NOTIFY disabled?

can you try that again please? it wasn't possible when libnotify was installed without this fix:

**Comment by jet-bird** [comment]
yes, it does

**Comment by abma** [comment]
thats the output here:
pkg-config --libs libnotify
-lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 

imo pkg-config on alt linux is broken/has a bug...

**Comment by jet-bird** [comment]
I've posted them a message.

**Comment by jet-bird** [comment]
They changed default pkg-config implicit linking to explicit (like in Fedora). 

After a little investigation I've found a cmake command which disencumbers of changing CMakeLists.txt:
```cmake . -DCMAKE_EXE_LINKER_FLAGS='-lobject-2.0'```

**Comment by abma** [comment]
how can a program like springlobby automaticly detect then, if a lib needs to be linked or not?

i'm pretty sure libnotiy can be configured/compiled in a way that it requires different libs.

**Comment by abma** [comment]
i don't see a springlobby bug here / have no idea how it could be fixed in springlobby.

it would be a very bad hack like:
if (system is fedora AND libnotify is found)
add -lobject-2.0

i refuse to add such a hack, this only leads to more problems in future :-|
