### ISSUE TITLE
updater seems to fail in unicode directories

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#329]
directory cleanup doesn't delete subdirs:

01:54:38: Warning: erasing dir C:\Dokumente und Einstellungen\nutzer\Anwendungsd
aten\springlobby\update\
Couldn't cleanup C:\Dokumente und Einstellungen\nutzer\Anwendungsdaten\springlob
by\update\
01:54:38: Error: Couldn't cleanup C:\Dokumente und Einstellungen\nutzer\Anwendun
gsdaten\springlobby\update\
Directory 'C:\Dokumente und Einstellungen\nutzer\Anwendungsdaten\springlobby\upd
ate\' couldn't be created (error 183: eine Datei kann nicht erstellt werden, wen
n sie bereits vorhanden ist.)
01:54:38: Error: Directory 'C:\Dokumente und Einstellungen\nutzer\Anwendungsdate
n\springlobby\update\' couldn't be created (error 183: eine Datei kann nicht ers
tellt werden, wenn sie bereits vorhanden ist.)
couldn't create update directoryC:\Dokumente und Einstellungen\nutzer\Anwendungs
daten\springlobby\update\
01:54:38: Error: couldn't create update directoryC:\Dokumente und Einstellungen\
nutzer\Anwendungsdaten\springlobby\update\
[Info] Using filesystem-writepath: C:\Dokumente und Einstellungen\nutzer\Eigene
Dateien\My Games\Spring
[Info] opened C:\Dokumente und Einstellungen\nutzer\Anwendungsdaten\springlobby\
springlobby-latest.zip

**Comment by abma** [comment]
updater seems to be broken when using an unicode directory:
- files can't be extracted (is empty, springlobby_updater.exe not found)

**Comment by Usaga** [comment]
Looks like this problem involves many FS functions of wxWidgets under Windows

**Comment by abma** [comment]
please test again with 0.214+

(seems to work there for me)

also as note: springlobby.exe downloads and extracts the update. when using an old version of springlobby, it may still contain bugs, so possible fails when updating to current version while current version should work in unicode dirs.
