### ISSUE TITLE
sort of userlist seems broken

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#332]
when a new user joins server, userlist seems unsorted and after a short time its sorted again.

looks a bit weird.

**Comment by Usaga** [comment]
It is because of sorting on timer.

**Comment by abma** [comment]
yeah, but it "unsorts" when a new user is added. whole list is unsorted not only the newly added user.

**Comment by Usaga** [comment]
This may be as result of filtering. I will look on it...

**Comment by jamerlan** [comment]
+1 Sorting of players changing all the time :-) looks strange.

**Comment by abma** [comment]
#333
