### ISSUE TITLE
"JOIN" button is not working sometimes

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#336]
SpringLobby 0.210-19-g79e26ca but was reproducible before 0.210 also

sometimes I cant join battle using "Join" button. But double click on battleroom name helps!
For example, if game is running already - I am trying to join - clicking button and nothing happens.

This is floating bug. Reproducible from time to time. I think the best way to find the cause is to log debug information on click handler. I dont know how to provide more info.

**Comment by jamerlan** [comment]
so I use "double click on battle" as a workaround

**Comment by Usaga** [comment]
Same bug was with double clicking, before I fixed it in vesion 210. I did`t use join button, so can`t say was this my fault or not. I will figure this out today

**Comment by jamerlan** [comment]
Double click works correctly. "Join" button contains a bug

**Comment by jet-bird** [comment]
About double click: when I start lobby double click drops the sorting of the battle list (tested on 0.210-33-g6b1abdf) . It happens from time to time. I usually set up the sorting by the number of players.

**Comment by jamerlan** [comment]
+1 to drop of sorting. I can provide more details: It acts sometimes like click on table header. This is old bug. If you click on first row - sometimes "table header" click triggered.

**Comment by abma** [comment]
can't reproduce / seems fixed

**Comment by jamerlan** [comment]
Please RE-OPEN this bug! I still have it!
I lost like 2 hours to setup "debugging" environment and I found this thing:
(sorry, screenshot is big, but its informative. 

Text Description: I dont know exactly how to reproduce it. Bug happens from time to time. But I can reproduce it this way:
1) battle should be in progress
2) click randomly on all tabs, select items in lists etc (like replay, singleplayer)
3) return to "battle list" and press "Join"
Sometimes (often enough) "Join" button is not working! Just no action at all. But! Double click on battle in the list works! 

This return works (breakpoint reached): 
	//Is there any battle selected?
	if (m_battle_list->GetSelectedIndex() < 0) {
		return;
	}
in this method:
void BattleListTab::OnJoin(wxCommandEvent& /*unused*/)

![join_bug](https://cloud.githubusercontent.com/assets/216801/8339959/fbec8acc-1ac3-11e5-95dd-fa67104dc1b5.png)

**Comment by abma** [comment]
whole battle list is atm reworked..
