### ISSUE TITLE
some maps can't be selected it seems

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#341]
springlobby offers to download them

was introduced when refactoring, maybe loading from cache fails?

**Comment by abma** [comment]
Error: runtime assertion ( src/gui/hosting/battleroomtab.cpp:488 ): Map does not exist.

**Comment by Usaga** [comment]
Looks like this is happen when lobby can't find selected map in cache. No an error, actually. I replaced this assert with "IF" operator and all is fine. Except, method with this code is called again and again until presented map is selected. This was cause of hundreds of MessageBoxes shown. Box is no longer shows but, I think, method is still called eating CPU...

**Comment by abma** [comment]
basicly the problem is that the code for this is just a mess.

needs some refactoring/cleanup... not sure if #48 is less work or refactoring/cleanup.

**Comment by abma** [comment]
can't reproduce
