### ISSUE TITLE
Invalid UTF-8

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#343]
![1](https://cloud.githubusercontent.com/assets/9379087/6203074/a3e7625e-b51d-11e4-87ab-7e68b50dd4e9.png)

The real message is something like "[teh]decay is online" (in russian possibly).

**Comment by Usaga** [comment]
From where these bugs are coming from? They are limitless. Unbelivable))

**Comment by abma** [comment]
lobby server!

**Comment by abma** [comment]
i guess usage of libnotify is to blame here.

**Comment by abma** [comment]
does "Invalid UTF-8" popup when you click in springlobby 0.214 edit->preferences->general->"Test Notification"?

**Comment by jet-bird** [comment]
it's ok now!
