### ISSUE TITLE
Invalid map name

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#347]
Lobby version: 0.210-33-g6b1abdf
![download map bug](https://cloud.githubusercontent.com/assets/9379087/6313922/ebba844c-b9d4-11e4-9454-2ca9d056b893.png)
OS: Alt Linux 7

**Comment by abma** [comment]
already fixed in current development version:

https://github.com/springlobby/springlobby/commit/a0debd189fc67166ea06f44a621706245e02ed08
