### ISSUE TITLE
logic error ( /home/revenant/springlobby/src/ibattle.cpp:662 ): Battle with empty map name!

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#350]
just got this error: "logic error ( /home/revenant/springlobby/src/ibattle.cpp:662 ): Battle with empty map name!"

on latest from master: 1c9c72fc0c14f38484a95baca57648c97d4105de

**Comment by abma** [comment]
fixed server side, empty map names aren't valid

**Comment by abma** [comment]
thanks for reporting, didn't notice that. very likely it was caused by notalobby
