### ISSUE TITLE
(v0.210) file search brings no results or "failed to parse search results"

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#351]
v0.210
1) go to Download-tabs
2) "Search a file"
3) enter something, click "search"
4 a) ... either simply no results are displayed 
4 b) ... or search-results are displayed they seem to incomplete, see in end of video when a search for "zero" only finds ~10 items. (there should be hundreds of zero-K versions?)
4 c) ... or an error appears:

![springlobby search results parse fehler](https://cloud.githubusercontent.com/assets/3044855/6353930/88b14550-bc4c-11e4-98ac-2196b835f8c3.png)

http://youtu.be/bVjpXpqWbCQ

**Comment by abma** [comment]
also it should crash in some cases.

(partly) fixed in current development version:

37379cdf08c2c55cc3a4306be2b292a8e55d4f4d

search doesn't search for non-stable rapid versions

**Comment by knorker** [comment]
> search doesn't search for non-stable rapid versions

hm, bit unclear:

1) Are the "incomplete" search results because of the bugs or is this working "as it should:"

When I search for "z" not a single stable zero-K version is found.
Only finds ~10 variants of:
"zero-K v1.2.12.2 Hacksaw Test" & "zero-k chicken madness"

Similiar I can not find spring tanks.
Should commits like
https://github.com/ZeroK-RTS/Zero-K/commit/0a848f62aae3c15e2793bfd3cd780a60abd04556
or
https://code.google.com/p/springtanks/source/detail?r=12
not create a stable version?
There exists http://packages.springrts.com/builds/springtanks-7.0.sdz = search should find it?

2) For "b" it works and finds BA 8.10 (currently latest)
But is it supposed to find ONLY BA 8.10? (and not previous stable BA versions too?)

**Comment by abma** [comment]
"failed to parse search results" is fixed... searching in rapid isn't implemented because pr-downloader isn't used in the backend yet, but thats on the todo.

**Comment by abma** [comment]
"TODO": https://github.com/springlobby/springlobby/blob/master/src/gui/contentdownloaddialog.cpp#L79
