### ISSUE TITLE
windows unitsync problems

### ISSUE THREAD

**Issue by mtroyka** [springlobby/springlobby#352]
When I go into edit->spring settings and try to save I get an error saying "could not save, unitsync not properly loaded". SL also fails to load any games/maps in skirmish, even after using the "reload maps/games" option, which I suspect is related. Manually specifying the path to unitsync.dll and spring.exe does not help, and after applying the settings it's like nothing changed at all (and the settings don't show any paths afterwards, if they're supposed to). This is under windows7/x64.

**Comment by abma** [comment]
thats a bit unspecific: whats the output of help->system info?

> Manually specifying the path to unitsync.dll and spring.exe does not help

what does happen then? is it it added to the list of engine versions?

**Comment by mtroyka** [comment]
>>what does happen then? is it it added to the list of engine versions?

D'oh, I didn't realize that was what I needed to look for. Now unitsync is properly loaded and everything is working.

**Comment by abma** [comment]
yeah, usability is pretty bad in this point :-|

**Comment by Usaga** [comment]
It looks like something must be done for simplification of adding engine to lobby configuration.

**Comment by abma** [comment]
i.e. disable gui elements which aren't usable because of missing spring:

https://github.com/springlobby/springlobby/issues/253

but mainly the bugs should be fixed which makes springlobby not automaticly find spring.

**Comment by abma** [comment]
@mtroyka 

whats the output of help->system info?

**Comment by mtroyka** [comment]
Well, now that I've fixed it:
SpringLobby 0.210 (win x32)
SpringLobby config file: C:\Program Files (x86)\Spring\springlobby.conf ( writable)
LobbyWriteDir (C:\Program Files (x86)\Spring\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Program Files (x86)\Spring\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Program Files (x86)\Spring\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\haplo\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\haplo\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Program Files (x86)\Spring\unitsync.dll
Current spring executable: C:\Program Files (x86)\Spring\spring.exe
Current uikeys.txt: C:\Users\haplo\Documents\My Games\Spring\uikeys.txt
Portable mode: yes
Compile Time Feb  2 2015 01:45:20
Compiled with wxWidgets 2.9.5.0
Started with: 
C:\Program Files (x86)\Spring\springlobby.exe
