### ISSUE TITLE
GetPrimaryModShortName: deprecated unitsync function called

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#353]
latest version: f8b43718981e490c7d90cac24664755ff8c5d482

when I download map, I have error in popup: GetPrimaryModShortName: deprecated unitsync function called: GetPrimaryModShortName

in console:
[Info] Using filesystem-writepath: /home/revenant/.spring
[Info] XmlRpcCurlClient new client: host api.springfiles.com, port 80.
[Info] XmlRpcCurlClient::execute: method springfiles.search.
[Info] XmlRpcCurlClient::execute: method springfiles.search completed.
[Info] opened /home/revenant/.spring/maps/frozenfourway.sd7
[Info] piece finished==========                ] 5832704/11715212 
[Info] piece finished                          ] 49804/11715212 
[Info] piece finished==========                ] 5832704/11715212 
[Progress]  50% [==============                ] 5832704/11715212

**Comment by abma** [comment]
https://github.com/springlobby/lsl/commit/86a6d115af754d815e037892be72b9a59af4b558

**Comment by abma** [comment]
now its
deprecated unitsync function called: GetPrimaryModName
