### ISSUE TITLE
Crash while trying to join battle

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#362]
Sometimes it is really hard to reproduce, sometimes this can happen after few join/leave iterations.
SIGSEGV appears in BattleListTab::OnListJoin (this code is changed for debugging):

...
auto selectedBattle = m_battle_list->GetSelectedData();	
if( selectedBattle==NULL ) {
  wxLogError( _T("BattleListTab::OnListJoin: m_battle_list->GetSelectedData()==NULL") );
  return;
}
int id = selectedBattle->GetBattleId(); <-- does SIGSEGV
...

CustomVirtListCtrl::GetSelectedData is passing assertion for correct m_selected_index value, so, it is looks like the problem in Battle object stored in list...

**Comment by abma** [comment]
can't reproduce with current master... rejoined ~10 times a battle.

**Comment by Usaga** [comment]
Very likely this bug has same origin as #364 and #336

**Comment by abma** [comment]
some easier to reproduceable (maybe related bug):

host new battle, select the battle you created in battle list, leave battle.

often all battles are selected after leaving the battle.

**Comment by abma** [comment]
@Usaga:

what do you think, is current version in a releaseable state?

imo this bug is crash is so rare, didn't get it once.

**Comment by Usaga** [comment]
Except of this misterious bug all seems fine.

**Comment by abma** [comment]
please test again with 0.214+
