### ISSUE TITLE
(v0.210) doubleclicking in battlelist sometimes try to join wrong battle

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#364]
Sometimes I doubleclick a battleroom in the battlelist and SL tries to join the wrong battle.
Example:
https://www.youtube.com/watch?v=R-85USLElec (14s)
I doubleclick on the XTA room but SL offers to download BA.
After scrolling a bit, it joins the clicked room correctly.

**Comment by abma** [comment]
duplicate #336

should be fixed in current development version

**Comment by abma** [comment]
+ thanks for reporting!

latest development version can be downloaded at http://springlobby.info/temp/builds/abma/sl_master.zip
