### ISSUE TITLE
autounspec only tries once on SPADS hosts

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#365]
When you check autosunspec, SL will only actually try to autounspectate once, on SPADS hosts.

I'm not sure why this is. I guess its that SL momentarily sees myself as a player, but in fact many other spectators became a player, only one of which actually stays as a player - the rest immediately become spectators again. But during this instant, SL has unchecked the "auto-unspectate" box.

I'm not sure if this genuinely a SL bug; maybe its a limitation of the lobby protocol or possibly even a SPADS bug.

**Comment by abma** [comment]
if multiple players have checked auto unspec, then the "fastest" will become player. spads will force other players automaticly back to be a spec. to prevent ping-pong and getting kicked by spads springlobby deselects the auto-unspectate as it failed the first time.

i'm not sure if this is a bug, imo its not so bad as it is.

**Comment by silentwings** [comment]
It doesn't bother me personally, but it does get alot of complaints (players usually blame the autohost).

**Comment by abma** [comment]
imo this can't be fixed in a clean way in springlobby. to fix it in a clean way imo spads has to be changed so it has some "unspec" list where clients can enlist and when possible, spads will unspec the client which subscribed first.

imo its not worth the trouble to implement this, we should focus on match making for that.

**Comment by silentwings** [comment]
It seems that it's not possible for SPADS to fix this - https://github.com/Yaribz/SPADS/issues/8
