### ISSUE TITLE
integration with "spring menu"

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#368]
"Spring" might maybe get a in-engine Lua menu that allows players to access the in-engine singleplayer menu of games.

Examples that demonstrate the IDEA: http://i.imgur.com/YdJSk4p.png or http://youtu.be/YNCj50dmgB8

some forum threads:
https://springrts.com/phpbb/viewtopic.php?f=14&t=33065
https://springrts.com/phpbb/viewtopic.php?f=23&t=33238
https://springrts.com/phpbb/viewtopic.php?f=23&t=33240&start=20#p567433  <-- SL mentioned.
----

How will a player get into this menu?
One way change the engine to load it on start.

I think for players it makes more sense if Springlobby offers a way load this menu.
For example with a "Start Spring Menu" button in SL.
It would start spring with a to-be-decided startscript.txt

**Comment by knorker** [comment]
My understanding was that lobbies would need some way to read the startscript from the mod-archive.
(like how lobbies read modinfo via unitsync, instead of lobbies all doing their own parsing)

So I made feature-request in mantis: https://springrts.com/mantis/view.php?id=4983 but the comments confuse me.

**Comment by abma** [comment]
basicly the mantis report is about distributiong spring without lobby. this feature request here is about a way to list games which contain a menu. imo the game should detect itself its it started in menu mode.

starting via lobby requires first a defined standard and then it can be implemented and used.

**Comment by knorker** [comment]
> basicly the mantis report is about distibuting spring without lobby.
No.
( The mantis-report is about adding 'something' to engine/unitsync that allows lobbies to read a startscript contained in the mod.
I thought this was nessecary because unitsync reads archives and because was told so. From mantis I learned that lobbies can already open any file they want, via OpenFileVFS() 
However if each lobby has to directly fumble with files like this, that seems unclean to me and unlikely to become widely used standard. I thought unitsync is the interface with purpose to avoid that.)

> this feature request here is about a way to list games which contain a menu.
This feature-request is about springlobby getting a Start-SP button that launches into the selected games Lua-singleplayer.

> imo the game should detect itself if its it started in menu mode.
The games already do that.
The problem is NOT for the game to detect if it is started in menu mode.
The problem IS for the lobby to start the game in menu mode.
(there are different methodes to detect menu-mode, the detection via modoptions or mapname, how excactly a games detects it does not really matter because all these conditions are in startscript)

> starting via lobby requires first a defined standard and then it can be implemented and used.
Ok, my proposal is that the startscript is named "lobbyStartScript.txt" and in gamedata\ folder of mod.

(There is of course some questions, like the lobby needs to know which engine-version to use.
This is however a general problem to lobbies, it happens with 'normal' SP or when hosting MP too)

**Comment by abma** [comment]
suggestion: rephrase the same in fewer words.

**Comment by abma** [comment]
this report is already unreadable -> closing

**Comment by abma** [comment]
also the general goal is: do not require a lobby any more
