### ISSUE TITLE
(v0.210) mapselection: crash on using mapname filter

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#369]
reproduceable:
1) map selection menu
2) start typing something into filter textbox
3) eventually springlobby will crash

In video I always type "frr" to make it crash, but other strings crash it too.
It seems to crash when filtering returns no results?
"way" "delta" "siege" all work but then "xx" crashes it.

http://youtu.be/-wGkXaQIGXc

**Comment by Usaga** [comment]
Can not reproduce on my PC. Video shows that your lobby works soooo slow even map grid widget can`t get load maps before you start typing. Probably bug is hiding somewere there. Anyway this is hard to say something without stacktrace...

**Comment by knorker** [comment]
If I wait for all map images to load it still crashes.
It seems half the map images appear instantly but other half takes a lot longer to show up. (30s or so) That does not change after restarting lobby.

--------

Call stack of main thread
Address    Stack      Procedure / arguments                 Called from                   Frame
0022DB98   01055C97   springlo.00EFE770                     springlo.01055C95             0022DB94
0022DBD8   00EFED3E   springlo.01059C80                     springlo.00EFED39
0022DC58   00531EB4   springlo.00EFEBB0                     springlo.00531EAF             0022DD44
0022DD48   0053B0A4   springlo.00531D90                     springlo.0053B09F             0022DD44
0022DE08   0053C601   ? springlo.0053AC90                   springlo.0053C5FC             0022DE04
0022DEA8   00C12A31   Maybe springlo.0053C580               springlo.00C12A2F             0022DEA4
0022DEAC   0022E124     Arg1 = 0022E124
0022DEC8   00C12ED7   Maybe springlo.00C12A10               springlo.00C12ED1             0022DEC4
0022DECC   03841B78     Arg1 = 03841B78
0022DED0   0053C580     Arg2 = 0053C580
0022DED4   00000000     Arg3 = 00000000
0022DED8   0022E124     Arg4 = 0022E124
0022DEE8   00C43B48   springlo.00C12EA0                     springlo.00C43B42             0022DEE4
0022DEEC   03841B78     Arg1 = 03841B78
0022DEF0   0484ED68     Arg2 = 0484ED68
0022DEF4   0022E124     Arg3 = 0022E124
0022DF18   00C43FC6   springlo.00C43AF0                     springlo.00C43FC1             0022DF14
0022DF58   00C44055   springlo.00C43F80                     springlo.00C44050
0022DF88   00C440DA   springlo.00C44030                     springlo.00C440D5             0022DF84
0022DF8C   0022E124     Arg1 = 0022E124
0022DFA8   00C44135   ? springlo.00C440A0                   springlo.00C44130             0022DFA4

**Comment by abma** [comment]
please test again with 0.214+

**Comment by knorker** [comment]
Happens again in v0.236
Maybe related to deleting content of maps\ folder from time to time. But it is after having done "reload maplist" several time.

**Comment by knorker** [comment]
reopen?
i forgot where sl saves crashlog..
