### ISSUE TITLE
master branch fails to compile

### ISSUE THREAD

**Issue by JoshuaPettus** [springlobby/springlobby#372]
I hit an error while trying to compile springlobby.   I'm on OSX 10.10 compiling against WxWidgets 3.0.2.0 with the AppleClang 6.0.0.6000057 compiler although same thing happened with GCC 4.9.2.

[ 76%]         void destroy_back_n( size_type n, const boost::true_type& )
                                       ^
Building CXX object src/CMakeFiles/springlobby.dir/gui/slbook.cpp.o
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:203:15: error: no member
      named 'SetDoubleBuffered' in 'MainChatTab'
                m_chat_tab->SetDoubleBuffered( true );
                ~~~~~~~~~~  ^
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:204:15: error: no member
      named 'SetDoubleBuffered' in 'BattleListTab'
                m_list_tab->SetDoubleBuffered( true );
                ~~~~~~~~~~  ^
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:205:15: error: no member
      named 'SetDoubleBuffered' in 'MainJoinBattleTab'
                m_join_tab->SetDoubleBuffered( true );
                ~~~~~~~~~~  ^
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:206:13: error: no member
      named 'SetDoubleBuffered' in 'MainSinglePlayerTab'
                m_sp_tab->SetDoubleBuffered( true );
                ~~~~~~~~  ^
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:208:17: error: no member
      named 'SetDoubleBuffered' in 'PlaybackTab'
                m_replay_tab->SetDoubleBuffered( true );
                ~~~~~~~~~~~~  ^
/Users/herecomethej/springlobby/src/gui/mainwindow.cpp:209:18: error: no member
      named 'SetDoubleBuffered' in 'MainDownloadTab'
                m_torrent_tab->SetDoubleBuffered( true );
                ~~~~~~~~~~~~~  ^
In file included from /Users/herecomethej/springlobby/src/gui/mapctrl.cpp:22:
In file included from /Users/herecomethej/springlobby/src/gui/mapctrl.h:11:
In file included from /Users/herecomethej/springlobby/src/lsl/src/lslunitsync/unitsync.h:10:
In file included from /opt/local/include/boost/signals2/signal.hpp:28:
In file included from /opt/local/include/boost/signals2/detail/slot_call_iterator.hpp:22:

**Comment by Usaga** [comment]
Remove this code from /Users/herecomethej/springlobby/src/gui/mainwindow.cpp

	if ( cfg().ReadBool(_T( "/GUI/DoubleBuffered" ))) {
		m_chat_tab->SetDoubleBuffered( true );
		m_list_tab->SetDoubleBuffered( true );
		m_join_tab->SetDoubleBuffered( true );
		m_sp_tab->SetDoubleBuffered( true );
	//	m_savegame_tab->SetDoubleBuffered( true );
		m_replay_tab->SetDoubleBuffered( true );
		m_torrent_tab->SetDoubleBuffered( true );
	}

This code makes more problems than benefits.

**Comment by JoshuaPettus** [comment]
That seemed to work!  Thanks.
If it's there to only benefit windows, why not put it around:
#ifdef __win32__ or whatever?

**Comment by abma** [comment]
code will be removed, soon. (don't have the time to do so atm)

**Comment by Usaga** [comment]
FIxed with https://github.com/springlobby/springlobby/commit/d6375de4f357aa666514cc9bdd63f1dbc9e0a839
