### ISSUE TITLE
Springlobby fails to download engine, still reports synced = true

### ISSUE THREAD

**Issue by springjools** [springlobby/springlobby#373]
Springlobby asks should a new engine be downloaded when joining battle, but it doesn't actually download anything. Synced status = true so user thinks game can begin. But when starting the game the engine is not found: turns out it has never been downloaded.

![image](https://cloud.githubusercontent.com/assets/5911982/6688102/7e4231e2-ccb9-11e4-9d15-3f1f38ab6f4c.png)

![image](https://cloud.githubusercontent.com/assets/5911982/6688135/c12a5a34-ccb9-11e4-8792-78896ded7ee6.png)

**Comment by Usaga** [comment]
Fixed with https://github.com/springlobby/springlobby/commit/99cb66f2cbb86a7adb07f0f4ebc9dada8802a01f
and
https://github.com/springlobby/springlobby/commit/1f8252de720f7d63880943470354871ae6527b00
