### ISSUE TITLE
SL doesn't realize I have a map

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#376]
See screenshot.

SL has just been started, I have switched to a new engine and opened a battle. SL seems to think I don't have DSD and shows no preview pic for it (but ofc I do have DSD and can start a battle without issue by pressing "start"). 

As a result of this (presumably), when I check or uncheck on the "lock battle" I get the error message

"[08:16:48] ** Server ** UPDATEBATTLEINFO failed - Empty mapname send: 17184944".

![slbug6](https://cloud.githubusercontent.com/assets/3885930/6768586/eacca2c8-d06c-11e4-80f1-43e1b491ee4c.png)

**Comment by abma** [comment]
selecting map afaik is fixed in current development version, "UPDATEBATTLEINFO failed - Empty mapname send: 1" is indeed a bug, springlobby shouldn't send this command at all when mapname is empty.

**Comment by abma** [comment]
please test again with 0.214+
