### ISSUE TITLE
Still some users with not working mapfolder detection

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#378]
[15:07:56] <Emru> Hello, I have a problem. Spring lobby doesn't see games and maps. I downloaded it.

Was gone before you could catch him.
Considered Downloading a map, and the recursive searching for the place it ended up?

**Comment by Usaga** [comment]
It is really hard to understand what you meant. You can't find were lobby downloading maps? Or spring  downloading maps but does not see them?

**Comment by PicassoCT** [comment]
I can find them.. allright.. 
No, it was a newbie in the #newbie channel. He seemed to have downloaded some maps/games via rapid, which he then could not see or use.

**Comment by abma** [comment]
should be fixed with 0.214
