### ISSUE TITLE
GUI Tabs are shown with bug in KDE4 (Oxygen)

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#379]
Hi!
I have KDE4 with theme Oxygen and 
gtk-theme-name="oxygen-gtk"
and gtkrc-2.0 with oxygen-gtk theme set:

```
# created by KDE, чт фев 26 10:56:00 2015
#
# If you do not want KDE to override your GTK settings, select
# Appearance -> Colors in the System Settings and disable the checkbox
# "Apply colors to non-KDE4 applications"
#
#

gtk-alternative-button-order = 1
gtk-fallback-icon-theme = "gnome"

include "/usr/share/themes/oxygen-gtk/gtk-2.0/gtkrc"

gtk-theme-name="oxygen-gtk"
```

Tabs do not contain what they should, for example battle list, see image below:

![gui-tabs-bug](https://cloud.githubusercontent.com/assets/9379087/6873838/fefcc204-d4c3-11e4-8b1b-1be26ec95728.png)

**Comment by jet-bird** [comment]
Btw, nice GUI performance optimization work! Lobby is joining battle much faster now! Cool!

**Comment by Usaga** [comment]
It looks good for me. Maybe wrong image posted?

**Comment by jet-bird** [comment]
Here is correct tab:
![correct container](https://cloud.githubusercontent.com/assets/9379087/6880385/f65f43a2-d53f-11e4-89e0-4a134c5c3130.png)

And here are empty tabs with content placed below them (not inside):
![gui-tabs-bug1](https://cloud.githubusercontent.com/assets/9379087/6880386/f664d2d6-d53f-11e4-8df4-40549a7c5dd8.png)

**Comment by Usaga** [comment]
Hm. May be this is gtk-theme bug or even wxgtk bug...

**Comment by abma** [comment]
i don't understand this bug report. whats wrong?

**Comment by jet-bird** [comment]
![fefcc204-d4c3-11e4-8b1b-1be26ec95728](https://cloud.githubusercontent.com/assets/9379087/6979071/364cca3e-d9e6-11e4-8b35-171ca5b033e2.png)

**Comment by jet-bird** [comment]
added new ticket to wxwidgets
http://trac.wxwidgets.org/ticket/16940#no1

**Comment by jet-bird** [comment]
I think this bug is somehow related to *wxAuiNotebook* widget. I took the *auidemo* sample from wxWidgets-2.9.5 which demonstrates wxAuiNotebook and there are no bug in it, look:
![auidemo](https://cloud.githubusercontent.com/assets/9379087/7062813/9841815e-dea9-11e4-9951-180d9dc58eb1.png)

**Comment by abma** [comment]
hmm, then the bug possible is in

https://github.com/springlobby/springlobby/blob/master/src/gui/slbook.cpp

**Comment by abma** [comment]
did this change with recent changes to springlobby? the "remove scrollbars" commits maybe fixed it...

**Comment by jet-bird** [comment]
No, it didn't.

**Comment by abma** [comment]
does this error happen with an empty springlobby.conf?

**Comment by jet-bird** [comment]
Yes:
![dialogwindow1](https://cloud.githubusercontent.com/assets/9379087/7316084/74d02d22-ea7c-11e4-89dc-464df2799fd8.png)

**Comment by abma** [comment]
please retry with the latest version. springlobby requires wxWidgets 3.0 at least which fixes A LOT of bugs.
