### ISSUE TITLE
maps & games detection problem

### ISSUE THREAD

**Issue by adam124312** [springlobby/springlobby#382]
Spring Lobby doesn't detect games nor maps

spring.exe detects them
springlobby downloads and saves maps correctly

I tried portable version on my desktop, installable version, portable version on a pendrive

I tried unchecking read-only box for spring-98.0 folder, I tried command "attrib" as in https://springrts.com/phpbb/viewtopic.php?t=31909, I tried to run springlobby.exe as an administrator

what will I do?

I use Windows 7 x64, 

system info output:
SpringLobby 0.210 (win x32)
SpringLobby config file: E:\spring-98.0\springlobby.conf ( writable)
LobbyWriteDir (E:\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
CachePath (E:\spring-98.0\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (E:\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Adam\Documents\My Games\Spring\)
	WX: no POSIX: no TRY: no
Current SpringData: ()
	WX: no POSIX: no TRY: yes
Current unitsync: 
Current spring executable: 
Current uikeys.txt: uikeys.txt
Portable mode: yes
Compile Time Feb  2 2015 01:45:20
Compiled with wxWidgets 2.9.5.0
Started with: 
E:\spring-98.0\springlobby.exe 

screenshoot:
![screenshoot](https://cloud.githubusercontent.com/assets/4093417/6960002/c2284bbe-d91e-11e4-8256-f275064657fb.png)

**Comment by Usaga** [comment]
You have to set up SpringLobby with actual location of unitsync library that came with spring.exe (and locates at same dir). SpringLobby does not doing this automatically even if it runs from directory containing spring and this needed library... 
Use Edit -> Preferences dialog
