### ISSUE TITLE
Messages area -> auto-scrolling issue

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#383]
Take a look at the video: https://youtu.be/dDZTHCLyxWQ

Steps to reproduce:
1. Text area is full of text
2. Someone added line (said smth)
result: text area scrolled top
expected result: the last message should be visible (text area should be scrolled down, not up)

I have this bug for a month or more. Was just too lazy to describe/create video.

I use: Fedora linux 21, WXWidgets 3, 

Springlobby: 
commit 3088ce2098c11d4ba463761e80ba44207c5771c8
Author: abma <spring@abma.de>
Date:   Thu Apr 2 02:22:24 2015 +0200

but as I said before: It started like a month ago (or more)

**Comment by jet-bird** [comment]
+1

**Comment by abma** [comment]
note to myself:

https://wiki.wxwidgets.org/WxTextCtrl#Scrolling
docs says this seems reliable / works cross platform:
ShowPosition(GetLastPosition())

**Comment by abma** [comment]
relevant code:

https://github.com/springlobby/springlobby/blob/master/src/gui/chatpanel.cpp#L474

**Comment by abma** [comment]
@jet-bird which version of wxwidgets are you using? (help->system info)

**Comment by abma** [comment]
was this bug introduced at some point? if so, bisecting would be nice. sadly i can't reproduce it :-|

**Comment by jet-bird** [comment]
wxWidgets 2.9.5.0

**Comment by abma** [comment]
ok, thanks. my recent changes broke scrolling on windows as well. :-|

on linux it still works for me ...

**Comment by jamerlan** [comment]
abma, can you try fedora 21 linux? :-D

**Comment by abma** [comment]
hmm, i partly can reproduce it now, seems my testing was wrong.

it seems to jump to the top when a user joins or leaves the battle. right?

**Comment by jamerlan** [comment]
>>it seems to jump to the top when a user joins or leaves the battle. right?
Hard to say :-) probably yes. Maybe for other "status" messages too

**Comment by jet-bird** [comment]
It also happens when you press "I am ready" button.

**Comment by jamerlan** [comment]
still not fixed completely :-)
scrolling is still "jumping" and in battleroom it still scrolls to the top/center sometimes.

**Comment by abma** [comment]
please give https://github.com/springlobby/springlobby/commit/7e1a47d138c13ac611f2f2e3fcf0dd40d6ca2ea3 a try

**Comment by jamerlan** [comment]
WOW! No jumping! And scrolling fixed! :+1:
