### ISSUE TITLE
springlobby 0.213 crashes on windows when a notification pops up

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#385]
can't reproduce atm, needs some testing.

locale maybe?

also some "random" crashes after logged in...

(TurBoss reported this)

**Comment by TurBoss** [comment]
on a diferent computer with windows 7 i get the same

http://paste.springfiles.com/view/a5124731

**Comment by abma** [comment]
it crashes because of notification popups! :-|

**Comment by abma** [comment]
when fixing this, add some "test notification" button in config which shows a popup

related to #343

**Comment by abma** [comment]
stacktrace:
http://paste.springfiles.com/view/74dbb4b6

src/gui/notifications/toasterbox/ToasterBoxWindow.cpp:41
