### ISSUE TITLE
Hover on countryflag wont tooltip the country name

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#388]
Hover on countryflag wont tooltip the country name (since about 2 years or so)

(on windows)

**Comment by abma** [comment]
afaik are tooltips disabled on windows due some (for me) unknown bug/problem on windows with it.

**Comment by abma** [comment]
let's see what happens :)

**Comment by FabriceFABS** [comment]
Actually on Linux => Same.
I regret not having this feature anymore...
