### ISSUE TITLE
feature request: height draggable 'Battle infos'

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#391]
feature request: height draggable 'Battle infos'

so the whole playerlist is easier to see, the list is refreshing itself often combined with the fact that the order of the players are different each time, makes it easy to miss some of the playernames.

**Comment by abma** [comment]
fixed via https://github.com/springlobby/springlobby/pull/847 or
https://github.com/springlobby/springlobby/pull/875
