### ISSUE TITLE
remembering ui (position,w/h) settings often are discarded when you reopen springlobby.

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#392]
remembering ui (tab order,position,w/h) settings often are discarded when you reopen springlobby.

(on windows)

**Comment by abma** [comment]
can you be more specific?

what exactly is discarded? was it maybe discared because of lobby update?

**Comment by Ruwetuin** [comment]
No this is a problem existing long before that. 
By tabs I mean: Chat, Battleroom, Replays, Downloads, Singleplayer, Battlelist.

On new spring installations I like to customize the layout. Dragging/snapping the Battlelist to the rightside. But then when I quit and relaunch springlobby it forgot to save the changes. After reconfiguring again and again it eventually saves and then i'm satisfied. (and maybe ...until i want to reconfigure the layout again :)

**Comment by abma** [comment]
can't reproduce... only thing which isn't preserved is order of tabs. size / position / w/h is stored.

can you please give a specific example which doesn't work for you?

i.e: edit->reset layout, quit springlobby, start springlobby -> drag ...
