### ISSUE TITLE
springlobby shows error message about broken demo when spring is already running

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#393]
since the latest release...

on startup it displays demo Error popup referring to corrupted demo

The demo is the currently still playing demo. An unfinished game still. (being ingame myself)

(on windows)

**Comment by Usaga** [comment]
I don't get it. SL says demo currently being played is corrupted?

**Comment by Ruwetuin** [comment]
If you are already ingame with spring, and then (re)open springlobby it shows the error message:
"There have been errors in loading playback procedure! Here is some of them:
File C:\Users\........\Spring\demos\20140404_155754-Nucl......sdf was corrupted and was deleted!"

(to make it clear, it did not delete anything)

**Comment by abma** [comment]
is this file/parent folder write protected / only accessible with admin rights?

**Comment by Ruwetuin** [comment]
no

**Comment by abma** [comment]
whats the output of help->system info?

does the path contain any special char?

**Comment by Ruwetuin** [comment]
SpringLobby 0.214 (win x32)
SpringLobby config file: C:\Users\Floris\Documents\My Games\Spring\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\Floris\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\Floris\Documents\My Games\Spring\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Users\Floris\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Floris\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\Floris\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Users\Floris\Documents\My Games\Spring\engine\98.0\unitsync.dll
Current spring executable: C:\Users\Floris\Documents\My Games\Spring\engine\98.0\spring.exe
Current uikeys.txt: C:\Users\Floris\Documents\My Games\Spring\uikeys.txt
Portable mode: yes
Compile Time Apr  3 2015 03:18:59
Compiled with wxWidgets 2.9.5.0
Started with: 
C:\Users\Floris\Documents\My Games\Spring\springlobby.exe

**Comment by abma** [comment]
springlobby only deletes replays which have a filesize of 0:

https://github.com/springlobby/springlobby/blob/master/src/replaylist.cpp#L83

whats the exact path of such an replay?

**Comment by Ruwetuin** [comment]
ah that explains... If a game get launched, a replay file(name) gets created that has filesize 0. It wont fill lthe replay file until spring exits. So if you close springlobby and stil lare ingame, and then openspringlobby, it tries to delete that replay, but its not allowed because it is in use by currently running spring.

**Comment by abma** [comment]
on linux this has the bad side-effect of the demofile beeing deleted when spring is already running.

**Comment by abma** [comment]
imo a better fix would be to add the (broken) file to the list of replays and mark it as broken (and don't auto delete it)
