### ISSUE TITLE
Can't choose starting position before game in BattleRoom Map

### ISSUE THREAD

**Issue by LinLo** [springlobby/springlobby#398]
Since 214, on multiplayer BattleRoom Map tab, I can't set starting position.
Player icon returns at top left of the map.

**Comment by abma** [comment]
oops, thanks for reporting!

**Comment by FabriceFABS** [comment]
I removed cache dir to be sure in .springlobby before starting SL, but sorry this problem still occurs today on 0.243-196-g878a71f under Linux...
BUT this problem is fixed on Windows (V0.243).

**Comment by abma** [comment]
works for me. please give instructions how to reproduce.

**Comment by LinLo** [comment]
All map start positions are at top left corner but you can move player icons. Reproduced with 0.243-218-gf20cd8b.

**Comment by abma** [comment]
should be fixed by:
https://github.com/springlobby/springlobby/commit/b753e48bf1b76a48d6af3c7c34214351acf8565b
