### ISSUE TITLE
Dialog windows expand bug

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#402]
Sometimes they cover the whole window, like this one ("Save settings before exit?")
![dialogwindow](https://cloud.githubusercontent.com/assets/9379087/7101485/9e4a4600-e064-11e4-82d5-d8c787ef8498.png)

I've seen this also with "download map/game" dialog.
Version: 0.217-4-g36cd8e5

**Comment by abma** [comment]
never seen this, maybe related to #379 ?!

**Comment by jet-bird** [comment]
Don't know... some more info: looks like they just inherit main window size, and I am still able to resize them back to normal state.

**Comment by Usaga** [comment]
This is ALTlinux?

**Comment by jet-bird** [comment]
Yes, it is :)

**Comment by abma** [comment]
did you manually resize the window?

springlobby doesn't store/load size settings for this message box, its "default" -> imo no bug.

**Comment by jet-bird** [comment]
Yes, I did (tried to make them smaller), but these dialogs don't remember the small (normal size) and grow up every next time.

**Comment by abma** [comment]
please retry with the latest version. springlobby requires wxWidgets 3.0 at least which fixes A LOT of bugs.
