### ISSUE TITLE
Scroll at battle room bug

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#406]
Steps for reproducing of bug:
1) set resolution of screen 1366x768
2) Enter battle room
![untitled-1](https://cloud.githubusercontent.com/assets/11837119/7125601/fdf2a2b4-e23a-11e4-9eb1-60f6febe6d79.jpg)
3) Scroll to right.
![untitled-2](https://cloud.githubusercontent.com/assets/11837119/7125602/fdf4d9bc-e23a-11e4-957d-782bf03cabab.jpg)
4) Click at ready button
![untitled-3](https://cloud.githubusercontent.com/assets/11837119/7125600/fdf18b5e-e23a-11e4-9a82-c2334dd4bc37.jpg)
5) Scroll back. As you can see, a lot of free space is appeared before controls.
![untitled-4](https://cloud.githubusercontent.com/assets/11837119/7125637/4d46c5ac-e23b-11e4-8699-b48c42cbd126.jpg)

**Comment by Usaga** [comment]
Yup,  I can reproduce it. Very strange bug

**Comment by Usaga** [comment]
As a temprorary solution, please, activate command "Изменить" -> "Сбросить компоновку". This should reset GUI layout and bring it to its normal state.

**Comment by abma** [comment]
i'Ve completely removed this scrollbar:

**Comment by abma** [comment]
(this introduces new problems, see: #408 )
