### ISSUE TITLE
column width in battlelist isn't saved/loaded any more

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#407]
https://github.com/springlobby/springlobby/commit/da534cf556de8ef46726dacd83d6b982962eff81

**Comment by Usaga** [comment]
This is happening only in battlelist?

**Comment by abma** [comment]
didn't check other places, but there it is pretty annoying as rows are always to small.

**Comment by abma** [comment]
list of replays is affected, too

**Comment by Usaga** [comment]
Hm. Under Windows all is ok. I can not do something with it right now, only after work. But you can try to add sett().SaveSettings() to customvirtlistctrl.cpp to the end of method AdjustColumnWidth. Or wait until I fix it after work...

**Comment by Usaga** [comment]
And sorry for that, I double checked it on Windows, all used to work well...

**Comment by abma** [comment]
no worries! this a general problem/feature with wxwidgets as it tries to use native platform gui and because of that it sadly often behaves different on linux. :-|

**Comment by abma** [comment]
ah, width of columns is applied to the description and not the contents.... thats whats happening atm.

**Comment by Usaga** [comment]
Hmm... I thought width of column is set by header only when list is been initialize, then it ovverides by sizes stored in configuration file...

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/da534cf556de8ef46726dacd83d6b982962eff81#diff-0446738ba3380658a3ab4db82f568232L321

which isn't stored any more?!
