### ISSUE TITLE
Voting panel in BattleRoomTab

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#410]
I have idea (and russian community approves it): add small panel under chat line in battleroomtab that will help to handle votes in chat. It might consist of staticText and three (or only two) buttons with icons or short labels (!y, !n). If there is vote started, label should show its description ("vote called for blah-blah command") and buttons might be used (along with accelerations shortcuts) for voting. When user had voted, buttons will be hidden. If there is no voting label is cleared and no buttons are shown. I can do this using wxPanel, so this tool could be placed anywhere in ChatRoomTab if there will be need for refactoring UI.

I think this will be very helpfull in battle with a lot of players in it. In such situation there is a huge chatting activity and sometimes it is really hard to understand what is voting about.

**Comment by abma** [comment]
TODO:

- fix compile: https://travis-ci.org/springlobby/springlobby/builds
- move detection of a vote out from gui + add events for it, sth. like OnVoteBegin / OnVoteCanceled  ...

also side notes:
- next time please use real tabs: https://github.com/springlobby/springlobby/commit/6cd2db98dac522bd9670890317a8b718a5e3f21e
- include as few other headers as possible in header files: https://github.com/springlobby/springlobby/commit/62956b9b6033cb2c4528bc38a5c95cdfa79aa9c1 (its VERY bad design/style when everything depends on everything)

**Comment by specing** [comment]
Is this done now? Can the issue be closed?

**Comment by Usaga** [comment]
@specing it was done three years ago. It need some refactoring but it works.
