### ISSUE TITLE
Hidden "Ready" checkbox

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#412]
Window size: 899x747 px.
![dialogwindow2](https://cloud.githubusercontent.com/assets/9379087/7339005/e98851f2-ec67-11e4-8805-b251f3c39380.png)

You can't see "ready" checkbox and forced to resize window to 1292(!)x747 px to see only checkbox (without "ready" label).
![dialogwindow3](https://cloud.githubusercontent.com/assets/9379087/7339006/eda9b7bc-ec67-11e4-8bea-6c0b839ab7f5.png)

**Comment by abma** [comment]
see #408

(as workarround increase window width)
