### ISSUE TITLE
crash under mac (springlobby 0.218  + mac os x 10.10.3)

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#413]
springlobby 0.218  + mac os x 10.10.3

1) I installed lobby from here https://springrts.com/phpbb/viewtopic.php?f=65&t=32970
2) I opened it and entered my existing account info into "register form"
3) It said smth like "user already registered" and crashed

http://pastebin.com/DRRJ8xJ7

Error is reproducible. I reproduced it 2 times. Also it asks "download 98 engine"? and I choose "no"

**Comment by JoshuaPettus** [comment]
Well there is no 98 engine for osx.  There were compile errors that have since been fixed.  Not sure about the logging in part.  It seems to work for me.  Do you have a windows computer? and can you log in there?

**Comment by abma** [comment]
@jamerlan 

can you run springlobby please with gdb attached and reproduce the crash and paste the stacktrace please?

i.e.:

   gdb src/springlobby
   run
   ... let it crash
   bt

**Comment by jamerlan** [comment]
done :-)
http://pastebin.com/QvZhdtJg

**Comment by abma** [comment]
note to myself:
check return of GetLocal():
https://github.com/springlobby/springlobby/blob/master/src/socket.cpp#L339
http://docs.wxwidgets.org/3.0/classwx_socket_base.html#a1751b32af0172a30f544068100ba90d2

hopefully this fixes the crash...
