### ISSUE TITLE
Sometimes user list at battle room stops refresh

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#418]
It's old bug and it was fixed but at last version it's appears again.
![untitled-3](https://cloud.githubusercontent.com/assets/11837119/7442792/040d64b6-f129-11e4-8052-b4ceec326252.jpg)

Helps only "Reset layout" and restart lobby.

**Comment by richardba** [comment]
I endorse

**Comment by abma** [comment]
"sometimes" ... does it happen after map changes?

**Comment by do2005** [comment]
At current moment i don't detected steps for reproducing of bug. But it's occurs often. Will try to detect.

**Comment by abma** [comment]
maybe this?

https://support.microsoft.com/en-us/kb/3048761

(please install the update and test)

**Comment by do2005** [comment]
OK, will be test

**Comment by do2005** [comment]
Fix Installed. Issue is present.

**Comment by abma** [comment]
can someone bisect this? i can't reproduce this bug on linux :-|

**Comment by Usaga** [comment]
I will try. I see this bug sometimes.

**Comment by do2005** [comment]
I have this issue very often, but i didn't found steps for reproduce

**Comment by knorker** [comment]
This also happens on win vista and win 7.
I have seen it on v0.219 and on v0.222

It can be  "fixed" by clicking into the playerlist to highlight it
(like on https://cloud.githubusercontent.com/assets/11837119/7442792/040d64b6-f129-11e4-8052-b4ceec326252.jpg ) and then use up&arrow keys to "drive" up/down through it...that refreshes it and list becomes readable.
Bit quicker than restarting lobby all the time.

**Comment by abma** [comment]
can you test if http://springlobby.info/temp/builds/abma/sl_master.zip fixed it for you please?

**Comment by abma** [comment]
no feedback -> i assume it is fixed

**Comment by do2005** [comment]
How it can be fixed if you didn't do new version? Still testing...

**Comment by abma** [comment]
download the link i provided and test that version of springlobby...

**Comment by do2005** [comment]
Last build - issue still present

**Comment by Usaga** [comment]
We are working on it. List widgets are been reimplemented, it is need some time to finish. Please, wait.

**Comment by abma** [comment]
should be fixed in development version

**Comment by do2005** [comment]
Issue still present!!! When it will be fixed at last?

**Comment by abma** [comment]
which version are you using?

**Comment by do2005** [comment]
0.225
