### ISSUE TITLE
Crash when trying to join a host. 

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#419]
Happens nearly always after you have returned from an idle period.

**Comment by abma** [comment]
windows/linux? springlobby version?

**Comment by Ruwetuin** [comment]
windows 8.1, 0.218

**Comment by abma** [comment]
do you join by double-click or by select item + join?

**Comment by Ruwetuin** [comment]
doubleclick

**Comment by abma** [comment]
i can't reproduce this crash, this is why i've to ask:
do you join hosts which use different engine versions?

**Comment by Ruwetuin** [comment]
blackholehost 1 or 2 usually

**Comment by Usaga** [comment]
This crash is showing itself only on Windows...

**Comment by do2005** [comment]
This bug maybe connects with sorting of battle list. It is necessary to sort out the battle and then wait for auto-update list. Very often after this at click at battle opens other battle than i clicked or i got the crash.

**Comment by MajBoredom** [comment]
Try running in debug mode / inside gdb and see if you can get a stack trace.

**Comment by abma** [comment]
imo fixed: join via double click / button seems to work reliable...

fix will be included 0.220, if it doesn't work there please reopen or create a new bug report :)

thanks!
