### ISSUE TITLE
Stable crash at internet disconnection

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#422]
Steps for reproduce:
1) Join to battle room
2) remove RJ-45
3) Waiting about 40 sec for disconnection from spring server.
4) insert RJ-45
5) Click at any tab. For example at battle list tab

I got the same situation when my internet provider gives me new IP.

**Comment by abma** [comment]
should be fixed by this change:

https://github.com/springlobby/springlobby/commit/f26e3b7b99b00a52693295676e6657ecdae28aa7#diff-5ffccd6da603ee57b4057e78a3da54bdL790

userlist wasn't always cleared after disconnect
