### ISSUE TITLE
Ring notification throws from the runned game

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#423]
Ring notification or friend come/leave notification throws me from the runned game. When i got notification the game went to minimize.

I don't know it this the bug of lobby or the spring but it hasn't occurs some time ago.
Win7 x64.

**Comment by abma** [comment]
did you restart springlobby while the game was/is running?

**Comment by do2005** [comment]
sure not

**Comment by abma** [comment]
please edit springlobby.conf and check if
[GUI]
NotificationPopupDisableIngame = 1
