### ISSUE TITLE
springlobby-0.195/src/downloader/lib/src/FileSystem/AtomicFile.cpp:27: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [springlobby/springlobby#424]
springlobby-0.195/src/downloader/lib/src/FileSystem/AtomicFile.cpp:27:44: warning: comparison of constant '0' with boolean expression is always false [-Wbool-compare]

 if (fileSystem->Rename(filename, tmpname)<0) {

**Comment by abma** [comment]
thats already fixed...

https://github.com/spring/pr-downloader/commit/3603896b2b2e5d1b04bedf5b2f05054bcb2d5c6e#diff-5b5474c92ce5445e119bb74bb30a3a19R27
