### ISSUE TITLE
Segmentation fault in IBattle:OnUserAdd(User&)

### ISSUE THREAD

**Issue by MajBoredom** [springlobby/springlobby#425]
The title says it all. Maybe this is tracked elsewhere but it happened while I was afk and I wanted to keep record of it:

Program received signal SIGSEGV, Segmentation fault.
0x000000000056863c in IBattle::OnUserAdded(User&) ()

**Comment by MajBoredom** [comment]
Unfortunately I forgot to collect the stack trace. Oh well :I next time.

**Comment by MajBoredom** [comment]
Here is one:
#0  0x000000000056863c in IBattle::OnUserAdded(User&) ()
#1  0x0000000000538bed in Battle::OnUserAdded(User&) ()
#2  0x000000000058e8b3 in ServerEvents::OnUserJoinedBattle(int, std::string const&, std::string const&) ()
#3  0x00000000005c8ea5 in TASServer::ExecuteCommand(std::string const&, std::string const&, int) ()
#4  0x00000000005d09d1 in TASServer::ExecuteCommand(std::string const&) ()
#5  0x00000000005d124f in TASServer::OnDataReceived() ()
#6  0x00000000005923bd in Socket::OnSocketEvent(wxSocketEvent&) ()
#7  0x000000350c87242e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /lib64/libwx_baseu-3.0.so.0
#8  0x000000350c9e5492 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /lib64/libwx_baseu-3.0.so.0
#9  0x000000350c9e5543 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /lib64/libwx_baseu-3.0.so.0
#10 0x000000350c9e589d in wxEvtHandler::TryHereOnly(wxEvent&) () from /lib64/libwx_baseu-3.0.so.0
#11 0x000000350c9e5913 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /lib64/libwx_baseu-3.0.so.0
#12 0x000000350c9e5975 in wxEvtHandler::ProcessEvent(wxEvent&) () from /lib64/libwx_baseu-3.0.so.0
#13 0x000000350c9e69a3 in wxEvtHandler::ProcessPendingEvents() () from /lib64/libwx_baseu-3.0.so.0
#14 0x000000350c875ff7 in wxAppConsoleBase::ProcessPendingEvents() () from /lib64/libwx_baseu-3.0.so.0
#15 0x00007ffff6bd53d2 in wxApp::DoIdle() () from /lib64/libwx_gtk3u_core-3.0.so.0
#16 0x00007ffff6bd54e3 in wxapp_idle_callback () from /lib64/libwx_gtk3u_core-3.0.so.0
#17 0x000000387f647dc6 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#18 0x000000387f648118 in g_main_context_iterate.isra.22 () from /lib64/libglib-2.0.so.0
#19 0x000000387f64851a in g_main_loop_run () from /lib64/libglib-2.0.so.0
#20 0x00000031d6d8a51d in gtk_main () from /lib64/libgtk-3.so.0
#21 0x00007ffff6be8c25 in wxGUIEventLoop::DoRun() () from /lib64/libwx_gtk3u_core-3.0.so.0
#22 0x000000350c8b4c50 in wxEventLoopBase::Run() () from /lib64/libwx_baseu-3.0.so.0
#23 0x000000350c87450d in wxAppConsoleBase::MainLoop() () from /lib64/libwx_baseu-3.0.so.0
#24 0x000000350c9005fd in wxEntry(int&, wchar_t**) () from /lib64/libwx_baseu-3.0.so.0
#25 0x00000000004d8818 in main ()

**Comment by abma** [comment]
what are you doing when this crash happens?

**Comment by abma** [comment]
ok, answered it myself.

it seems it was a lobbyserver inconsistency which made springlobby crash:

i guess a user which was still in a battle but wasn't on lobby server.

**Comment by abma** [comment]
also as note: workarrounded server side (for the moment)
