### ISSUE TITLE
Long lag delays & disconnects

### ISSUE THREAD

**Issue by MajBoredom** [springlobby/springlobby#427]
Since 2015-05-06 or so, I have been experiencing very long lag effects. It seems to be the connection to uber because I do not experience this in-game or on my other open connections. There will be a long silence in lobby, followed by 20+ lines of text that all have the same timestamp. 

Springlobby will notice the lack of traffic and will disconnect itself after 90 seconds of inactivity. I have raised this hard-coded limit to 600 seconds but even so, springlobby will disconnect me at least once or twice a day. It looks just like standard network lag but I have verified that it occurs only with the connection to uber and does not affect ingame play nor other TCP traffic (web browsing).

**Comment by abma** [comment]
next time when this happens can you please update this post here with the time when it happened? i'll look into server logs then...

**Comment by abma** [comment]
whats your usual ping time? (bottom right of springlobby)
