### ISSUE TITLE
(v0.217) reversed line of chat 

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#428]
![springlobby_chat_backwards](https://cloud.githubusercontent.com/assets/3044855/7556242/2a9ab00c-f769-11e4-9a93-b54965035846.png)

no idea how

**Comment by abma** [comment]
same question here, does it happen with springlobby 0.219, too?

**Comment by knorker** [comment]
no idea how to reproduce it, it happend randomly and only once so far -> can not test it..

**Comment by Usaga** [comment]
Maybe this is happened after some specific text was printed in chatbox that might be recognized as some sort of reversion command by wxWidgets?

**Comment by springraaar** [comment]
maybe raaar is to blame

**Comment by abma** [comment]
seems to fixed in 0.236. as wxwidgets was updated there it was a wxwidgets bug.
