### ISSUE TITLE
(v0.217) Lots of "Map does not exist!" error boxes

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#429]
![springlobby_map_not_exist_boxes](https://cloud.githubusercontent.com/assets/3044855/7556247/557554b2-f769-11e4-8474-99cf280c06aa.png)

when going to map-selection screen in multiplayer (i think)
I do not remember changing anything or deleting maps.
Some days ago I tried out the new zero-K lobby, had not played since then. 
Even with deleted maps, there should be some limit to how many error boxes can pop up.

**Comment by abma** [comment]
does this happen with springlobby 0.219, too?

**Comment by Usaga** [comment]
This was fixed with 8cca9a5d707cb4f66495b44ec9e461d46916d240 since v 0.219

**Comment by knorker** [comment]
yes, does not seem to happen anymore in 0.219

**Comment by knorker** [comment]
Happens again in v0.236
The dialogboxes do not appear all at once now, instead appear one by one.
Maybe related to deleting content of maps\ from time to time. But it is after having done "reload maplist" several time.
