### ISSUE TITLE
springlobby sends invalid OPENBATTLE when description containts a tab character

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#430]
This is old version again (some minutes before update) but maybe still interessting, so..

A strange room (apart from the obscenity):
http://abload.de/img/springlobbby_nota_is_0mjwv.png
-The description/title field is empty.
-The mod's name is the description:
Both in the list and in details field at bottom.

On friends PC with different lobby it looked like this, the mod was actually NOTA:
http://abload.de/img/123wtsy9.jpg

**Comment by Usaga** [comment]
SpringLobby might got embarrassed by 'Anal with Nina' phrase so it confused with columns order. It is too young for this!

**Comment by abma** [comment]
ah, easy to reproduce:

host a game which contains a tab in the description

**Comment by abma** [comment]
will be fixed by:
https://github.com/spring/uberserver/commit/abc67b08d1851b23af9b6c43374faed82441c885

and

https://github.com/spring/uberserver/issues/169

**Comment by abma** [comment]
aww... wait:

springlobby can send this, too: this has to be fixed by replacing \t with space (x8?)
