### ISSUE TITLE
remove autohost / battle presets?

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#431]
it seems it wasn't used as it was broken and nobody complained.

shall it be removed or is it needed / still useful?

as note: maybe singleplayer/offline mode gets merged into multiplayer at some point. it already works, but gui is... uhm... i need ideas for that :D

@Usaga @MajBoredom

![presets-autohostcontrols](https://cloud.githubusercontent.com/assets/301564/7622680/f98b3fb6-f9d1-11e4-8921-42b5149fc5e2.png)

**Comment by abma** [comment]
part of #408

**Comment by Usaga** [comment]
As for me Manage Presets looks like completely usefull. I do not know anyone how had used this at least once))) But I had used Player Management very often when relayhost was live, to play with friends behind the NAT. May be this will usefull again sometime?..

**Comment by abma** [comment]
it can be used to save/store battle settings. not sure whats stored, i guess everything: map + game settings.

ok, when you use it at least its ok to keep it :)
