### ISSUE TITLE
crash when trying to enter chicken defence v3.15 battleroom

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#436]
I have a crash if I dont run using gdb. And I got a freeze when I run it with gdb:
http://pastebin.com/uBzCtMzT
(lobby was compilled from sources yesterday 0.219+)

**Comment by jamerlan** [comment]
steps to reproduce:
just try to join battleroom with chicken defence v3.15

**Comment by abma** [comment]
oh, duplicate of #444

http://paste.springfiles.com/view/raw/bee06e7f
