### ISSUE TITLE
Userdoc

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#437]
I assume https://github.com/springlobby/springlobby/wiki/Userdoc is the manual meant for players.

- pictures hosted on third party site (imagebin.ca) are all dead

- These sites are linked:
http://springfiles.com - http://www.darkstars.co.uk/downloads/ - http://spring-portal.com - http://www.tasdownloads.com
Only springfiles.com is still useful for players. 
(http://www.darkstars.co.uk/downloads/ only has few VERY old files, the other two are dead)

- Some text reads quite strange, for ex. games are described like this:
> The Mod files tell the Spring engine what the rules are for navigating and getting to dominate the environment and your enemy. 

-" ... /spring/mods ... "   changed to spring/games

- > The maximum number of players for each battle-room is displayed under the m-column. The number of active players for each battle-room is displayed under the P-column. The number of spectators for each battle room is displayed under the A-column. 
> ...the Rank Limit (under the R column),
> ... The country (under the C column) tells you where the host is located

At least with german language the columns have proper titles , so they do not need explaining anymore.

**Comment by abma** [comment]
feel free to change it, its a wiki!

(also springfiles.com isn't dead)
