### ISSUE TITLE
error message in springlobby 0.219+

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#438]
I got popup with this error:

logic error ( /home/revenant/springlobby/src/serverevents.cpp:128 ): New user from server, but already exists!

Probably its better to just log it. Not to display via popup

**Comment by jamerlan** [comment]
OnUserJoinedBattle(): Lobby server inconsistency: user in battle which doesn't exist. Please report as lobby server bug!

**Comment by jamerlan** [comment]
I have messages like that (see above). Cant join any battleroom!

**Comment by jamerlan** [comment]
latest lobby (0.219-7-g926cda5)

**Comment by abma** [comment]
this message is annoying for users, yes, but it shouldn't happen. if it does, sth. is horrible broken at lobby server, so better let this message stay and people complain at bug trackers... imo.
