### ISSUE TITLE
Messages in log are not clear. Please check

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#439]
Hi! I have error messages (that is good) in console during springlobby start. But looks like error message contains the same path 2 times. Probably its a typo in string concatenation? OR another path was not specified. Is it possible to show both places?

Error: Found a "tempest.sd7" already in "/home/revenant/.spring/maps/", ignoring one in "/home/revenant/.spring/maps/"

**Comment by abma** [comment]
thats a message from unitsync.

to "fix" delete /home/revenant/.spring/maps/tempest.sd7 (its already there with a different file name)

**Comment by abma** [comment]
hmm.. what do you suggest, how to make this clear?

**Comment by jamerlan** [comment]
I suggest to show all paths for that file. For example:
Error: Found multiple copies of this file "tempest.sd7":
1) "/home/revenant/.spring/maps/tempest.sd7"
2) "/home/revenant/.spring/games/tempest.sd7", ignoring this one
3) "/home/revenant/games/spring98/maps/tempest.sd7", ignoring this one

**Comment by abma** [comment]
hmm, thats a feature request for spring's unitsync...

**Comment by jamerlan** [comment]
I dont know where to fill these change requests :-) So I created it as a bug report here: https://springrts.com/mantis/view.php?id=4784

Thanks, abma!

**Comment by jamerlan** [comment]
(closing this issue because its not springlobby related)
