### ISSUE TITLE
0.219 fails to build from source springlobby_config.h: No such file or directory

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#440]
Hello,

I tried to build the latest version, 0.219, on Debian GNU/Linux but this version fails to build from source. Apparently springlobby_config.h cannot be found or does not exist.

[ 89%] Building CXX object src/CMakeFiles/springlobby.dir/utils/version.cpp.o
cd /tmp/buildd/springlobby-0.219/obj-x86_64-linux-gnu/src && /usr/bin/c++   -DHAVE_LIBNOTIFY -DLOCALE_INSTALL_DIR=\"/usr/share/locale\" -DSPRINGLOBBY_CONFIGH=\"/tmp/buildd/springlobby-0.219/obj-x86_64-linux-gnu/springlobby_config.h\" -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DNDEBUG  -std=gnu++11             -Wextra -Wall -Wno-strict-aliasing -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -I/tmp/buildd/springlobby-0.219/src -I/tmp/buildd/springlobby-0.219/src/lsl/src -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include    -o CMakeFiles/springlobby.dir/utils/version.cpp.o -c /tmp/buildd/springlobby-0.219/src/utils/version.cpp
/tmp/buildd/springlobby-0.219/src/utils/version.cpp:7:29: fatal error: /tmp/buildd/springlobby-0.219/obj-x86_64-linux-gnu/springlobby_config.h: No such file or directory
 #include SPRINGLOBBY_CONFIGH
                             ^
compilation terminated.
src/CMakeFiles/springlobby.dir/build.make:2495: recipe for target 'src/CMakeFiles/springlobby.dir/utils/version.cpp.o' failed
make[4]: *** [src/CMakeFiles/springlobby.dir/utils/version.cpp.o] Error 1
make[4]: Leaving directory '/tmp/buildd/springlobby-0.219/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:363: recipe for target 'src/CMakeFiles/springlobby.dir/all' failed
make[3]: *** [src/CMakeFiles/springlobby.dir/all] Error 2
make[3]: Leaving directory '/tmp/buildd/springlobby-0.219/obj-x86_64-linux-gnu'
Makefile:139: recipe for target 'all' failed
make[2]: *** [all] Error 2

**Comment by abma** [comment]
does it compile after you run "make version"?

**Comment by apoleon** [comment]
*** No rule to make target 'version'.  Stop.

No, that doesn't work.

**Comment by abma** [comment]
as workarround copy this file http://paste.springfiles.com/view/raw/dd88036b

will fix this, but will take a bit...
