### ISSUE TITLE
all battles get selected when a selected battle gets closed

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#441]
to reproduce:

host battle, select your battle in battle list, close battle

-> all battles are selected

(afaik thats an old bug)

**Comment by Usaga** [comment]
Can not reproduce it under Windows... It's been a while since I saw this bug last time. Does it reproduces stable?

**Comment by abma** [comment]
yep, i can always reproduce it. all battles selected seems to disappear after a "refresh" / resort, so you have to be fast to see it.
