### ISSUE TITLE
0.219 doesn't build on gentoo (springlobby_BINARY_DIR vs springlobby_SOURCE_DIR)

### ISSUE THREAD

**Issue by OursDesCavernes** [springlobby/springlobby#443]
Hello,

A change from 0.218 to 0.219 doesn't work on gentoo.
You search for springlobby_config.h in springlobby_BINARY_DIR instead of springlobby_SOURCE_DIR.
This doesn't matter when you build within the sources (springlobby_BINARY_DIR = springlobby_SOURCE_DIR) but fails with build systems that build in a separate directory (Gentoo works this way).

${springlobby_BINARY_DIR}/springlobby_config.h
should be:
${springlobby_SOURCE_DIR}/springlobby_config.h

The following patch fixes the issue on my system (2 lines change):

diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 20df4e1..8cb2976 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -288,9 +288,9 @@ add_custom_command(OUTPUT ${springlobby_BINARY_DIR}/springlobby_config.h
                        COMMAND ${springlobby_SOURCE_DIR}/tools/regen_config_header.sh ${springlobby_SOURCE_DIR} ${springlobby_BINARY_DIR}
                )
 
-set_property(SOURCE utils/version.cpp APPEND PROPERTY OBJECT_DEPENDS ${springlobby_BINARY_DIR}/springlobby_config.h)
+set_property(SOURCE utils/version.cpp APPEND PROPERTY OBJECT_DEPENDS ${springlobby_SOURCE_DIR}/springlobby_config.h)
 
-set_source_files_properties(utils/version.cpp PROPERTIES COMPILE_DEFINITIONS SPRINGLOBBY_CONFIGH="${springlobby_BINARY_DIR}/springlobby_config.h")
+set_source_files_properties(utils/version.cpp PROPERTIES COMPILE_DEFINITIONS SPRINGLOBBY_CONFIGH="${springlobby_SOURCE_DIR}/springlobby_config.h")
 
 
 FILE( GLOB header "*.h" )

**Comment by abma** [comment]
@OursDesCavernes 
this change broke compile on the buildslave: http://buildbot.springlobby.info/builders/abma-win/builds/764/steps/buildConfig/logs/stdio

can you please test if my fix for the buildslave didn't break it on gentoo?
https://github.com/springlobby/springlobby/commit/e81834da4f2462f6d3dd868a8b1c1ae4d55c4804

thanks! :)

**Comment by OursDesCavernes** [comment]
I've tested the latest version version (CONFIGH) on gentoo and it works.
Thanks
