### ISSUE TITLE
[0.219 error new regression from 0.210] can't create file ...

### ISSUE THREAD

**Issue by MetaMemoryT** [springlobby/springlobby#449]
full error message when trying to connect from a local uberserver:

```
can't create file
'C:\Users\Brian\AppData\Roaming\springlobby\chatlog\10.180.124.105:8200\server.txt' (error 123:
the filename, directory name, or volume label syntax is incorrect.)
```

I think this bug is because the C++ code is not sanitizing the colon (:) in the pathname as no colons are allowed on FAT32 file paths.

I think this error is being created from here:

https://github.com/springlobby/springlobby/blob/ac32b6ee1ba06177441465d3e33e33eef0f97104/src/utils/slpaths.cpp#L286

could be related:

https://github.com/springlobby/springlobby/issues/143

https://github.com/springlobby/springlobby/issues/127

**Comment by abma** [comment]
whats the output of help->system info?

**Comment by abma** [comment]
oops, forget it... will check

**Comment by MetaMemoryT** [comment]
SpringLobby 0.219 (win x32)
SpringLobby config file: C:\Users\Sean\AppData\Roaming\springlobby\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\Sean\AppData\Roaming\springlobby\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\Sean\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Users\Sean\s\springlobby-0.210-win32\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Sean\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\Sean\Documents\My Games\Spring\engine\98.0.1-451-g0804ae1\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Users\Sean\Documents\My Games\Spring\engine\98.0.1-451-g0804ae1\unitsync.dll
Current spring executable: C:\Users\Sean\Documents\My Games\Spring\engine\98.0.1-451-g0804ae1\spring.exe
Current uikeys.txt: C:\Users\Sean\Documents\My Games\Spring\engine\98.0.1-451-g0804ae1\uikeys.txt
Portable mode: no
Compiled with wxWidgets 2.9.5.0
Started with: 
C:\Users\Sean\s\springlobby-0.210-win32\springlobby.exe

**Comment by MetaMemoryT** [comment]
Do you need any other debug info?

**Comment by abma** [comment]
no, i was just blind :-)

**Comment by abma** [comment]
thats a build from the current development branch:
http://springlobby.info/temp/builds/abma/sl_master.zip

(if you want to test...)

just ignore the updater message that a new version is available when you use it.

**Comment by abma** [comment]
should be version 0.219-49-g8625924 or greater

**Comment by MetaMemoryT** [comment]
Thanks for quick response!

**Comment by MetaMemoryT** [comment]
Appears to be working! good job!
