### ISSUE TITLE
crash at exit

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#450]
Program received signal SIGSEGV, Segmentation fault.
0x00000000019e4fb0 in ?? ()
(gdb) bt
0  0x00000000019e4fb0 in ?? ()
1  0x00007ffff65e6f05 in wxWindowBase::~wxWindowBase() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
2  0x00007ffff63ca0e8 in wxWindow::~wxWindow() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
3  0x00007ffff63bf4f2 in wxTopLevelWindowGTK::~wxTopLevelWindowGTK() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
4  0x0000000000994769 in CustomMessageBox::~CustomMessageBox (this=0x1b9c030, __in_chrg=<optimized out>)
    at src/gui/customdialogs.cpp:119
5  0x0000000000994798 in CustomMessageBox::~CustomMessageBox (this=0x1b9c030, __in_chrg=<optimized out>)
    at src/gui/customdialogs.cpp:122
6  0x00007ffff5ccfb32 in wxAppConsoleBase::DeletePendingObjects() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
7  0x00007ffff5ccfbb1 in wxAppConsoleBase::ProcessIdle() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
8  0x00007ffff6488993 in wxAppBase::ProcessIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
9  0x00007ffff637ee0e in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
10 0x00007ffff637ef43 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
11 0x00007ffff188bb4d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
12 0x00007ffff188bf20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
13 0x00007ffff188c242 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
14 0x00007ffff25f9857 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
15 0x00007ffff63a0745 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
16 0x00007ffff5d15750 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
17 0x00007ffff5cd1a46 in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
18 0x00007ffff5d6c660 in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
19 0x000000000078d3fa in main (argc=1, argv=0x7fffffffe3d8) at src/springlobbyapp.cpp:67

**Comment by Usaga** [comment]
Apparently this might be caused by e0ffe08a5c3e0d1076dfa5702241800205bf35e5 
Perhaps I have to used wxDELETE(GetSizer()) instead of delete this->GetSizer()

**Comment by abma** [comment]
why are these deletes needed at all? doesn't wxWidgets do refcounting / free when not used any more?

**Comment by abma** [comment]
ok, seems not all wx objects are refcounted: http://docs.wxwidgets.org/3.0/overview_refcount.html

**Comment by Usaga** [comment]
No, it does not. I checked. Under Windows at least.

**Comment by Usaga** [comment]
Looks like wxWindow deletes nothing when it gets destoyed. Only manually deleted main sizer start chain of destructors invocation... This is odd, actually.)))

**Comment by abma** [comment]
after my change it crashes this way: http://paste.springfiles.com/view/raw/eaab6293

is https://github.com/springlobby/springlobby/commit/a165e78bf8cec936ab8741e792cdec15c78718a7 a proper fix for this?

**Comment by abma** [comment]
and yes, always nullify pointers after deletes! this safes a lot of headache when debugging...

**Comment by Usaga** [comment]
No, as I estimate due to my experiments, all you have to do is to delete topmost sizer (that contains all other sizers and controls) and it will properly calls destructors of all its elements...
So this should be enough:
blah::~blah()
{
wxDELETE(GetSizer());
}

**Comment by Usaga** [comment]
And yes, it does not crash for me. Maybe this is because platform realization defference... Feel free fix it in your way)) Your the boss))

**Comment by Usaga** [comment]
And I did not nullified pointer because there wasn't any. Or you meant to call SetSizer(nullptr)?

**Comment by abma** [comment]
hm, the more i investigate this, the more i think wxDELETE(m_main_sizer); is invalid. i can't make it work non-crashing, it always complains about double-free.

in which case did it fail for you that made you add the deletes?

**Comment by abma** [comment]
also i can't find an example where they delete wxSizer/wxBoxSizer in the destructor:

as example(s):

https://github.com/wxWidgets/wxWidgets/blob/master/samples/wrapsizer/wrapsizer.cpp
https://github.com/wxWidgets/wxWidgets/blob/master/samples/controls/controls.cpp
https://github.com/wxWidgets/wxWidgets/blob/master/samples/minimal/minimal.cpp

**Comment by abma** [comment]
can't find a better doc yet: wxWindow::Destroy():
http://docs.wxwidgets.org/trunk/classwx_window.html#a6bf0c5be864544d9ce0560087667b7fc

**Comment by abma** [comment]
ah, does this explain your problem?

wxWindow::Destroy()
Frames and dialogs are not destroyed immediately when this function is called – they are added to a list of windows to be deleted on idle time

**Comment by Usaga** [comment]
>>in which case did it fail for you that made you add the deletes?
I noticed that desctructors of derived classes from windows and controls are not called at all. I have had added wxMessageBox into different destructors and no box had shown when lobby closed. Then I derived class from wxBoxSizer and put wxMessageBox to it's dtor and replace some sizers with it. And no messages again. Then I called delete GetSizer() in dtor and saw massive MessageBox spam when lobby was about to close. And more: there were Messages from other sizers I replaced with my derived class, but those sizer was not called with delete directly!
So I thougt that wxWidgets does not deletes controls you adding to its windows due to runtime...

**Comment by Usaga** [comment]
Hm, wxWindow::Destroy() looks like an answer. But still it should call destructors at some time after lobby was closed, but non of that I saw...

**Comment by abma** [comment]
maybe it just doesn't create a messagebox on "shutdown"?

did you test with wxLog?

**Comment by Usaga** [comment]
Oh sh*t... I had tested it with logging and it worked as it should... I really sorry for this, I confused you with untested assumptions... Really, sorry((

**Comment by abma** [comment]
no worries, try and error is a good (+ fast) way to learn :)
