### ISSUE TITLE
Please make the build reproducible

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#457]
Hi,

some time ago I reported #420. I think you missed one __DATE__ and __TIME__ macro in

src/lsl/lib/cimg/CImg.h

Could this be removed too?

**Comment by abma** [comment]
hmm, i've updated cimg... is there an report upstream about this? else next time it will possible break again...

**Comment by abma** [comment]
https://github.com/springlobby/lsl/commit/176b801b2e1c7eff01ee1e3968a58f821ee7eba5
