### ISSUE TITLE
True skill column stop to work at version 0.222

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#458]
True skill column stop to work at version 0.222 after visit at blackhole server. I get "-" instead true skills.

**Comment by abma** [comment]
i guess you've answered this yourself... just to be sure:

trueskill is optional, so if autohost doesn't provide values, "-" is used.

**Comment by do2005** [comment]
I got this later at other server, but i cannot reproduce it again, so i'm close the ticket until i got it again.
