### ISSUE TITLE
Engine in single player tab affected by joining/hosing an online battle with another engine

### ISSUE THREAD

**Issue by OursDesCavernes** [springlobby/springlobby#460]
When I choose an engine (say 0.96) in the single player tab and then join/host an online battle with a different engine (say 0.98), 0.98 is launched instead of 0.96 when I come back to the single player tab and start the single player game.
If I choose the engine again, I get the right one.
I don't see this bug one the other way (changing SPBattle engine doesn't affect MPBattle engine launched) so the solution is somewhere in the MPbattleTab code.

I'll look into that, maybe one of you have a clue/tip.

**Comment by abma** [comment]
i guess a call to SetEngineVersion() is missing...

**Comment by abma** [comment]
see the FIXME

https://github.com/springlobby/springlobby/blob/master/src/gui/singleplayertab.cpp#L392

this is part of the bug imo :)

**Comment by abma** [comment]
remove both lines there and it possible already works...
