### ISSUE TITLE
0.224: test fails on 32bit i686

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#466]
Hi,

0.224 fails to build from source because one of the tests fails to execute correctly.
This only happens on a 32bit i686 architecture, x86_64/amd64 works fine.

The error message:

test 4
    Start 4: testlslconversion

4: Test command: /tmp/buildd/springlobby-0.224/obj-i586-linux-gnu/src/tests/test_lslconversion
4: Test timeout computed to be: 9.99988e+06
4: Running 5 test cases...
4: /tmp/buildd/springlobby-0.224/src/tests/lslconversion.cpp(177): error in "hashes": check "-2061996886" == LSL::Util::MakeHashSigned(LSL::Util::ToString(overflow)) failed
4:~
4: *** 1 failure detected in test suite "lobbyid"
4/5 Test #4: testlslconversion ................***Failed    0.03 sec
Running 5 test cases...
/tmp/buildd/springlobby-0.224/src/tests/lslconversion.cpp(177): error in "hashes": check "-2061996886" == LSL::Util::MakeHashSigned(LSL::Util::ToString(overflow)) failed

**Comment by abma** [comment]
bad bug, because it very likely shows status unsynced when it should show synced.

**Comment by apoleon** [comment]
On 05.06.2015 01:08, abma wrote:
> bad bug, because it very likely shows status unsynced when it should
> show synced.

Here is the full build log by the way.

https://buildd.debian.org/status/fetch.php?pkg=springlobby&arch=i386&ver=0.224-1&stamp=1433286373
