### ISSUE TITLE
add support for "spring" camera (spring 99) in springsettings

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#471]
Spring camera is new default camera in spring 99 it have its own settings like: CamSpringScrollSpeed,
 CamSpringZoomOutFromMousePos, CamSpringEdgeRotate etc (​https://github.com/spring/spring/blob/develop/rts/Game/Camera/SpringController.cpp)

These settings are hard to configure for user (no springlobby->spring settings support)

Please add at least scroll speed

**Comment by jamerlan** [comment]
Also there is ability to select default camera (radio buttons in springsettings) - new spring camera could be added too

**Comment by abma** [comment]
see #877
