### ISSUE TITLE
springlobby prompts to download already downloaded content

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#473]
take a look at screenshot attached. I have a map + game + engine but it still prompts me to download when I try to join the battle
![sl_already_downloaded](https://cloud.githubusercontent.com/assets/216801/8024515/135440ca-0d3f-11e5-9dee-6b14fdf23b00.png)

additional info:
SpringLobby 0.224-13-g1548150 (unix x64)

P.S. I did "git submodule sync; git submodule update" before compiling lobby.

**Comment by abma** [comment]
imo related to #466

**Comment by Usaga** [comment]
Great!
