### ISSUE TITLE
Could not connect to game created with RelayHost

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#479]
I can create battle with RelayHost, can setup it. But when I start the game spring launches and start counter indicating it cannot connect to server...

I tried it with the bots, I tried with my friend and my friend tried it on his machine.

**Comment by abma** [comment]
set "NAT traversal" to None.

this is already fixed in current development version (there its not possible to set it)

**Comment by abma** [comment]
uh... wait, sth. got broken again

**Comment by abma** [comment]
thats no springlobby bug, relayhost doesn't override the hostport for some reason. no clue why it worked for me but now doesn't...

**Comment by abma** [comment]
https://github.com/springlobby/relayhost/blob/master/autohost.py#L295

**Comment by abma** [comment]
fixed: https://github.com/springlobby/relayhost/commit/ee613c807499566b476d164221565398970c4030
