### ISSUE TITLE
Strange portable version at Windows

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#483]
I have Win7 x64 and i'm installed portable version of SpringLobby to drive D: (~400Mb)
But all maps/mods downloading to C:\Users\UserName\Documents\My Games\Spring\ (~4.5Gb)
What the sense of portable version if its puts the files to the drive C:? I think the "portable" word meaning portable and i'm expected to find all files of lobby at the place where it was installed.

**Comment by abma** [comment]
edit springlobby.conf and set DownloadDir to the path where it should download files. atm there is no gui setting for that.

**Comment by do2005** [comment]
This springlobby.conf is reset every time after upgrade of Lobby and this settings is lost every time. Is it possible to do springlobby.conf not resetable after upgrade?
But thanks, it's looks like temporary solution anyway.

**Comment by Usaga** [comment]
Belived to be fixed by adding ability to change DownloadDir in GUI.
