### ISSUE TITLE
failed at /usr/include/wx-3.0/wx/ctrlsub.h(144) in InsertItems(): can't insert items in sorted control. This bug is still not fixed  

### ISSUE THREAD

**Issue by Ecauzey** [springlobby/springlobby#484]
Traceback (most recent call last):
  File "/usr/local/bin/cyberdog", line 864, in OnEncrypt
    self.open_helper(e)
  File "/usr/local/bin/cyberdog", line 888, in open_helper
    dlg = EncryptionDialog(self, -1, '', self.settings, False)
  File "/usr/local/bin/cyberdog", line 288, in __init__
    self.user_acls.InsertItems(user_acls,0)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 1178, in InsertItems
    return _controls_.ListBox_InsertItems(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!IsSorted()" failed at /usr/include/wx-3.0/wx/ctrlsub.h(144) in InsertItems(): can't insert items in sorted control

**Comment by abma** [comment]
what is cyberdog?

**Comment by abma** [comment]
i don't see a relationship to springlobby...

**Comment by Ecauzey** [comment]
I've seen that error posted on your repository before. Are their any fixes
for it?

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/1212f49906e7cd8c7f38ff8d23d253dd8b1a2698

**Comment by abma** [comment]
next time READ before dumping your crap into a foreign issue tracker.

"InsertItems(): can't insert items in sorted control." imo is a pretty clear message.

also the last comment here also shows the fixing commit: https://github.com/springlobby/springlobby/issues/238
