### ISSUE TITLE
0.225: test still fails on i386 32bit error in "hashes" check

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#485]
Hi,

Old bug report:

https://github.com/springlobby/springlobby/issues/466

There is still a bug when running the tests on i386.

test 4
    Start 4: testlslconversion

4: Test command: /tmp/buildd/springlobby-0.225/obj-i586-linux-gnu/src/tests/test_lslconversion
4: Test timeout computed to be: 9.99988e+06
4: Running 7 test cases...
4: /tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(196): error in "hashes": check LSL::Util::MakeHashUnsigned("3807049253") == LSL::Util::MakeHashUnsigned("-487918043") failed
4: /tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(197): error in "hashes": check LSL::Util::MakeHashUnsigned("-2567621") == LSL::Util::MakeHashUnsigned("4292399675") failed
4: /tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(199): error in "hashes": check LSL::Util::MakeHashSigned("3807049253") == LSL::Util::MakeHashSigned("-487918043") failed
4: /tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(200): error in "hashes": check LSL::Util::MakeHashSigned("-2567621") == LSL::Util::MakeHashSigned("4292399675") failed
4: 
4: *** 4 failures detected in test suite "lobbyid"
4/5 Test #4: testlslconversion ................***Failed    0.03 sec
Running 7 test cases...
/tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(196): error in "hashes": check LSL::Util::MakeHashUnsigned("3807049253") == LSL::Util::MakeHashUnsigned("-487918043") failed
/tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(197): error in "hashes": check LSL::Util::MakeHashUnsigned("-2567621") == LSL::Util::MakeHashUnsigned("4292399675") failed
/tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(199): error in "hashes": check LSL::Util::MakeHashSigned("3807049253") == LSL::Util::MakeHashSigned("-487918043") failed
/tmp/buildd/springlobby-0.225/src/tests/lslconversion.cpp(200): error in "hashes": check LSL::Util::MakeHashSigned("-2567621") == LSL::Util::MakeHashSigned("4292399675") failed

*** 4 failures detected in test suite "lobbyid"

test 5
    Start 5: testslpaths

5: Test command: /tmp/buildd/springlobby-0.225/obj-i586-linux-gnu/src/tests/test_slpaths
5: Test timeout computed to be: 9.99988e+06
5: 12:46:54: Warning: deleting testdir/dir1/dir2
5: 12:46:54: Warning: deleting testdir/dir1
5: 12:46:54: Warning: deleting testdir/dir3/dir4
5: 12:46:54: Warning: deleting testdir/dir3
5: 12:46:54: Warning: deleting testdir
5: Running 1 test case...
5: 
5: *** No errors detected
5/5 Test #5: testslpaths ......................   Passed    0.02 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   0.53 sec

The following tests FAILED:
	  4 - testlslconversion (Failed)
Errors while running CTest

**Comment by abma** [comment]
are you sure that the used submodule lsl is up to date?

**Comment by apoleon** [comment]
Am 19.06.2015 um 14:58 schrieb abma:
> are you sure that the used submodule lsl is up to date?

I have downloaded your source tarball from

http://springlobby.info/landing/index.php

as usual.

**Comment by abma** [comment]
ok, thx, will test / fix.

**Comment by abma** [comment]
this time i tested with a 32 bit linux. i guess i should cared more about the doc for atoi:
" if the converted value would be out of the range of values representable by an int, it causes undefined behavior."

with the custom implementation, this shouldn't happen any more. thanks for reporting!

**Comment by apoleon** [comment]
Am 20.06.2015 um 22:07 schrieb abma:
> this time i tested with a 32 bit linux. i guess i should cared more
> about the doc for atoi:
> " if the converted value would be out of the range of values
> representable by an int, it causes undefined behavior."
> 
> with the custom implementation, this shouldn't happen any more. thanks
> for reporting!

You're welcome. Thanks for your outstanding work on Springlobby and Spring!
