### ISSUE TITLE
springlobby + #ru + russian topic

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#486]
I set a topic in "ru" channel a few days ago. It was working good. But now it is broken
[00:28:24] ** Channel topic:
[00:28:24] Invalid unicode-encoding (should be utf-8)
[00:28:24] ** Set by [teh]decay
how to do it properly? I did that: !topic Добро пожаловать в русскоязычное сообщество Spring RTS! http://vk.com/taspring Если возникли вопросы, можете задать в группе или здесь (отвечают не моментально! надо подождать)

Is it a springlobby related bug?

**Comment by jamerlan** [comment]
Just tested. If you set such topic and reconnect - it shows: Invalid unicode-encoding (should be utf-8)

**Comment by cleanrock** [comment]
Seem to be a uberserver problem:
CHANNELTOPIC ru [teh]decay 1434748482000 Invalid unicode-encoding (should be utf-8)

**Comment by abma** [comment]
yeah, very likely a uberserver bug, but i leave this open as its possible a springlobby bug (not sure atm)

**Comment by jamerlan** [comment]
I tried weblobby and I got the same result: Invalid unicode-encoding (should be utf-8)
that is sad

**Comment by jamerlan** [comment]
closing this bug and opening bug for uberserver https://github.com/spring/uberserver/issues/180
