### ISSUE TITLE
0.225 doesn't compile at ibattle.cpp

### ISSUE THREAD

**Issue by JoshuaPettus** [springlobby/springlobby#488]
I'm compiling on OSX with gcc4.9.  It stops with this error a couple of times.

/Users/herecomethej/springlobby/src/battle.cpp: In member function 'virtual void Battle::FixTeamIDs(IBattle::BalanceType, bool, bool, int)':
/Users/herecomethej/springlobby/src/battle.cpp:974:6: error: 'FromIntString' is not a member of 'LSL::Util'
      LSL::Util::FromIntString(CustomBattleOptions().getSingleValue("startpostype", LSL::Enum::EngineOption));
      ^

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/issues/482#issuecomment-112884511

**Comment by abma** [comment]
in short: please update git submodules!
