### ISSUE TITLE
clang: springlobby 0.225 fails to compile at chatpanel.cpp.o

### ISSUE THREAD

**Issue by JoshuaPettus** [springlobby/springlobby#491]
Hi, the reason i was messing with gcc to compile springlobby is because clang fails here:

[ 52%] Building CXX object src/CMakeFiles/springlobby.dir/gui/chatpanel.cpp.o
/Users/herecomethej/springlobby/src/settings.cpp:1456:56: error: call to 'abs' is ambiguous
        cfg().Write(_T( "/GUI/AutoloadedChatlogLinesCount" ), std::abs(count));

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:660:1: note: candidate function
abs(float __x) _NOEXCEPT {return fabsf(__x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:664:1: note: candidate function
abs(double __x) _NOEXCEPT {return fabs(__x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:668:1: note: candidate function
abs(long double __x) _NOEXCEPT {return fabsl(__x);}
^

**Comment by abma** [comment]
does it work when you change the line to

std::abs<long>(count) ? (<long double> would be weird imo)

**Comment by JoshuaPettus** [comment]
Doesn't seem to like <long>

/Users/herecomethej/springlobby/src/settings.cpp:1456:69: error: expected '(' for function-style cast or type construction
        cfg().Write(_T( "/GUI/AutoloadedChatlogLinesCount" ), std::abs<long>(count));

**Comment by abma** [comment]
github eats characters. thats what i mean: http://paste.springfiles.com/view/raw/ab8ef58e

**Comment by JoshuaPettus** [comment]
yeah, I did that sry it didn't show, here was the output
http://paste.springfiles.com/view/484b33ff

**Comment by abma** [comment]
oh, this function is no template, try this:

std::abslong((long)count)
or:
(long)std::abslong(count)
or:
(long)std::abslong((long)count)

**Comment by JoshuaPettus** [comment]
says "error no member named abslong in namespace standard"

**Comment by abma** [comment]
you forgot the colons...

**Comment by JoshuaPettus** [comment]
If I did, it wouldn't know to look in namespace std. I copy pasted.

**Comment by abma** [comment]
then the brackets are missing

**Comment by abma** [comment]
abslong makes no sense at all. can be only abs((long)count)

**Comment by JoshuaPettus** [comment]
I agree,  abslong doesn't seem to work.  I did a quick google looks like this springmeyer knows whats up

https://github.com/Project-OSRM/osrm-backend/issues/1000

    This occurs with latest clang++ on OS X and is easy to replicate when building against libc++ in c++11 mode
    There are numerous possible workarounds. I think the simplest is to use std::fabs

I just gave fabs a try and seems to work fine.

**Comment by abma** [comment]
i gave three possibilities which could work but you tried none of them according to the output you wrote back. can you please give verbose messages of each version?

1. std::abslong((long)count)
2. (long)std::abslong(count)
3. (long)std::abslong((long)count)

**Comment by JoshuaPettus** [comment]
I tried them all, there is no abslong in std.  That is what it said.

**Comment by Usaga** [comment]
Try this: std::abs( (double) count )

**Comment by Usaga** [comment]
This may work

**Comment by Usaga** [comment]
Or even better variant: std::abs(static_cast&lt;double&gt;(count))

**Comment by JoshuaPettus** [comment]
Excellent, both seem to work so which ever is preferable.  Just out of curiosity, and because I am studying very basic C++ right now, is there a reason why feeding a double to std::abs is preferable to using std::fabs?

**Comment by Usaga** [comment]
Preferable variant is to use static_cast. And I do not see any reason why you can not use std::fabs. 

std::asb is just a wrapper made to simplify reading of code.

**Comment by JoshuaPettus** [comment]
I see, well thanks! and thanks abma

**Comment by Usaga** [comment]
Don't mention it

**Comment by abma** [comment]
this is not fixed. @Usaga: why did you close this report?

its still the same code/error:
https://github.com/springlobby/springlobby/blob/master/src/settings.cpp#L1470

**Comment by Usaga** [comment]
I do not know how this had happened. Probably I changed code but forgot to push O_o. Sorry for this.

**Comment by abma** [comment]
no worries, just wondered.

"He who makes no mistakes, makes nothing"  :)

**Comment by JoshuaPettus** [comment]
Np, thanks a lot!   Works fine now.  I'll turn off the lights this time. :)

**Comment by abma** [comment]
#include \<cstdlib\>

could fix this. JoshuaPettus, can you please test, if that works?

**Comment by JoshuaPettus** [comment]
Yup, including the cstdlib directive seems to work fine.   Thanks for looking into it.

**Comment by abma** [comment]
thanks a lot!
