### ISSUE TITLE
compilation failed for commit: 1ad1c84563db7d55d1b101d8684dbd4b93f9e639

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#492]
latest commit was:
commit 1ad1c84563db7d55d1b101d8684dbd4b93f9e639
Author: Ruslan <masturofpuppets@gmail.com>
Date:   Wed Jun 24 18:26:46 2015 +0600

Error message:
CMakeFiles/Makefile2:487: recipe for target 'src/CMakeFiles/springlobby.dir/all' failed
make[1]: *** [src/CMakeFiles/springlobby.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Usaga** [comment]
I know, I am working on it
