### ISSUE TITLE
latest dev springlobby throws a lot of Error messages

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#493]
Lobby shows A LOT of message boxes with message:
PlaybackDataModel::GetValue:column=-1

I have fedora 22 linux with gnome desktop. And gnome "hangs" during that error messages spam. Impossible to make screenshot))

latest commit was:
commit 10e72c40f6a9cd00cd7666efd29a3be9b9a51c94
Author: Usaga <masturofpuppets@gmail.com>
Date:   Wed Jun 24 22:06:14 2015 +0600

**Comment by Usaga** [comment]
Test new commit, please. Must be suppressed

**Comment by Usaga** [comment]
Double warkaround: bb31dd6e150d330dc73b1feaad704f7581e1c442

**Comment by Usaga** [comment]
No sorting -> no problems)))

Will investigate this situation later.

**Comment by jamerlan** [comment]
yep, now it works. But "replays" tab looks bad.
![replays_tab](https://cloud.githubusercontent.com/assets/216801/8336243/c9d8612c-1aab-11e5-9fb1-1b8b0051459f.png)

**Comment by jamerlan** [comment]
And scrolling with mouse wheel is still not working. Работает только если мышкой плзунок тянуть

**Comment by Usaga** [comment]
Попробуй раздвинуть колонки и перезапустить лобби. Картина повторится?

**Comment by jamerlan** [comment]
раздвинул, перезапустил. Остались раздвинутыми. Но скроллинг колесиком мыши не починился.
Если у других юзеров все схлопнется, то не факт, что они догадаются раздвинуть)))
