### ISSUE TITLE
initial with of replay / battleroom list is ~1px

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#497]
thats a bit annoying, after each restart with of list has to be manual set as its default width seems to be 1px.
![screenshot](https://cloud.githubusercontent.com/assets/301564/8389646/3a7f4c86-1c75-11e5-95ab-e3e5406b659e.png)

**Comment by Usaga** [comment]
Weird, I had not meat this on Windows. Looks like auto column resize code is broken

**Comment by Usaga** [comment]
Please, test new changes if it is work for you.

**Comment by abma** [comment]
seems to work, thanks!
