### ISSUE TITLE
issues with downloader (stopper for new players)

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#498]
I made some attempts to advertise spring and failed because people were unable to install engine/games.  I created text + screenshots instruction but still they all suffer from bugs.

And I was suffering from bugs too! :-) These bugs are stoppers for many players who wanted to try spring games. Please fix these bugs so I will be able to continue promoting spring.

I created video tutorial for newbies here: https://youtu.be/sVtPbBfL44w
No need to watch the whole video. I created shortcuts below. Please ignore Russian texts.

1) Some scary errors at 2:10 https://youtu.be/sVtPbBfL44w?t=2m10s
2) Downloading was not starting at all at 7:00 - 9:00 https://youtu.be/sVtPbBfL44w?t=7m
3) Many people complained that  downloading stuck at 70% for example. I guess it was just a visual bug on "Downloads" tab

4) Not such a big issue but still.. column sizes by default are bad: https://youtu.be/sVtPbBfL44w?t=4m25s

**Comment by Usaga** [comment]
All of it must be fixed in current development version
