### ISSUE TITLE
code style could be better

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#499]
1. a lot of files have now wrong line endings, all have to be LF but the most recent ones are CRLF
2. there are A LOT new compile warnings, see https://travis-ci.org/springlobby/springlobby/jobs/68633297 for example.

**Comment by Usaga** [comment]
I will fix this

**Comment by abma** [comment]
thanks a lot for doing this! :)

**Comment by Usaga** [comment]
I failed -> I fixed

**Comment by abma** [comment]
thanks!
