### ISSUE TITLE
Invisible player rows on player list

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#501]
Sometimes when I join games the players on the player list don't show up, but they are there.

They are only "revealed" when I click on the list.

**Comment by springraaar** [comment]
screenshot here : http://snag.gy/5BHGm.jpg

**Comment by abma** [comment]
springlobby version? should be already fixed by most recent commits...

**Comment by abma** [comment]
also very likely a duplicate of #418

**Comment by springraaar** [comment]
version is 0.225

And you're right, it's probably a duplicate of 418.

**Comment by Usaga** [comment]
This is <s>replaced by another bugs</s> fixed in development version
