### ISSUE TITLE
changing engine from 98.0 to 99.0 breaks spring settings and in-game camera

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#502]
on the single player tab, after changing the engine from 98.0 to 99.0 and starting the game this happened:
- camera was stuck in max zoom out until I changed it to another using the ctrl-F[1-5] keys
- max particles settings was changed from 20000 to 1000 (that's why CEG weren't showing, again). I think it also changes several other settings.

notes:
- to see that the values changed I had to reopen the springsettings window (without saving)
- I already had played games using spring 99.0 and set the settings for it before

**Comment by silentwings** [comment]
@raaar, you can hotfix the rabbit level crazy issue of Spring resetting camera everytime you switch with this widget: http://imolarpg.dyndns.org/trac/balatest/browser/trunk/luaui/widgets/camera_remember_mode.lua

**Comment by springraaar** [comment]
Ah, thanks.

**Comment by abma** [comment]
see #877
