### ISSUE TITLE
Simplify download system in SpringLobby

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#503]
Another round of "rewrite-it-all" proposal: at this monent SL uses prDownloader for content downloading. It capable of multithreaded downloads, can use two (some time ago three) downloading interfaces (http, rapid and plasma) and stores content in pool. But IMO all those advanced futures are not demanded by regular players (and by me too). All they want is just to download map/game/engine and be capable to find it in some predicatble place in original useful form (to be able to copy it or remove) and nothing more. 

At this point prDownloader is not perfect: it can silently disobey "download" command, show wrong progress and even crash. All this can be fixed, of course. But prDownloader (as I saw it's code) is redudantly complicated. May be it is worth to replace it with much more simlier curl-based (or similar) mechinism that only can spam single thread for single download, using some preseted directory for download and, may be, rewrite DownloadTab to be capabale manage downloaded content(not only to observe downloading proccess but to manage already downloaded content: moving it and deleting)?

Is there thougths about it?

**Comment by abma** [comment]
pr-downloader is curl based. idk what you want to simplify... can you more specific?

what could be simplified is the usage of pr-downloader. atm it uses an event when a download is finished and reloads unitsync. very likely the crashes come from reloading unitsync (which is what is VERY complicated imo) and not from the downloader lib.

**Comment by abma** [comment]
also, some game versions can only be downloaded via rapid, its not possible to download them via a regular download. rapid also heavily reduces download size and used disk usage after the download. whats missing here is a way to delete .sdp files which should be difficult to implement. biggest problem here is the gui...

plasma is disabled in newer versions of pr-downloader as its broken.

**Comment by Usaga** [comment]
I meant not to use pool because it makes impossible to manage downloaded content, drop support of multithreaded downloads and protocols other then http. So make code much lesser and simplier...

**Comment by springraaar** [comment]
I'm not sure if it's a springlobby issue, but recently people often have trouble downloading games and maps. Sometimes they apparently finish download but remain unsynched in the battle room (using the reload maps/games doesnt fix it)

Others keep downloading the same map over and over.

I remember it being more stable 6 months ago, but maybe i'm wrong.

**Comment by abma** [comment]
> I meant not to use pool because it makes impossible to manage downloaded content.

thats wrong: just add some gui which allows to delete the .sdp files, then the game/map won't show up in the list any more.

and again: some game versions only exists at rapid, so support is a must!

the real issue here is, that reloading unitsync to get downloading maps/games is very bad code / broken! downloading works in most cases fine!

**Comment by Usaga** [comment]
Ok. And again - polishing existing code is a better solution! :-)
