### ISSUE TITLE
engine + game download when joining battleroom seems not work very well

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#506]
often a lobby restart / battle rejoin is needed to make it work.

also, when game/engine is missing, it has to be joined twice.

**Comment by Usaga** [comment]
Hm. Looks like "clean" installation of SL failes to install spring100 - it downloads it but then say "Failed to extract engine!". May be problem with access to fs.

**Comment by abma** [comment]
hm, works fine for me, whats the output of help->system info?

**Comment by abma** [comment]
i get unhandled exceptions when downloading stuff, very likely because of #536 (unhandled exceptions in contentmanager)

**Comment by Usaga** [comment]
SpringLobby 0.225-143-gc825398 (win x32)
SpringLobby config file: C:\Users\Руслан\AppData\Roaming\springlobby\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\Руслан\AppData\Roaming\springlobby\)
	WX: yes POSIX: no TRY: no
CachePath (C:\Users\Руслан\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: no TRY: no
ExecutableFolder (C:\Program Files\springlobby\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Руслан\Documents\My Games\Spring\)
	WX: yes POSIX: no TRY: no
Current SpringData: ()
	WX: no POSIX: no TRY: no
Current unitsync: 
Current spring executable: 
Current uikeys.txt: uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Program Files\springlobby\springlobby.exe

**Comment by abma** [comment]
-> #507

**Comment by Usaga** [comment]
Hm. Bad.

**Comment by Usaga** [comment]
What means TRY word?

**Comment by Usaga** [comment]
Strange: after reloading of SL spring100 was found and used...

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/master/src/gui/infodialog.cpp#L73

when extraction fails, engine search/refresh isn't invoked.

**Comment by Usaga** [comment]
At this moment downloading and extractinon works very well for me. May be some more testing is needed.

**Comment by abma** [comment]
before the changes it worked already well for me. i'll test soon but i expect it to work fine :)

thanks!

**Comment by Usaga** [comment]
Thank you for your advice with _wunlink!

**Comment by abma** [comment]
should be fixed in current version
