### ISSUE TITLE
sorting of lists isn't restored

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#509]
should be fixed...

**Comment by jamerlan** [comment]
I bet people will complain A LOT :-) if you release with this bug. 

Sorting is not restored in battle list and in battle room. But table have icon like it is sorted already.

**Comment by Usaga** [comment]
Yep, another dont-know-what-to-do-with-it bug :-( Need some workaround like done with #533

**Comment by Usaga** [comment]
Looks like this problem is veeeeery old:
http://osdir.com/ml/wx-users/2015-07/msg00059.html

**Comment by abma** [comment]
ouch.
direct link to the ticket: http://trac.wxwidgets.org/ticket/15626

@jamerlan afaik the problem only exists on linux. on windows it works fine

**Comment by abma** [comment]
should be fixed in wxwidgets 3.0.3
