### ISSUE TITLE
springlobby seems to allow to start a game with the wrong engine version selected

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#510]
this should be prevented somehow

(not 100% sure if it was springlobby or TASC for example)

**Comment by silentwings** [comment]
It's possible that some users put DisableVersionCheck in their config years ago (for e.g. a testing game, before server allowed non-standard Spring versions) and forgot about it.

**Comment by abma** [comment]
just had an idea how to fix:

just show an message box about version check disabled when engine is started, sth. like:

"Warning, DisableVersionCheck is enabled, very likely this game will desync!"

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/d9d8a6ddb1f032f7f5ff017efa3901fba1b7ff4a/src/contentmanager.cpp#L95

**Comment by Usaga** [comment]
What benefits brings this option?

**Comment by Usaga** [comment]
What fro it is needed?

**Comment by abma** [comment]
developing
