### ISSUE TITLE
transparency of icons in list is black

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#512]
![screen](https://cloud.githubusercontent.com/assets/301564/8512071/0aba587c-2334-11e5-9d69-097deb0336ac.png)

**Comment by Usaga** [comment]
Strange...

**Comment by Usaga** [comment]
I have a couple of thougths abouts this. I will try to fix it tomorrow.

**Comment by Usaga** [comment]
Is it fixed?

**Comment by abma** [comment]
for rank + status yes, for flags / colour no.

![screenshot](https://cloud.githubusercontent.com/assets/301564/8567748/1acee56c-2568-11e5-803b-accd1074859c.png)

**Comment by Usaga** [comment]
Oh, my fault - forgot to modify GetFlagBmp method. I will fix it today
