### ISSUE TITLE
(v0.225) double/wrong entries in playerlist (reproduce via 'hide bots')

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#513]
Sometimes playernames are double/wrong in playerlist.
One way to reproduce is to toggle the "[x] hide bots" option, but I think it can also happen randomly and happend before this option was added...
It fixes when highlighting the entry, see video.

https://youtu.be/TLER5FFlhZk

**Comment by Usaga** [comment]
This bug is known and fixed in current development version

**Comment by knorker** [comment]
ah ok. i saw some commits but "better safe than..."

**Comment by Usaga** [comment]
Yep))
