### ISSUE TITLE
(v0.225) downloads finish at != 100%

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#514]
Sometimes downloads are shown as complete ("vollständig") when at random numbers like 37% or 59% or even 110%
Seems to happen for games,mods, engine
Attached some screenshots

![download progress](https://cloud.githubusercontent.com/assets/3044855/8538264/6e95da42-246a-11e5-8b66-17e0d201e3b2.png)

(yes, some noob really took a photo of his monitor...)

![download progress 2](https://cloud.githubusercontent.com/assets/3044855/8538265/6eb48a14-246a-11e5-992c-17a504bba25c.png)

On the photo the downloads are still "status: downloading" but already > 100%
On the other picture the dls are all finished (maps were playable etc) but < 100%

**Comment by Usaga** [comment]
We already working on it. Hope will fix in next release

**Comment by Usaga** [comment]
Fixed in development version
