### ISSUE TITLE
(v0.225) "engine 99.0" does not work but is reported as complete, then crash

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#515]
I try to join a battleroom that runs spring 99.0
Other players told me that TASClient sucessfully downloaded spring99.0 for them but they said SL failed. I tested.

Video is mostly repeating the same steps and at start is v0.224 but then I update, dont have video cutter for mp4:
http://youtu.be/Oewp4LSnUHo

1min50
Status="Herunterladen" (downloading)
0% complete
but at bottom it says in green text "Download finish"

4min40
springlobby crashed

**Comment by Usaga** [comment]
Hyperlink does not work - it says "author set limited access to video"

**Comment by knorker** [comment]
think youtube takes while to update, it should work soon..

**Comment by abma** [comment]
please try again with 0.226
