### ISSUE TITLE
(v0.225) map-dl problems ("map doesnt exit!" spam, minimap off centered)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#516]
http://youtu.be/uPf_dQrH4uI shows some bugs, think those (or similiar) were already fixed at some time.

At start:
Messagebox popup spam about "Map XY doesn't exist!"
(there were more before i started recording)

At 0min12
No minimap shown.
On mouse-over and rotating mousewheel the minimap shows, but it is not centered.

0min20
Map-dl "EpicShore" is "finished" but also at 20%

**Comment by abma** [comment]
download status should be fixed in dev version (didn't see issues / wrong status with it)
