### ISSUE TITLE
(0.225) unclear sync-status of maps/games after update

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#517]
Again video https://www.youtube.com/watch?v=Oewp4LSnUHo but seperate bug (I think)

After lobby update all games&maps were unsynced for a while. 

At 1min
synced with most rooms (have most games&maps)

Then update lobby 0.224 to 0.225 & restart
Now unsynced with all rooms (have no game or map)
but engines are still shown synced "green"

At 2min0
click "reload games/maps", but nothing happens

At 2min52
doubleclick a battleroom and now all games&maps show, synced again.
Not sure if the click triggered that or if lobby was re-caching in background anyway.

Not sure if bug or 'just missing feature of better feedback to player.'

**Comment by abma** [comment]
should be fixed in 0.226, please try again
