### ISSUE TITLE
Game keeps crashing after a few minutes on singleplayer and multiplayer - Please help!

### ISSUE THREAD

**Issue by Yuret42** [springlobby/springlobby#521]
Dear all,

I've just installed Spring and manually copied the patch 2.25 into the spring folder on my Windows 7 Laptop. However, now I can't seem to start a singleplayer or host a multiplayer game without the Springlobby error message after a few minutes into the battle - not responding and then it crashes. When I try to join a multiplayer game, it just hangs on "Connecting to server" blackscreen then causes everyone else to crash and mine just reverts back to the Springlobby battleroom.

Any help would be gratefully appreciated?

Many thanks!

**Comment by abma** [comment]
basicly thats the wrong bugtracker here. the spring engine crashes and its bug tracker is there:
https://springrts.com/mantis/

does it work when you run spring with safemode? also when it crashes, please attach infolog.txt.

**Comment by abma** [comment]
maybe some more pointers:

https://springrts.com/wiki/Springsettings.cfg#Safemode
https://springrts.com/wiki/Infolog.txt

**Comment by Yuret42** [comment]
Sorry - sent it to MantisBT now with Infolog attached. Thanks again
