### ISSUE TITLE
Spring launches about 3 seconds later than everybody else

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#522]
cant pick backspots since over a year now

**Comment by abma** [comment]
there is no delay or sth. like that. how come that you think it starts "later"?

**Comment by Ruwetuin** [comment]
because everybody gets the ingame icon and i suddenly because one of the first to pick to one of the last... like more than a year ago. reinstall didnt fix

**Comment by abma** [comment]
what is your ping-time in lobby? (see the right bottom corner)

**Comment by Usaga** [comment]
I have same "problem" some time when I have memory stall (torrent working in background, browser with a lot of tabs and so on), so I do not blame spring/springlobby. Maybe be you running low of free memory? This can not be a surprise (https://github.com/springlobby/springlobby/issues/464)

**Comment by Ruwetuin** [comment]
18 ms
Because I 'm on fiber optics, I'm always the first to get autounspecced.

I've 32 GB memory. Spring files are located at my SSD.

**Comment by abma** [comment]
> Don't know about the data dirs, where can I find those? (i dont think this will be the issue either though)

infolog.txt

**Comment by abma** [comment]
did springlobby 0.226 fix this?

**Comment by Ruwetuin** [comment]
Srry I did respond this late, but the clearing of all various cache fixed it.
