### ISSUE TITLE
sorting battlelist by game/map/engine ver doesn't work

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#523]
order is "random". other columns seems to work!

**Comment by Usaga** [comment]
Hm. It works good for me under Windows 8. Battle description and Host sorted by the same code. Does they work normal?

**Comment by abma** [comment]
sorting by host & description works.

also sorting by engine version doesn't work, too.

**Comment by abma** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/301564/8772289/518fe1c0-2ecb-11e5-9b2c-0344ba0eb522.png)

**Comment by Usaga** [comment]
I think I know what can cause this. Will try to fix it at evening today.

**Comment by abma** [comment]
thanks!
