### ISSUE TITLE
Player reported Springlobby troubles

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#525]
Original Thread:
https://springrts.com/phpbb/viewtopic.php?f=64&t=33676

1. when i install spring in C:\Users\myusername\Documents\My Games\Spring
then springlobby does not download stuff (maps,mods,games) and everytime brings download popup again and again and again..
-> after deinstall spring completely and install in C:\Program Files (x86)\Spring it was working

2. springlobby fails somehow to get the path of springengine automatically
the setting page where u can click on "automatic retrieve engine path" stuff is simply not working and frustrating - its not intuitive
somehow after clicking around and reinstall spring i found, that you actually have to ADD in the left side a engine and then manually add spring.exe and unitsync stuff to get that shit working

3. installing spring without zero-k will install spring with zero-k but not springlobby - installing spring without springlobby but zero-k result in same - installing spring with both zero-k and springlobby installs zero-k and finally springlobby

4. the lobby hangs on downloads (finished) and blocks over many seconds all the UI

5. the lobby is massive sluggish with redraw gui stuff -> tasclient is WAY MORE fluid and nice in that

6. every map change, springlobby is getting bigger in ram usage -> there is a HUGE memoryleak and when springlobby reaches maximum amount of usable ram (~ 1,8GB for win32) it crashes!

im getting more and more pissed about this lobby and i have to use it cause weblobby and tasclient isnt working anymore/at all/dead/whatever

...
tarted springlobby update today
got error: it cannot cleanup appdata/roaming/springlobby/update
(i even didnt know that this dir exists)

after some try and error, i was removing readonly flag from the roaming/springlobby dir and update was running finally

after update i joined a host with DSD

dsd not found.. download? -> klicked yes -> nothing happens

im in battleroom without map -> klicking on the download button -> nothing happens

after some seconds -> ---------------------------
Fehler
---------------------------
Item (DeltaSiegeDry) requested for download could not be found. Sorry.
---------------------------
OK
---------------------------

battleroom switched to desertsiege_v2b (not found)

klicking on download -> nothing happens

after some seconds ->
---------------------------
Fehler
---------------------------
Item (DesertSiege_v2b) requested for download could not be found. Sorry.
---------------------------
OK

**Comment by abma** [comment]
the index server was offline for a few (short) times, this is why files couldn't be found.

whats the output of help->system info?

very likely paths are invalid/broken/not writeable.

**Comment by abma** [comment]
1. thats an invalid path, springlobby should refuse to be installed there.
2. more info needed, which path doesn't it find automaticly?
3. what? how do you install springlobby? spring doesn't contain zero-k lobby
4. known issue, see #48
5. fixed in dev version
6. memleak is already reported here: #464


so only left is 1 & 2 which needs more info.

**Comment by knorker** [comment]
the original thread is closed without link to this report -> original poster likely will not read this / can't reply

**Comment by Usaga** [comment]
Original poster made it clear he does not care about any bugtracker...

**Comment by knorker** [comment]
Players rarely care about bugtrackers (because at worst they have to register in 3 unknown services: tracker of lobby,engine,game),
Eitherway if player has no link to report it is useless to wait for his "feedback"..

**Comment by abma** [comment]
most issued should be covered / fixed by
https://github.com/springlobby/springlobby/issues/529
https://github.com/springlobby/springlobby/commit/45d64a8af033ce1b5e1d22b6fe2335782e216236

without feedback its difficult to verify if fixes work :-|

(i assume / hope all issues are fixed now)
