### ISSUE TITLE
Map DL problems

### ISSUE THREAD

**Issue by logit05** [springlobby/springlobby#526]
Spring Lobby is installed on a separate drive K: but continues to require maps, games, and everything to be in C:/user/(name)/mygames/spring

Why does it do this? why not allow users to set a download folder based inside the install dir?

I just recently deleted C:/user/(name)/mygames/spring in order to fix the map/game DL problem where it pops up to DL and never actually downloads the assets and promps again.

**Comment by abma** [comment]
whats the output of help->system info?

when you edit springsettings.cfg you can change the download path.

**Comment by abma** [comment]
does (name) contain non-asscii chars?

**Comment by logit05** [comment]
SpringLobby 0.225 (win x32)
SpringLobby config file: K:\Program Files (x86)\Spring\springlobby.conf ( writable)
LobbyWriteDir (K:\Program Files (x86)\Spring\)
	WX: yes POSIX: yes TRY: yes
CachePath (K:\Program Files (x86)\Spring\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (K:\Program Files (x86)\Spring\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\KEVIN\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\KEVIN\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: K:\Program Files (x86)\Spring\engine\100.0\unitsync.dll
Current spring executable: K:\Program Files (x86)\Spring\engine\100.0\spring.exe
Current uikeys.txt: C:\Users\KEVIN\Documents\My Games\Spring\uikeys.txt
Portable mode: yes
Compiled with wxWidgets 2.9.5.0
Started with: 
K:\Program Files (x86)\Spring\springlobby.exe

**Comment by logit05** [comment]
I'll test changing the path in springsettings.cfg and see what happens I currently fixed it by deleting my spring folder on C:\Users\KEVIN\Documents\My Games\Spring and re-adding my maps/widgets to it

**Comment by abma** [comment]
current dev version allows to change download dir in settings (before it was only possible by config file)

very likely your paths were broken
