### ISSUE TITLE
springlobby_updater issues

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#527]
seems it throws some error message boxes when doing a "normal" update.

it seems it doesn't wait correctly for springlobby to exit.

should be fixed for the next release.

**Comment by abma** [comment]
i got some permission error messages "couldn't write files..." if i remember right. these messages should be not shown when running in non-admin mode. ideally springlobby updates without admin rights.

**Comment by Usaga** [comment]
I thought updater uses temprorary directory and does not require admin rights...

**Comment by abma** [comment]
if it is system-"installed" it requires admin rights.

**Comment by abma** [comment]
![error](https://cloud.githubusercontent.com/assets/301564/8824213/074280aa-3074-11e5-874f-41d728160710.png)

**Comment by abma** [comment]
![error](https://cloud.githubusercontent.com/assets/301564/8824223/22575d20-3074-11e5-8680-9ae6f8610f7f.png)

**Comment by abma** [comment]
only issue seems, that it shows the error messages when run as non-admin.

**Comment by Usaga** [comment]
Hm. But SL has permission for writing to "D:\Games\Springlobby"?

**Comment by Usaga** [comment]
If so, maybe springlobby.exe did not exited yet?

**Comment by abma** [comment]
current user had no write permissions to that directory as it was "installed" by admin.

**Comment by Usaga** [comment]
I do not understand why theese errors should be hidden? Even in silent mode...

**Comment by abma** [comment]
because they are no real errors...

updater works like this:
try to update files as normal users, if error happens try as admin.

i'm not sure, if there is an easy / reliable way to check if admin permissions are needed, if so, that should be prefered.

**Comment by abma** [comment]
so maybe to fix this in a better way:

before doing a write, if its possible: i.e. check before a copy if destination dir/file is writeable.

before doing any operation, permissions have to be checked:

for files:
- rename
- copy
- delete
- overwrite

for dir:
- create dir
- delete dir

but code won't be KISS :-|

**Comment by Usaga** [comment]
Possibly it is not so hard https://msdn.microsoft.com/en-us/library/windows/desktop/aa446645(v=vs.85).aspx

**Comment by abma** [comment]
it should work cross-platform! :-)

**Comment by Usaga** [comment]
I thought it has problems only with Windows O_o

**Comment by abma** [comment]
the updater currently is only used on windows... but when we find some time to create static builds for linux it will be used there, too.

**Comment by Usaga** [comment]
I think this is not a problem - just separate platform-dependent code with preprocessing macroses. Create some PermissonManager in three different instances with #ifdef's and populate it with IsWritable, IsDeletable methods...

**Comment by abma** [comment]
3 classes / cpp files with platform specific code vs. possible a single line of code.

**Comment by Usaga** [comment]
I doubt that one single line of code can handle three different OS low-level abilities

**Comment by abma** [comment]
wxLogNull log; in UpdaterApp::StartUpdate()
