### ISSUE TITLE
create a release

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#528]
todo before release imo:

- ~~#527~~ should be checked / fixed
- ~~#525~~ & ~~#526~~ : possible what could be wrong with non-asscii usernames (atm thats the guess why download doesn't work correctly, more info needed)
- #506: check if "stock" download works & if installing via engine installer works
- ~~#529~~ & ~~#538~~ validate download dir
- ~~#536~~ error when clicking ok on update message
- ~~#537~~ updater fails
- ~~#539~~ message box spam when joining a battle without map/game locally available
- ~~#540~~ logic error in tasserver.cpp
- ~~#547~~ failing assert
- ~~#550~~ compile error

other issues are minor / can be ignored for the moment imo.

@Usaga : thoughts? did i miss sth. important?

**Comment by Usaga** [comment]
It seems you listed all actual problems. The main problem as I see it - that is SpringLobby does not saying what it thinks is wrong (no write permissions, wrong encoding, no download service available and so on). This is really annoys people and makes hard to understand what is wrong.

I think before release we must at least make SL to inform user about problems it meets. More MessageBoxes. This will make next bug reports more informative. I thnik.

**Comment by Usaga** [comment]
Btw, I started to implement ContentManager (very minor at this moment) planning to use it for content managing (observe downloaded maps/mods/engines, delete it) and download managing (list actual and completed downloads, check if content already downloaded, cancell downloads and so on - this is partially done). If we move all code interacting with prDownloader to a single place it help us greatly to make SL a bit better)))

**Comment by abma** [comment]
> (no write permissions, wrong encoding, no download service available and so on)

i guess best is, to check on startup and if it fails, show an error and prompt the user to fix it. but will be difficult, i'm not sure about the reason for this, atm i think it could be because of non-asscii chars in paths: the windows posix api sucks there! ( i.e. https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows )
a workarround already is implemented in pr-downloader but seems to fail in some cases guess.

**Comment by Usaga** [comment]
At this moment engine downloading does not work for me under Windows 8. Without crashing, just silent "downloading complete" and nothing more. Maybe pr-downloader meets error but couldn't report about it.

**Comment by abma** [comment]
console output would be VERY useful. very likely it already contains information about the problem.

**Comment by Usaga** [comment]
Yep, console could be useful but it does not work in my SL builds - I do not know why. Maybe wrong configuration of project? I do not know. Furthermore, regular users do not run SL from console, so error message in GUI still needed.

**Comment by abma** [comment]
just run with a debug build of with springlobby -fl springlobby.log -l 9

**Comment by Usaga** [comment]
Oops. If forgot about that. What a idiot)) Thanks!

**Comment by ForbodingAngel** [comment]
**Usaga Said:**
> At this moment engine downloading does not work for me under Windows 8. Without crashing, just silent "downloading complete" and nothing more. Maybe pr-downloader meets error but couldn't report about it.

This sounds like what I have been complaining about here:
https://springrts.com/phpbb/viewtopic.php?f=11&t=33031

**Comment by abma** [comment]
@ForbodingAngel then please answer the question in that thread, i can't reproduce it / don't have details about the problem(s) so can't fix it.

**Comment by ForbodingAngel** [comment]
Here you have someone with the same issue... That's what I'm telling you.

**Comment by abma** [comment]
@ForbodingAngel this info is not useful, please answer the questions in the thread.

**Comment by abma** [comment]
@Usaga 

> At this moment engine downloading does not work for me under Windows 8. Without crashing, just silent "downloading complete" and nothing more. Maybe pr-downloader meets error but couldn't report about it.

can you please open a bug report at https://github.com/spring/pr-downloader/issues and fill in details? (i.e. output of pr-downloader, etcetc)

**Comment by Usaga** [comment]
Yep, I will do

**Comment by abma** [comment]
oh, wow, only testing left it seems.

not sure whats up with #533, i tried on fedora, too and it crashed there the same way. but i couldn't find a way to fix it, no clue whats wrong there.

**Comment by Usaga** [comment]
I could not find solution for fedora too. Stack trace show gtk+ tries to update DataView after it was cleared.

**Comment by abma** [comment]
-> clear is broken on fedora?

-> try to remove one by one?

**Comment by Usaga** [comment]
I have tried to remove items one-by-one but with the same result -> crash. Furthermore, I can get crash even after using filter in battlelist.

**Comment by abma** [comment]
sooo, we are back at testing before release :D

**Comment by Usaga** [comment]
Yep))
