### ISSUE TITLE
validate download dir

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#529]
as a gui setting exists, this became more relevant:

1. springlobby should check somehow if the download dir is "inside" the data dir. this can be checked on the unitsync reloaded event

2. it should be checked if the the download dir is writeable at start

same applies to other writeable paths, too i guess (cache, update dir, ...?!)

**Comment by Usaga** [comment]
I do not get it. Download directory must be a subdirectory of data directory?

**Comment by abma** [comment]
mhmm, it must be the same (i guess)

if unitsync for some reason ignores the download dir, all downloads don't get recognized by unitsync -> springlobby will try to download again and again...

**Comment by abma** [comment]
edit:
the more i think about that, the more i'm not sure how to check that reliable. unitsync uses multiple directories by default for reading content. :-|

**Comment by Usaga** [comment]
All we need is to check them all. I think this is possible.

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/08951f0fa8c814b7bee70bcecc955f528e9f2b92
