### ISSUE TITLE
Crash while downloading (anithing)

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#531]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 5948.0x1510]
CHttpDownloader::getDataByHandle (this=0x13f4dc90, downloads=...,
    easy_handle=0x1494f780)
    at C:/springlobby/src/downloader/lib/src/Downloader/Http/HttpDownloader.cpp:
359
359                     if (downloads[i]->curlw->GetHandle() == easy_handle) {
(gdb)

**Comment by Usaga** [comment]
Unfortunately, I cannot say when this started (what commit caused this)

**Comment by abma** [comment]
ooops, will fix. most recent commits to pr-downloader have caused this, very likely https://github.com/spring/pr-downloader/commit/5498204ff048f342f008b31137a76015e3361f14

**Comment by Usaga** [comment]
Probably, fixing it can help to close a bunch of other issues. I hope, at least))

**Comment by abma** [comment]
can't reproduce, are you sure the pr-downloader is up to date?

current version is: 0.7-181-g1e3ffde

**Comment by Usaga** [comment]
Yep, all is up-to-date: 1e3ffdef22c8b8a06c28237fe6f54c90fa6ac197 is last commit a have

**Comment by abma** [comment]
do you have pr-downloader locally available? if so, does it crash, too?

easiest to get it should be by editing CMakeCache.txt and setting PRD_CONSOLETOOL:BOOL=ON

**Comment by Usaga** [comment]
I have it, but do not know how to use it. I mean what I should write to download BA9.0? --http-download <WHAT>?

**Comment by abma** [comment]
pr-downloader ba:stable

https://springrts.com/wiki/Pr-downloader#download_the_latest_version_of_zero-k

**Comment by Usaga** [comment]
Separate application works fine, downloads mods and engines

**Comment by Usaga** [comment]
New crash, but with different reason:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1704.0x15cc]
CHttpDownloader::download (this=0xb0b2da0a, download=..., max_parallel=3) at C:/springlobby/src/downloader/lib/src/Downloader/Http/HttpDownloader.cpp:524
524                             curl_easy_getinfo(downloads[i]->curlw->GetHandle(), CURLINFO_CONTENT_LENGTH_DOWNLOAD, &tmp);

**Comment by abma** [comment]
can you please give exact instructions how you get it crash?

**Comment by Usaga** [comment]
Launch SL, switch to battlelist tab, right click on battle with BA9 -> choose download game. Download begins, progress reaches about 50% and then - crash. Same for any other map/mod

**Comment by Usaga** [comment]
https://github.com/springlobby/springlobby/commit/314c1c827486a66beb0de111257bef6701b695dd did not help. Still crashing.

**Comment by abma** [comment]
meh, and i can't reproduce the crash :-|

**Comment by Usaga** [comment]
Hm. Maybe this crashed is specific for my build... Will investigate tomorrow

**Comment by abma** [comment]
yeah, maybe a full rebuild helps :)

**Comment by abma** [comment]
ohhh, the official build crashes for me too, seems to be windows only then:

http://paste.springfiles.com/view/raw/42031025

**Comment by abma** [comment]
for me this works again:
https://github.com/spring/pr-downloader/commit/255b1940f8229e059295131b4ce4ebcc4ed1ee49

does the current development version work for you, too?

**Comment by Usaga** [comment]
Will check it after work. I beleave it should be fixed.

**Comment by Usaga** [comment]
Yep, issue fixed. Thanks a lot!
