### ISSUE TITLE
SlPaths::mkDir failes to work with path with non-ascii chars.

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#538]
This causing dirs validation to fail on "clear" SL installation and error boxes spam.

**Comment by abma** [comment]
can you give details?

**Comment by abma** [comment]
hm, tested myself + with most recent changes it seems to work. i only need to test if the self-updater still works.

**Comment by Usaga** [comment]
What details? About why I made this change?

**Comment by abma** [comment]
details about the error / problems. but imo these should be fixed in current development version.

**Comment by abma** [comment]
i assume this is fixed...
