### ISSUE TITLE
logic error(): invalid battle id when closing/leaving battle hosted by relayhost

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#540]
current dev version, tasserver.cpp:1320

**Comment by Usaga** [comment]
Hm. What tasserver.cpp do you mean? My version has only 1296 lines...

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/master/src/tasserver.cpp#L1320

**Comment by Usaga** [comment]
Can not reproduce on Windows

**Comment by abma** [comment]
didn't see this message for a while, too. weird
