### ISSUE TITLE
SpringSettings ID_MENUITEM_RESET / resetSettings() causes access violation

### ISSUE THREAD

**Issue by isosphere** [springlobby/springlobby#541]
Executing resetSettings() causes an access violation and crashes the application. I executed springlobby with verbose logging and no crash handler, but this is all I have in my crash log:

>Message: SpringLobby 0.225 started
>Message: OpenLogFile( ) BATTLE
>Message: ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\Matt\AppData\Roaming\springlobby\chatlog\Official server\BATTLE.txt.
>Message: PlaybackTab::PlaybackTab()

I'm running this on Windows 10.

Here's what the Windows event log shows:
>Faulting application name: springlobby.exe, version: 0.0.0.0, time stamp: 0x5581f49b
>Faulting module name: springlobby.exe, version: 0.0.0.0, time stamp: 0x5581f49b
>Exception code: 0xc0000005
>Fault offset: 0x00803f8e
>Faulting process id: 0xe1c
>Faulting application start time: 0x01d0d1f66a5dc386
>Faulting application path: C:\Program Files (x86)\Spring\springlobby.exe
>Faulting module path: C:\Program Files (x86)\Spring\springlobby.exe
>Report Id: b3393e15-4fd0-4380-aafa-74227bf94881
>Faulting package full name: 
>Faulting package-relative application ID:

**Comment by Usaga** [comment]
Yep, I confirm this.

**Comment by isosphere** [comment]
Playing with OllyDbg (I don't know what I am doing), I can see the violation happens at 0x00c03f8e here:
` MOV ESI, DWORD PTR DS:[EDX-0C]

EDX is 0x00000002, so it's trying to read from 0xFFFFFFF6.

ECX is "BumpWaterAnisotropy" which was populated just a few instructions above.

**Comment by Usaga** [comment]
#0  0x00718b6e in wxString::compare(wxString const&) const ()
    at C:/wxWidgets/include/wx/log.h:886
#1  0x00ca2e21 in std::map<wxString, float, std::less<wxString>, std::allocator<
std::pair<wxString const, float> > >::operator[] (this=0xe648f44, __k=...)
    at C:/wxWidgets/include/wx/string.h:2111
#2  0x00609d7a in abstract_panel::loadDefaults ()
    at C:/springlobby/src/springsettings/tab_abstract.cpp:196
#3  0x005e9be5 in settings_frame::resetSettings (this=0x12bf6ce8)
    at C:/springlobby/src/springsettings/frame.cpp:308
#4  0x005ece9f in settings_frame::OnMenuChoice (this=0x12bf6ce8, event=...)
    at C:/springlobby/src/springsettings/frame.cpp:256
