### ISSUE TITLE
random crash with latest lobby

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#542]
http://pastebin.com/QxpgwksZ

0.225-178-g6110658

**Comment by abma** [comment]
do you have filters active?

**Comment by jamerlan** [comment]
yes

**Comment by Usaga** [comment]
Origin of this crash is the same as of crash at lobby exit

**Comment by jamerlan** [comment]
but this time I wanted to play some DSD and joined battleroom. This battleroom was opened and it showed some messages and than it crashed

**Comment by abma** [comment]
added a workarround, shouldn't crash the same way
