### ISSUE TITLE
yet another lobby crash

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#543]
lobby was IDLE. I was not even in the battleroom. Lobby was just opened to receive messages during the night.
http://pastebin.com/qy8f9mjS

0.225-180-gbd656ae

**Comment by abma** [comment]
duplicate of #533 

stacktrace is similar/the same:

TASServer::OnDisconnected()

**Comment by abma** [comment]
still thanks for reporting, this should makes reproducing it easer

**Comment by jamerlan** [comment]
Yep, disconnect crashed lobby :-)
