### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#546]
/home/travis/build/springlobby/springlobby/src/gui/basedataviewctrl.h:22:7: warning: 

      'BaseDataViewCtrl<User>::AssociateModel' hides overloaded virtual function

      [-Woverloaded-virtual]

        bool AssociateModel(BaseDataViewModel<DataType>*);

             ^

/home/travis/build/springlobby/springlobby/src/gui/nickdataviewctrl.h:18:32: note: 

      in instantiation of template class 'BaseDataViewCtrl<User>' requested here

class NickDataViewCtrl: public BaseDataViewCtrl<User> {

                               ^

/usr/include/wx-3.0/wx/gtk/dataview.h:129:18: note: hidden overloaded virtual

      function 'wxDataViewCtrl::AssociateModel' declared here: type mismatch at

      1st parameter ('wxDataViewModel *' vs 'BaseDataViewModel<User> *')

    virtual bool AssociateModel( wxDataViewModel *model );

**Comment by Usaga** [comment]
Hm. I will fix it today.
