### ISSUE TITLE
failing assert in basedataviewmodel.h:191 GetColumnType()

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#547]
http://pastebin.com/m9GiuV7y

last commit was:
commit a719322eff884e8dd4266ac4be66ce43f3397550
Author: abma <spring@abma.de>
Date:   Fri Aug 14 00:58:04 2015 +0200

    implement BaseDataViewModel::GetColumnCount():

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/dcffb4a4c66709c50a8f9063ea4e21f2ae3b94c7

**Comment by abma** [comment]
@jamerlan can you please retest current development version, if it works for you?
