### ISSUE TITLE
failed assert in [1] BaseDataViewModel<User>::UpdateItem(User const&) /home/abma/Projects/SpringLobby/src/gui/basedataviewmodel.h:192

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#548]
http://pastebin.com/R27SeGzk

**Comment by Usaga** [comment]
Hm.

**Comment by Usaga** [comment]
Oh, probably updated status of bot which one is filtered out. This is not critical, I will fix it

**Comment by Usaga** [comment]
I do not meet this bug anymore. I hope this is because it was fixed. @abma, do you still see it?

**Comment by abma** [comment]
nope
