### ISSUE TITLE
re-sort battlroom on team changes

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#549]
I have a recent springlobby: 0.225-215-gb93fb86

and I have sorting by "Ally" in the battleroom
but with time it becomes a mess. And every time I need to re-sort it manually

![springlobby_sorting](https://cloud.githubusercontent.com/assets/216801/9293216/7b245358-442a-11e5-9222-4b34a453a200.png)

**Comment by Usaga** [comment]
This happens only with "Ally" column?

**Comment by jamerlan** [comment]
I tested for "Team" column - same bug

**Comment by Usaga** [comment]
Did it fixed for you?

**Comment by jamerlan** [comment]
looks like fixed! Thanks!
But probably I need to test more
