### ISSUE TITLE
springlobby 0.226 - mac os x crash

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#553]
crash when you try to join a battleroom

http://pastebin.com/bUWuQwYn

**Comment by jamerlan** [comment]
Probably this bug happens when you are trying to join a battleroom when you have no map

**Comment by abma** [comment]
relevant parts from stacktrace:

0 + 4519592515
BattleRoomTab::UpdateMapInfoSummary() + 1253
BattleRoomTab::UpdateBattleInfo(wxString const&) + 1025
BattleRoomTab::SetBattle(IBattle*) + 1325
Ui::OnJoinedBattle(IBattle&) + 64
ServerEvents::OnJoinedBattle(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 740
TASServer::ExecuteCommand(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) + 12554
TASServer::ExecuteCommand(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 2760
TASServer::OnDataReceived() + 704

**Comment by abma** [comment]
uncatched exception i guess:

https://github.com/springlobby/springlobby/blob/master/src/gui/hosting/battleroomtab.cpp#L501

**Comment by abma** [comment]
@Usaga:

we should not use exceptions imo. c++ compilers sadly doesn't detect uncatched exceptions at compile time :-|

**Comment by abma** [comment]
oh, i'm tired, sorry this exception should be catched, no clue why it crashes in this function. but still the usage of the exception in this function is weird. it is not needed.

**Comment by abma** [comment]
@jamerlan:

can you please test if the commit fixes the crash?

**Comment by Usaga** [comment]
I did not wrote that code nor modifed it, so do not know why it uses exceptions.

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/10a1bb65b5234f44095f89a1e9741461da0d5485

**Comment by Usaga** [comment]
Oh shi... Why I done this :-)

**Comment by abma** [comment]
no clue if my change fixed the crash, it shouldn't, but lets see...

**Comment by JoshuaPettus** [comment]
Here is a test version
https://www.dropbox.com/s/6bnqxmwv5x4d9k2/SpringLobby-0.226-4-g7bebb06-OSX-10.10.dmg?dl=0
Seems to work for me

**Comment by JoshuaPettus** [comment]
He said it works :) 
https://springrts.com/phpbb/viewtopic.php?f=65&t=32970&start=40

**Comment by abma** [comment]
great, thanks!
