### ISSUE TITLE
hangs when host uses !addbox on autohost mode

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#554]
to reproduce, host a multiplayer game, go to "player management" and enable "autohost", and then on the battle chat type "!addbox 10 10 5 5" -> lobby hangs and must be restarted 

this happens on springlobby 0.226

**Comment by abma** [comment]
i hopefully didn't break sth. else as i removed the teamno offset

https://github.com/springlobby/springlobby/commit/bdf66432b4ab0285be6f358205e6ed24d01a025b#diff-7e43a52fbeb26319c83e95ce16bd6d3dL210
