### ISSUE TITLE
replay list is very slow

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#556]
sorting / deleting files is VERY slow. not sure about the cause atm

**Comment by abma** [comment]
to reproduce: have a lot of replays (>500)

- sort files -> hang
- delete file -> hang
- reload files -> hang

**Comment by Usaga** [comment]
This happens under linux?

**Comment by Usaga** [comment]
Looks like this is veeeeeeery old problem: http://trac.wxwidgets.org/ticket/13515

**Comment by abma** [comment]
yeah, seems to happen only on linux :-|

**Comment by abma** [comment]
oh:
"This has been discussed on wx-users, topic: "wxDataView and sorting - slow performance". I have a workaround for now: I override wxDataViewModel::Resort and stop it from sorting after a value change or between item changes."

**Comment by abma** [comment]
should be fixed in wxwidgets 3.0.3
