### ISSUE TITLE
starting a game in singleplayer mode results in being called "Player", even if you are logged in with a username

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#559]

**Comment by silentwings** [comment]
and the same for rank & country

**Comment by specing** [comment]
Hmm, does this even matter?

**Comment by specing** [comment]
bump

**Comment by silentwings** [comment]
It matters for missions, where users would expect to be identified by their own username and country. 

Rank ofc is as good as deprecated.

**Comment by abma** [comment]
i agree, thats no issue: even when springlobby writes this to script.txt this info is missing when spring.exe directly is started. The game has to workarround this IMHO.

**Comment by silentwings** [comment]
The game can't because it doesn't know the name of the player.

**Comment by specing** [comment]
#817 could also be used to force people to sign-in before starting. No need for any lualobby machinery. Actually, it could be used to forward special id+pass to use when the game communicates with some master server on its own. Actually SL could provide an authenticated tunnel to that server on its own.

**Comment by silentwings** [comment]
SL can't assume it has an internet connection, for singleplayer mode, imo. However, if there is one, and the player signs in, singleplayer mode should use the username provided.

**Comment by specing** [comment]
It can, however, refuse to work if there is no internet connection and the selected game requires one.

**Comment by silentwings** [comment]
SL has no way of knowing if the game requires an internet connection; and the game itself may not discover until it tries to use LuaSocket.

**Comment by specing** [comment]
That is true right now.

**Comment by silentwings** [comment]
It will always be true. SL cannot predict with any accuracy how the games code and/or users will behave.

**Comment by specing** [comment]
That is why such a toggle could be added to bundles.
