### ISSUE TITLE
check for free space / add OS version to help->system info

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#563]
got some user in chat where maps/games weren't detected, paths were default.

SpringLobby 0.225 (win x32)
SpringLobby config file: C:\Users\Hans\AppData\Roaming\springlobby\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\Hans\AppData\Roaming\springlobby)
    WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\Hans\AppData\Roaming\springlobby\cache)
    WX: yes POSIX: yes TRY: yes
ExecutableFolder (D:\Spring)
    WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Hans\Documents\My Games\Spring)
    WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\Hans\Documents\My Games\Spring)
    WX: yes POSIX: yes TRY: yes
Current unitsync: D:\Spring\unitsync.dll
Current spring executable: D:\Spring\spring.exe
Current uikeys.txt: C:\Users\Hans\Documents\My Games\Spring\uikeys.txt
Portable mode: no
Compiled with wxWidgets 2.9.5.0
Started with: 
D:\Spring\springlobby.exe

**Comment by abma** [comment]
works for me.

only idea i have is to check for free disk space

**Comment by specing** [comment]
I see some free space code in git log, is this done?

**Comment by abma** [comment]
yep, pr-downloader + unitsync checks for free space.

latest unitsync (>104.0) version reports an error, older unitsync (104.0) versions silently fail afaik.
