### ISSUE TITLE
SL tried to start spring 100.0 in relay-host-room with spring 98.0

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#571]
as pictured

![bla](https://cloud.githubusercontent.com/assets/3044855/10325454/b496e738-6c91-11e5-90a8-b2e718232e4b.png)

**Comment by abma** [comment]
whats the output of help->system info?

**Comment by abma** [comment]
at least i can partly reproduce the problem here:
Warning  src/downloader/prdownloader.cpp:230 Unhandled category: engine_linux64

**Comment by abma** [comment]
are you shown as unsynced in battle?

**Comment by knorker** [comment]
In battle room it is synced.
Not sure if it is problem of downloader..when hosting "98.0" is selected, "98.0" also shows in battlelist...nowhere is something with 100.0

------------
SpringLobby 0.236 (win x32)
SpringLobby config file: C:\Spiele\spring-98.0\springlobby.conf ( writable)
LobbyWriteDir (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Spiele\spring-98.0\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\dell\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Spiele\spring-98.0\unitsync.dll
Current spring executable: C:\Spiele\spring-98.0\spring.exe
Current uikeys.txt: C:\Spiele\spring-98.0\uikeys.txt
Portable mode: yes
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Spiele\spring-98.0\springlobby.exe

**Comment by Usaga** [comment]
This can be part (or result) of #573.
