### ISSUE TITLE
lobby will "connect" to anything

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#575]
No matter what gibberish is entered as server details, springlobby will "pretend" to connect to it.
(actually it then connects to official server)

*\* Server *\* Connecting to server lolollololol34serzdgd...
*\* Server *\* Connected to lolollololol34serzdgd.
*\* motd *\* Welcome, 123!
*\* motd *\* There are currently 122 clients connected

**Comment by Usaga** [comment]
Very fun bug)))

**Comment by abma** [comment]
you have to enter

dns name:port

i.e.

lobbyserver:8200

**Comment by knorker** [comment]
I know.
The bug is that the lobby gives no error message, it just says:
 ** Server ** Connected to lolollololol34serzdgd.
In this case it is obviously that there is no possible way that the lobby really connected to that.
In other cases not so clear = confusing.

The log should read something like:

Connecting to server lolollololol34serzdgd...
Error: Could not connect to lolollololol34serzdgd.
Trying next server...
Connecting to springrts:8200...
Connected to springrts:8200

**Comment by abma** [comment]
duplicate / related to #433
