### ISSUE TITLE
remove installer/ dir from tarball

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#576]
Hi,

please consider to provide source-only tarballs again as until recently. (version 0.237) The windows binaries in the new installer directory are of no use on non-Windows systems. They just take up space. 

According to installer/nsis_plugins/README.txt, some of the plugin licenses are unknown. That makes them non-distributable due to copyright law. Debian also requires that all binaries can be built from source and therefore the sources must be at least provided together with the binaries. (I know the GPL allows you to put the source code for the (L)GPL licensed plugins on a different site but then you also have to make sure that the source remains available for as long as you distribute the dll files". Debian cannot rely on this because it is also distributed on physical media for example.)

So I have removed the installer directory for now but I would rather like to see the old source tarballs again. That was perfect. Thanks for considering.

**Comment by abma** [comment]
thanks!

**Comment by abma** [comment]
damn, fix didn't work :-|

**Comment by apoleon** [comment]
Hi,

is there anything that can be done to resolve this bug? I mean it worked very well before and the windows files are clearly not needed on other platforms.
