### ISSUE TITLE
(v0.243) error spam: "logic error (/data/private/buildbot/slabes.... m_server_chat"

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#578]
Windows 7, completly fresh install
1) downloaded springlobby-0.243-win32.zip
2) unpacked to G:\Spiele\SpringLobby
3) start springlobby.exe, register account
4) Lobby instantly says "No engine found, download 100.0?" 
5) Click "No", because first want to set download location.
6) Go to options, set Download-directoy = "G:\Spiele\SpringLobby\"
7) Meanwhile springlobby has produced these message boxes, and makes new ones at rate of one every dozen seconds or so:

![bla](https://cloud.githubusercontent.com/assets/3044855/10770991/973d4c5a-7cee-11e5-8929-9b2713750c2b.jpg)

(no idea what triggers it, in chat was no new messages)

SpringLobby 0.243 (win x32)
SpringLobby config file: C:\Users\otte\AppData\Roaming\springlobby\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\otte\AppData\Roaming\springlobby\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\otte\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (G:\Spiele\SpringLobby\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (G:\Spiele\SpringLobby\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: ()
	WX: no POSIX: no TRY: yes
Current unitsync: 
Current spring executable: 
Current uikeys.txt: uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
G:\Spiele\SpringLobby\springlobby.exe

**Comment by knorker** [comment]
random chatlog, at least one other user with this error:

[21:07:35] <MrBlack> anyone know how to stop the logic erro popup?
[21:07:35] <[Fx]Bluestone> your gonna need waaaaay more info that than before anyone know what you're talking about
[21:07:35] <MrBlack> fiar enoguh... to come
[21:07:35] <MrBlack> is in springloby
[21:07:35] <MrBlack> logic error /home/user/springlobby-2.19/src/gui/mainchattab.cpp:95):m_server_chat = 0
[21:07:35] <[Fx]Bluestone> i dont see any error but the bugtracker is here https://github.com/springlobby/springlobby/issues
[21:07:35] <MrBlack> ok, will look into that, it basically pops in springlobby and I have to ok it.  
[21:07:35] <MrBlack> it pops ever few seconds and makes it difficult to do anything

**Comment by knorker** [comment]
no new information but these "screenshots" are too amazing to be lost.
![amazing](https://cloud.githubusercontent.com/assets/3044855/11132802/6bdcbfc2-8992-11e5-8a3c-a6d7ce8a52fa.jpg)

![amazing2](https://cloud.githubusercontent.com/assets/3044855/11132843/abc5810a-8992-11e5-8e84-2ac447410fe5.jpg)

**Comment by abma** [comment]
can be reproduced when the server tab is closed it seems

**Comment by knorker** [comment]
ive had it happen with server tab not closed. I closed server tab for test and few minutes later it made those errors again..or maybe random.

another such error popup with different msg: https://github.com/springlobby/springlobby/issues/594

**Comment by abma** [comment]
fixed by 72b8c14243ec84a9ef5a1a686724c5463597463f
