### ISSUE TITLE
subscribe checkbox is not working?

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#579]
I have "subscribe" unchecked for "#sy" channel
and If I click it - popup menu closes... and when I open it agail - still not checked
lol... for #springlobby it's allways checked
can't uncheck

---

SpringLobby 0.243-10-g4d23922 (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
    WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
    WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
    WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
    WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
    WX: yes POSIX: yes TRY: yes
Current unitsync: /usr/lib64/libunitsync.so
Current spring executable: /usr/bin/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
/home/revenant/springlobby/src/springlobby

**Comment by abma** [comment]
subscription still is experimental.

imo first https://github.com/spring/uberserver/issues/183 should be implemented before touching this code at springlobby 

is it checked when you restart springlobby?

**Comment by jamerlan** [comment]
yep, when I restart lobby - checkbox updated

**Comment by specing** [comment]
No subscription button -> no issue!
