### ISSUE TITLE
(v0.243) downloads dialog (filesize 0MB, denglisch, file spam)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#580]
Fresh install, joined an authost, looked at downloads tab:
The "XTA" mod is listed twice.
The map "duck" is displayed as filesize 0 MB.
There is german/englisch mix of words.
There is lots of downloads with no name &  lots of "versions.gz" in download list, all with file 0MB.
(maybe hide from user or group it together or so...it looks very broken)

![bla](https://cloud.githubusercontent.com/assets/3044855/10771343/7d047fe6-7cf0-11e5-8daa-669cb43770a4.jpg)

**Comment by knorker** [comment]
Also despite all downloads appearing to finishing succesful and the files having appeared on HDD, lobby still says unsynced:
![bla](https://cloud.githubusercontent.com/assets/3044855/10771517/81982778-7cf1-11e5-9eb7-bbffd591682c.jpg)

"Reload maps/games list" does not fix it.
Restarted lobby, rejoin the same autohost.

Lobby says: "Required to download blabla", it has already downloaded this files just minutes ago...

In singleplayer neither a map or game is listed, howerver engine-dropdown lists "98.0"

![bla](https://cloud.githubusercontent.com/assets/3044855/10771634/1f9139ba-7cf2-11e5-930c-a9a3fd76b748.jpg)

**Comment by knorker** [comment]
every time I click "Download" under the invisible minimap a new duck appears:

![bla](https://cloud.githubusercontent.com/assets/3044855/10771835/46dac3c8-7cf3-11e5-99ef-488ef98fa474.jpg)

all ducks are displayed as "vollständig" (="complete") 
...

**Comment by abma** [comment]
related to #577

**Comment by knorker** [comment]
joined different autohost:
engine 100.0, map DeltaSiegeDry, mod BA
Excactly same problems

**Comment by knorker** [comment]
I edited
C:\Users\otte\Documents\My Games\Spring\springsettings.cfg (was empty)
and added: 
SpringData = G:\Spiele\SpringLobby
(same folder as set for downloads in springlobby options)

That way I could sync and start a game with springlobby. (All the other issues are unchanged)

However now more files are appearing in user-folder (and wrong disc) like:
demos\
LuaUI\
lups.cfg
cache\
etc
which I wanted to avoid...

**Comment by abma** [comment]
for bugs / ideas / ... wrt portable mode please use #584

**Comment by abma** [comment]
should be fixed, atm only one download is reported, dependant downloads are not shown
