### ISSUE TITLE
fedora 22, gnome 3 - no close button for "system info" window

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#581]
![screenshot from 2015-10-27 23-23-55](https://cloud.githubusercontent.com/assets/216801/10771463/f0cf3478-7d01-11e5-9294-c1e190f17e4d.png)

**Comment by jamerlan** [comment]
"About" have the close button for example

**Comment by Usaga** [comment]
Test it, please. It should be fixed now. I hope so...

**Comment by jamerlan** [comment]
yep, fixed! thanks!
