### ISSUE TITLE
(v0.243) GUI rows are too narrow by default in lists

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#582]
In chat playerlist, replays list, battleroom playerlist, downloads list, battlelist:
The rows all have the same size, which is too small to fit most informations:

![bla](https://cloud.githubusercontent.com/assets/3044855/10771978/f0db717e-7cf3-11e5-9ad0-04300175dbde.png)

The names etc do not fit and get displayed as shortend version, basically unreadable.

windows 7

**Comment by Usaga** [comment]
Should be fixed now...
