### ISSUE TITLE
rework download status stuff

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#583]
code can be simplified / deduplicated.

add to prdownloader.cpp

void updatelistener(int downloaded, int filesize)
{
/*
TODO:
		store values
		send event to main thread
		create event in main thread

		add events:
			- progress (here)
			- start (prd)
			- failed (prd)
			- done (prd)
*/
}

IDownloader::setProcessUpdateListener(updatelistener);

**Comment by Usaga** [comment]
Hm, seems prdownloader is broken now. It downloads stuff, but shows its incomplete. Works fine only with engines. I mean logs show problem not in lobby itself.

**Comment by abma** [comment]
sorry for current breakage, its WIP

**Comment by Usaga** [comment]
Not a problem.

**Comment by Usaga** [comment]
What is WIP?

**Comment by abma** [comment]
work in progress :)

**Comment by abma** [comment]
self-update is broken atm

**Comment by abma** [comment]
related to #577

**Comment by Usaga** [comment]
@abma, I could rework download stuff, but I do not want to touch pr-downloader library, meanwhile I want IDownloaderProcessUpdateListener function to receive not only progress and size, but item's name too (I think this is needed for DownloadTab and for proper calculation of total download progress if more than one download is present). Could you introduce new function (or rework old one) to make pr-downloader able to provide more information about downloading progress?

**Comment by abma** [comment]
imo all info is there:

currently no parallel downloads are supported, so the name is the most recent download which is started....

not the niced thing, but should allow to make it work as before. imo it would be better if the listener would have a parameter with the download id, so required info can be fetched.

**Comment by abma** [comment]
i think i'm done with the large refactoring.

now all required download events should exist, but some stuff like unitsync switching is missing for now / and it needs a bit to stabelize.

**Comment by abma** [comment]
its done, possible still needs fixing see #678 maybe
