### ISSUE TITLE
do not "hide bots" in battlelist (it is useful for !notify)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#585]
When clicking/selecting a room in battlelist it shows a "preview" of the players in that room.
The autohosts are no longer included in that list.
That used to be useful because one send !notify private messages to other hosts, without having to change rooms.

**Comment by Usaga** [comment]
Hm. Does all autohosts support this ability? I mean !notify command?

**Comment by knorker** [comment]
I do not remember seeing any autohosts without !notify command. But I think there is no real standard how an autohost has to work? So in theory someone could make his autohost with different commands or something. But at least the hosts of BA, Techa, NOTA, XTA support it...

**Comment by Usaga** [comment]
I asked it because I though may be it is simplier for users to make context menu in battle list with !norify command in it...

**Comment by knorker** [comment]
For !notify it would would work I think. (like it also works for !start)
Other commands not so much, for example autohosts have an !addbox command for startboxes, but use different coordinate systems...

**Comment by FabriceFABS** [comment]
I agree with knorker for not hiding bots.
Between, why hiding them ?

I use this way also for !sb or others informations I may need.
Actually with hidden bot feature, I should go in #[ACE] channel (or anywhere there are ACE autohosts), uncheck @bottom the button [Hide Bots], double-click on the autohost, to get it finally in private.
This is too complex.

It would be good to set this option in user preference (not in each channel & battle list).
Hiding bots set on by default with possibility for user to globally disable it.

I've just test #585 menu for getting a notification in the battlelist.
This is a nice idea, but this feature is written no-where.
Maybe better a check-box on the bottom of the battlelist window, in the game's window information near filter button for instance.

**Comment by specing** [comment]
This is already implemented in the commit above. Buttons for notify and PM can be added to game info.

**Comment by specing** [comment]
@FabriceFABS  please check out https://springrts.com/phpbb/viewtopic.php?p=585247#p585247

**Comment by abma** [comment]
minor changes by https://github.com/springlobby/springlobby/pull/847 or
https://github.com/springlobby/springlobby/pull/875
