### ISSUE TITLE
closing dialogs should mean "no / cancel"

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#586]
I think standard way in most programs is that closing a dialog-window is the same as clicking no/cancel.
But in springlobby closing the dialog means "yes."

Example:

1) be in battleroom
2) try to join a different room
3) Lobby asks:
"Do you want to leave current room and join different room?
[yes] [no]"
4) That dialog has a close-window-X-button.
=> Closing the dialog with "X" makes you leave room & join other one.

Same thing for dialog "Do you want to download...?  yes/no"
Closing the window with "X" starts the downloads.

Maybe the "X" should just be disabled in such dialogs.

**Comment by Usaga** [comment]
This sounds more as bug neither alternative behavior...
