### ISSUE TITLE
join #main by default

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#587]
#main chatchannel is pretty much deserted,  <20 players and it has been ages since I have seen a human chatline there.
After spamattacks from last years many players left it (because spam sucks) and it is stopped being default channel.
I think a common chatchannel that as many lobbies as possible join by default is important.

**Comment by abma** [comment]
"#newbies" is used for that

**Comment by knorker** [comment]
Imo the channel-name matters and "#newbies" sounds too much like channel for help/troubleshooting only, so it does not get accepted.
There is no "normal chat" for finding other players (outside the two big BA/Techa rooms), announcements (maybe tourneys, like there was 5 years ago) etc..

**Comment by springraaar** [comment]
I agree with this. There should be a channel all players would join automatically, and which would allow for promoting games, etc.

Currently the "promote" option is nearly useless....as the only channel with a sizable population is the "newbies" channel and people aren't allowed to promote games there...

**Comment by knorker** [comment]
not relevant anymore because spring games are now to be advertised seperatly with their own customized lobbies. the various lobbies and games knowingly moved away from the the #main channel (or destroyed it with advertisement spam), why would they add it back?
