### ISSUE TITLE
subscriptions + fresh springlobby

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#589]
Imagine this situation:
I have some subscriptions ( like #badev, #sy etc). I was AFK a few days (OS on my PC was f#cked). 
And now I reinstalled OS + reinstalled springlobby and I want to read all messages in "subscribed" channels

When I login - I have no "#badev" or "#sy" opened.. and it looks like I lost all messages. 
But actually when I join the channel (for example #sy) - I can see some messages but with "current" timestamp. 

My suggestion:
1) reopen all "subscribed" channels if they have "pending" messages - after login
2) (nice to have) - print "sent message" timestamp for subscribed messages, not "received by you" timestamp. Currently the whole conversation looks like it happened in current second

**Comment by Usaga** [comment]
By "subscribed" you mean those channels that has opened when lobby starts? This is not subscription, just lobby saves list of previously opened channels in local configuration file. If you have lost your configuration due to OS cataclism or something similar so you have lost and your "subscribtion".

**Comment by jamerlan** [comment]
>>By "subscribed" you mean those channels that has opened when lobby starts?
no, if you rightclick on channel - you have a "subscribe" in menu items. VERY useful feature!

**Comment by abma** [comment]
https://github.com/spring/uberserver/issues/183 should be implemented first...

**Comment by abma** [comment]
-> #807
