### ISSUE TITLE
fedora 23 - compilation failed

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#590]
I don't know.. maybe it's my system fail.. I updated fedora 22 to fedora 23 and then springlobby is not compiling (linking) anymore: http://pastebin.com/GaGeBZZA

latest commit was: 
commit f96008b9796de3daebc58fab14b993cf83a8eb9d
Author: abma <spring@abma.de>
Date:   Thu Nov 5 00:54:13 2015 +0100

**Comment by abma** [comment]
very likely paths / versions of libs have changed, cmake doesn't always detect this.

just try a fresh build and it should work.

i.e.

    $ git clean -f -d -x
    $ cmake . && make

(git clean -f -d -x will delete ALL not versioned files in the git repository)

**Comment by jamerlan** [comment]
thanks! worked!
