### ISSUE TITLE
(v0.243) logic error (src/tasserver.cpp:1605 ): Not current battle

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#594]
![bla 2](https://cloud.githubusercontent.com/assets/3044855/11171214/d5c8c3b8-8bea-11e5-9386-5a444c541659.png)

after a game had ended and people were chatting/leaving

**Comment by abma** [comment]
could be a lobby server bug

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/0.243/src/tasserver.cpp#L1605

hmm, did you host a game when this happened?
did you try to make a player a spectator?
