### ISSUE TITLE
lobby crash

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#599]
(gdb) bt full
0  0x00000000006a639c in BattleListTab::UpdateBattle(IBattle&) ()
1  0x0000000000678e5b in Ui::OnBattleInfoUpdated(std::pair<IBattle*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) ()
2  0x000000000067b0e9 in Ui::OnUserBattleStatus(wxCommandEvent&) ()
3  0x00007ffff4e8873e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () at /lib64/libwx_baseu-3.0.so.0
4  0x00007ffff500ebf8 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
5  0x00007ffff500efee in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
6  0x00007ffff500f07e in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
7  0x00007ffff500f143 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
8  0x00007ffff500f1a5 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
9  0x00007ffff500fc3a in wxEvtHandler::ProcessPendingEvents() () at /lib64/libwx_baseu-3.0.so.0
10 0x00007ffff4e8af47 in wxAppConsoleBase::ProcessPendingEvents() () at /lib64/libwx_baseu-3.0.so.0
11 0x00007ffff5518192 in wxApp::DoIdle() () at /lib64/libwx_gtk3u_core-3.0.so.0
12 0x00007ffff5518283 in wxapp_idle_callback () at /lib64/libwx_gtk3u_core-3.0.so.0
13 0x00007ffff70ede3a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
14 0x00007ffff70ee1d0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
15 0x00007ffff70ee4f2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
16 0x00007fffeee87785 in gtk_main () at /lib64/libgtk-3.so.0
17 0x00007ffff5537d95 in wxGUIEventLoop::DoRun() () at /lib64/libwx_gtk3u_core-3.0.so.0
18 0x00007ffff4eca283 in wxEventLoopBase::Run() () at /lib64/libwx_baseu-3.0.so.0
19 0x00007ffff4e8f636 in wxAppConsoleBase::MainLoop() () at /lib64/libwx_baseu-3.0.so.0
20 0x00007ffff4f1c050 in wxEntry(int&, wchar_t**) () at /lib64/libwx_baseu-3.0.so.0
21 0x00000000004d4188 in main ()

SpringLobby 0.243-53-g994fa10 (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
	WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /usr/lib64/libunitsync.so
Current spring executable: /usr/bin/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
/home/revenant/springlobby/src/springlobby

**Comment by jamerlan** [comment]
I don't know why line 21 is so big :-D

**Comment by abma** [comment]
should be already fixed with f51658cdf194a4c695f812a62c5f619a251d4f58
