### ISSUE TITLE
can't close messageBox

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#602]
I was watching a big BA battle.. it was boring.. so I decided to test chicken defense on "singleplayer" tab. I clicked "start" but forgot to close BA battle.. so I got "Spring error: You cannot start spring instance while another is already running". But I can't close this message box!

maybe "close" button doing nothing... or new message box instantly appearing
![nag_screen](https://cloud.githubusercontent.com/assets/216801/11325433/b242f692-915e-11e5-8bf3-472866aab02a.png)
----------------------
springlobby version: 0.243-53-g994fa10

**Comment by Usaga** [comment]
Looks like fixed
