### ISSUE TITLE
(v0.243) can only add one startbox and it is always team 2

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#603]
1) Host new Room
2) Startpositions = "choose ingame"
3) Go to "map"
4) use mouse to click & drag start areas
5) Only one startbox can be created:
Every time one tries to make a second box, the first one disappears.
The startbox is always team 2.
Adding/removing bots does not change it

**Comment by abma** [comment]
thanks for reporting, its already fixed in the development version.

https://github.com/springlobby/springlobby/commit/f57f0c8af2fc8b1aa8c83adefa364aceb7108b29
