### ISSUE TITLE
Infinite loop on Arch Linux

### ISSUE THREAD

**Issue by rlcevg** [springlobby/springlobby#604]
Springlobby hangs after 3-5 seconds after start.

Bisected to next commits
works: b93fb869d463a252717dcf873cb36e8ec2de5bb9
broken: 7ed7df92c1cfa905c8e25d5eb488948c1bab43ac

Broken commit is stuck in the loop (not recursion) infinitly calling BaseDataViewCtrl<DataType>::AddItem (and Resort).
Removing Resort from AddItem "fixes" freeze (tested only with 7ed7df92).

**Comment by abma** [comment]
which wxwidgets version is used?

how many replays do you have?

**Comment by rlcevg** [comment]
wxwidgets 3.0.2
Oops, found 3004 files in demos (don't know how i missed them). After demos removal it hangs no more (tested 7ed7df9 and 0.243).

**Comment by abma** [comment]
see #556

**Comment by Usaga** [comment]
It should be nice if we can distinguish between adding of bunch of items (where we can disable soring) on init and adding single item (like it made in chat list).

**Comment by Usaga** [comment]
Or, at least, make some notification that user has too many files to procees so it can take some time for SL to handle them...

**Comment by abma** [comment]
imo adding a bunch of files should used. afaik this is already implemented for the nicklist.

**Comment by abma** [comment]
should be fixed by https://github.com/springlobby/springlobby/commit/fd59d562c5744a9972aa89ed9bd6e047dbe9f422
