### ISSUE TITLE
Autoscaling columns after fresh install don't work

### ISSUE THREAD

**Issue by J0ga** [springlobby/springlobby#607]
Autosclaing the columns don't work after a fresh install in windows( don't know for linux users ))

it may be a Gui toolkit issue !

**Comment by Usaga** [comment]
In what version of SL autoscaling was working?

**Comment by J0ga** [comment]
I never had it working ! And i always used :
Windows 7 ( arium version ) x64 .
But i think its not only an os problem !

**Comment by Usaga** [comment]
Should be fixed now
