### ISSUE TITLE
change unsync ico in battle rooms

### ISSUE THREAD

**Issue by J0ga** [springlobby/springlobby#608]
once upon a time : they where a pretty ico no it has been remplaced with somethig ugly ! and i don't find the commit who may change that !

**Comment by Usaga** [comment]
I did it when was reimplementing list controls. These icons where built-in in application a long time ago and I used them instead of generation ones on a fly (like it was before) because it was easy and I did not saw any difference betwen them.
I will try to use pretty icons again.

**Comment by J0ga** [comment]
OK great , you may only need to copie the normal ico (synced) and add a warning panel in front !:)

**Comment by Usaga** [comment]
It's done!

**Comment by J0ga** [comment]
Great
