### ISSUE TITLE
game/map download broken (by "This battle requires map to be downloaded..." ?!)

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#609]
when clicking yes, nothing happens

**Comment by abma** [comment]
maybe because of 
https://github.com/springlobby/springlobby/commit/38afc99d91798514b755de09fa7e2e693ecb8caf

?!

**Comment by Usaga** [comment]
You mean dialog doesn't closed or downloading not started after dialog closed?

**Comment by abma** [comment]
download doesn't start after dialog closed

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/38afc99d91798514b755de09fa7e2e693ecb8caf/src/gui/battlelist/battlelisttab.cpp#L427

hmmm

**Comment by abma** [comment]
please test!
