### ISSUE TITLE
crash at start (win32 only it seems)

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#612]
(gdb) bt
0  0x0094360b in wxDataViewCtrl::GetBestColumnWidth(int) const ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
1  0x00944397 in wxDataViewColumn::GetWidth() const ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
warning: (Internal error: pc 0x0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x2 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x3 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x2 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x2 in read in psymtab, but not in symtab.)

2  0x00000003 in ?? ()
3  0x131f65f8 in ?? ()
4  0x00a56267 in wxHeaderCtrl::DoSetCount(unsigned int) ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
5  0x0093f37d in wxDataViewCtrl::OnColumnsCountChanged() ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
6  0x00000000 in ?? ()

**Comment by abma** [comment]
same stacktrace with newer gdb:

(gdb) bt
0  0x0094360b in wxDataViewCtrl::GetBestColumnWidth(int) const ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
1  0x00944397 in wxDataViewColumn::GetWidth() const ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
2  0x00000003 in ?? ()
3  0x131364c8 in ?? ()
4  0x00a56267 in wxHeaderCtrl::DoSetCount(unsigned int) ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
5  0x0093f37d in wxDataViewCtrl::OnColumnsCountChanged() ()
    at /data/private/buildbot/slaves/springlobby/mxe/build/mxe/usr/lib/gcc/i686-
w64-mingw32.static/5.2.0/include/c++/ext/new_allocator.h:110
6  0x00000000 in ?? ()

**Comment by Usaga** [comment]
new_allocator? What does this means? This introduced after my commits?

**Comment by abma** [comment]
not sure yet, as it crashes wxDataViewCtrl::GetBestColumnWidth, it seems to be at least related to autoresize columns related.

**Comment by Usaga** [comment]
After manipulations with json library in SL in around of 236 version or something there I am not able to compile it on Windows anymore, so can't catch such errors...

**Comment by abma** [comment]
can you create a bug report about this please?

**Comment by Usaga** [comment]
SL was not meant to be buildable on WIndows. It was really hard to make it work. So I think it is not worth it to spend your time... But it will be nice if it could be build on Windows :-)

**Comment by Usaga** [comment]
I can't say exactly what commit had broken all, but I can tell it was related to removing JSON library from SL (or replacing it with some other, I can't tell thoroughly)

**Comment by abma** [comment]
> SL was not meant to be buildable on WIndows.

imo it should build with mingw on windows. if not i see it as bug as it possible doesn't compile on osx, too.

**Comment by Usaga** [comment]
Problem in build scripts which is insanly hard to configure under Windows... Looks like there not much people like me who dared to do that))) If it still builds fine on Linux and OSX - it is fine. OSX might have same environment like Linux, so it has no problem with building SL...

**Comment by abma** [comment]
... can you please create a bug report with the problem/error you had? i'm pretty sure it can be easily fixed.

**Comment by Usaga** [comment]
All right, I will set up building environment and reproduce building error...

**Comment by abma** [comment]
hmm, i guess it would be good to create some libs repo like for spring:

https://github.com/spring/mingwlibs

only missing libs there are wxwidgets i guess

**Comment by Usaga** [comment]
Looks like wxWidgets does not support wxCOL_WIDTH_AUTOSIZE under Windows... Or I do not understand something :-(
