### ISSUE TITLE
buildbot: always use/build this repo

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#613]
personal repositories aren't used any more...

**Comment by abma** [comment]
@Usaga 

fyi: the buildbot now automaticly builds a development build after each commit.

it has a delay of 6 minutes in average unti the build starts.

output is here:

http://springlobby.info/temp/builds/develop/

when you set UpdateChannel=develop it will use these files / automaticly update to it.

**Comment by Usaga** [comment]
Oh, nice! Thanks for information!
