### ISSUE TITLE
Failed to compile under Windows

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#614]
In file included from C:\springlobby\src\utils\platform.cpp:12:0:
**C:/springlobby/src/lsl/src/lslutils/misc.h**:9:33: **fatal error**: boost/noncopyable.hpp: No such file or directory **#include \<boost/noncopyable.hpp\>**

**Comment by Usaga** [comment]
Looks like something wrong with CMakeList...

**Comment by abma** [comment]
there:

https://github.com/springlobby/springlobby/blob/master/src/CMakeLists.txt#L383

add 

      PRIVATE ${Boost_INCLUDE_DIRS}

**Comment by Usaga** [comment]
It didn't helped - same error in the same place...

**Comment by Usaga** [comment]
Helped adding such record to this file: https://github.com/springlobby/springlobby/blob/master/src/updater/CMakeLists.txt#L26

**Comment by abma** [comment]
thats the problem with incomplete log files :-)

glad that it helped, does it compile now?

**Comment by Usaga** [comment]
No, but it moved forward greatly (from 14% to 46%):
[ 46%] Building CXX object src/CMakeFiles/springlobby.dir/crashreport.cpp.obj
[ 47%] Building CXX object src/CMakeFiles/springlobby.dir/log.cpp.obj
C:\springlobby\src\crashreport.cpp:7:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>

**Comment by abma** [comment]
you can already guess what could fix it :-)


in https://github.com/springlobby/springlobby/blob/master/src/CMakeLists.txt#L383

add 

      PRIVATE ${CURL_INCLUDE_DIRS}

should help! :-)

**Comment by Usaga** [comment]
Help adding PRIVATE ${CURL_INCLUDE_DIR} to main CMakeList

**Comment by Usaga** [comment]
These two little changes helped! SL compilated and is crashing as it shoud! Really-really thanks for your advice!!
I think theese changes in CMakeLists should not brake compilation under Linux?..

**Comment by abma** [comment]
yes, please add them! :)
