### ISSUE TITLE
a way to start games in SP-mode

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#620]
Some games contain lua-scripted singleplayer.
The lobby has no button to start it.

Proposal:
1) mod.sz contains a file gamedata\lobbystartscript.txt
2) lobby adds a button "Launch the game's included singleplayer"

**Comment by abma** [comment]
> 1) mod.sz contains a file gamedata\lobbystartscript.txt

how can the lobby check if all required files are available? (mostly the map)

> 2) lobby adds a button "Launch the game's included singleplayer"

what information to show? lobby only knows game name.

**Comment by knorker** [comment]
> how can the lobby check if all required files are available? (mostly the map)

Lobby can know the mapname from startscript.
The check would work like lobby always check files, for joining MP game or when playing replay..
 
> what information to show? lobby only knows game name.

no need to show anything special. Only a button, like in this is mockup in bottom left corner:
![mockup](https://cloud.githubusercontent.com/assets/3044855/12075041/e871be4a-b172-11e5-8c70-150edf50b25e.png)

**Comment by knorker** [comment]
I found something better and have no need for this anymore

**Comment by abma** [comment]
share your knowledge maybe?
