### ISSUE TITLE
Ubuntu version is outdated

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#621]
https://springrts.com/phpbb/viewtopic.php?f=11&t=34216
"I have installed Springlobby from the ppa:spring/ppa repository, and I have installed libsdl2-2.0-0."
-> "Version 0.169"

https://springrts.com/phpbb/viewtopic.php?f=11&t=33285
"I tried to follow the instructions on https://github.com/springlobby/springlobby/wiki/Install#Ubuntu, but it installs springlobby version 0.169. This versions says "incompatible spring" when I try to join a battle."

**Comment by abma** [comment]
contact the package maintainer, i can't do much about this...

**Comment by knorker** [comment]
the instructions to use that package are on SL page https://github.com/springlobby/springlobby/wiki/Install#Ubuntu so that was my attempt to contact him here.

**Comment by abma** [comment]
"You should however consider using the more up-to-date packages from this "ppa":https://launchpad.net/~spring/+archive/ppa"

**Comment by knorker** [comment]
@renemilk

**Comment by renemilk** [comment]
I'm not updating any spring related packages any longer. Sorry.
