### ISSUE TITLE
manual engine download seems to not work (win32 at least)

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#622]
search for 100.0.1-640-g2a7b9f5

try to download

nothings happens (it seems)

**Comment by Usaga** [comment]
downloading does not working at all since prdownloader has been reworked...

**Comment by Usaga** [comment]
I did not touch that, thinking you stil working on it...

**Comment by abma** [comment]
last time i checked map / game download worked (just no status is shown...)

and yes, still wip

**Comment by Usaga** [comment]
I got this 
![assert](https://cloud.githubusercontent.com/assets/10685845/12114144/12b63f3c-b3da-11e5-98ad-c12dece1a542.png)

**Comment by Usaga** [comment]
And no file was downloaded. It is possible, that my build is wrong...

**Comment by Usaga** [comment]
Strange error log shown wile trying to download engine:
```
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\File.cpp:67:Open(): file opened before old was closed
[Error] C:\springlobby\src\downloader\lib\src\Downloader\Http\HttpDownloader.cpp:323:setupDownload(): No mirror found
[Error] C:\springlobby\src\downloader\lib\src\Downloader\Http\HttpDownloader.cpp:486:download(): no piece found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z: Archive not found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z: Archive not found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\FileSystem.cpp:376:removeFile(): Couldn't delete file C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\File.cpp:67:Open(): file opened before old was closed
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\FileSystem.cpp:376:removeFile(): Couldn't delete file C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z
[Error] C:\springlobby\src\downloader\lib\src\Downloader\Http\HttpDownloader.cpp:323:setupDownload(): No mirror found
[Error] C:\springlobby\src\downloader\lib\src\Downloader\Http\HttpDownloader.cpp:486:download(): no piece found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z: Archive not found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z: Archive not found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z: Archive not found
[Error] C:\springlobby\src\downloader\lib\src\FileSystem\FileSystem.cpp:376:removeFile(): Couldn't delete file C:\Users\Р СѓСЃР»Р°РЅ\Documents\My Games\Springngine\spring_{develop}100.0.1-644-g3f7b6e0_minimal-portable.7z
```

**Comment by Usaga** [comment]
I noticed just now that downloader produces zero-sized files (maps, mods and engines). So I unable to download anything((

**Comment by Usaga** [comment]
It is strange. Commit d186d82210cb70aea020a07cc3c85b84ad767a4a in pr-downloader library is detached from springlobby repo. When I do `git submodule update` this commit is deached. When I do `git checkout master` in pr-downloader library and then rebuild I get able to download mods, but not maps...

**Comment by abma** [comment]
possible current pr-downloader / springlobby are incompatible, thats what i didn't test... gimme some time! :)

**Comment by Usaga** [comment]
No no no! Me want it working yesterday! :-)

**Comment by abma** [comment]
hm, was introduced here it seems:

https://github.com/spring/pr-downloader/commit/605b9d1e0c419bc7433481ec5412825c65e92176

**Comment by abma** [comment]
more detailed stacktrace about the failing assert:

0  0x00007ffff2cf9267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
1  0x00007ffff2cfaeca in __GI_abort () at abort.c:89
2  0x00007ffff2cf203d in __assert_fail_base (fmt=0x7ffff2e54028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x15adfa0 "handle==__null", 
    file=file@entry=0x15ad8a0 "src/downloader/lib/src/FileSystem/File.cpp", line=line@entry=212, 
    function=function@entry=0x15ae440 <CFile::SetPieceSize(int)::__PRETTY_FUNCTION__> "bool CFile::SetPieceSize(int)") at assert.c:92
3  0x00007ffff2cf20f2 in __GI___assert_fail (assertion=0x15adfa0 "handle==__null", file=0x15ad8a0 "src/downloader/lib/src/FileSystem/File.cpp", line=212, 
    function=0x15ae440 <CFile::SetPieceSize(int)::__PRETTY_FUNCTION__> "bool CFile::SetPieceSize(int)") at assert.c:101
4  0x0000000000d013cb in CFile::SetPieceSize (this=0x610000211140, pieceSize=65536) at src/downloader/lib/src/FileSystem/File.cpp:212
5  0x0000000000cffe8e in CFile::Open (this=0x610000211140, filename="/home/abma/.spring/maps/holdthefire.sd7", size=16335168, piecesize=65536)
    at src/downloader/lib/src/FileSystem/File.cpp:65
6  0x0000000000cee57b in CHttpDownloader::download (this=0x6020008a7ab0, download=..., max_parallel=1) at src/downloader/lib/src/Downloader/Http/HttpDownloader.cpp:475
7  0x0000000000ce5ab3 in DownloadStart () at src/downloader/lib/src/pr-downloader.cpp:226
8  0x0000000000ad40fa in DownloadItem::Run (this=0x60b00073cea0) at src/downloader/prdownloader.cpp:67
9  0x0000000000bb4a37 in LSL::WorkItemQueue::Process (this=0x6110000fd388) at src/lsl/src/lslutils/thread.cpp:123
10 0x0000000000bbee86 in boost::_mfi::mf0<void, LSL::WorkItemQueue>::operator() (this=0x61500010f138, p=0x6110000fd388) at /usr/include/boost/bind/mem_fn_template.hpp:49
11 0x0000000000bbed1a in boost::_bi::list1<boost::_bi::value<LSL::WorkItemQueue*> >::operator()<boost::_mfi::mf0<void, LSL::WorkItemQueue>, boost::_bi::list0> (this=0x61500010f148, 
    f=..., a=...) at /usr/include/boost/bind/bind.hpp:253
12 0x0000000000bbe8f6 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, LSL::WorkItemQueue>, boost::_bi::list1<boost::_bi::value<LSL::WorkItemQueue*> > >::operator() (
    this=0x61500010f138) at /usr/include/boost/bind/bind.hpp:893
13 0x0000000000bbe452 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, LSL::WorkItemQueue>, boost::_bi::list1<boost::_bi::value<LSL::WorkItemQueue*> > > >::run (this=0x61500010ef80) at /usr/include/boost/thread/detail/thread.hpp:116
14 0x00007ffff67f8bc5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
15 0x00007ffff63cd6aa in start_thread (arg=0x7fffd910f700) at pthread_create.c:333
16 0x00007ffff2dcaeed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by abma** [comment]
happy testing! ;-)

**Comment by Usaga** [comment]
Maps and mods can now be successfully downloaded. Thanks! But engines still could not be downloaded...

**Comment by abma** [comment]
indeed, manual download now works (downloads->search file), but "automatic" doesn't (right click battle -> download engine)

**Comment by abma** [comment]
next try, please test again! :-)

**Comment by abma** [comment]
currently i get this:

[Info] opened C:\Users\abma\Documents\My Games\Spring\engine\spring_{develop}100.0.1-856-g61559fa_minimal-portable.7z
[Info] md5 correct: a3b711d4980b53d7b539d91247634b40
[Info] Extracting C:\Users\abma\Documents\My Games\Spring\engine\spring_{develop}100.0.1-856-g61559fa_minimal-portable.7z to C:\Users\abma\D
ocuments\My Games\Spring\engine\100.0.1-856-g61559fa develop
[Info] done

download seems to work, extraction is triggered, but it doesn't extract

**Comment by abma** [comment]
@Usaga 

does it work for you, too?

**Comment by Usaga** [comment]
I will try it today after work

**Comment by Usaga** [comment]
Yep, it works now. Thanks!
