### ISSUE TITLE
tabs not replaced in chat text ?

### ISSUE THREAD

**Issue by cleanrock** [springlobby/springlobby#632]
I suspect SL do not replace tabs in sent chat text (e.g. SAY message), correct ?
From http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html:
Make sure to replace all TABs in your sentences with spaces (2 or 8 usually)! If you do not, your command is invalid, and will not be read correctly by the server.

**Comment by abma** [comment]
hm, specification is a bit unclear in this case imo.

as the param "message" is the last "sentence", replacement isn't really needed...

sourcecode, sending part:

https://github.com/springlobby/springlobby/blob/master/src/tasserver.cpp#L1034

receiving part:

https://github.com/springlobby/springlobby/blob/master/src/tasserver.cpp#L608

=> yes, no replacements are made.

**Comment by abma** [comment]
"{} {} ... = two or more sentences. They are separated by TAB characters."
vs
"{} = sentence = several words (at least one!) separated by space characters"

**Comment by abma** [comment]
imo how it is shouldn't change, as it allows OTR to work.

https://otr.cypherpunks.ca/Protocol-v3-4.0.0.html

atm only via the irc bridge its possible to use it.

**Comment by abma** [comment]
-> docs should be improved in this case

**Comment by cleanrock** [comment]
Sonds good. I just wanted to check with you before i changed flobby to accept tabs in these cases.
