### ISSUE TITLE
OpenFileVFS failed to load side icons

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#636]
For some time (I did not check since when) I can not see side (factions) icons. I debuged it till file unitsync.cpp, line 498 `const int ini = susynclib().OpenFileVFS(image_path);` that failed to load icon (returns zero). It looks like this function changes icon extention from png to bmp and then failes to load such file...

It happenes on Windows. Did not check linux builds.

**Comment by abma** [comment]
looking into source code helps:
https://github.com/springlobby/lsl/blob/master/src/lslunitsync/unitsync.cpp#L477

springlobby tries first to load SideName.png, and if it fails SideName.bmp

i guess it should be checked if the file exists first so no error message is shown...

**Comment by abma** [comment]
@Usaga 

for which game does it fail? i can't reproduce it ... works on linux / BA.

**Comment by Usaga** [comment]
It works on all BA's after clearing springlobby's cache...

**Comment by Usaga** [comment]
I meant if failes on all BA games...

**Comment by Usaga** [comment]
This change in LSL coused this issue: https://github.com/springlobby/lsl/commit/7d95d2fc4d03bd4dfb7428c8668836392def1e79#diff-aa450d6eb17e66c5f3b42641c96ce51f
