### ISSUE TITLE
springlobby crashed after new user registration

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#637]
crash info: http://pastebin.com/m9Z69hCM

--------------
SpringLobby 0.243-137-g0e31613 (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
	WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /usr/lib64/libunitsync.so
Current spring executable: /usr/bin/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
/home/revenant/springlobby/src/springlobby

**Comment by jamerlan** [comment]
also crash on server stop:
http://pastebin.com/Z6i68cR0

**Comment by Usaga** [comment]
And again Fedora has introduced some unique bugs((

**Comment by abma** [comment]
it looks more like fixes/changes in GlobalEventManager introduced the crash. the assert i added is currently failing.

**Comment by abma** [comment]
hmm, looks like connect / disconnect logic fails in some cases.

couldn't reproduce it reliable, but it seems to crash, when login fails and then a user is registered.
