### ISSUE TITLE
TrueSkill rank is not rounded correctly

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#640]
Seems the method of rounding is incorrect / not same way between different interface.
I think that from 17 to 17,99 => DISPLAY 17

For instance my poor rank actually is 17,93.
So, values are different :
On SpringFILES or !sb in private = 17,93 (Privacy OFF, however, if ON I think it will be surely displayed 18)
http://img4.hostingpics.net/pics/288996screenshot9.png

On ADVPlayerLIST rank = 18
http://img4.hostingpics.net/pics/390388ADVPlayerLIST.jpg

On SpringLOBBY rank = 17.
http://img4.hostingpics.net/pics/609542screenshot11.png

What about displaying :
17 from 17,00 to 17,49 and 18 from 17,50 to 17,99 ?

**Comment by abma** [comment]
now its rounded correctly, before values where just truncated...  showing exact values makes no sense imo

**Comment by FabriceFABS** [comment]
Agreed, thx for fix.
