### ISSUE TITLE
New replay format (sdfZ) does not supported by Lobby

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#641]
Spring 101 introduced new zipped SDFZ format for replays. It is unsupported by SL currentlry.

**Comment by Usaga** [comment]
I tried to do it by myself, but wxZipInputStream class could not handle sdfz file, complaining it is invalid zip file (probably some new algorythms was used to create it?). So, at this point, I could not do it)

**Comment by abma** [comment]
afaik zip != gzip

**Comment by abma** [comment]
maybe see https://github.com/spring/spring/blob/develop/rts/System/FileSystem/Archives/PoolArchive.cpp#L56 for an example

**Comment by abma** [comment]
with the most recent changes i get these compile warnings:

src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::avail_in’ [-Wmissing-field-initializers]
     z_stream strm = {0};
                       ^
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::total_in’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::next_out’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::avail_out’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::total_out’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::msg’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::state’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::zalloc’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::zfree’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::opaque’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::data_type’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::adler’ [-Wmissing-field-initializers]
src/replaylist.cpp:182:23: warning: missing initializer for member ‘z_stream_s::reserved’ [-Wmissing-field-initializers]

**Comment by abma** [comment]
and address sanitizer complains about operator new[] vs delete mismatch:

==8574==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x62a000048200
    0 0x7f1059418a0a in operator delete(void*) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99a0a)
    1 0x7f537d in std::default_delete<unsigned char>::operator()(unsigned char*) const /usr/include/c++/5/bits/unique_ptr.h:76
    2 0x7f4be9 in std::unique_ptr<unsigned char, std::default_delete<unsigned char> >::~unique_ptr() (/mnt/tmp/home/dev/SpringLobby/src/springlobby+0x7f4be9)
    3 0x7f2d6a in ReplayList::getUnzippedData(unsigned char*, unsigned long, wxInputStream&) const src/replaylist.cpp:184
    4 0x7f1dc1 in ReplayList::GetReplayInfos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, StoredGame&) const src/replaylist.cpp:150
    5 0x7dc478 in IPlaybackList::LoadPlaybacks(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) src/iplaybacklist.cpp:27
    6 0x7f0038 in PlaybackLoader::PlaybackLoaderThread::Entry() src/playbackthread.cpp:65
    7 0x7f1057223351 in wxThread::CallEntry() (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x1b4351)
    8 0x7f105722a752  (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x1bb752)
    9 0x7f10588d6669 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7669)
    10 0x7f10556de01c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10701c)

0x62a000048200 is located 0 bytes inside of 20480-byte region [0x62a000048200,0x62a00004d200)
allocated by thread T5 here:
    0 0x7f1059418592 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    1 0x7f2bbb in ReplayList::getUnzippedData(unsigned char*, unsigned long, wxInputStream&) const src/replaylist.cpp:185
    2 0x7f1dc1 in ReplayList::GetReplayInfos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, StoredGame&) const src/replaylist.cpp:150
    3 0x7dc478 in IPlaybackList::LoadPlaybacks(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) src/iplaybacklist.cpp:27
    4 0x7f0038 in PlaybackLoader::PlaybackLoaderThread::Entry() src/playbackthread.cpp:65
    5 0x7f1057223351 in wxThread::CallEntry() (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x1b4351)

Thread T5 created by T0 here:
    0 0x7f10593b5213 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36213)
    1 0x7f10572271b7  (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x1b81b7)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch ??:0 operator delete(void*)
==8574==HINT: if you don't care about these warnings you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==8574==ABORTING

**Comment by Usaga** [comment]
Wow... I will fix it. Thanks for pointing to this.

**Comment by Usaga** [comment]
Must be fixed now.

**Comment by abma** [comment]
works for me, thanks!
