### ISSUE TITLE
strange message window

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#642]
I removed all engines then I was trying to join a battle with dev version of engine
lobby: 0.243-179-g20b6268
![wtf](https://cloud.githubusercontent.com/assets/216801/13598669/288315d8-e530-11e5-8b99-21b2e4ca094d.png)

**Comment by Usaga** [comment]
Thanks for feedback!

**Comment by jamerlan** [comment]
Fixed! thanks!
