### ISSUE TITLE
engine downloading bug

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#643]
https://youtu.be/HsWU6CEtsJ0

1) Delete all engines (easy to reproduce this way)
2) Restart springlobby
3) Open springlobby -> all maps and games are "unknown" too
4) Click on any battle

5) springlobby is trying to download engine, game (bug!, I have this game) and map (bug!, I have this map)

6) engine is downloaded but change is not applyed! (bug: maps and games are still unknown)
But! if you open Edit->Preferences then select engine and press "Apply" -> then springlobby will see maps and games https://youtu.be/HsWU6CEtsJ0?t=2m25s

P.S. This bug present in current release version of the lobby too

---------------------------------------------
SpringLobby 0.243-180-g44f2fdf (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
	WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /home/revenant/.spring/engine/101.0.1-103-gf4376b1 develop/libunitsync.so
Current spring executable: /home/revenant/.spring/engine/101.0.1-103-gf4376b1 develop/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
/home/revenant/springlobby/src/springlobby

**Comment by abma** [comment]
(wrt rename: wrong issue, sorry)

automatic engine switch atm is basicly broken atm. you have to manually select the used engine version afaik (in settings or singleplayer tab i guess)

**Comment by jamerlan** [comment]
This is absolutely frustrating for users because now they have many engines -> needs to be fixed asap :-)

**Comment by abma** [comment]
thats the drawback of using the development version. sorry + thanks for your reports / help

**Comment by abma** [comment]
oops, search string atm is wrong:

GET /json.php?category=engine_linux64&torrent=true&springname=spring HTTP/1

version is missing :-|
