### ISSUE TITLE
Spring RTS 101.0 with SL under Linux : Bad start positions display

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#646]
Bad start positions are displayed under Linux , with those conditions :
- Spring V101.0,
- Under Linux,
- Version : SpringLobby 0.243-198-g83ce5f7
Have a look to the pic, with it's BlockWarsFFA-V2.3.mapinfo generated today at 12:54.

<a href="http://www.hostingpics.net/viewer.php?id=254607SL01.png"><img src="http://img15.hostingpics.net/thumbs/mini_254607SL01.png" alt="Heberger image" /></a>
And BlockWarsFFA-V2.3.mapinfo >>>  http://paste.springfiles.com/view/115799e8

Edit : To reproduce, don't forget in order
- Quit SL,
- Remove/rename /home/user/.springlobby/springlobby.conf (this permits to remove all engines / conf already set),
- Remove /home/user/.springlobby/cache,
- Start SL and set the desired engine and do tests with maps.

.
.

May sure help, was about to publish a vid (now not needed anymore), I discovered those :
- Works ok Spring101.0 + Windows,
- Works ok Spring100.0 + Linux,
- Works ok Spring94.1 + Linux.

Thank you.

**Comment by abma** [comment]
can't reproduce with current development version. can you please retest?

**Comment by FabriceFABS** [comment]
Yeah nice, everythings rocks.
Thanks !
