### ISSUE TITLE
Duplicate lines of channels list

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#647]
With SpringLobby 0.243-198-g83ce5f7 under Linux, when I call Channel list in the menu :
<a href="http://www.hostingpics.net/viewer.php?id=689951SLMenu.png"><img src="http://img15.hostingpics.net/thumbs/mini_689951SLMenu.png" alt="Heberger image" /></a>
.
.
1st time, display is correct
<a href="http://www.hostingpics.net/viewer.php?id=7120241st.png"><img src="http://img15.hostingpics.net/thumbs/mini_7120241st.png" alt="Heberger image" /></a>

2nd time and + : Duplicate lines of channels.
<a href="http://www.hostingpics.net/viewer.php?id=3355072nd.png"><img src="http://img15.hostingpics.net/thumbs/mini_3355072nd.png" alt="Heberger image" /></a>
.
.
Thank you !

**Comment by Usaga** [comment]
Fixed for me. Test it, please.

**Comment by FabriceFABS** [comment]
I've check it and it's ok.
Thanks, you can close !
