### ISSUE TITLE
crash on closed battle

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#649]
Take a look at the logs: I did !restart
then lobby showed me "battle was closed" message 2 times
Then lobby crashed
0.243-201-g481ab3f

Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 SAIDBATTLE [teh]decay !restart
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 SAIDBATTLEEX BlackHoleHost7 * AutoHost restart scheduled (reason: requested by [teh]decay in battle lobby)
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 LEFT BlackHole BlackHoleHost7 Quit: AutoHost restarting
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 BATTLECLOSED 17265
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 REMOVEUSER BlackHoleHost7
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 ADDUSER BlackHoleHost7 RO 1799 909063
Warning  /home/revenant/springlobby/src/serverevents.cpp:134 logic error ( /home/revenant/springlobby/src/serverevents.cpp:134 ): New user from server, but already exists!
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 CLIENTSTATUS BlackHoleHost7 80
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 JOINED BlackHole BlackHoleHost7
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 BATTLEOPENED 17473 0 0 BlackHoleHost7 188.213.171.197 8457 128 0 0 1602584005 spring	101.0.1-139-ga146a0c develop	DeltaSiegeDry	The BlackHole Mods and Engine Testing	Balanced Annihilation test-5206
Message  /home/revenant/springlobby/src/tasserver.cpp:470 #25 UPDATEBATTLEINFO 17473 1 0 1602584005 DeltaSiegeDry
Message  /home/revenant/springlobby/src/tasserver.cpp:980 sent: #26 LEAVEBATTLE
Error    /home/revenant/springlobby/src/springlobbyapp.cpp:211 Fatal exception!
[1]    6013 abort (core dumped)  /home/revenant/springlobby/src/springlobby -cl -l9

**Comment by abma** [comment]
it looks like a failing assert in src/utils/globalevents.cpp:153

are you using a debug build?

**Comment by jamerlan** [comment]
I don't know it's debug or not :-)
https://youtu.be/DDgbTbBJVZ8
http://pastebin.com/H7Frga0y

**Comment by jamerlan** [comment]
maybe this can answer your question about the build: http://pastebin.com/BxgPaXh3

**Comment by abma** [comment]
in the build dir, just run:

grep CMAKE_BUILD_TYPE CMakeCache.txt

**Comment by jamerlan** [comment]
➜  springlobby git:(master) ✗ grep CMAKE_BUILD_TYPE CMakeCache.txt
CMAKE_BUILD_TYPE:STRING=Release
