### ISSUE TITLE
deleted engines aren't detected probably / removed from config / default engine isn't re/unset

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#650]
sometimes it not downloading the engine
https://youtu.be/04jArX3yleU

http://pastebin.com/tbbDbCvU

**Comment by abma** [comment]
Warning  /home/revenant/springlobby/src/log.cpp:165 Error: FIXME: Couldn't load the unitsync library '/home/revenant/.spring/engine/101.0/libunitsync.so': /home/revenant/.spring/engine/101.0/libunitsync.so: cannot open shared object file: No such file or directory

why this error message? same reason as in #651?

**Comment by jamerlan** [comment]
bug title is the answer: starting lobby without engines
I am starting lobby without engines - so that is the reason why file can not be opened

**Comment by abma** [comment]
springlobby doesn't manually add non-existing files, was the engine deleted but it was still present in config?

**Comment by jamerlan** [comment]
I removed all child directories of /home/revenant/.spring/engine
Springlobby should have a check for such situations :-)

**Comment by abma** [comment]
i agree, but this is minor imo

**Comment by abma** [comment]
please test, this should fix most of your issues
