### ISSUE TITLE
not downloading engine 101+

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#651]
lobby just downloaded 100 engine but it refuses to download 101+
https://youtu.be/KaqCoHFWOtw
http://pastebin.com/RhFSzMTW

**Comment by abma** [comment]
issue is hidden in log:

Warning  /home/revenant/springlobby/src/log.cpp:165 Error: FIXME: Couldn't load the unitsync library '/home/revenant/.spring/engine/101.0/libunitsync.so': /home/revenant/.spring/engine/101.0/libunitsync.so: cannot open shared object file: No such file or directory

why can't it be opened?

**Comment by jamerlan** [comment]
I had no engines before I started the lobby. Then lobby downloaded 100 engine.
I guess 101 cannot be opened - because it was not downloaded yet

**Comment by abma** [comment]
should be retested when #650 is fixed
