### ISSUE TITLE
not starting singleplayer

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#652]
https://youtu.be/J1Vf3oGk1vY
http://pastebin.com/2fXBRnh2

**Comment by abma** [comment]
this happens when you delete the default spring engine version...

**Comment by jamerlan** [comment]
? As you can see from the video I have this default spring.
Also I pressed "Ok" and "Apply" to make sure that engine was applied - still not working
And why it searching for 101 engine if "100" is selected in dropdown

**Comment by abma** [comment]
this should be retested when #650 is fixed

**Comment by abma** [comment]
can't reproduce -> seems fixed
