### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nixtux** [springlobby/springlobby#653]
SpringLobby 0.243-205-ge0ae12d

pastebin of stack trace http://pastebin.com/XxFtmTtu

not sure what i was doing when it crashed, if you need anything else please ask

**Comment by abma** [comment]
the more i think about it, the more i think this crash isn't fixed.

when fixing this, tasutils.* should be rewritten by not using any wx function

**Comment by abma** [comment]
partly done with https://github.com/springlobby/springlobby/commit/eed09eef23c17b7ac2843ddb51857a86c3bdb4cd

but this commit still needs some work / has bugs it seems

**Comment by abma** [comment]
seems to work for me. i hope/assume this bug is fixed as well as the most recent commits remove a lot of wx->std->wx->std string conversions
