### ISSUE TITLE
On Linux, weird & no save of SL Engine preference + BattleList filter

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#655]
Under Linux, with SL 0.243-215-gf83cb47,
When I go in Edit / Preferences and after in [Spring] tab for engine selection, let's say there's no engine registered yet.

I add a new engine by selecting **libunitsync.so** in the drawer **spring_101_minimal**....
This shows after a new entry on left nammed **101.0**, with everything correct regards it on right.

I press **ADD NEW** button, I add a new engine by selecting **libunitsync.so** in the drawer **spring_100_minimal**....
This shows after a new entry on left nammed **100.0**, with everything correct regards it on right.

After, I just show you what's next :
So, everythings is at this time, ok
<img src="http://img4.hostingpics.net/pics/289867SL1.png" />
//
//
But after, when I click back on 101.0 :
<img src="http://img4.hostingpics.net/pics/341562SL2.png" />
//
//
But when I want to remove it with the button where the mouse is...
<img src="http://img4.hostingpics.net/pics/930337SL3.png" />
//
//
**Everything disappear.**
<img src="http://img4.hostingpics.net/pics/475344SL4.png" />
//
//
When I can add, at least only 1 engine, it shows me in the battlelist that I got the maps & mods sync.
But **filter for only games I have** _sucks_ (now) and show a blank battlelist because it forces me to filter rank limit < 1.
<img src="http://img4.hostingpics.net/pics/727811SLBL.png" />
//
//
Changing it / applying new values for rank + Quit => Nothing change, Rank limit came back again.
**And now, I've just discovered that the Spring Engine preference is not saved anymore, blank list...**
<img src="http://img4.hostingpics.net/pics/475344SL4.png" />
//
//
A game could surely be played in single mode, also in networking mode too.

**But if you quit SL, you'll have to add again ONLY 1 engine, and your filter preferences will be set with rank limit < 1.**

**Comment by FabriceFABS** [comment]
Seems there is a bug +/- similar, not sure from _jamerlan_ 1 say ago.
I precise that if I set Engine V100, and I quit SL, when I re-open it, no engine saved.

**Comment by abma** [comment]
no, this bug was introduced by the "fix" of #650

**Comment by FabriceFABS** [comment]
For Engine list preference, it's OK !
However, BattleList filter still buggung.
