### ISSUE TITLE
unitsync boost::filesystem::detail::status error

### ISSUE THREAD

**Issue by eronoobos** [springlobby/springlobby#656]
In Arch linux i installed the springlobby package (2.43) with pacman, connected to the official server, said yes to downloading engine 100, let it download, connected to a game using engine 100, and said yes to downloading map and game. After the map finishes downloading, springlobby crashes without report. If i start springlobby after this, I get this stacktrace:

Call stack:
0x7f3cda8ffe80 
0x7f3cdbed263d boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)
0x7f3cca8deb5f 
0x7f3cca8c8ca9 
0x7f3cca8c8d65 
0x7f3cca8ca011 
0x7f3cca8e6237 
0x7f3cca949935 Init
0x87c126 LSL::UnitsyncLib::_Init()
0x87c378 LSL::UnitsyncLib::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0x856b6c LSL::Unitsync::LoadUnitSyncLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0x856c9b LSL::Unitsync::ReloadUnitSyncLib()
0x5b510f SpringLobbyApp::OnInit()
0x7f3cdc523202 wxEntry(int&, wchar_t**)
0x4d55d8 main
0x7f3cda56e710 __libc_start_main
0x52b969 _start

Deleting ~/.spring fixes the error, which returns after repeating the download process. If I delete everything in ~/.spring except the engine, the error on launching springlobby remains.

**Comment by abma** [comment]
thats very likely the same issue as reported here: https://springrts.com/phpbb/viewtopic.php?f=64&t=34511

to workaround the crash: delete all self-compiled / system installed spring / unitsync and use only the downloaded spring executable.

**Comment by abma** [comment]
no feedback -> closing
