### ISSUE TITLE
Linux : Battleroom filter > Forced to RankLimit & Players nb

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#657]
_(On Linux)_
I want a filter with «Only maps I have».
This works ok and is stored.

but

On each launch, SL add extra 2 restrictive filter :
Rank Limit = 1, and Player = 0

<img src="http://img15.hostingpics.net/pics/77288354BF.jpg">

So I change it with the set of RankLimit + Player = All.
This works, for now.

But on next SL launch, the filter is not saved and it's again the same filterlist setting above applied.

**Comment by Usaga** [comment]
Thanks for your feedback!

**Comment by Usaga** [comment]
Fixed
