### ISSUE TITLE
Windows + FR > Battle FilterList : Value «Tous» / «All» not centered.

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#658]
All is in the title...
<img src="http://img15.hostingpics.net/pics/682748Centre.png">

**Comment by Usaga** [comment]
What is "FR"?

**Comment by FabriceFABS** [comment]
French sorry as you see 'Tous" word that means "All".
Didn't tried with ENG version.

**Comment by Usaga** [comment]
Test it, please if it fixed under Linux too...

**Comment by FabriceFABS** [comment]
Well, sorry I can't test it (compile it exatly) under Windows.
And under Linux, after recompilation, this changed nothing (no bug before, no bug after :) ).

**Comment by Usaga** [comment]
Compilation under Linux was broken so you should not be able to compile it :D . I fixed it and checked under Kubuntu and it seems it works.

**Comment by Usaga** [comment]
Should be fixed now

**Comment by FabriceFABS** [comment]
Hehe :-) agreed that it was not updated during my tests.
I got now gb8c783a and it changed now, the list is not the same like others !
You killed the nice list button :D

<img src="http://img11.hostingpics.net/pics/500359SLAll.png">

**Comment by Usaga** [comment]
Reworked control for better looking
