### ISSUE TITLE
Linux : Prefs / Groups > Doesn't work

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#659]
Under Linux for lastest SL, groups doesn't work.
.
.
<img src="http://img15.hostingpics.net/pics/923508SLG.png">
_**SpringLobby 0.243-222-g7bb2489**_
.
.
.
<img src="http://img15.hostingpics.net/pics/687754SLG0201.png">
**_SpringLobby 0.201_**

**Comment by Usaga** [comment]
This is not occurred under Windows - only Linux. Look like another surprise from wxWidgets...

**Comment by Usaga** [comment]
wxWidgets developers have disabled ability to set background colour of wxDataViewCtrl deliberately with no idea why they did this - https://groups.google.com/forum/#!topic/wx-users/8w8tqIybEiM.

So nothing could be done at this moment. My be some hack could be reached...
