### ISSUE TITLE
Linux : SinglePlayer map overview > Really too small on first start

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#660]
<img src="http://img15.hostingpics.net/pics/491735MapOverV.png">
.

Sorry, but I think you **should** see this video, this will maybe help you to resolve it...
https://youtu.be/dIBU7HpsxWo

**Comment by Usaga** [comment]
Problem in resize event that is not handled properly. I wokring on this for some time. As temprorary solution you can resize main window, so this will resize minimap...

**Comment by FabriceFABS** [comment]
Ok_ That's what I've done in the video in fact.

**Comment by FabriceFABS** [comment]
Resolved also with #669 
Thx !
