### ISSUE TITLE
Linux : BattleRoom > Sort order not saved

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#661]
Sort order is not saved on quit.

Video made : https://youtu.be/Zu-f4xNkPqs
(I precise that under **Windows, this issue NOT occurs**)

**Comment by Usaga** [comment]
Yes, this is not occurred under windows, problem in Linux port of wxWidgets - it ignores settings of sort order. Do not know how to fix this at this moment...

**Comment by FabriceFABS** [comment]
May this help ?
In command line : 27x this following (on start only), no more errors :

> (springlobby:11910): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

**Comment by abma** [comment]
see #509, wxwidgets bug
