### ISSUE TITLE
Linux : Battlelist > Various esthetics issues on columns

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#663]
On [Battlelist] tab, some problems on columns :
<img src="http://img15.hostingpics.net/pics/989430SLBattleList.png">

[S] : Should be renamed to Status ? // Sizeable, minimal size is too much.

[C] : Should be renammed to Country ? // Sizeable, minimal size is too much.

[Description] ,[Map] ,[Game], [Host], [Engine] : Ok

[Spectators], [Players], [Max], [Running] : Sizeables, minimal size is too much.

**Comment by FabriceFABS** [comment]
Extra-search

<img src="http://img15.hostingpics.net/pics/429441SLSTATUS.png">
On double-click on the right of the [Status] collumn, seems that the best fit size is wrong.
As you may know, it's not open_game.png <img src="http://img15.hostingpics.net/pics/806648opengame.png"> or others status icons because they are sized 16x16.

**Comment by specing** [comment]
My $0.03:

-  I don't think column names are even required for Status and C. It is quite obvious what they are. 
- max column width should be set to max graphic width (in current ratio with height)
- I think "Max", "Host" and "Engine" should be thrown out and shown at the bottom when clicked
- password icon is waaaaaay too small

**Comment by abma** [comment]
fixed via https://github.com/springlobby/springlobby/pull/847 or
https://github.com/springlobby/springlobby/pull/875
