### ISSUE TITLE
Linux : Accented letters impossible to write

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#665]
SpringLobby 0.243-222-g7bb2489 (and older versions [[but NOT 0.201 => OK]] )

Impossible to write accented letters like : « » € é è ç à œ Œ ÉÈ Ç À............etc
Each try of such an unique letter don't write it, but returns 4x the following in the console :
`** (springlobby:17707): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input`

I've just discover that a copy-paste, for instance from here « » € é è ç à œ Œ ÉÈ Ç À
To SL text input, works (Paste + enter) => Displayed correctly.

**Comment by Usaga** [comment]
You need to delete po/.gmo + /usr/local/share/locale//LC_MESSAGES/springlobby.mo and regenerate them.

**Comment by FabriceFABS** [comment]
I don't fully understand...
I got no file in /usr/local/share/locale...

You mean I have to remove *.gmo and regenerate ?
How could I proceed for regenerate ?
Thx

**Comment by Usaga** [comment]
In SL source code directory find and remove .gmo files and then rebuild SL (this will rebuild locales too)

**Comment by abma** [comment]
rm po/*.gmo

**Comment by FabriceFABS** [comment]
rm po/*.gmo  >>> :D :-) :P
BTW, I prefer using this : rm -v po/*.gmo

What do you call «regenerate» >>> Recompile (make, cmake, etc) ?
Seems it doesn't worked in that way, did I do something wrong ?

**Comment by abma** [comment]
> rm po/.gmo
> rm -v po/.gmo

thats wrong, the wildcard is missing

**Comment by FabriceFABS** [comment]
Yes exact, just the fault here, I used wildcards in procedure.
But sorry, seems not fix it.
Here what I did :

```
rm -rvf /home/fab/springlobby
git clone --recursive git://github.com/springlobby/springlobby.git
cd ~/springlobby
cmake -j 11 .
make -j 11
rm -v po/*.gmo
make DESTDIR=/home/fab/Applications/Jeux/SpringRTS/SpringLobby -j 9 install
```
Thank you

**Comment by abma** [comment]
sorry, can't reproduce this issue. are you sure its not a bug in wxwidgets / wrong input configuration?

did you delete the install dir?

rm -rvf /home/fab/springlobby
make DESTDIR=/home/fab/Applications/Jeux/SpringRTS/SpringLobby -j 9 install

these dirs don't match, it should be
rm -rvf /home/fab/Applications/Jeux/SpringRTS/SpringLobby

**Comment by FabriceFABS** [comment]
Well, what is sure that SL 0.201 don't have this issue... Maybe WxW again ??? :-(
OK, thanks.
Here my script that doesn't change anything, sorry :
```
#!/bin/bash

rm -rvf /home/fab/springlobby /home/fab/Applications/Jeux/SpringRTS/SpringLobby && git clone --recursive git://github.com/springlobby/springlobby.git && cd ~/springlobby && cmake -j 11 . && make -j 11 && rm -v po/*.gmo && make DESTDIR=/home/fab/Applications/Jeux/SpringRTS/SpringLobby -j 11 install
```
Yell on me if I'm wrong...

After this on command line, 1st run :
27x ```(springlobby:24587): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed```
And each time such a character «é» for instance typed :
4x ```** (springlobby:24587): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input```

**Comment by abma** [comment]
in the script the path is still wrong...

**Comment by FabriceFABS** [comment]
`rm -rvf /home/fab/springlobby /home/fab/Applications/Jeux/SpringRTS/SpringLobby`
shows remove source & dest dir...
This is not that you want ?

**Comment by abma** [comment]
whats the output of springlobby -cl -l5 when you start springlobby? maybe you have selected an invalid locale / the locale can't be loaded...

is your input system configured probably?

the error message"Error converting text from IM to UTF-8" let me think your input system isn't configured correctly.

**Comment by FabriceFABS** [comment]
(Follow the sentense `Message  /home/fab/springlobby/src/tasserver.cpp:480 #14 SAID newbies [ACE]FabriceFABS CARE Gonna try to type accented letter` )
 
`/home/fab/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby -cl -l5`
returns > http://paste.springfiles.com/view/112ca403

--------------
_Interesting to checkout the following_
`/home/fabrice/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby -cl -l5 > ~/Bureau/LogSL`
returns (strange cause of 2 different outputs and redirection don't catch all...) :

**I. Console returns**
27x ```(springlobby:24587): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed```

And each time such a character «é» for instance typed :
4x ```** (springlobby:24587): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input```
No other messages.

**II. LogFile** : http://paste.springfiles.com/view/eabd42a3

**Comment by abma** [comment]
for the reference: #639

is ibus used / correctly conficured on your system?

**Comment by abma** [comment]
i.e. run ibus-setup

**Comment by FabriceFABS** [comment]
Well, I don't use ibus... 
Ibus is required for complex lang like Chinese and others... (documentation)
I installed it, and tried, nothing netter.
.
I remind you that with SL 0.201 I got no problem with that....

**Comment by abma** [comment]
can you please test if this works for you:

right click in the edit box -> input methods -> Select None

what was/is currently selected?

**Comment by abma** [comment]
you can also try to start springlobby this way:
GTK_IM_MODULE=scim src/springlobby -cl

i faced into the same issue with xfce.

**Comment by abma** [comment]
whats the output of echo $GTK_IM_MODULE ?

for me its "xim" which seems invalid. see ~/.xinputrc and im-config maybe.

**Comment by FabriceFABS** [comment]
(As usual) With Linux Mint 17.3 64bits MATE Ed. :
1. 
right click in the edit box -> input methods -> Select "None"
Previously on System (X Input Method), I selected None => **WORKS OK !!!**

2.
GTK_IM_MODULE=scim src/springlobby -cl
WORKS OK !!!, and input methods is on System (X Input Method) on start.

3. 
echo $GTK_IM_MODULE returns **xim** too
I didn't find ~/.xinputrc and im-config maybe.

**Comment by abma** [comment]
seems to be a bug in linux mint, idk what / how to fix with springlobby, sorry. at least a workarround seems to exist.
