### ISSUE TITLE
Linux : SinglePlayer option > Text overwritten with BAR game

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#669]
With BAR5302 game, text option is overwritten, and «vertical lift» is not available.
<img src="http://img11.hostingpics.net/pics/152875SL34.png">
<img src="http://img11.hostingpics.net/pics/358269SL44.png">
..
..
..
But with BA3.35, it rocks.
<img src="http://img11.hostingpics.net/pics/270667SL14.png">
<img src="http://img11.hostingpics.net/pics/323353SL24.png">
..
..
I've discover just now that the solution you gave me @Usaga on #660 solved this issue, but this should be done each time on first SpringLobby launch, and first singleplayer game.

**Comment by Usaga** [comment]
This should be fixed by now like #660. Test it please.

**Comment by FabriceFABS** [comment]
Yes, this is perfect (also #660)
Thx !
