### ISSUE TITLE
Linux : Enabling scrolling list with mouse rolling

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#670]
Some areas in SL can be scrollable by mouse roll button, and some others can't.

Here are the area we can't mouse-roll lists :
[Unit Restrictions] in BattleRoom and SinglePlayer,
Nicknames in [Chat],
Games & nicknames in the windows's game selected (bottom-right) in [BattleList],
[Replays],
[Channel List],
[Downloads] << To be checked.

**I've discover that in fact, it doesn't want to mouse-roll in the window, but ONLY when mouse is placed on the "lift" of the window'list.**
Have a look : You cannot scroll in the red-X zone, but on the rounded-window lift it works.
<img src="http://img11.hostingpics.net/pics/919331SLRoll.png">

**Comment by abma** [comment]
scrolling does work for me. which wxwidgets version are you using?

see help->system info

**Comment by abma** [comment]
then it is fedora specific / not fixable imo

**Comment by Usaga** [comment]
Yes, there were some other bugs that we fixed with workarounds. Do not know how to "fix" this)

**Comment by abma** [comment]
pray that its fixed in fedora 23 / 24 :p

basicly i guess its (again) an issue in wxwidgets in a combination with gtk

**Comment by FabriceFABS** [comment]
> then it is fedora specific / not fixable imo

No, I'm under Linux Mint 17.3 Rosa 64 bits.

Maybe my initial message is not complete, but some zones actually works, some others don't.
I've listed above the ones that don't work with mouse roll in the area list but roll only on the "lift" : BTW; what's the goal to use wheel on the lift instead of the left mouse button if you are forced to do so ?
The few zones list that works normally are :
- Any chat window,
- ... Didn't find any other actually.

Regards to WxWidgets I don't know witch package version I use I should return to you, here are some installed :
- wx-common : 3.0.0-2
- wx2.8-headers : 2.8.12.1
- wx3.0-headers : 3.0.0-2

**Comment by FabriceFABS** [comment]
I'm sure it is fixable, because as said above, some few areas works.
Plz try a fix on it, this, with the group colors / notifications, etc  doesn't working => Really annoying... :(

**Comment by abma** [comment]
3.0.0-2 very likely contains bugs. update to 3.0.2 at least if possible

**Comment by Usaga** [comment]
@FabriceFABS you didn't say anything about notifications not working...

**Comment by FabriceFABS** [comment]
Humm possible, I should check this out again to be sure.
Sorry, OFT : @abma >> Seems Springrts.com down... (Forum, Lobby... etc)

**Comment by abma** [comment]
i could swear i saw a bug report wrt wxwidgets 3.0, but can't find it. wrt springrts.com: can't do much atm, dansan has to reset it. looks like the vm is crashed (kernel panic, etc)

**Comment by FabriceFABS** [comment]
@Usaga >> Sorry, notifications are OK, it is colors only, already reported here #680
