### ISSUE TITLE
springlobby don't want to download dev engine

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#671]
http://pastebin.com/yU8HCVj6

video https://youtu.be/EzWzLBwtm9o

**Comment by Usaga** [comment]
Yep, annoying bug. If you remove all *.sz files in .spring/engines/ and restart SL it may (or may not) download engine properly..

**Comment by abma** [comment]
do the files exit at all?

i.e. search here: http://api.springfiles.com/ for specific the engine version + platform

**Comment by Usaga** [comment]
Yes, they does exist. I been able to download them after some iterations with removing of 7z files and SL restarting.

**Comment by abma** [comment]
sorry, i can't reproduce this, it works for me. joining BlackHoleHost7 made springlobby ask for downloading the engine and then it downloaded it and i was then able to join.

**Comment by abma** [comment]
for spring 101.0.1-179* it doesn't work as linux64 built isn't available:

http://api.springfiles.com/?springname=spring+101.0.1-179*&filename=&tag=&sdp=&category=engine_linux64

**Comment by jamerlan** [comment]
Currently downloading engines is still broken. But don't expect that I will report them.
1) I am kind of demotivated and lost hope in reporing/fixing these bugs
I know you are working hard to fix them. But also it looks like you are not motivated to fix them/test your work also (I have a strange feelings about that)
2) I am very busy these days in RL

**Comment by abma** [comment]
this info isn't useful, its just demotivating, too

what does "Currently downloading engines is still broken" mean: for me it works!

what are you doing? which battle are you joining, which exact engine version was tried to download?

**Comment by abma** [comment]
3) for me it looks like you have set weird config in springlobby.conf / created some symlinks / an develop version inside a dir where springlobby autodetects spring but something fails / did something wrong

**Comment by abma** [comment]
tried again, worked fine... -> fixed / can't reproduce
