### ISSUE TITLE
Linux / Windows : Channel list > Topic description shoun't be centered

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#673]
All is in title...
<img src="http://img15.hostingpics.net/pics/675274Screenshotat20160319084439.png">
<img src="http://img15.hostingpics.net/pics/800334Screenshotat20160319084510.png">

But under windows, this issue is less annoying...
<img src="http://img15.hostingpics.net/pics/122545Win.jpg">

**Comment by Usaga** [comment]
Fixed
