### ISSUE TITLE
Linux : Minimap generated are wrong (cache files seems ok)

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#674]
On SL 0.243-226-gbebe500
<img src="http://img15.hostingpics.net/pics/845387ScreenS.png">

Same result with cache deleted before SL launch.

**Comment by Usaga** [comment]
This happens under Windows too.

**Comment by abma** [comment]
can't reproduce, please try with current version

**Comment by Usaga** [comment]
Yes, now it works fine!

**Comment by FabriceFABS** [comment]
Yeah ok for me too, thx !
