### ISSUE TITLE
Feature request: Distinguish between Start and Rejoin

### ISSUE THREAD

**Issue by ashdnazg** [springlobby/springlobby#675]
When I join a game to spectate I somehow miss the fact it's not running yet and accidentally press start which either spams !start or causes a vote which really wasn't my intention.

Changing the text on the button or giving me some way to see I'm going to spam "!start" near the button will make me much less impolite.

Thanks!

**Comment by specing** [comment]
Fixed in ecdcd957f8db0b5437a3194125d1c561edaa6d1a with more coming soon.
