### ISSUE TITLE
src/channel.cpp:210:23: error: ‘ToLower’ is not a member of ‘LSL::Util’

### ISSUE THREAD

**Issue by bterwijn** [springlobby/springlobby#676]
In the head of master branch I get this error when compiling, function is not defined:

  src/channel.cpp:210:23: error: ‘ToLower’ is not a member of ‘LSL::Util’

Hope this can be fixed shortly.

Thanks for your efforts.
Bas Terwijn

**Comment by abma** [comment]
try:
git submodule sync
git submodule update

**Comment by bterwijn** [comment]
Thanks, that worked
