### ISSUE TITLE
User group color highlight does not work (anymore)

### ISSUE THREAD

**Issue by q-r-a-y** [springlobby/springlobby#680]
Small bug:
Example: choose highlight color for group "friends". In older versions (e.g. 0.225) these names were highlighted in the user list in chat windows and battles hosted by these users where highlighted in the battlelist. This does not work in e.g. 0.243 and current master.

Has been confirmed by friends who have the same issue. All using linux systems.

**Comment by abma** [comment]
see #659 (wxGTK bug)

**Comment by q-r-a-y** [comment]
Ah, that explains it. Didn't find that entry, when looking through the issue list. Sorry for double post.

**Comment by abma** [comment]
not sure if thats the correct one, but sounds reasonable:
http://trac.wxwidgets.org/ticket/17164

this should fix it:
http://trac.wxwidgets.org/changeset/76a75ddc6a0cf4bb5f78c25ea17ac02373ff362f/git-wxWidgets

so hopefully fixed with wxwidgets 3.0.3
