### ISSUE TITLE
missing game download button inside battle

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#681]
when joining a battle and game download is rejected, there is no easy way to start the download.

**Comment by specing** [comment]
Is it our fault that the download was rejected? Anyway this could be merged into rewrite of downloads:
queue these downloads as pending approval and flash the downloads tab yellow/orange.

Or even better, don't ask for download and only provide a right-click->join without downloading option on the battlelist. Good for experienced players (they can use the same menu to download should they so choose) and good for newbies (less obstacles in the form of Ask()).

**Comment by specing** [comment]
I don't think this issue is valid.

**Comment by abma** [comment]
with the new button which ask for download this shouldn't be an issue any more
