### ISSUE TITLE
CORE word : In ippercase

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#686]
Is it normal (in the sense that the name that wants it) that CORE word is in uppercase in the [battleroom] section (and elsewhere maybe) ?
<img src="http://img15.hostingpics.net/pics/928164CORE.png">

**Comment by abma** [comment]
no, and no clue where it comes from.

springlobby afaik should pick the info from sidedata:

http://imolarpg.dyndns.org/trac/balatest/browser/trunk/gamedata/sidedata.lua

**Comment by abma** [comment]
for me both sides are uppercase... can't reproduce. does it still happen when you delete the cache file?

look into:

Balanced Annihilation V9.35-*sides.json / delete them.

**Comment by FabriceFABS** [comment]
Thank you for information.
I've just discover that in BA 3.35 all is in uppercase, corresponding to the like file you gaved to me.

With your help, I've discovered that's a BAR related issue :
http://imolarpg.dyndns.org/trac/balatest/browser/branches/BAR/gamedata/sidedata.lua

Closing & reporting to BAR.
