### ISSUE TITLE
crash when switching to replays tab

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#688]
when switching to the replays tab, springlobby on wine crashes:

=>0 0x00da7efa in springlobby (+0x9a7efa) (0x0f67ea98)
  1 0x00da8992 in springlobby (+0x9a8991) (0x0f67eb18)
  2 0x00db4ceb in springlobby (+0x9b4cea) (0x0f67ebb8)
  3 0x010407df _ZN8wxString6assignEPKcj+0x62(sz="d¡4", n=0x34a364) [include/wx-3.0/wx/string.h:2637] in springlobby (0x0f67ec38)
  4 0x01041222 _ZN8wxStringC1ERKSs+0x85(str=0xf67ee70) [include/wx-3.0/wx/string.h:1328] in springlobby (0x0f67eca8)
  5 0x005b6b13 _ZNK17PlaybackDataModel8GetValueER9wxVariantRK14wxDataViewItemj+0x310(variant=0xf67ef10, item=0xf67f080, col=0) [src/gui/playback/playbackdatamodel.cpp:53] in springlobby (0x0f67eeb8)
  6 0x008e7c5e in springlobby (+0x4e7c5d) (0x0f67ef58)
  7 0x009037c0 in springlobby (+0x5037bf) (0x0f67f188)

possible related to #678

**Comment by abma** [comment]
note: happens on wine/win32 only it seems

**Comment by abma** [comment]
weird, can't reproduce on a real windows

**Comment by Usaga** [comment]
This is really weird bug. According to this stacktrace some replay have had "date_string"  containing "di4" and overall string length of 0x34a364. Do not know how this could be possible.

**Comment by abma** [comment]
some invalid string conversion / mem corruption? imo very likely related to #678

**Comment by Usaga** [comment]
Could not reproduce..

**Comment by abma** [comment]
can't reproduce, too. not sure if it was fixed or just some side-effect of #678
