### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by nixtux** [springlobby/springlobby#689]
Crash happens when you install a new engine and try and join a battle running a different engine

https://gist.github.com/55a6bdd7380664304fa57c6f450ab438

you can work around it by doing edit>prefences>select engine the battle you want to join is running

**Comment by abma** [comment]
please update to latest version.

also to be sure: please run "git submodule update"

the line src/lsl/src/lslunitsync/unitsync.cpp:1145 doesn't exist.

also the call of GetMapOptionsPath() is at line 1100:
https://github.com/springlobby/lsl/blob/master/src/lslunitsync/unitsync.cpp#L1100

**Comment by nixtux** [comment]
thanks fixed by updated and rebuilt to latest git -- 0.243-275-g61071f4
