### ISSUE TITLE
release

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#691]
what needs to be tested?

~~1 changelog~~
2 install to system without config / content files
2.1 register new user
~~2.2 join autohost~~
~~2.3 host battle~~
~~2.4 relay host~~
~~3 self update~~

@Usaga 

did i miss sth. important? no release blocker bug is currently known

**Comment by Usaga** [comment]
Most relevant feature for me is stuff downloading - and it seems working fine now. #687 is not annoying bug, it might be fixed later.

Players will do the testing and tell us what we had missed.

**Comment by jamerlan** [comment]
I suggest to add: 
remove all engines, restart lobby - make sure it will download default spring engine
try to download "unknown"(dev) version of engine

currently when I start lobby - it asks to download "100" engine but douing nothing when I click "yes"
when I manually installed latest "dev" version - it was not listed in preferences (it was empty). When I added manually - no factions in battleroom were displayed. Restart not helped to display factions. I was trying a6b233efc926a8e307b94d600ad52844dba16447 lobby.
Will not provide additional details. Feel free to delete this comment as offtopic. I just wanted to say: downloading is still broken :-D

**Comment by abma** [comment]
>  remove all engines, restart lobby - make sure it will download default spring engine

thats 2.

**Comment by Usaga** [comment]
@jamerlan, I found stupid typo that caused SL to failed download engine at start. It should be fixed by now.

**Comment by abma** [comment]
imo #687 should be fixed before release (will try to do so soon)

**Comment by abma** [comment]
selfupdater seems to work (again)

**Comment by abma** [comment]
released 0.244

**Comment by Usaga** [comment]
yey)
