### ISSUE TITLE
Battleroom : Player color button > Always black

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#692]
SpringLobby 0.243-298-g7150f66
Any action this button stays black.
<img src="http://img15.hostingpics.net/pics/180624Screenshotat20160404203342.jpg">

**Comment by Usaga** [comment]
Color sets properly after rejoin. Related to #687.

**Comment by FabriceFABS** [comment]
No, I'm not sure this is related to this.
>> Reporting another bug actually, maybe related on it...

**Comment by FabriceFABS** [comment]
You are true Usaga, sorry, I confirm it.

**Comment by Usaga** [comment]
This should be fixed.

**Comment by FabriceFABS** [comment]
It is, I confirm :)
