### ISSUE TITLE
reflective water settings

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#694]
Spring settings have some water options... 
Is this change reflected? 
- rename the 'ReflectiveWater' config-key to 'Water' (to match the command)

Is springsettings a part of springlobby?

**Comment by abma** [comment]
yes, but basicly its unmaintained

**Comment by abma** [comment]
IMHO springsettings should be shrinked to most basic settings like screen resolution / vsync. the other stuff can be set ingame.
