### ISSUE TITLE
unit restrictions not working in singleplayer mode

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#695]
list is empty

https://github.com/springlobby/springlobby/commit/1fc00f768ccc760f504140a1b398a8e5422a16bd ?

**Comment by abma** [comment]
hmm, seems to happen only for some files: i guess the games are broken?!

**Comment by FabriceFABS** [comment]
I've discovered by hazard yesterday this bug (With BA 9.33 & Online mode with presets that disable units ([ACE]Pirine).

For SinglePLAYER mode, here it the summary :
- BA-CD 3.17 -> OK,
- BAR 5569 -> OK,
- BA 9.19 -> OK,
- BA 9.33 -> OK,
- BA 9.35, 9.36 -> NO DISPLAY,
- CT Test-1835 -> OK,
- ImperialWintrer b63 -> OK,
- Kernel Panic 4.6 -> OK,
- TA V2.38.9 -> OK,
- TA V2.39.2 ... V2.39.7 -> NOT DISPLAY,
- 0K V1.6.6.2 -> NOT OK
- 0K V1.4.6.9 -> OK.

This should be be re-opened ?
What is strange that when playing online mode, it does NOT work with BA 9.33 (that works SinglePLAYER see above...).
