### ISSUE TITLE
edit -> spring settings is always grayed out

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#696]
...

**Comment by FabriceFABS** [comment]
FYI maybe you already know it, NOT under linux, neither on 0.244.

**Comment by abma** [comment]
for me it happens under linux

**Comment by jamerlan** [comment]
I was on linux, spring settings was grayed out (disabled)

**Comment by abma** [comment]
workarround: tools -> reload maps/games

**Comment by FabriceFABS** [comment]
Ahaha I confirm it in Linux too... :) => I did before a reload maps/games surely that's why I didn't see it grayed. Upgrading SL now.
