### ISSUE TITLE
vote panel didn't appear

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#697]
[23:12:56] * [ACE]Perge * [RuR]Dixon called a vote for command "set map AltairHeckCrossing-V1.2" [!vote y, !vote n, !vote b]
[23:12:56] * [ACE]Perge * User(s) allowed to vote: Yarra,cghislai,[ACE]FabriceFABS,[CF]ManDude

**Comment by abma** [comment]
(i spectated / wasn't affected)

**Comment by abma** [comment]
-> does it basicly work in at least one case?

**Comment by jamerlan** [comment]
+1, I had it too. People were voting for DSD, I was a "player" but no voting buttons..

**Comment by FabriceFABS** [comment]
I had it too on 0.244.
Seems this bug has been fixed right now on SpringLobby 0.244-4-gd4d1d9d.
To be closed ?

**Comment by abma** [comment]
no, as nothing was changed related to this bug

**Comment by FabriceFABS** [comment]
So... I see vote panel back on SpringLobby 0.244-4-gd4d1d9d also on windows, after SpringLobby update execution.

**Comment by abma** [comment]
@FabriceFABS 
which autohost?

**Comment by FabriceFABS** [comment]
I tried this on [ACE]Metalic during other bug reports, but I'm surely think that it doesn't matter.

**Comment by FabriceFABS** [comment]
I try to focus what makes buttons appears actually.
<img ="http://img15.hostingpics.net/pics/369072VirtualBoxWindowsXP11042016143408.png">

**Comment by FabriceFABS** [comment]
OK Found it.

<img src="http://img15.hostingpics.net/pics/652462341.png">
Buttons vote appears **1 time** only and during the next calling vote of the game you joined.
- Every vote for anything after this one -that displayed button- won't display vote buttons anymore,
- If you quit + rejoin same autohost => No more button display.

<img src="http://img15.hostingpics.net/pics/316420722.png">
However, if you go on anyelse autohost, same that above (works 1 time).
If you go back to an autohost that don't display votes anymore, still no button display.

As I'm not allowed to rename titles, you can maybe change it on something like :
«**Users see vote buttons only on the first next calling vote after they join the autohost**» or something like that.
