### ISSUE TITLE
SpringSettings : UI & Render tabs > Bad gfx sentenses display

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#699]
Seems some sentences are badly displayed Linux / Windows on 2 firsts tabs only :
Sentences are wrong pos on Linux version.
Sentences dropped on Windows version.

INFO : Full screen window under linux doesn't change anything.

**1. UI Options**
<img src="http://img15.hostingpics.net/pics/87237638UI.png">
<img src="http://img15.hostingpics.net/pics/592709UIWin.png">

**2. Render quality / Video mode**
<img src="http://img15.hostingpics.net/pics/240877SLRender.png">
<img src="http://img15.hostingpics.net/pics/156954SLRenderWin.png">

Others tabs SpringSettings tabs are OK_

**Comment by abma** [comment]
springsettings is unmaintained... (->feature)

**Comment by abma** [comment]
see #877
