### ISSUE TITLE
SpringSettings : Quit without saving dialog & actions

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#700]
When I want to quit Settings and I choose [cancel] button, I should have the possibility to go back on it.
The window settings disappear :

**1. Under Linux, before the small confirmation window (yes / no / cancel)**
<img src="http://img15.hostingpics.net/pics/812408SLSave.png">

**2. Under Windows, after the confirmation window**
<img src="http://img15.hostingpics.net/pics/501917SLSaveWin.png">

**Comment by abma** [comment]
see #877
