### ISSUE TITLE
System library of jsoncpp is not properly detected

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#705]
Hello,

I packaged 0.244 for Debian and I noticed that springlobby couldn't be compiled against the system library of jsoncpp despite the fact that I set the configure options: 

-DPRD_JSONCPP_INTERNAL=OFF 
-DLSL_JSONCPP_INTERNAL=OFF

To be more specific. There are two embedded code copies of jsoncpp in

src/downloader/lib/src/lib/jsoncpp
src/lsl/lib/jsoncpp

Apparently for the former one the detection works but not for the latter. Presumably because you didn't provide a FindJsoncpp.cmake file for this one? I added the following patch to work around this issue but I wonder if embedding two copies of jsoncpp could be avoided. If it can't be completely removed, at least one copy should be sufficient.

https://anonscm.debian.org/cgit/pkg-games/springlobby.git/tree/debian/patches/FindJsoncpp.patch

**Comment by abma** [comment]
the lsl doesn't require jsoncpp when compiling springlobby, this needs to be fixed. thanks for reporting!

**Comment by abma** [comment]
err, its needed... cache files use json. (doh!)

still needs fixing

**Comment by abma** [comment]
> if embedding two copies of jsoncpp could be avoided. If it can't be completely removed, at least one copy should be sufficient.

yes, it can be avoided: needs either prd + lsl submodule beeing merged or cross compile env needs some rework to install it there.

**Comment by abma** [comment]
added as todo: #709
