### ISSUE TITLE
mac os x compile errors

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#708]
I just noticed this message. Sorry if you know about this already (I have no idea)

https://springrts.com/phpbb/viewtopic.php?p=577020#p577020
-----------------------------------------

/Users/herecomethej/springlobby/src/lsl/src/lslunitsync/image.cpp:55:20: error: use of undeclared identifier 'fmemopen'; did you mean 'freopen'?
        std::FILE* file = fmemopen((void*)data, size, "rb");
                          ^~~~~~~~
                          freopen
/usr/include/stdio.h:248:7: note: 'freopen' declared here
FILE    *freopen(const char * __restrict, const char * __restrict,
         ^
/Users/herecomethej/springlobby/src/lsl/src/lslunitsync/image.cpp:55:29: error: cannot initialize a parameter of type 'const char *' with an rvalue of type 'void *'
        std::FILE* file = fmemopen((void*)data, size, "rb");
                                   ^~~~~~~~~~~
/usr/include/stdio.h:248:38: note: passing argument to parameter here
FILE    *freopen(const char * __restrict, const char * __restrict,
                                        ^
2 errors generated.

**Comment by abma** [comment]
should be fixed by https://github.com/springlobby/lsl/commit/0ecd69ee394c4b2679e6857432e64ded69e50fdf
