### ISSUE TITLE
Spring Lobby notifications without popup window

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#715]
Actually, I can't prove where it comes from, but I receive sometimes, randomly maybe ?...  the SpringLobby notify sound without the corresponding notification popup window.
I'm searching where it comes from.

**Comment by abma** [comment]
maybe ring?

**Comment by FabriceFABS** [comment]
No no, I really talk about the notification sound.
Out of topic a bit, but by this talking, I received one day a ring, without being in any game...
Just reporting because you know really better Spring/Lobby and by this you already focused me on my thinks regards to things I may ignore.

The sound is sometimes 1 time (like when someone leaves) or 2 times, like a promotion message, but without popup window.

2 things to consider :
- So... I don't know actually if this is a bug, or if someone is «playing» on me with SpringLobby protocol or so.
- In SL, I've disabled most of my group notifications and keep only 1 group with notifications.

Seems those calm down, but I should wait at least 1 week for period-test and if there are no more notifications sounds without popup-window, I will re-enable notifications back and I will see.

**Comment by abma** [comment]
check edit -> preferences -> chat -> highlighted words 

is ring checked?

**Comment by FabriceFABS** [comment]
Just the word to highlight  «« [ACE]FabriceFABS; »» and "Additionally play sound/flash titlebar" UNchecked from ever...

**Comment by specing** [comment]
I sometimes get ringed twice when closing SL. I also can't see any notification windows in general.

**Comment by abma** [comment]
please retest with springlobby 0.265: if it still fails, please reopen and with springlobby.log containing the problem.
