### ISSUE TITLE
SL hangs everytime spring exits

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#717]
Every time I start spring.exe from SL, and then exit spring.exe, it causes SL to hang for about 60 seconds.

It looks like SL is reloading all maps/games/etc everytime spring exits, which for me (large number of sdds) takes Spring about 60 seconds. Can reproduce in both singleplayer and battle tabs, both self hosted and autohosted.

**Comment by abma** [comment]
it should only search for replays when spring exits.

can you please test if this hang disappears when you rename the demos folder?

**Comment by silentwings** [comment]
Deleting my demos did the trick (I had 2207 of them, most only a few seconds long).

**Comment by abma** [comment]
hm, still reading the demos should be threaded and not block gui.

possible updating the interface takes needs this long, list controls still has some flaws :-|

**Comment by abma** [comment]
duplicate of #717
