### ISSUE TITLE
Clang compile error

### ISSUE THREAD

**Issue by JoshuaPettus** [springlobby/springlobby#718]
Unfortunately, the osx version of springlobby requires clang as the mac version of wxwidgets has some Objective-C. 
But when building springlobby with clang I get this:

/Users/herecomethej/springlobby/src/lsl/src/lslunitsync/image.cpp:55:20: error: use of undeclared identifier 'fmemopen'; did you mean 'freopen'?
        std::FILE* file = fmemopen((void*)data, size, "rb");
                          ^~~~~~~~
                          freopen
/usr/include/stdio.h:248:7: note: 'freopen' declared here
FILE    *freopen(const char * __restrict, const char * __restrict,
         ^
/Users/herecomethej/springlobby/src/lsl/src/lslunitsync/image.cpp:55:29: error: cannot initialize a parameter of type 'const char *' with an rvalue of type 'void *'
        std::FILE* file = fmemopen((void*)data, size, "rb");
                                   ^~~~~~~~~~~
/usr/include/stdio.h:248:38: note: passing argument to parameter here
FILE    *freopen(const char * __restrict, const char * __restrict,
                                        ^
2 errors generated.

(Sorry git hub kills the formating)

**Comment by abma** [comment]
oops, i forgot to update the submodule, should already compile when lsl is updated to latest version.

**Comment by abma** [comment]
oh, its up to date, sorry for the confusion. can you please try again with the latest version of springlobby?

latest version contains a custom fmemopen:
https://github.com/springlobby/lsl/blob/master/src/lslunitsync/image.cpp#L46

**Comment by JoshuaPettus** [comment]
That's right I forgot about the sub-modules! I feel like a moron. That worked just fine once I updated. I need to add this to a script. I keep forgetting every 6 months or so when i look at the project...

**Comment by abma** [comment]
no worries, glad to hear that it works / thanks for your help!
