### ISSUE TITLE
Springlobby downloaded same game and map multiple times, then crashed

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#725]
game 	Tech Annihilation v2.39.5
map	Techno Lands

I joined the room and didn't have game or map.

Springlobby auto-download started and they were downloaded twice each (according to the downloads tab), then lobby crashed

**Comment by springraaar** [comment]
unitsync.log

http://pastebin.com/8AgMZ6Xk

**Comment by abma** [comment]
it looks like SpringData is configured wrong:

Using configuration source: "C:\Users\Rui\Documents\My Games\Spring\springsettings.cfg"
Using additional configuration source: "C:\Users\Rui\Documents\Spring\springsettings.cfg"
Using read-write data directory: C:\Users\Rui\Documents\My Games\Spring\
Using read-only data directory: C:\Users\Rui\Documents\Spring\

please remove the config setting.

**Comment by abma** [comment]
side note: it doesn't crash for me when joining a autohost with engine 101.0...

**Comment by abma** [comment]
maybe the map is just broken? couldn't test with this map as no autohost uses it currently.

**Comment by springraaar** [comment]
there's only one springdata in my springesttings.cfg

SpringData = C:\Users\Rui\Documents\My Games\Spring

The glitch and crash only happened once though.

I removed the C:\Users\Rui\Documents\Spring directory (the settings file inside was empty)

**Comment by abma** [comment]
very likely related to #723
