### ISSUE TITLE
add pr-downloader logging to springlobby.log

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#731]
atm its not logged at all (just to console)

**Comment by specing** [comment]
There is a problem... It does work if I add extern functions to pr-downloader, but standalone pr-downloader does no longer compile. 

```
[ 98%] Linking CXX executable prd_test
../src/libDownloader.a(Logger.cpp.o): In function `L_LOG':
src/Logger.cpp:40: undefined reference to `prdlogerror(char const*, __va_list_tag*)'
src/Logger.cpp:52: undefined reference to `prdlogdebug(char const*, __va_list_tag*)'
src/Logger.cpp:46: undefined reference to `prdloginfo(char const*, __va_list_tag*)'
src/Logger.cpp:36: undefined reference to `prdlograw(char const*, __va_list_tag*)'
collect2: error: ld returned 1 exit status
```

I'm also open to suggestions on:
- whether to implement this via 4 functions as above, or a single one with priority
- whether to use va_list or (format, ...) like lsl
- how to make the above compile.

**Comment by specing** [comment]
This is done as of fde597e66f62c37f037fdfb54e7f73caaa9b50d1.
