### ISSUE TITLE
compilation issue on fedora 24

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#732]
I am noob in this area. I have an error. What should I do? Wait for fedora/nvidia guys to fix it?
==========================================================================
[ 97%] Building CXX object src/CMakeFiles/springlobby.dir/utils/curlhelper.cpp.o
[ 97%] Building CXX object src/CMakeFiles/springlobby.dir/utils/slconfig.cpp.o
/home/revenant/springlobby/src/utils/platform.cpp: In function ‘int RunProcess(const wxString&, const wxArrayString&, bool, bool)’:
/home/revenant/springlobby/src/utils/platform.cpp:165:77: warning: unused parameter ‘async’ [-Wunused-parameter]
 int RunProcess(const wxString& cmd, const wxArrayString& params, const bool async, const bool root)
                                                                             ^~~~~
/home/revenant/springlobby/src/utils/platform.cpp:165:95: warning: unused parameter ‘root’ [-Wunused-parameter]
 int RunProcess(const wxString& cmd, const wxArrayString& params, const bool async, const bool root)
                                                                                               ^~~~
[ 98%] Linking CXX executable springlobby
/usr/lib64/nvidia/libnvidia-glcore.so.367.27: undefined reference to `nv_vasprintf_alloc'
/usr/lib64/nvidia/libnvidia-glcore.so.367.27: undefined reference to `nv_vasprintf_vsnprintf'
/usr/lib64/nvidia/libnvidia-glcore.so.367.27: undefined reference to `nv_vasprintf_free'
collect2: error: ld returned 1 exit status
src/CMakeFiles/springlobby.dir/build.make:3768: recipe for target 'src/springlobby' failed
make[2]: *** [src/springlobby] Error 1
CMakeFiles/Makefile2:515: recipe for target 'src/CMakeFiles/springlobby.dir/all' failed
make[1]: *** [src/CMakeFiles/springlobby.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abma** [comment]
did you install binary nvidia drivers? imo it looks like the install broke it...

i.e.

https://devtalk.nvidia.com/default/topic/948906/undefined-references-to-nv_vasprintf_-symbols-in-libnvidia-glcore-so-367-27/
https://forums.gentoo.org/viewtopic-p-7933776.html?sid=fdf46261ea74f1f32209b393dabacee2

**Comment by jamerlan** [comment]
yep, I have binary nvidia drivers
Are opengl libs requred to build springlobby?

(feel free to close this ticket. looks like nvidia bug)

**Comment by abma** [comment]
with opengl libs it should compile fine...

**Comment by jamerlan** [comment]
I don't know who fixed issue.. you or fedora/nvidia guys. But now it works!! AWESOME!
