### ISSUE TITLE
Unit restrictions not working in OnlineMODE

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#733]
Spring 100 + BA 9.33

Unit restriction tab stays blank on both sides.
Applying a restrictive unit preset on [ACE]Pirine doesn't change this issue and still doesn't show anything more.
<img src="http://img11.hostingpics.net/pics/627796Screenshotat20160711014800.png">
<img src="http://img11.hostingpics.net/pics/773072Screenshotat20160711014811.png">

**Comment by abma** [comment]
i guess thats the reason:

Warning  src/log.cpp:195 Unitsync: Balanced Annihilation V9.35 ProcessUnits: luaParser.Execute() failed: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/moveDefs.lua, [string "gamedata/moveDefs.lua"]:317: attempt to call field 'GetModOptions' (a nil value)

springlobby tries to fetch all units without using a map which very likely causes this error. (just a guess atm)

**Comment by abma** [comment]
reported to BA, not sure who to blame:
http://imolarpg.dyndns.org/trac/balatest/ticket/1136

**Comment by abma** [comment]
i don't see this as springlobby bug. the error is from unitsync (=spring)
