### ISSUE TITLE
downloads etc. not working because of non-asscii chars in springlobby write dir

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#735]
Windows 10
1. download springlobby v0.249 portable,
2. launch lobby, it suggests download springrts 102,
3. after a few percents downloaded it fails.

**Comment by abma** [comment]
more details please: what does "it fails" mean. is there an error message? whats inside springlobby.log?

**Comment by spike-spb** [comment]
Yes, there is an error message: Failed to download selected item, see picture:

https://yadi.sk/i/ozSgjhRwtTmyv

Also, I can't find springlobby.log in **%APPDATA%\springlobby\springlobby.log**, don't know where it can be.

**Comment by abma** [comment]
does start->run "%APPDATA%\springlobby\springlobby.log" work on windows 10?

whats the output in springlobby of help->system info?

**Comment by spike-spb** [comment]
> does start->run "%APPDATA%\springlobby\springlobby.log" work on windows 10?
no, it doesn't. 

System info:
`SpringLobby 0.249 (win x32)
SpringLobby config file: C:\Users\Леонид\AppData\Roaming\springlobby\springlobby.conf ( writable)
LobbyWriteDir (C:\Users\Леонид\AppData\Roaming\springlobby\)
	WX: yes POSIX: no TRY: no
CachePath (C:\Users\Леонид\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: no TRY: no
ExecutableFolder (C:\Users\Леонид\Downloads\springlobby-0.249-win32\)
	WX: yes POSIX: no TRY: no
DownloadDir (C:\Users\Леонид\Documents\My Games\Spring\)
	WX: yes POSIX: no TRY: no
Current SpringData: (C:\Users\Леонид\Documents\My Games\Spring\engine\spring-100.0\)
	WX: yes POSIX: no TRY: no
Current unitsync: C:\Users\Леонид\Documents\My Games\Spring\engine\spring-100.0\unitsync.dll
Current spring executable: C:\Users\Леонид\Documents\My Games\Spring\engine\spring-100.0\spring.exe
Current uikeys.txt: C:\Users\Леонид\Documents\My Games\Spring\engine\spring-100.0\uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Users\Леонид\Downloads\springlobby-0.249-win32\springlobby.exe `

**Comment by abma** [comment]
LobbyWriteDir (C:\Users\Леонид\AppData\Roaming\springlobby\)
	WX: yes POSIX: no TRY: no

check the permissions in this directory! :-|

**Comment by spike-spb** [comment]
well, this is very difficult operation in windows for me :))) 
I've done else:

1. renamed **%appdata%/springlobby** to **%appdata%/springlobby-old**,
2. started springlobby again (there is new **%appdata%/springlobby** folder created), 
3. error didn't go.

**Comment by abma** [comment]
then its very likely an issue with the non-asscii chars in the path.

**Comment by abma** [comment]
any change with springlobby 0.253?

**Comment by spike-spb** [comment]
Many errors:
https://yadi.sk/i/-EGCaXDvtkQfE
https://yadi.sk/i/bFo8FCjttkQjJ
https://yadi.sk/i/h39a5KlTtkQkK
https://yadi.sk/i/d8nvoYtqtkQku
https://yadi.sk/i/UVJRX46ytkQmY

**Comment by Usaga** [comment]
@spike-spb please test if it is working for you. There have been some changes so it should work now.

**Comment by spike-spb** [comment]
It finally worked.

But there is something that should be posted here about that:
0. downloaddir set to **c:\games\springlobby-download** 
1. there was already installed non-portable version of springlobby;
2. also there was a portable version in **c:\games\springlobby-0.253-win32**;
3. I've tried **sl_master.zip** (**0.254-19-ge41dcf9**, unpacked in **c:\games\springlobby-0.253-win32**), but there were errors:
https://yadi.sk/i/jF59hk8qtrwzQ
https://yadi.sk/i/XdcR1l0ftrwzt

4. I've uninstalled springlobby from control panel, then downloaded latest portable **springlobby-0.254**, unpacked to **c:\games\springlobby** and patched with **sl_master.zip**,
5. its download dir is initially set to **c:\users\Леонид\.......**, and there was an error at first start:
https://yadi.sk/i/RNrUNyHNtrxHA
6. after setting download dir to **c:\games\springlobby-download** there were no more errors (+ no errors after restart)

But the error still exists in the non-portable version.

**Comment by abma** [comment]
in the development version this is very likely already fixed:

https://github.com/springlobby/springlobby/commit/e304365f00850210372df590f19bec78a2cf1e48

**Comment by abma** [comment]
should be fixed with 0.255
