### ISSUE TITLE
irc colors broken

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#737]
oops

[ACE] autohosts use them with !promote

**Comment by FabriceFABS** [comment]
FYI, this used to work in the past, I don't know how from how long it is broken.
IMO, I think it's recent.
This should be see like this :
<img src="http://img15.hostingpics.net/pics/71932669WL.png">

And you finally see :
<img src="http://img15.hostingpics.net/pics/691087SL251.png">

You can test it with !promote message, typed in any [ACE] host, and the result is in #main, #fr, #french, and #[ACE] lobby channels.

**Comment by FabriceFABS** [comment]
Hey !
Have a look @ this issue #724 : You can check the last SL version working with colors since it's broken with the date of this issue and/or maybe also on my pics in this report.

**Comment by abma** [comment]
724 is basicly unrelated to this issue...

**Comment by FabriceFABS** [comment]
I agree, I just wantes to let you know that pics of #724 shows SL colors working perfect with !promote message.
You could guess what's wrong between SL upgrades.
