### ISSUE TITLE
Failure to Compile for OSX clang .

### ISSUE THREAD

**Issue by JoshuaPettus** [springlobby/springlobby#739]
Hi when trying to compile I get this error in the CMakeError.log

error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'

When I tried to remove it, I got:

error: invalid argument '-std=c++11' not allowed with 'C/ObjC'

Anything we can do about this?

**Comment by abma** [comment]
does -std=c11 work?

**Comment by JoshuaPettus** [comment]
Hmm strange

error: invalid argument '-std=c11' not allowed with 'C++/ObjC++' 

I don't get it...

**Comment by abma** [comment]
please paste the full output, there is missing a lot of stuff / idk what you are doing.

**Comment by JoshuaPettus** [comment]
I see, well before I started playing with compat_flags.cmake  replacing the instance of -std=gnu++11 with -std=c11 or any other changes.

Here is the full CMakeError.log

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /Users/herecomethej/springlobby/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0a9bc/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_0a9bc.dir/build.make CMakeFiles/cmTC_0a9bc.dir/build
Building C object CMakeFiles/cmTC_0a9bc.dir/CheckIncludeFile.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -mtune=native  -Wextra -Wall -Wno-strict-aliasing  -std=gnu++11   -o CMakeFiles/cmTC_0a9bc.dir/CheckIncludeFile.c.o   -c /Users/herecomethej/springlobby/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'
make[1]: *** [CMakeFiles/cmTC_0a9bc.dir/CheckIncludeFile.c.o] Error 1
make: *** [cmTC_0a9bc/fast] Error 2
```
It was this fault that led to this in std error for the build script

CMake Error at /opt/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.6/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /opt/local/share/cmake-3.6/Modules/CMakeFindDependencyMacro.cmake:65 (find_package)
  /opt/local/share/cmake-3.6/Modules/FindBoost.cmake:1401 (find_dependency)
  src/CMakeLists.txt:34 (FIND_PACKAGE)

**Comment by abma** [comment]
what did you change? whats the output of git diff?

**Comment by JoshuaPettus** [comment]
All I did was try to fix the problem by editing compat_flags.cmake replacing the instance of -std=gnu++11 with -std=c11, or removing -std=gnu++11, -std=c++11 and -std=c++0x.  Nothing seems to work.

**Comment by abma** [comment]
-std=c++11 is for c++ / the c++ compiler and -std=c11 is for c code/c compiler!

you can't mix these flags. CMAKE_C_FLAGS basicly are unset when CMAKE_CXX_FLAGS are heavily modified by the cmake scripts.

i hope this info helps?!

**Comment by JoshuaPettus** [comment]
Why it does that and then attempts to use the wrong compiler is beyond me.  And why does it do this all of a sudden?

**Comment by abma** [comment]
maybe you've set CMAKE_C_COMPILER / CMAKE_CXX_COMPILER wrong?

very likely it does so because you told it to do so ;-)

**Comment by JoshuaPettus** [comment]
I didn't set them at all and was relying on the default settings.   I did try setting them, one thing I tried was install and older version of clang/llvm (in this case 3.4) on macports and try to use that instead.  Same result.

**Comment by abma** [comment]
from your log output:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -mtune=native  -Wextra -Wall -Wno-strict-aliasing  -std=gnu++11   -o CMakeFiles/cmTC_0a9bc.dir/CheckIncludeFile.c.o   -c /Users/herecomethej/springlobby/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c

"cc" is the c compiler and its used to compile a .c file. but there are c++ flags (-std=gnu++11) used, this is why it prints an error.

idk why this happens, but something was done wrong / installed wrong.

**Comment by abma** [comment]
try to clean your build dir (git clean -f -d -x)

**Comment by JoshuaPettus** [comment]
Thanks, but already did.   I'll keep picking at it, hopefully I can come up with something.

**Comment by abma** [comment]
which command are you using to create the build system files?

(cmake ... ?)

**Comment by JoshuaPettus** [comment]
cmake .. -Wno-dev -DALURE_LIBRARY=/Users/herecomethej/Documents/SpringDevStuff/alure/lib/libalure-static.a -DALURE_INCLUDE_DIR=/Users/herecomethej/Documents/SpringDevStuff/alure/include/OpenAL

I start from a build folder in the source folder.  ALURE isn't part of macports so I had to make a separate install of it.

For jokes I tried the macports gcc install, fully expecting it to fail because It doesn't do objective-c AFIK.  It did at least get past that point.  I don't know if that's a clue or just lets me know my clang install is somehow borked as far as cmake is concerned.

**Comment by abma** [comment]
why "cmake .."? i'm not sure if out of source builds work well, you should run "cmake ."

when running cmake in a clean source dir: can you paste the full output please?

**Comment by JoshuaPettus** [comment]
Well that's always worked just fine before, so I'd be surprised if that was it.  I did it because it's easy to clean, but then that was before I knew about git clean -f -x -d.  

I modified the script to do an in source build and that clean method.
And the full output

```

-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1") 
-- Found Doxygen: /opt/local/bin/doxygen (found version "1.8.10") 
-- Found Doxyfile.in: /Users/herecomethej/springlobby/doc/Doxyfile.in  
-- Found LATEX: /opt/local/bin/latex   
-- Found xgettext: /opt/local/bin/xgettext
-- Found msgmerge: /opt/local/bin/msgmerge
-- Checking to see if CXX compiler accepts flag -std=gnu++11
-- Checking to see if CXX compiler accepts flag -std=gnu++11 - yes
-- Using -std=gnu++11
-- Checking to see if CXX compiler accepts flag -std=c++11
-- Checking to see if CXX compiler accepts flag -std=c++11 - yes
-- Checking to see if CXX compiler accepts flag -std=c++0x
-- Checking to see if CXX compiler accepts flag -std=c++0x - yes
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Configuring incomplete, errors occurred!
See also "/Users/herecomethej/springlobby/CMakeFiles/CMakeOutput.log".
See also "/Users/herecomethej/springlobby/CMakeFiles/CMakeError.log".
):
  /opt/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.6/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /opt/local/share/cmake-3.6/Modules/CMakeFindDependencyMacro.cmake:65 (find_package)
  /opt/local/share/cmake-3.6/Modules/FindBoost.cmake:1401 (find_dependency)
  src/CMakeLists.txt:34 (FIND_PACKAGE)


```
Here is  CmakeError.log

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /Users/herecomethej/springlobby/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ae47b/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_ae47b.dir/build.make CMakeFiles/cmTC_ae47b.dir/build
Building C object CMakeFiles/cmTC_ae47b.dir/CheckIncludeFile.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -Wextra -Wall -Wno-strict-aliasing  -std=gnu++11   -o CMakeFiles/cmTC_ae47b.dir/CheckIncludeFile.c.o   -c /Users/herecomethej/springlobby/CMakeFiles/CMakeTmp/CheckIncludeFile.c
error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'
make[1]: *** [CMakeFiles/cmTC_ae47b.dir/CheckIncludeFile.c.o] Error 1
make: *** [cmTC_ae47b/fast] Error 2

```
And the CMakeOutput.log

http://pastebin.com/5HRkFtfz

**Comment by JoshuaPettus** [comment]
If nothing else works, I can always try the latest XCode Beta and commandline tools

**Comment by abma** [comment]
for me it looks like boost can't be found. is boost installed? maybe a reinstall helps, too.

**Comment by abma** [comment]
also possible its a bug in cmake: cmake-3.6 is very new. i don't see a bug in springlobby here (closing)

**Comment by JoshuaPettus** [comment]
Nope it is definitely not a springlobby bug,  thanks for your help!   I thought Boost wasn't required anymore?  Didn't look like the initial problem was boost related but I'm sure I would have hit something down the line. That's good to know.

**Comment by abma** [comment]
boost is still required!

**Comment by abma** [comment]
maybe at the spring forum / osx people can better help:
https://springrts.com/phpbb/viewforum.php?f=65

i don't have osx / much experience with it.

afaik you must compile wxwidgets / boost with the same compiler as springlobby, maybe thats the issue here?!

no clue about cmake...

**Comment by JoshuaPettus** [comment]
For the record, I rolled back to cmake 3.5.2 on macports, and still had the same issue.   Boost and wxwidgets were both compiled by the current version of clang... The macports package had to compile from scratch because I wanted the +monolithic variant which eased bundling.

**Comment by abma** [comment]
whats inside the files:

   See also "/Users/herecomethej/springlobby/CMakeFiles/CMakeOutput.log".
   See also "/Users/herecomethej/springlobby/CMakeFiles/CMakeError.log".

?

**Comment by JoshuaPettus** [comment]
Same as, before 9 comments up

**Comment by abma** [comment]
can you try to add the line at the beginning of CMakeLists.txt please:
    set(CMAKE_C_FLAGS "")

i have no clue why cmake sets the C_FLAGS from CXX_FLAGS.

**Comment by JoshuaPettus** [comment]
good thought, but no change

**Comment by abma** [comment]
is there any output of grep std=c++11 CMakeCache.txt ?
