### ISSUE TITLE
system installed springlobby complains with  "/usr/bin is not writable!"

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#740]
http://paste.springfiles.com/view/a23a9786#L22

ExecutableFolder (/usr/bin/)
        WX: no POSIX: no TRY: no

**Comment by JoshuaPettus** [comment]
How about /usr/local/bin?

**Comment by abma** [comment]
ExecutableFolder beeing not writeable shouldn't throw an error, it doesn't matter if its /usr/local/bin /usr/bin or sth. else...

**Comment by JoshuaPettus** [comment]
Well, as a matter of best practice nothing but disto software belongs in /usr/bin. For one thing future upgrades may modify or delete anything in there without warning.  But I do see what you mean.
