### ISSUE TITLE
Using some special unicode characters is title desc > Displays empty title in BattleRoom

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#743]
Battlename is supposed to be "\* Balanced Annihilation \* →3v3← SmallMaps"
<img src="http://img4.hostingpics.net/pics/81425054SL.png">
<img src="http://img4.hostingpics.net/pics/553625SWL.png">

But it can be used in chat :
<img src="http://img4.hostingpics.net/pics/456022SL2.png">

**Comment by abma** [comment]
hmm, ok maybe i'm wrong with unicode: for me it looks like SWL has wrongly implemented utf-8.

**Comment by abma** [comment]
also i don't see a -> in the ASCII table:

https://en.wikipedia.org/wiki/ASCII

**Comment by abma** [comment]
when i host in springlobby "→3v3←" it works fine

**Comment by abma** [comment]
i don't see whats should be wrong in springlobby
