### ISSUE TITLE
Fail to start after connection.

### ISSUE THREAD

**Issue by frju365** [springlobby/springlobby#747]
Hello,
I've  a problem. When I start springlobby on my debain stretch (v. 9), two windows appears. In one of them I can connect myself. But when I click on "Ok". All the windows disappear and my terminal writes
"Abandon". The last line of the springlobby.log is : 
"Error    /build/springlobby-4Cg77y/springlobby-0.255+dfsg/src/springlobbyapp.cpp:224 Fatal exception!".
I don't know where my problem comes from but it's surely a bug. This problem was created when I update my system (weekly update).
My log :
[springlobby.txt](https://github.com/springlobby/springlobby/files/466141/springlobby.txt)

Thank you for your help,
frju365

**Comment by abma** [comment]
can you please try if removing /home/abld/.spring/engine/98.0/ fixes it?

**Comment by frju365** [comment]
Yes. It fixes it. Thank you for your help.
frju365

**Comment by frju365** [comment]
All was fixed and I forgot to close the issue. Sorry.
