### ISSUE TITLE
Archive not found (planet annihilation v3)

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#748]
After I press "start" (mod Planet Annihilation V3) I see message 
![image](https://cloud.githubusercontent.com/assets/9379087/19017142/9a72a31a-8838-11e6-8c1c-d214fc273250.png)

System info:
`
    SpringLobby 0.255 (win x32)
    SpringLobby config file: C:\Users\Р›РµРѕРЅРёРґ\AppData\Roaming\springlobby\springlobby.conf (writable)
    LobbyWriteDir (C:\Users\Леонид\AppData\Roaming\springlobby\)
        WX: yes POSIX: yes TRY: yes
    CachePath (C:\Users\Леонид\AppData\Roaming\springlobby\cache\)
        WX: yes POSIX: yes TRY: yes
    ExecutableFolder (C:\Program Files (x86)\SpringLobby\)
        WX: no POSIX: yes TRY: no
    DownloadDir (C:\Games\springlobby-downloads\)
        WX: yes POSIX: yes TRY: yes
    Current SpringData: (C:\Games\springlobby-downloads\)
        WX: yes POSIX: yes TRY: yes
    Current unitsync: C:\Users\Р›РµРѕРЅРёРґ\Documents\My Games\Spring\engine\spring-    100.0\unitsync.dll
    Current spring executable: C:\Users\Р›РµРѕРЅРёРґ\Documents\My Games\Spring\engine\spring-    100.0\spring.exe
    Portable mode: no
    Compiled with wxWidgets 3.0.2.0
    Started with: 
    C:\Program Files (x86)\SpringLobby\springlobby.exe`

**Comment by abma** [comment]
IMHO this should be fixed. reopen with springlobby.log when it happens again please.
