### ISSUE TITLE
improvements to spring settings management

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#754]
springlobby 0.255

Currently, on springlobby menu, "Edit > Spring Settings" opens the separate "SpringSettings" application which i've been told is outdated. Many engine settings aren't shown there and it's unclear to which engine versions they apply.

From springlobby there's no way to change some of the internal spring settings at all.
- modify springsettings to allow changing ALL settings 

OR
- modify springlobby to allow changing ALL settings directly

in either case there should be a sentence describing what each setting does, similar to what's available on "https://springrts.com/wiki/Springsettings.cfg"

settings could also be grouped by category

**Comment by jamerlan** [comment]
Spring itself have settings editor. But it's impossible to use it for regular player. So SpringSettings is still much better then nothing :-)

**Comment by abma** [comment]
see #877
