### ISSUE TITLE
replace springlobby logo

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#756]
spring games are about machines, about planets, about war.

and the logo is.....a winking yellow sun thingy???

please replace it with something "cool".

note : the same yellow sun thingy with black shades is not a valid replacement.

It should look more like the engine program logo
https://avatars2.githubusercontent.com/u/41930?v=3&s=200

**Comment by Usaga** [comment]
SpringLobby != Spring. It may have different logo.

**Comment by springraaar** [comment]
i made an example
![springlobby_logo](https://cloud.githubusercontent.com/assets/11828472/19673780/e54fffb4-9a7a-11e6-9f01-e349901dd5de.png)

**Comment by gajop** [comment]
That's not a good logo. You'd do better by removing the sun and adding the people inside.
See wiki & chobby logo as well as the relevant forum thread.

**Comment by ashdnazg** [comment]
I actually like the springlobby logo :(

**Comment by abma** [comment]
as long as there is no better proposal as the current logo i don't see anything change here, sorry.

and i personally think the current logo is okish.

**Comment by gajop** [comment]
I think the existing logo is good, but the icon could be modernized.

**Comment by springraaar** [comment]
> You'd do better by removing the sun and adding the people inside.

exactly, that's one of the options I thought, but my designer skills aren't good so didn't draw it.

Don't think about it as something that opens your good old "dev chat". Think about it as if you're new to SpringRTS games and just downloaded the lobby as a gate to something like supreme commander, or planetary annihilation.  Would the lobby icon give a good first impression?

Look at all the other game/lobby icons on your desktop. Think about the purpose. Can you find one  that you would you consider "worse" than the SL logo?

**Comment by gajop** [comment]
I look at Skype, Steam, Desura, Chrome and similar popular applications, and the icon doesn't really tell what the application is about. It's much more important that it's attractive I think.
Abma has it right however. Unless there's a concrete proposal (preferably with an example icon), there's not much to do.

**Comment by tomjn** [comment]
When The SY's made Spring they envisioned the word to mean springy mechanical springs, the sort you would find in a machine or a mattress. That the logo that was chosen was a half sun reflected the misunderstanding by the community, and a lack of decent logos ( nobody put forward any branding in that competition, it was literally just a graphic ), so I don't see why the Spring Lobby logo needs the same

There's also a problem with using the engines logo and branding, in that it implies SpringLobby is the official lobby and an official project, which isn't true else it'd be bundled with the engine. For this reason I'm not keen on it switching to an arbitrary icon inside the logo frame I designed

**Comment by springraaar** [comment]
https://springrts.com/wiki/GamesDownloads

Apparently springlobby's still the officially endorsed lobby. It makes sense, considering it shares the name with the engine. Also history.

I'll make a few other logos.

**Comment by springraaar** [comment]
two other logos with some variations

2
![springlobby_logo2](https://cloud.githubusercontent.com/assets/11828472/19834888/4519d11a-9e6b-11e6-829e-278e53cbde55.png)

3
![springlobby_logo3](https://cloud.githubusercontent.com/assets/11828472/19834889/60befe0e-9e6b-11e6-9b3a-2575b3a6b2ba.png)

4
![springlobby_logo4](https://cloud.githubusercontent.com/assets/11828472/19834892/7438bda8-9e6b-11e6-9a27-703be248e13b.png)

5
![springlobby_logo5](https://cloud.githubusercontent.com/assets/11828472/19834894/8ed89746-9e6b-11e6-8f3f-018f6e6d81ea.png)

6
![springlobby_logo6](https://cloud.githubusercontent.com/assets/11828472/19834896/909a6b22-9e6b-11e6-9940-4a84a914d9ca.png)

**Comment by gajop** [comment]
@tomjn that's an interesting piece of history i didn't know. I'd like to see you write a more detailed "History of Spring" one day.

**Comment by springjools** [comment]
Nice! 500 times better than the ones we have today at least.

**Comment by Usaga** [comment]
These logos are look like for some chat app not gaming lobby) But number 4 is not so bad.

**Comment by tomjn** [comment]
Notes:

- they need to be vector not raster, the logo is already blurry on
non-retina screens never mind newer machines and iPhones, those look super
blurry
- the drop shadow isn't in keeping with the design, it should be a golden
glow around it
- the corners are curved, they shouldn't be sharp
- the items inside shouldn't be translucent, they should be white or have a
tint of golden yellow at max luminosity
- the gradient overlay makes the bottom right corner too dark
On Sun, 30 Oct 2016 at 06:40, springraaar <notifications@github.com> wrote:

two other logos with some variations

2
[image: springlobby_logo2]
<https://cloud.githubusercontent.com/assets/11828472/19834888/4519d11a-9e6b-11e6-829e-278e53cbde55.png>

3
[image: springlobby_logo3]
<https://cloud.githubusercontent.com/assets/11828472/19834889/60befe0e-9e6b-11e6-9b3a-2575b3a6b2ba.png>

4
[image: springlobby_logo4]
<https://cloud.githubusercontent.com/assets/11828472/19834892/7438bda8-9e6b-11e6-9a27-703be248e13b.png>

5
[image: springlobby_logo5]
<https://cloud.githubusercontent.com/assets/11828472/19834894/8ed89746-9e6b-11e6-8f3f-018f6e6d81ea.png>

6
[image: springlobby_logo6]
<https://cloud.githubusercontent.com/assets/11828472/19834896/909a6b22-9e6b-11e6-9940-4a84a914d9ca.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/springlobby/springlobby/issues/756#issuecomment-257135056>,
or mute the thread

**Comment by springraaar** [comment]
Thanks

I've remade logo 4 with some of the suggested changes, like rounded corners and yellowish glow. It's also bigger (not vector though).

I can provide a .pdn file with the separate layers, including persons and lines without glow/blur, if anyone's interested (it's a free img editing software for windows that supports layers by no vector images)

![springlobby_logobig](https://cloud.githubusercontent.com/assets/11828472/19846725/a5e7bc54-9f39-11e6-8669-5941f67d78cb.png)

**Comment by springjools** [comment]
It looks very nice. Kind of reminds me of a chat program such as messenger, but that's actually quite what it is :)

**Comment by tomjn** [comment]
Is it possible to get it in a more portable format? A lot of people use Linux or macOS

If possible, Inkscape should let you place the rasterised layers into an SVG that can be imported into Illustrator and Photoshop etc

**Comment by springraaar** [comment]
I wasn't suggesting using pdn for the definitive file, just as a temporary container to hand it over to whoever's going to integrate this.

here are some other possibilities.

8
![springlobby_logobig_8](https://cloud.githubusercontent.com/assets/11828472/19956603/5ea47ac2-a186-11e6-861c-04888e899882.png)

9
![springlobby_logobig_9](https://cloud.githubusercontent.com/assets/11828472/19956606/669330ac-a186-11e6-9a0e-caae0b9a2b75.png)

**Comment by Usaga** [comment]
Very nice! I like last variant with sun) Is it possible to combine these last two logos? Make sun bigger and place those guys inside it. May be it would be looked better.

**Comment by springraaar** [comment]
Thanks.

the problem with the linked people is that it looks confusing when using very small thumbnails.

10
![springlobby_logobig_10](https://cloud.githubusercontent.com/assets/11828472/19957523/43af4cca-a18f-11e6-8668-64f4d9b776b1.png)

Glowy white people were hard to tell apart from the yellow background so I put dark ones. I could replace the people with dots.

Another thing is the colours. Should they have logo keep the same orange/blue frame as the engine logo?

**Comment by Usaga** [comment]
Yep, this logo scaring me)

**Comment by PicassoCT** [comment]
Like the Planet with sunrise one. Red Planet White/Yellow Sunriseß

**Comment by PicassoCT** [comment]
Just because its pixelated doesent meant the springlobby logo cant be takken seriously- gringo springo and the likes of him are the bare metall of pixelated logos that make sennse on zoom in
![senorspringo copy](https://cloud.githubusercontent.com/assets/1271047/19984008/a465c9e0-a20c-11e6-8b55-7cba6771af51.png)
![seriousmuderiousbuisness](https://cloud.githubusercontent.com/assets/1271047/19984007/a4645394-a20c-11e6-8a55-e531f384709c.png)

**Comment by springraaar** [comment]
logo 7 or logo 9?

7 has the spring logo's background colors and the people-links, 9 is a yellow planet-sun thing closer to the current one.

**Comment by tomjn** [comment]
The blue border on the spring logo is a little too large for my taste and has a corner radius issue I didn't catch when I first made them.

With this in mind, here's a 100% pure CSS/HTML version of the logo. I'd advise placing an SVG element inside the inner div, it will center the contents vertically and horizontally. You may need to swap text-shadow for box-shadow and adjust the radius on the glow accordingly for best results. Change the `font-size` to scale the entire thing up or down, use helvetica/arial for any text.

HTML:
```
<div class="spring-container">
	<div class="spring-contents">
		Hi
	</div>
</div>
```

CSS:
```
.spring-container {
	height: 6em;
    width: 6em;
    border-radius: 0.5em;
    border: 0.3em solid rgb(48,92,142);
    background: rgb(183,49,31); /* Old browsers */
    background: -moz-linear-gradient(-45deg, rgba(183,49,31,1) 0%, rgba(183,49,31,1) 100%); /* FF3.6-15 */
    background: -webkit-linear-gradient(-45deg, rgba(183,49,31,1) 0%,rgba(183,49,31,1) 100%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(135deg, rgba(183,49,31,1) 0%,rgba(183,49,31,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#b7311f', endColorstr='#b7311f',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
    copy;
    color: #ffffff;
    font-size: 50px; // sets the scale of the whole thing, all other units are based on this
}
.spring-contents {
    text-shadow: gold 0 0 0.3em;
    line-height: 100%;
    vertical-align: middle;
}
```

<img width="484" alt="screen shot 2016-11-07 at 17 14 34" src="https://cloud.githubusercontent.com/assets/58855/20067601/bb3dbeda-a50d-11e6-870c-8fbdfb91abd2.png">

In terms of what the logo should be, 2 peg characters with a simple explosion inbetween them, arranged diagonally bottom left to top right would be much more scalable and simpler than the circular arrangement at the moment

**Comment by springraaar** [comment]
simple 2 letter logo would be too vanilla i think
![test_logo](https://cloud.githubusercontent.com/assets/11828472/20086402/d6ca3c1e-a567-11e6-8d28-91af1cae1588.png)

2 pegs and explosion? like this



11
![springlobby_logobig_11](https://cloud.githubusercontent.com/assets/11828472/20087226/8a373d00-a56e-11e6-8957-cbcdd4fb0eb8.png)

12
![springlobby_logobig_12](https://cloud.githubusercontent.com/assets/11828472/20087238/a59d1d9e-a56e-11e6-8d6d-0acd3b3b2336.png)

I still prefer logo 9

`<img src="https://avatars3.githubusercontent.com/u/833669?v=3&s=400">`

**Comment by abma** [comment]
wrong:
https://github.com/springlobby/springlobby/blob/master/src/images/springlobby.svg

**Comment by tomjn** [comment]
Here's that SVG in a codepen:

https://codepen.io/anon/pen/jVPgoe

As for your examples, the explosions are too high res and detailed to make for a good logo, and won't scale down or up well. They'll be blurry or pixelated, and too complicated. [Here's an SVG explosion that's much simpler](https://upload.wikimedia.org/wikipedia/commons/e/e0/Explosion.svg). If a new logo is not vector then it's a regression. So far the best logo posted here is the SVG Abma linked to.

**Comment by tomjn** [comment]
Here's an explosion svg https://codepen.io/anon/pen/bBVbGK

**Comment by PicassoCT** [comment]
Sorry find this doesent communicate the whole lobby thing.  Explosion doesent communicate the spring connection. Maybe showing two persons is not that wrong. But how to show at the same time spring-origin and rts purpose.. ?

**Comment by tomjn** [comment]
I don't think it needs to, Steam doesn't incorporate every genre platform and game into its logo. Instead it relies on good branding.

SpringLobby too should have branding, a raster bitmap logo isn't branding

**Comment by gajop** [comment]
Explosion thing is what a bug reporting app should have.

**Comment by springraaar** [comment]
> wrong:
> https://github.com/springlobby/springlobby/blob/master/src/images/springlobby.svg

this means Springlobby devs have had their precious svg logo since 2009. Despite that, it's late 2016 and both the [SL entry page on github](https://github.com/springlobby) and the task bar icon still look ugly and pixelated.

the raster logos I kept posting were examples. No point trying to provide a "final" version of something that's going to be discarded.

Using the new background and border Tomjn provided makes it look somewhat different compared to the engine logo, even if the colors are similar.

so....should the new lobby logo..
a- have the same (or similar) coloured background as the current engine logo?
b- have people pegs in it?
c- have the familiar planet/sunrise thing that's in the current logo?
d- have something about the war-like nature of spring games?

**Comment by tomjn** [comment]
If an explosion implies a bug tracker ( I disagree ) then a sword will do. I don't think the pegs are necessary, or the sunrise ( if the engine background is used I'd definately avoid including the sun )

**Comment by springraaar** [comment]
the logo isn't going to change, isn't it?

**Comment by tomjn** [comment]
It's an open source project with ill defined leadership, the correct course of action is to make a call yourself and do the work, then submit a pull request. Even if we all agree on a new logo, who's going to implement:

 - the icon
 - releasing the new version
 - updating the website
 - updating the github org photo

Right now the issue of the logo being pixelated has little to do with its design and everything to do with people taking the smallest version of the logo and uploading it in places that need much higher resolution. The Spring logo itself should suffer the same problem but it doesn't. Look at the GH org for this repository, it's clear somebody took a 500x500 slot and put an 80x80 image inside

**Comment by PicassoCT** [comment]
Spring - the bowling simulator.

**Comment by abma** [comment]
i don't see a better image in this report.

as tomjn already said: pull requests are welcome!

**Comment by PicassoCT** [comment]
Ask yourselfself - what would Stallmann do?
![logo3](https://cloud.githubusercontent.com/assets/1271047/25507532/e1d1d560-2bac-11e7-9953-0900c47e4b61.jpg)
![logo1](https://cloud.githubusercontent.com/assets/1271047/25507536/e9b4fb86-2bac-11e7-9084-0a313e4c1d6a.jpg)
![logo2](https://cloud.githubusercontent.com/assets/1271047/25507539/ec3fe03c-2bac-11e7-973c-fc00d8442168.jpg)

**Comment by abma** [comment]
Some thoughts: svg is a must. also it should be simple. I'm a bit undecided if it should be similar to the official spring engine logo or not. The current logo IMO is ok because its very unique.

**Comment by PicassoCT** [comment]
I try to get close to the offical logo as possible - colorwise.
Uniqueness is possible, though i always found the smiley is slightly remiscent of the Zero-K Planet Logo.
![reduced](https://cloud.githubusercontent.com/assets/1271047/25640130/c3a704ee-2f8e-11e7-8f3c-c6e8182f738e.jpg)

**Comment by tomjn** [comment]
Just needs someone to create a large raster version of the logo from the existing SVG, and recreate the .ico files and re-upload the GH org image

**Comment by PicassoCT** [comment]
No, springlobby needs a change. That cellphone, smiley reeks of amateurism. Just admit it.
It looks like a tax-deducting app had sex with a chat-app.
