### ISSUE TITLE
option to stay idle in a room without auto-joining games

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#759]
springlobby 0.255

Currently, the lobby automatically starts spring for all users in the room whenever a game starts.

There should be an option to turn this behaviour off, as users may want to idle on game rooms as spectators while they do other stuff (which can be other non-spring related full screen games).

**Comment by specing** [comment]
How should this option be called and where should the checkbox be placed?

**Comment by springraaar** [comment]
Maybe it could be called "No auto-join" or "Chat only" and it should be disabled by default to avoid confusing new players.

**Comment by specing** [comment]
> should be disabled by default to avoid confusing new players.

Maybe there should be an "Expert mode" enable in settings that would enable these sort of things.

I'd also like to remove the whole "I'm ready" stuff, i.e. until you enable expert mode you will always be ready.

**Comment by springraaar** [comment]
i've seen people who can't find the "ready" checkbox, but removing it could generate misunderstanding and frustration due to "false" starts.

**Comment by specing** [comment]
False starts? They wanted to play after all.

**Comment by specing** [comment]
or rather, why would you join a room with no intention to play?

Anyway this is now resolved.

**Comment by abma** [comment]
ah, thanks.

implemented in 0.261:
"add option to not launch spring when speccing a battle"
https://github.com/springlobby/springlobby/blob/master/ChangeLog#L9
