### ISSUE TITLE
Just installed spring. Getting bombarded with error messages.

### ISSUE THREAD

**Issue by FalcoGer** [springlobby/springlobby#760]
Just installed from ubuntu repositories for ubuntu 16.04 LST with gnome. launched for the first time. was asked to register, which I did.
Suddenly an error pops up:
logic error ( /build/springlobby-snPMON/springlobby-0.237/src/gui/mainchattab.cpp:95 ): m_server_chat = 0
I close it, then it pops up again. Every few seconds a new error message opens. If I don't click it it will continue to spam more error messages on top of each other. Fix your code before putting it in the repos, please.

**Comment by abma** [comment]
0.237 is old, please update springlobby to latest version (currently 0.255)
