### ISSUE TITLE
battlelist column changes and promotion tracking/integration

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#761]
currently the battlelist on SL 0.255 (windows) looks something like this
![springlobby_player_list_old](https://cloud.githubusercontent.com/assets/11828472/20615723/57093032-b2d4-11e6-941f-172f920a4b1d.jpg)

if you're an unfortunate ubuntu user stuck with SL 0.237, it looks like this
![springlobby_player_list_ubuntu_old](https://cloud.githubusercontent.com/assets/11828472/20615732/6db7499a-b2d4-11e6-8aa0-2ace888ebd00.png)

The columns and proposed changes
S - state, keep
C - country, keep
R - what does it even mean? relay status? remove or append status to other column
Description - keep
Map - keep
Game - keep
Host - keep
Spectators - keep, but should be narrow, use vertical text or something
Players - keep but modify (*)
Max - keep, but should be narrow, maybe merge into "players"
Running - keep
Engine - should appear after game

( * ) the "players" column could show
current/(nTeams * teamSize) (+X), where X is (nTeams * teamSize - current), or the minimum number of players required for even teams.

if anyone on that host used a promote command within the last minute and the game hasn't yet started, the players cell or the whole line should blink for a minute unless the game starts or all players leave.

if at least one room is blinking due to "promote", the battlelist tab should blink too.

half-assed example
![springlobby_player_list_new](https://cloud.githubusercontent.com/assets/11828472/20616030/150ab504-b2d7-11e6-88e6-5372c0a6e115.jpg)

That'd be a much more powerful way to signal "eagerness" to start a game than what we currently have, which is useless for most people (typically, the "newbies" room is by far the most populated one and bots are banned there).

If the default font sizes mean lots of columns end up clipped, maybe a smaller font should be used.

**Comment by specing** [comment]
I took a look at the list view code and I further propose the following:

- The "spectators" column should be dropped entirely as battle rooms are not supposed to be chat rooms.
- "R" apparently means minimum rank and should be put into a tooltip when hovering over the room + the row greyed out if user does not qualify. Likewise spectators can be put into this tooltip.
- "Description" should be renamed to "Name" or "Room name"
- "C" (country) can likewise be put into that tooltip as it is not that important in RTS context.
- Host goes into tooltip as well.
- The players column data format should be (players)/(max players) or the one you propose, with sorting reprogrammed to reward rooms that are closer to filling up more than those that have the highest number of players.
- "Max" is not relevant at all, it means the maximum clients that can be in a room and not maximum players which would be useful, but can be merged into players.
- The "running" column only counts running time as far as the client is concerned, not actual running time and can likewise be dropped or fixed to display real running time.
- The "engine"  column conveys little usable information as it more or less follows from game & its version.

Some fancy sizing could be done with 1/2 the space freed up such that manually stretching those columns around would no longer be necessary.

**Comment by springraaar** [comment]
comments regarding previous post:
- disagree with dropping the spectators column, but it should be shown in a compressed form ("spectators" header makes the column too wide, I suggested using vertical text, or just an "eye" icon)

- not sure, agree some of the room's properties could be shown on-hover, maybe that's one of them

- agree with the description -> name change

- not sure, the flags do look colourful and may help the lag-conscious pick the "nearest" server, or avoid the ones from countries they don't like.....hmm.....maybe that's a bad thing

- agree with the players, the room "max" could be shown on-hover, the key here is showing <current>/<minimum needed to start game>, and may be tricky to sort out. Are 2 players ready set to play 1v1, or waiting for a third player to play ffa? or maybe waiting and won't start until they get 6 players for a 3v3? I made a suggestion for this on the previous post

- the running time could be shown on-hover on the room status column or merged into it somehow

- maybe the engine could be merged into the game column

**Comment by specing** [comment]
- vertical text is bad, but eye would be doable. Though I'd still rather just drop it altogether.
- How are the lag-conscious going to pick the nearest server when everyone is in a single room? Note that the above change is part of the strategy to have people not be so bound to a single room.
- that is trivial to find out, for 1v1 it would be shown as 2/2 + 0 and for 1v1v1 it would be shown as 2/3+1. For 3v3: 2/6 +4. This all assumes they won't be steadily increasing teamsize, but if they do so the people that came for 1v1 might leave and the ones for 3v3 could join a 0/6 room instead.

Reordering columns while running should be supported, too.

**Comment by springraaar** [comment]
About the sort order. I think the two most useful modes would be 
- players DESC : already available, maybe should the the default

- game, players DESC : this would highlight the different games and the most populated room for each game. There are some issues in doing this properly, as there are several variants being hosted for some games that could be lumped together somehow. In the future there could be a restriction to only show the top N populated rooms for each game (with a "+" button to show the remaining games), to prevent a game with many rooms from taking over the UI space. It could also have an extra "header" row for each game with just one column with the total number of players in all rooms hosting that game

**Comment by specing** [comment]
more in #663

**Comment by specing** [comment]
@abma is there any way to get current nbteams and teamsize? This does not seem exported in the lobby protocol and would be very important in calculating number of missing players from filling up and showing realistic player maximums.

**Comment by abma** [comment]
i'm not sure what you mean but some info is only broadcasted inside battles. i.e. which player is in which team.

https://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#MYBATTLESTATUS:client

**Comment by specing** [comment]
I mean host-set nbteams and teamsize (in this case referring to SPADS commands). Currently the Max column is a bit worthless as it shows the maximum people in a room, not the maximum players. The latter would be much better from a sorting perspective.

**Comment by abma** [comment]
fixed via https://github.com/springlobby/springlobby/pull/847 or
https://github.com/springlobby/springlobby/pull/875
