### ISSUE TITLE
Spring fails when I Launch from springlobby

### ISSUE THREAD

**Issue by frju365** [springlobby/springlobby#762]
Hello,
I need help because Spring failed when I launch it from Springlobby. 
infolog.txt : http://paste.springfiles.com/view/6d4f0f6f#L86
I see a message "Broken pipe (SIGPIPE)"
Any idea ?

Thanks for your help.
frju365

**Comment by Usaga** [comment]
Does this happen only when launching Spring from SpringLobby? Did you try to remove\reset Spring settings in SpringLobby?

**Comment by frju365** [comment]
That's it. I can't reproduce this bug because it seems to work again.
Thanks,
frju365
