### ISSUE TITLE
Too small height of input message chat field.

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#763]
I'm set 150% size of windows elements because i have too small screen at laptop and got trouble.
![springlobby_font](https://cloud.githubusercontent.com/assets/11837119/22252745/419b571e-e260-11e6-98c8-e02bf650481b.jpg)
![windows_150](https://cloud.githubusercontent.com/assets/11837119/22252746/419dd5d4-e260-11e6-805c-b69efd01dbe7.jpg)

**Comment by do2005** [comment]
I'm sorry, but why is it marked as enhancement? I thought that if current functional don't work properly it's called bug. I cannot see the text what i typed in chat of lobby. It's bring to difficult to change map and write something. I suppose that it's serious bug.

**Comment by Usaga** [comment]
I can't do much about this. Looks like it's the way Windows 7 resizes wxWidgets UI. I am using Windows 10 and it's doing fine:
![untitled](https://cloud.githubusercontent.com/assets/10685845/23575187/399f03a0-009a-11e7-9826-33e25c92f357.png)

**Comment by do2005** [comment]
Please check it out further.  I think that i changed fonts of the chat in spring settings too.
![spring_font_bug](https://cloud.githubusercontent.com/assets/11837119/23577471/d5878dba-00d0-11e7-8901-c47deacb21ae.jpg)

**Comment by adrianulima** [comment]
I have this same problem using a 4k monitor, I'm also using Windows scale feature.

**Comment by do2005** [comment]
It's possible to increase the input height in twice? I suppose it will solve all problems.

**Comment by Usaga** [comment]
I will look ugly (more uglier) for all other users, I suppose...

**Comment by do2005** [comment]
You are will be look fine and springlobby too. It will be looking like multi string input. Why this input should be in one thin string? Everyone can not see a completely long text if it is being typed at the moment.

**Comment by do2005** [comment]
At Win 10 we have another problem with this chat input also. Increased size of fonts in springlobby settings and in windows don't increase font of input and size of input.
Please do something with this input field.
![springlobby_chatinput_small](https://cloud.githubusercontent.com/assets/11837119/25304880/f55a8560-2778-11e7-92e9-76cd192fa787.jpg)
