### ISSUE TITLE
Unable to watch replays moved into ~/.config/spring/demos

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#764]
An image is worth a thousand words: https://lut.im/SY8aQKlrbE/cMGJlrb1Ab8WqUdN.png
Summary: "the engine broken map broken and game broken is required to play. Should they be downloaded?"

Springlobby is built with 9999 overlay ebuild at 2569bc0

**Comment by specing** [comment]
maybeX are the 1944_Titan demos from 22 of january 2017: e.g. http://think.nsupdate.info:9000/s44/autohosts/demos/WorldAtWarII_rapid2/20170122_185111_1944_Titan_103.sdfz

**Comment by abma** [comment]
the demofiles can't be parsed. the error here is that the download window shows up, instead it should show an error message that the demo couldn't be parsed.

**Comment by specing** [comment]
Why can't they be parsed? This looks more like a bug than an "enhancement".

**Comment by abma** [comment]
thats why its an enhancement: it should show more details about the error / problem. there will be always replays which can be broken / can't be parsed.

**Comment by specing** [comment]
Buumi has just said that he can watch these replays.

**Comment by abma** [comment]
~/.springlobby/springlobby.log maybe gives hints whats wrong with these files.

**Comment by specing** [comment]
Warning  /tmp/portage/games-util/springlobby-9999/work/springlobby-9999/src/replaylist.cpp:138 Name of the file /home/specing/.config/spring/demos/maybe1_20170122_001406_1944_Titan_103.sdfz could not be parsed!

**Comment by abma** [comment]
try to remove "maybe_" in the filename

**Comment by specing** [comment]
How else am I supposed to designate downloaded demos? Does springlobby read some other demo directory in addition to ~/.config/spring/demos?

**Comment by abma** [comment]
no, the filename must be correct. not sure if this was fixed recently: needs retest with at least springlobby 0.263

**Comment by specing** [comment]
No, I've looked at that code and it definetely 250% needs rewriting, especially the magic offsets part.
