### ISSUE TITLE
[BAD BUG]: Issue Registering Account with Spring, Persistent Invalid Characters Error

### ISSUE THREAD

**Issue by Hexxitfan11** [springlobby/springlobby#766]
I was attempting to have a friend of mine download the game, and when they went to make and account, it simply responded with the message stating that invalid characters were present. Only ASCII characters were part of the username and it had no disallowed characters in it. My friend tried multiple different usernames, including an all-lowercase sequence of letters, to no avail. this issue is present on both the Evolution RTS Steam lobby and the SpringLobby at "http://springlobby.info/landing/index.php". Some help would be appreciated. I will have them uninstall both lobbies and reinstall to see if that resolves the issue. I have successfully had five other people download, register and play on both lobbies with no issues.  Unfortunately I cannot provide the exact error message being given or the friend's attempted username as we were not in the same location. My gratitude in advance for any help anyone can provide.

**Comment by abma** [comment]
which operating system is he using?
which version of springlobby is used?

**Comment by Hexxitfan11** [comment]
operating system is windows, I am waiting for a reply from them but I believe it is windows 10. springlobby version is whatever the latest is.

**Comment by Hexxitfan11** [comment]
next time they are on I will have them try a 6-8 character all lowercase username to see if length is the issue

**Comment by abma** [comment]
which username does he try to register?

**Comment by Hexxitfan11** [comment]
the username is Pansophic_Magician

**Comment by Hexxitfan11** [comment]
He hasn't been online yet to try a shorter one

**Comment by abma** [comment]
i've looked into the server log / db: the username isn't registered yet.

did he forgot to register the name first?

the username should work...

**Comment by abma** [comment]
note: i couldn't find any related message in the server log: maybe he is behind some restrictive firewall / tries to connect to the wrong server?

**Comment by abma** [comment]
i don't see where this could be a springlobby or lobby server bug. without more details i can't help, sorry.
