### ISSUE TITLE
Could I use http proxy while downloading?

### ISSUE THREAD

**Issue by ppaanngggg** [springlobby/springlobby#767]
How to set it if avaliable?

Thanks! :D

**Comment by abma** [comment]
windows or linux?
libcurl is used for downloading, very likely it uses the env-vars to detect a proxy. on a linux terminal:

export http_proxy=http://proxy:3128/
export https_proxy=http://proxy:3128/
springlobby

could work. not sure if this works on linux, possible it uses the system settings for proxy detection.

https://curl.haxx.se/libcurl/c/libcurl-tutorial.html#Environment

**Comment by ppaanngggg** [comment]
@abma Thanks!
