### ISSUE TITLE
"is not writeable"

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#768]
screenshot: https://lut.im/b2Axv1O28Y/YrExX7zYTaMr3R9m.png

Happened after moving springlobby.conf out of the way and starting springlobby again to register another bot. There was another springlobby.conf with -f pathtootherconf running if that matters.

springlobby was built via  -9999 ebuild around 28th of january.

**Comment by abma** [comment]
please update to the latest version and try again

**Comment by specing** [comment]
Unable to reproduce
