### ISSUE TITLE
SL freezes after every game ends

### ISSUE THREAD

**Issue by PtaQQ** [springlobby/springlobby#776]
Probably a known bug, but to be sure: 
After game ends SL hangs for 10-20 sec, it is connected with reloading replays afaik, as clearing \demos folder fixes the issue.

**Comment by specing** [comment]
I am experiencing the same, performance degrading with the increase in the number of replays. The same happens when sorting them in the replays tab, leading me to believe it is a performance issue with either sorting or WXWidgets or both.

**Comment by abma** [comment]
@PtaQQ @specing 

are you using windows or linux?

**Comment by specing** [comment]
GNU/Linux

**Comment by specing** [comment]
Probably a duplicate of #717

**Comment by abma** [comment]
yeah, duplicate
