### ISSUE TITLE
Error dialog at startup: "Error had happened: basic_string::_S_create"

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#779]
https://i.imgur.com/eYEmztV.png

after the error you have to connect manually

**Comment by Ruwetuin** [comment]
springlobby.log:

Message  /data/private/buildbot/slaves/springlobby/release/build/src/springlobbyapp.cpp:124 SpringLobby 0.256 started
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/utils/wxTranslationHelper.cpp:26 Couldn't load locale 0, fallback to default
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) BATTLE
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 15 lines from C:\Users\Flowris\Documents\My Games\Spring\chatlog\Official server\BATTLE.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/gui/playback/playbacktab.cpp:60 PlaybackTab::PlaybackTab()
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:169 Error: FIXME: Couldn't load the library C:\Users\Flowris\Documents\My Games\Spring\engine\103.0.1-1222-g37dc534\unitsync.dll: 
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:169 Error: FIXME: Couldn't load the library C:\Users\Flowris\Documents\My Games\Spring\engine\103.0.1-1222-g37dc534\unitsync.dll: 
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:169 Error: FIXME: Couldn't load the library C:\Users\Flowris\Documents\My Games\Spring\engine\103.0.1-1222-g37dc534\unitsync.dll: 
Error    /data/private/buildbot/slaves/springlobby/release/build/src/springlobbyapp.cpp:190 Error had happened: basic_string::_S_create
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/gui/mapgridctrl.cpp:280 Map EvoRTS - Delta Siege - v12 already in grid!
Message  /data/private/buildbot/slaves/springlobby/release/build/src/utils/slconfig.cpp:84 config file saved: C:\Users\Flowris\Documents\My Games\Spring\springlobby.conf
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) chatpanel-server
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 15 lines from C:\Users\Flowris\Documents\My Games\Spring\chatlog\Official server\chatpanel-server.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) server
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 15 lines from C:\Users\Flowris\Documents\My Games\Spring\chatlog\Official server\server.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:987 sent: LOGIN ... <password removed>
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1002 sent: #3 LISTSUBSCRIPTIONS

**Comment by abma** [comment]
does deleting / redownloading C:\Users\Flowris\Documents\My Games\Spring\engine\103.0.1-1222-g37dc534 fix the error?

**Comment by abma** [comment]
no feedback -> closing
