### ISSUE TITLE
No engine compatible to the lobby server.... message sticks out like a sore thumb

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#781]
When registering and the nickname is already taken, this message is opened behind the registration window
When logging-in and the password is wrong
When ...

Why the heck does it even check this even before the account is created? Who cares about getting the stable engine when they don't have any games and maps.

**Comment by abma** [comment]
the existence of games / maps can be only checked when a working engine is found. current engine version is checked when connecting to the lobby server.

**Comment by specing** [comment]
Could this dialog be made before asking for registration data?

Could it be complemented with a dialog for a whole-game-package (engine+assorted maps+game)?

**Comment by specing** [comment]
tbh this dialog is bullshit altogether. game+map will have to be downloaded anyway when a room is joined and SL might as well download the engine as well at that time. Plus the player might want to play something that uses a different engine so this download would just eat bandwidth and clutter their HDD.

IMO either offer a full game package for download or nothing at all.
