### ISSUE TITLE
Command: "FAILED" params: "cmd=LEAVEBATTLE	msg=couldn't find battle".

### ISSUE THREAD

**Issue by verybadsoldier** [springlobby/springlobby#783]
I was on [ACE]Pirine and suddenly all (?) hosts disappeared from lobby. I had this message:
`[22:33:33] !! Command: "FAILED" params: "cmd=LEAVEBATTLE	msg=couldn't find battle".`

Hosts are now slowly coming back one after the other.

**Comment by abma** [comment]
very likely caused by https://github.com/spring/uberserver/issues/222

if you see that again: please open a new ticket, thanks!
