### ISSUE TITLE
no error from cmake when wxgtk-dev is missing

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#788]
Hello

I get this error when trying to compile springlobby

http://paste.springfiles.com/view/f5ccbf44

Thanks

**Comment by abma** [comment]
very likely

    git clean -f -d -x && cmake . -G Ninja && ninja

will fix it

**Comment by TurBoss** [comment]
http://paste.springfiles.com/view/30c69022

**Comment by abma** [comment]
wxgtk not correctly installed?

**Comment by abma** [comment]
is the submodule not up to date?

i.e.
git submodule sync
git submodule update -f

should update it

**Comment by TurBoss** [comment]
ok checking

**Comment by TurBoss** [comment]
I'm sorry libwxgtk3.0-dev was missing hehe

**Comment by TurBoss** [comment]
succes 

Thank you

**Comment by abma** [comment]
thats weird, cmake should complain about it.

**Comment by TurBoss** [comment]
ya thats what was thinking
