### ISSUE TITLE
Inaccessible options (missing scrollbar?)

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#792]
An image is worth a thousand words: 
https://lut.im/riA1s7Jc4Z/SThqxU8zmVAzBbgL.png

**Comment by abma** [comment]
weird, this worked some time ago.

as workaround: when i resize the main window the options "expand".

**Comment by abma** [comment]
in current ubuntu it works: (old) wxgtk bug?

**Comment by specing** [comment]
Reproducible in wxgtk 3 as well.
