### ISSUE TITLE
springlobby crashing on start

### ISSUE THREAD

**Issue by 6uoW** [springlobby/springlobby#793]
Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	springlobby.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	00000000
  Nombre del módulo con errores:	msvcrt.dll
  Versión del módulo con errores:	7.0.7601.17744
  Marca de tiempo del módulo con errores:	4eeaf722
  Código de excepción:	c0000005
  Desplazamiento de excepción:	00009f40
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	13322
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

Lea nuestra declaración de privacidad en línea:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0c0a

Si la declaración de privacidad en línea no está disponible, lea la declaración de privacidad sin conexión:
  C:\Windows\system32\es-ES\erofflps.txt
![screenshot 635](https://user-images.githubusercontent.com/12882580/31473436-7a8fa4b0-aec2-11e7-9b21-a879695daf23.jpg)

**Comment by 6uoW** [comment]
[springlobby.log](https://github.com/springlobby/springlobby/files/1377590/springlobby.log)

**Comment by abma** [comment]
very likely it crashes because of the old unitsync.

try if deleting C:\Users\manuel\Documents\My Games\Spring\engine\98.0\ makes the crash disappear.

with a recent spring version it should work fine.

**Comment by 6uoW** [comment]
still crashes, need some other file? im using windows in spanish btw.

**Comment by abma** [comment]
can you please test if renaming "%appdata%\springlobby\springlobby.conf" to springlobby2.conf fixes the crash?

**Comment by abma** [comment]
no feedback + can't reproduce :-|
