### ISSUE TITLE
Column Max Players in Battle list is labeled as Map

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#795]
Hu?

german translation maybe?

**Comment by abma** [comment]
doesn't happen on linux...weird

**Comment by specing** [comment]
Yes it does and on latest git.

https://lut.im/gTkqX2zMKG/LglfypBDmZxnYpqU.png

**Comment by specing** [comment]
Translations and the german one in particular are a train wreck.

I switched to DE and got this: "XYZ hat den the battle verlassen ().". All the strings involved have _() around them and the translation itself is present in po/de.po.
