### ISSUE TITLE
Spring Lobby Crashing on Login/Register

### ISSUE THREAD

**Issue by AlanHeckinJohnston** [springlobby/springlobby#797]
I was unable to log in, got a crash... decided to try and make a new account, this also made a crash.

**Comment by abma** [comment]
whats the version of springlobby?

**Comment by AlanHeckinJohnston** [comment]
The most recent release, I used to play and would like to get back into it

**Comment by abma** [comment]
can you paste springlobby.log please to http://paste.springfiles.com?

https://springrts.com/wiki/Springlobby.log

**Comment by AlanHeckinJohnston** [comment]
I am unable to find this file, where is it located?

**Comment by abma** [comment]
i assume you are on windows?

if so: "%APPDATA%\springlobby\springlobby.log"

**Comment by AlanHeckinJohnston** [comment]
http://paste.springfiles.com/view/a425bfc8

**Comment by abma** [comment]
is spring crashing or springlobby?

**Comment by abma** [comment]
can you please update to springlobby 0.260 and paste springlobby.log again please?

**Comment by AlanHeckinJohnston** [comment]
I uninstalled, installed the new version, and the crash still occurred. Here is the new version:
http://paste.springfiles.com/view/9a893b52

**Comment by abma** [comment]
i don't see any suspicious in this log :-|

can you please paste "%APPDATA%\springlobby\springlobby.conf" but before doing so please remove all lines with "Pass=" !?

**Comment by abma** [comment]
ok, thanks! i still can't reproduce it with your config but this answers some questions.

when does springlobby crash? you have autologin disabled.

do you have to do something to make it crash?

**Comment by AlanHeckinJohnston** [comment]
Nope, just spring lobby. It crashes when I press the login or register button.

**Comment by abma** [comment]
then it looks like something is blocking springlobby from connection to the lobby server.

do you have a local firewall installed which blocks springlobby from connecting to lobby.springrts.com:8200 / version.springlobby.info:80 ?

when telnet is installed you could try:
$ telnet lobby.springrts.com 8200
Trying 78.46.100.157...
Connected to springrts.com.
Escape character is '^]'.
TASServer 0.36 104.0 8201 0

**Comment by AlanHeckinJohnston** [comment]
I let it through the firewall.

Still, a crash.

Perhaps a crash is a bit of an overreaction to not being let through the firewall xD

**Comment by abma** [comment]
can you please test if the development version works for you?
http://springlobby.info/temp/builds/develop/sl_master.zip

if not: please paste again springlobby.log.

**Comment by abma** [comment]
i assume this as fixed
