### ISSUE TITLE
option to show icons indicating players' lobby client

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#799]
On the battle room and maybe the general chat, each player should have an icon displaying its lobby client or "?" if unknown. On mouse over, the client's version should be displayed.

Maybe make this a lobby option (disabled by default).

When new players need help it'd be very useful to know which lobby client and version they're using. It'd also be useful to get a general idea of what lobbies people are using.

**Comment by springraaar** [comment]
related to this:
https://github.com/spring/LobbyProtocol/issues/35

**Comment by abma** [comment]
no icon but agent + version:
https://github.com/springlobby/springlobby/commit/7da4a2ff762012a341cfe1449bb7c029ffe17422
