### ISSUE TITLE
spring lobby crashing after file dll

### ISSUE THREAD

**Issue by ArturasNoit** [springlobby/springlobby#801]
I changed my OS from win 10 to linux ubuntu and lobby failing hard for me.
At start rapid dll wasn't working, but i managed to fix that. Now i can't join some hosts if i dll all files(maps, game, engine), lobby crashes. I can join them sometimes, but it's random. When i start dll some file it crashes sometimes too, same with map/game reload, i can't find what triggers it.

log from terminal
** Error in `springlobby': malloc(): smallbin double linked list corrupted: 0x000000000164d890 ***
https://pastebin.com/Pz8qKJb8

System info:
SpringLobby 0.260 (unix x64)
SpringLobby config file: /home/archie/.springlobby/springlobby.conf (writable)
LobbyWriteDir (/home/archie/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/archie/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/usr/local/bin/)
	WX: no POSIX: no TRY: no
DownloadDir (/home/archie/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/archie/.spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /home/archie/.spring/engine/104.0/libunitsync.so
Current spring executable: /home/archie/.spring/engine/104.0/spring
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
springlobby

**Comment by abma** [comment]
is there something useful in springlobby.log?

very likely this crash is caused by mixing system installed spring and downloaded spring engine.

i.e. apt-get remove spring possible fixes this crash.

**Comment by abma** [comment]
please retry with current springlobby version (currently 0.263) and post springlobby.log when it still crashes.
