### ISSUE TITLE
game-specific lua AIs are sometimes missing from the "add bot" list

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#808]
game-specific lua AIs are sometimes missing from the "add bot" list, both on single player menu or on multiplayer battle rooms. 

Seems it's more likely to happen after changing engine or game selection.

Often I need to use "reload maps/games" as a workaround.

**Comment by springraaar** [comment]
this still happens on 0.261

**Comment by abma** [comment]
which game?

very likely they are missing because of lua errors in game.

can you post springlobby.log when this happened please?

**Comment by springraaar** [comment]
Metal Factions v0.991. 3 MFAI entries should show up in the list.

How can it be lua errors? If i use "reload maps/games" then the AIs show up. Game-side lua errors should cause the issue to happen every time (right?)

**Comment by specing** [comment]
Got this today, but cannot reproduce it again. And yes it was after engine change.

**Comment by abma** [comment]
not sure, but very likely the engine switch still has some issues: in some cases it loads stuff before unitsync is loaded. then empty stuff is returned, in this case an empty ai list.

**Comment by springraaar** [comment]
it happened again here on 0.264-78-g4b.. I think i had engine selected after starting the lobby, then choose map and game, then add ai and....

![sl_luaai_missing](https://user-images.githubusercontent.com/11828472/44221575-d0bd9400-a179-11e8-8ecf-e9361f49ea6a.jpg)

MFAI are missing

**Comment by abma** [comment]
please retest with springlobby 0.265: if it still fails, please reopen and with springlobby.log containing the problem.
