### ISSUE TITLE
unsynced on battle room despite having downloaded the resource

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#809]
SL 0.260.

I joined the battle room for BA 10.02, apparently the game was downloaded, but i remained unsynced. 

Using reload maps/games and restarting the lobby didn't fix it.

"C:\Users\Rui\Documents\My Games\Spring\cache\104rel-\ArchiveCache12.lua" had the reference to the BA 10.02

but the battle room's engine version was 104.0.1.something maintenance, and "C:\Users\Rui\Documents\My Games\Spring\cache\104dev-maintenance\ArchiveCache12.lua" didn't have the reference to BA 10.02.

Trying to download it again by rejoining the room or by using the downloads > search option didn't work.

What worked was removing "C:\Users\Rui\Documents\My Games\Spring\cache\104dev-maintenance\ArchiveCache12.lua" and rejoining the battle room (after which the archivecache12.lua for the dev-maintenance was regenerated).

**Comment by abma** [comment]
springlobby.log please.

it looks like the wrong unitsync was selected for some reason / switch to 104.0.1... failed.

**Comment by springraaar** [comment]
now the issue is solved, I'm not sure if the springlobby.log contains what you want, but here it is

[springlobby_fail_sync.log](https://github.com/springlobby/springlobby/files/1592471/springlobby_fail_sync.log)

**Comment by abma** [comment]
very likely this change fixes it:

https://github.com/spring/spring/commit/cb383dbd844ec900aaad1368f40b258a3c2e6618

**Comment by abma** [comment]
...as long as 104.0 + multiple branches with base content changes aren't mixed again.

**Comment by springraaar** [comment]
it happened again on the spring 1944 room. It's using 103.0 engine.

In that case the archivecache lua file i had to delete before rejoining the room was not inside "C:\Users\Rui\Documents\My Games\Spring\cache\103rel-\", but was the "C:\Users\Rui\Documents\My Games\Spring\cache\ArchiveCache10.lua"

**Comment by abma** [comment]
are you switching engine via settings or in the singleplayer tab when beeing in a battleroom?

i never had this issue.

**Comment by springraaar** [comment]
here's the log for today

[springlobby_fail_sync2.log](https://github.com/springlobby/springlobby/files/1593942/springlobby_fail_sync2.log)

I think i just joined the room and downloaded without touching the single player engine selector, then rejoined when i saw it didn't make me show up as "synced".

Sometimes users start single player games to check stuff while they're idling in battle rooms for other games and engine versions.

Also, the user may hop between rooms with different engine versions and resource dependencies before the downloads finish. That shouldn't be a problem.

**Comment by abma** [comment]
are you sure the download was finished?

**Comment by springraaar** [comment]
apparently so.

This happened again on SL 0.263, on the s44 game room, it'd download, but then it remained unsynced until i removed the archivecache10.lua and restarted the lobby (room used engine 103.0)

**Comment by abma** [comment]
then springlobby.log please when it happens!
