### ISSUE TITLE
Springlobby Register/Login Crash

### ISSUE THREAD

**Issue by AkagiShiroe** [springlobby/springlobby#810]
![log](https://user-images.githubusercontent.com/14356240/34455384-7cdc584c-edc1-11e7-9c83-d30fdc2b9fb9.png)
log doesn't give anything, just like that.. crash

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/25c658aa5182aa07d9ebcd33336c6b061f5bfd15
