### ISSUE TITLE
- engine spring xxx is missing

### ISSUE THREAD

**Issue by tuxutku** [springlobby/springlobby#812]
although i have spring engine 103 and can play single player and multiplayer, i can't watch the replay of the game i play, gives 
<pre>
2018-01-01 19:26:37.460 Message /home/utku/Programlar/springlobby-0.261/src/gui/playback/playbacktab.cpp:260 Watching replay 3 
2018-01-01 19:26:37.461 Message /home/utku/Programlar/springlobby-0.261/src/gui/customdialogs.cpp:83 Content is required to play. Should it be downloaded?
- engine spring 103

2018-01-01 19:26:41.921 Message /home/utku/Programlar/springlobby-0.261/src/gui/customdialogs.cpp:83 Failed to download selected item.
</pre>
error at springlobby.log
Here is the full log:
[springlobby.log](https://github.com/springlobby/springlobby/files/1596212/springlobby.log)
More information:
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ ls -l /home/utku/.spring/engine
total 50368
drwxr-xr-x 9 utku utku     4096 Dec 31 17:39  100.0
drwxr-xr-x 9 utku utku     4096 Nov 11 14:40  103.0
drwxr-xr-x 8 utku utku     4096 Nov 11 14:33  104.0
drwxr-xr-x 9 utku utku     4096 Dec 18 20:26 '104.0.1-104-g2135e2e maintenance'
-rw-r--r-- 1 utku utku 13142276 Dec 31 17:39  spring_100.0_minimal-portable-linux64-static.7z
-rw-r--r-- 1 utku utku 13182122 Nov 11 14:40  spring_103.0_minimal-portable-linux64-static.7z
-rw-r--r-- 1 utku utku 12601756 Nov 11 14:33  spring_104.0_minimal-portable-linux64-static.7z
-rw-r--r-- 1 utku utku 12624269 Dec 18 20:26  spring_{maintenance}104.0.1-104-g2135e2e_minimal-portable-linux64-static.7z
</pre>
Here is the files from /home/utku/.springlobby/:
[script.txt](https://github.com/springlobby/springlobby/files/1596214/script.txt)

springlobby.conf:
<pre>
ResetLayout=0
[General]
LanguageID=0
SettingsVersion=32
CacheVersion=15
firstrun=0
ParallelHTTPCount=3
WebBrowserPath=
WebBrowserUseDefault=1
AutoUpdate=1
CompletionMethod=2
ClientPort=0
LastUpdateCheck=1514821417
UpdateChannel=release
LocalePath=/usr/local/share/locale
[Spring]
DownloadDir=/home/utku/.spring/
DefaultName=Player
CurrentIndex=100.0
Safemode=0
[Spring/Paths]
[Spring/Paths/100.0]
SpringBinPath=/home/utku/.spring/engine/100.0/spring
UnitSyncPath=/home/utku/.spring/engine/100.0/libunitsync.so
SpringBundlePath=/home/utku/.spring/engine/100.0
[Spring/Paths/104.0.1-104-g2135e2e\ maintenance]
SpringBinPath=/home/utku/.spring/engine/104.0.1-104-g2135e2e maintenance/spring
UnitSyncPath=/home/utku/.spring/engine/104.0.1-104-g2135e2e maintenance/libunitsync.so
SpringBundlePath=/home/utku/.spring/engine/104.0.1-104-g2135e2e maintenance
[Spring/Paths/103.0]
SpringBinPath=/home/utku/.spring/engine/103.0/spring
UnitSyncPath=/home/utku/.spring/engine/103.0/libunitsync.so
SpringBundlePath=/home/utku/.spring/engine/103.0
[Spring/Paths/104.0]
SpringBinPath=/home/utku/.spring/engine/104.0/spring
UnitSyncPath=/home/utku/.spring/engine/104.0/libunitsync.so
SpringBundlePath=/home/utku/.spring/engine/104.0
[Server]
Default=Official server
Autoconnect=1
ExitMessage=Using http://springlobby.info/
[Server/Servers]
[Server/Servers/Official\ server]
Host=lobby.springrts.com
Port=8200
TLS=1
Certificate=0124dc0f4295b401a2d81ade3dc81b7a467eb9a70b0a4912b5e15fede735fe73
Nick=tuxutku
Pass=qwerty1230456
savepass=1
[Server/Servers/Test\ server]
Host=lobby.springrts.com
Port=7000
TLS=1
Certificate=bafee3142009baa105ade65b0f712ca5fcf30de8e91664a8825e0185a609277c
[Channels]
[Channels/AutoJoin]
[Channels/AutoJoin/Channel0]
Name=newbies
Password=
[Channels/DisplayJoinLeave]
BATTLE=1
chatpanel-server=0
newbies=0
chatpanel-pm-OverKillHost1=1
chatpanel-pm-\[PinK\]pta\[Q___Q\]=1
chatpanel-pm-\[PinK\]triton=1
[Channels/newbies]
lastid=342119
[GUI]
CloseOnAll=0
ShowPromotions=1
AutoloadedChatlogLinesCount=10
SplitBRoomHorizontally=1
UseTabIcons=1
ShowTooltips=1
Editor=
StartTab=3
UseNotificationPopups=1
NotificationPopupPosition=0
NotificationPopupDisplayTime=5
NotificationPopupDisableIngame=1
[GUI/MAINWINDOW]
left=0
top=0
height=689
width=1280
maximized=1
[GUI/ColumnWidths]
[GUI/ColumnWidths/BattleDataViewCtrl_BattleList]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
[GUI/ColumnWidths/NickDataViewCtrl_BattleListTab]
0=0
1=0
2=0
3=0
[GUI/ColumnWidths/BattleroomDataViewCtrl_Battleroom]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
[GUI/ColumnWidths/replays_dataview]
0=162
1=174
2=160
3=77
4=85
5=79
6=76
7=451
[GUI/ColumnWidths/playback_battleroom_view]
0=73
1=80
2=78
3=73
4=82
5=63
6=187
7=84
8=65
9=54
10=132
[GUI/ColumnWidths/DownloadDataViewCtrl_MainDownloadTab]
0=67
1=73
2=89
3=100
4=55
5=880
[GUI/ColumnWidths/ChannelChooser_ChannelListView]
0=0
1=0
2=0
[GUI/ColumnWidths/NickDataViewCtrl_ChatPanel]
0=0
1=0
2=0
3=0
[GUI/ColumnWidths/ContentDownloadDialog_ContentSearchResultView]
0=249
1=80
2=119
3=74
4=121
[GUI/ColumnVisibilities]
[GUI/ColumnVisibilities/BattleDataViewCtrl_BattleList]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
[GUI/ColumnVisibilities/NickDataViewCtrl_BattleListTab]
0=0
1=0
2=0
3=0
[GUI/ColumnVisibilities/BattleroomDataViewCtrl_Battleroom]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
[GUI/ColumnVisibilities/replays_dataview]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
[GUI/ColumnVisibilities/playback_battleroom_view]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
[GUI/ColumnVisibilities/DownloadDataViewCtrl_MainDownloadTab]
0=0
1=0
2=0
3=0
4=0
5=0
[GUI/ColumnVisibilities/ChannelChooser_ChannelListView]
0=0
1=0
2=0
[GUI/ColumnVisibilities/NickDataViewCtrl_ChatPanel]
0=0
1=0
2=0
3=0
[GUI/ColumnVisibilities/ContentDownloadDialog_ContentSearchResultView]
0=0
1=0
2=0
3=0
4=0
[GUI/CHANNELCHOOSER]
left=0
top=0
height=400
width=470
maximized=0
[GUI/MapSelector]
left=225
top=89
height=511
width=830
maximized=0
HorizontalSortorder=0
VerticalSortorder=0
SelectionFollowsMouse=0
HorizontalSortkeyIndex=0
VerticalSortkeyIndex=0
[GUI/CONTENTDIALOG]
left=196
top=221
height=400
width=670
maximized=0
[GUI/preferences]
left=4
top=69
height=620
width=1055
maximized=0
[GUI/SETTINGSFRAME]
left=151
top=33
height=670
width=1055
maximized=0
[GUI/ADDBOTDIALOG]
left=454
top=137
height=525
width=456
maximized=0
[GUI/AUI]
lastperspective_name=
mainfunctabs=02bd2cc05a06f655000c4af300000002=0,1,2,3,*4,5@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=640;besth=305;minw=640;minh=305;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02bd2cc05a06f655000c4af300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainsingleplayertab=02b34e605a06f655000bac9600000002=*0,1,2@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=633;besth=276;minw=633;minh=276;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02b34e605a06f655000bac9600000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainjoinbattletab=02a805405a06f655000a48e300000002=*0,1,2,3@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=633;besth=276;minw=633;minh=276;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02a805405a06f655000a48e300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
[GUI/AUI/SpringLobby-default]
mainsingleplayertab=02b34e605a06f655000bac9600000002=*0,1,2@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=673;besth=326;minw=673;minh=326;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02b34e605a06f655000bac9600000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainjoinbattletab=02a805405a06f655000a48e300000002=*0,1,2,3@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=673;besth=326;minw=673;minh=326;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02a805405a06f655000a48e300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainfunctabs=02bd2cc05a06f655000c4af300000002=*0,1,2,3,4,5@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=680;besth=355;minw=680;minh=355;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02bd2cc05a06f655000c4af300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
[GUI/AUI/_battle]
mainsingleplayertab=02b34e605a06f655000bac9600000002=*0,1,2@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=673;besth=300;minw=673;minh=300;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02b34e605a06f655000bac9600000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainjoinbattletab=02a805405a06f655000a48e300000002=0,1,*2,3@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=673;besth=300;minw=673;minh=300;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02a805405a06f655000a48e300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
mainfunctabs=02bd2cc05a06f655000c4af300000002=*0,1,2,3,4,5@layout2|name=dummy;caption=;state=2098174;dir=3;layer=0;row=0;pos=0;prop=100000;bestw=680;besth=329;minw=680;minh=329;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=02bd2cc05a06f655000c4af300000002;caption=;state=2098172;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=200;besth=200;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|
[Chat]
HistoryLinesLenght=1000
UseIrcColors=1
Font=Sans 8
HighlightedWords=tuxutku;
PMSound=1
BroadcastEverywhere=1
ReqAttOnHighlight=0
[Chat/Colour]
JoinPart=rgb(66, 204, 66)
Mine=rgb(138, 138, 138)
Highlight=rgb(255, 0, 0)
Error=rgb(128, 0, 0)
Background=rgb(255, 255, 255)
Normal=rgb(0, 0, 0)
Server=rgb(0, 80, 128)
Time=rgb(100, 100, 140)
Action=rgb(230, 0, 255)
Notification=rgb(255, 40, 40)
Client=rgb(20, 200, 25)
[BattleDataViewCtrl_BattleList]
sorting_column=8
sorting_order=0
[NickDataViewCtrl_BattleListTab]
sorting_column=-1
sorting_order=1
[BattleFilter]
lastprofile=default
Active=0
[BattleFilter/default]
description=
host=
map=
map_show=0
maxplayer=0
maxplayer_mode==
mod=
mod_show=0
player_mode==
player_num=0
rank=0
rank_mode=<
spectator=0
spectator_mode==
status_full=0
status_locked=0
status_open=0
status_passworded=0
status_start=0
highlighted_only=0
[BattleListTab]
ShowExtendedInfos=1
[BattleroomDataViewCtrl_Battleroom]
sorting_column=-1
sorting_order=1
[ChatLog]
chatlog_enable=1
[Hosting]
LastAutoLock=1
AutoAnnounceDescription=0
AutoSpectTime=0
AutoControl=0
AutoStart=0
MyLastColour=#FFFF00
MyLastBattleId=2057
MyLastScriptPassword=05e1f8a4
[Hosting/ModDefaultPreset]
Balanced\ Annihilation\ V9.46=
Balanced\ Annihilation\ test-8322-f3064f8=
Planet\ Annihilation\ v3.99=
[BattleRoomTab]
PlayerPanelSashPosition=240
[replays_dataview]
sorting_column=-1
sorting_order=1
[playback_battleroom_view]
sorting_column=-1
sorting_order=1
[ReplayFilter]
lastprofile=default
[ReplayFilter/default]
duration=
map=
map_show=0
filesize=
filesize_mode=>
duration_mode=>
mod=
mod_show=0
player_mode==
player_num=1
[DownloadDataViewCtrl_MainDownloadTab]
sorting_column=-1
sorting_order=1
[ChannelChooser_ChannelListView]
sorting_column=-1
sorting_order=1
[NickDataViewCtrl_ChatPanel]
sorting_column=-1
sorting_order=1
[Groups]
[Groups/Default]
[Groups/Default/Opts]
HLColor=#FF0000
[Groups/Default/Opts/ActionsList]
none=1
highlight=0
notify_login=0
ignore_chat=0
ignore_pm=0
autokick=0
notify_hosted=0
notify_status=0
[Groups/Ignore\ PM]
[Groups/Ignore\ PM/Opts]
HLColor=#FF0000
[Groups/Ignore\ PM/Opts/ActionsList]
none=1
ignore_pm=1
highlight=0
notify_login=0
ignore_chat=0
autokick=0
notify_hosted=0
notify_status=0
[Groups/Ignore\ chat]
[Groups/Ignore\ chat/Opts]
HLColor=#FF0000
[Groups/Ignore\ chat/Opts/ActionsList]
none=1
ignore_chat=1
highlight=0
notify_login=0
ignore_pm=0
autokick=0
notify_hosted=0
notify_status=0
[Groups/Battle\ Autokick]
[Groups/Battle\ Autokick/Opts]
HLColor=#FF0000
[Groups/Battle\ Autokick/Opts/ActionsList]
none=1
autokick=1
highlight=0
notify_login=0
ignore_chat=0
ignore_pm=0
notify_hosted=0
notify_status=0
[Groups/Friends]
[Groups/Friends/Opts]
HLColor=#0000FF
[Groups/Friends/Opts/ActionsList]
none=1
highlight=1
notify_login=1
notify_hosted=1
ignore_chat=0
ignore_pm=0
autokick=0
notify_status=0
[Channel]
bridgebot=TIZBOT
[ContentDownloadDialog_ContentSearchResultView]
sorting_column=-1
sorting_order=1
[SpringSettings]
mode=5000
disableWarning=0
[Battle]
[Battle/Sides]
Balanced\ Annihilation\ V9.46=0
Balanced\ Annihilation\ test-8322-f3064f8=0
Planet\ Annihilation\ v3.99=0
[SinglePlayer]
LastAI=KAIK 0.13
</pre>

**Comment by springraaar** [comment]
I have the same issue.

I've just played a game using engine 104.0 but after the game ended i went to the replays section to try to see it and i got the same error.

It prompts to download, but if you say yes, it fails.

It seems to happen to all replays, even old ones, regardless of the spring version.

[springlobby_0261_engine104_missing_fail.log](https://github.com/springlobby/springlobby/files/1596384/springlobby_0261_engine104_missing_fail.log)

**Comment by abma** [comment]
thanks for reporting!

should be fixed in the next version.
