### ISSUE TITLE
wxDataViewItemAttr::SetBackgroundColour is not portable

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#816]
From http://docs.wxwidgets.org/trunk/classwx_data_view_item_attr.html#ae52c06a3fbd22c7b3f6c9310d9fef6be

> Currently this attribute is only supported in the generic version of wxDataViewCtrl and ignored by the native GTK+ and OS X implementations.

Result is that setting the background does not work for me (wxGTK). However, something can colour the background as selecting a row colours it blue and a workaround is thus possible. This blocks at least #761 and among others causes user lists to be rather useless for e.g. finding friends in the battlelist.

**Comment by abma** [comment]
> as selecting a row colours it blue and a workaround is thus possible

imo a wrong assumption. wxwidgets (tries) to use the native gui implementations of controls: if the function isn't available there we are out of luck. the color change when selecting a row works out of the box, afaik springlobby has no working code which changes the background when using wxwidgets with gtk.

**Comment by abma** [comment]
-> an upstream bug report should be created / patch send to wxwidgets

**Comment by specing** [comment]
This is documented at upstream and they don't seem to mind having this bug/flaw/whatever-you-name-it.
There is also a dead forum thread about it and a bug that was opened about this but then closed by OP a month later without any upstream response.

**Comment by abma** [comment]
links please

**Comment by Usaga** [comment]
@specing I also had seen such things caused by "platform-native" nature of wxWidgets. And also asked devs to do something with that. No luck. If this is bug, they will told you to fix this by yourself and send patch\pull request. If it is by desing - make your own control, derive from existing on, and implement needed things by yourself.

I did it a couple of times, other springlobby devs did it before. Ther's no other way, unfortunately. Sorry.

**Comment by specing** [comment]
@Usaga So ... workaround with a custom dataview renderer? Or just port SL to QT? :D 

@abma https://forums.wxwidgets.org/viewtopic.php?f=1&t=25760&p=110220&hilit=SetBackgroundColour#p110220
http://trac.wxwidgets.org/ticket/11297

**Comment by Usaga** [comment]
@specing make your own renderer implementation. It's much cheaper (in terms of needed time) then porting entire application to Qt.

**Comment by abma** [comment]
as a lot of people are color blind i wouldn't focus on colors... IMHO its not worth the time. An own renderer will just cause trouble / problems in the future.

better change/implement it upstream in wxwidgets.

**Comment by specing** [comment]
@Usaga it was a joke (for now)

I don't think there are many colour blind people among our user base. I also can't fix (or have them fix it) it in wxwidgets as

1. wxwidget trac registration mail is nowhere to be found
2. no upstream response to that ticket
3. upstream themselves documented this as not working
4. their IRC channel is dead
5. the forum post on this topic also got no response
6. this issue is now at least 10 years old
7. upstream doesen't seem to care
8. ...

that joke about QT is looking less and less like a joke and more like unfortunate reality.

**Comment by abma** [comment]
i don't see anybody fixing / implementing this on springlobby side...

**Comment by specing** [comment]
Thats right, I'm fully transparent (and waiting on upstream, mostly).
