### ISSUE TITLE
connecting to "unknown" lobby server doesn't work

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#828]
for some reason the stored fingerprint isn't used when connecting: connection is dropped then.

**Comment by abma** [comment]
to reproduce:

start uberserver:

./server.py

try to register at localhost:8200

fingerprint is detected + stored. on reconnect it isn't used.

**Comment by silentwings** [comment]
This isn't fixed (for me) in 0.265

server.log https://pastebin.com/0NTVcbX0
springlobby.log https://pastebin.com/4B17sGx9

**Comment by silentwings** [comment]
There is something strange though. SL will not connect to my local uberserver when I manually open the "login" dialogue, enter my username/pw and press "OK". Doing that always generates the errors above; I am always asked to re-trust the fingerprint and get disconnected immediately after doing so.

However, SL *will* connect to my local uberserver if it is trying to automatically re-connect, without the login dialogue box being open or any input from me -- after the above has tried and failed.

**Comment by silentwings** [comment]
This is still present in 0.266.
