### ISSUE TITLE
idea: provide the option for springlobby to generate a random password on connect

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#830]
1/2 add hide password/show password toggle
2/2 add third toggle option that generates a random password upon selecting it

**Comment by specing** [comment]
actually, why are we even using passwords and bothering newbies with them?

**Comment by specing** [comment]
I have some preliminary code, but I haven't yet figured out how to switch between hide/show in a textbox

Github does not support .patch files wtf....
see https://github.com/spring1944/springlobby

**Comment by abma** [comment]
how to store the password in a save manner?

IMHO the user must handle safe password storage.

**Comment by specing** [comment]
SpringLobby must be fixed to not eat passwords.

**Comment by abma** [comment]
requires https://github.com/spring/uberserver/issues/8 at least IMHO

**Comment by abma** [comment]
> SpringLobby must be fixed such that it no longer eats passwords.

what does this mean? springlobby doesn't "eat" or delete passwords.

**Comment by specing** [comment]
it was in response to "how to store the password in a save manner?".

**Comment by specing** [comment]
I'm now reasonably certain that registrations should be dropped entirely from lobby clients, just have them open a web browser to a common registration web site that also serves captchas and deals with email and whatnot. The whole recoveraccount, email and resulting lobby protocol back&forth is imo overly complex for something that existing solutions can serve on the web.

**Comment by abma** [comment]
"no"
