### ISSUE TITLE
crashing when after lobby start new game while loading

### ISSUE THREAD

**Issue by cookins** [springlobby/springlobby#831]
hey
just installed springlobby (played some years before).
decided to try 1944 game... so started map with 3 bots and in loading screen it crash with next windows:
![crash1](https://user-images.githubusercontent.com/7893051/36706053-cef84c26-1b70-11e8-8366-54b515c17cdc.jpg)
![crash1-2](https://user-images.githubusercontent.com/7893051/36706056-d0cbb8f8-1b70-11e8-9c77-26490eff8fc2.jpg)
K-zero, balanced annihilation works fine. what problem is here?

**Comment by cookins** [comment]
all vredist last.

**Comment by abma** [comment]
this bug tracker is about springlobby not the spring engine which crashes here.

the bug tracker of the spring engine is https://springrts.com/mantis/

please provide infolog.txt when reporting bugs there: usually it already has some errors which leads to the cause of the problem.

are the bots compatible to spring 1944? are you using a recent version of the spring engine? are your gfx drivers up to date?

**Comment by cookins** [comment]
ah sorry
