### ISSUE TITLE
please remove the "A battle with no opponents is not a battle at all" message

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#832]
1) It is irritating for devs, who have good reason to start and repeated re-start a battle with no other players/bots present.
2) Most, if not all, of the bots don't work anyway.
3) Not all cases (e.g. standalone mission sdzs) need the startscript to provide opponents.

**Comment by specing** [comment]
1. You can host such a battle in singleplayer.
2. #817 will solve this
3. I see. But can newbies start such a mission and are they supposed to start it online?

I guess we could open a dialog that would offer to add a bot if no opponent is present.

**Comment by specing** [comment]
Is there a good reason to allow opponent-less battles? If so, I can push fix.

**Comment by abma** [comment]
is there a reason for keeping this message?

IMHO there is no clear reason: remove it -> KISS

**Comment by specing** [comment]
This message is to prevent newbies to start a battle with no opponents and then wondering why nothing is happening.

**Comment by silentwings** [comment]
1. Using the singleplayer tab is a worse interface, and would not be suitable for cases where devs were trying to test elements related to the GameSetup phase of online play. Adding a NullAI is not a solution, as is made clear by the presence of item 3. 
2. #817 will partially workaround, but it certainly won't solve it the issue that most bots are broken.
3. In some situations, yes, people are expected to do this. There is no particular reason why they would be newbies or otherwise.  

| This message is to prevent newbies from starting a battle with no opponents and then wondering why nothing is happening.
If it a problem for a *game* that this happens, the *game* can provide an error message and an option to Spring.Reload/Restart with a bot, or simply return to lobby and add bot. The lobby is unable to determine what the best course of action is, and should not interefere.

**Comment by specing** [comment]
Alright, I will add a "start anyway" option.

**Comment by silentwings** [comment]
I think you are missing the point - there should not be a warning message, or a warning, since the lobby has no real reason to think that anything is wrong.

**Comment by silentwings** [comment]
Thank you!

(In such a case, thanks to the existence of Spring.Reload, the only excuse a game dev has for expecting user to exit/restart via lobby would be their own laziness!)

**Comment by PtaQQ** [comment]
How about Don't show this message again checkbox?
