### ISSUE TITLE
option to limit amount of demos stored to... 100?

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#835]
cause it eats drive space and more importantly springlobby gets slow when you have hundreds of demos

**Comment by silentwings** [comment]
+1

**Comment by specing** [comment]
This problem only occurs to people that have played for a while (therefore not newbies) and who can be reasonably expected to know how to delete demos and/or be able to ask for how to do it.
Additionally, the only way to properly implement this would be via fixing the loading code to not freeze, e.g. #776 #619 #556 and can as such be marked as a duplicate of those bugs and a non-issue.

**Comment by silentwings** [comment]
I would have thought a setting to auto-delete all demos older than X days, with default X=60, would be the most obvious way and easy to deal with this.

**Comment by specing** [comment]
I have very bad experience with software (Bash) that auto-removes history older than XYZ. Even if you set it to infinite it inevitably ends up eating your history. I will never do this in my software.

**Comment by silentwings** [comment]
Fwiw, in my coding, I have a principle of not imposing my personal experiences on my users.

**Comment by specing** [comment]
I'm not saying deleting demos should not be implemented, I'm simply saying this particular way of implementing it is bad.

**Comment by silentwings** [comment]
In case it is not already clear, I rate the justification you gave for that viewpoint as poor.

**Comment by abma** [comment]
slowdown is fixed, so IMHO this is no real issue any more.
