### ISSUE TITLE
Springlobby does not connect to the Server on Win10

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#838]
Springlobby has been cleared in the firewall, is run with administrator rights - but will not connect to the server. No error is thrown, just a  silent bounce back to the login menue.

[springlobby.log](https://github.com/springlobby/springlobby/files/1803154/springlobby.log)

**Comment by abma** [comment]
does cmd.exe -> ping lobby.springrts.com work?

**Comment by abma** [comment]
locks for me like a local problem, i.e. some personal firewall / antivirus blocks the the connection attemp.

**Comment by PicassoCT** [comment]
ping does work flawlessly-  i assumed its the firewall myself- thus deactivated it for a test. Did not help. There is a rule all by its own for springlobby in and out.
Also tryied several variants of backwards compatability.
No success there either.

**Comment by PicassoCT** [comment]
PS: Antivirus is deactivated. Snakeoil is bad for the pistons.

**Comment by abma** [comment]
does telnet lobby.springrts.com 8200 work?

very likely telnet needs to be installed first on windows :-|

**Comment by abma** [comment]
should look like this:

telnet lobby.springrts.com 8200
Trying 78.46.100.157...
Connected to springrts.com.
Escape character is '^]'.
TASServer 0.36 104.0 8201 0

**Comment by PicassoCT** [comment]
Network Error Connection refused- sounds local allright

**Comment by abma** [comment]
news on this?

**Comment by PicassoCT** [comment]
Hi abma. The issue seemed to be connection related.. As in the provider filtering the packets out..
Im in a hotel now and the same system without further changes connects flawless.
it sounds wild but this is my best guess.
The holiday houses web was a sign in solution from https://www.easy-internet.co.uk/.

Sorry to have bothered you.

**Comment by abma** [comment]
no worries, thanks for the feedback!
