### ISSUE TITLE
Battleroom toolbar is displayed incorrectly

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#841]
See the screenshot. 
Environment: KDE, GTK theme: Breeze
[Screenshot](https://yadi.sk/i/P2Gaa9NV3TT2Xu)
version 0.264

**Comment by specing** [comment]
Is the whole toolbar full to its end or is there still some free space left?

**Comment by spike-spb** [comment]
https://yadi.sk/d/GrRYZQND3UCEcH

**Comment by spike-spb** [comment]
I've built it in Debian to check the toolkit, all ok there.. so the problem is in wx in my OS.

**Comment by specing** [comment]
Which version and which backend? wxGTK? Mine is also broken (both 2.8 something and 3.0.3), but not so obviously.

**Comment by abma** [comment]
current version of springlobby requires wxGTK >= 3.0

https://github.com/springlobby/springlobby/blob/master/src/CMakeLists.txt#L58

**Comment by spike-spb** [comment]
wxGTK is 3.0 in my case
