### ISSUE TITLE
crash when download game clicked

### ISSUE THREAD

**Issue by spike-spb** [springlobby/springlobby#846]
program version 0.264

gdb shows:

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd34a7982 in boost::object_cache<boost::re_detail::cpp_regex_traits_base<char>, boost::re_detail::cpp_regex_traits_implementation<char> >::do_get(boost::re_detail::cpp_regex_traits_base<char> const&, unsigned long) ()
   from /home/jetbird/.spring/engine/104.0.1-138-gf19449b maintenance/libunitsync.so

**Comment by spike-spb** [comment]
can reproduce in revision "4a595bd821a93895d5eac5eebd7636d78c594854"

**Comment by spike-spb** [comment]
core dump: https://yadi.sk/d/gIINDoHc3Txw5c

**Comment by spike-spb** [comment]
binary: 
[springlobby.tar.gz](https://github.com/springlobby/springlobby/files/1866427/springlobby.tar.gz)

**Comment by spike-spb** [comment]
problem solved after removing ~/.spring directory

**Comment by abma** [comment]
see #848

**Comment by spike-spb** [comment]
I just wanted to get some more information about this bug.
There is a notice about Spring <= 101 that should be blocked.
But I did not download those versions of Spring. Versions that I've downloaded:
Spring v103, v104-dev..
And lobby was still playable for some time. Then it began to crash on game download click.
Is this really connected with "Spring <= 101 versions" problem?

**Comment by abma** [comment]
springlobby.log from such a crash please!

**Comment by spike-spb** [comment]
https://yadi.sk/d/fktKZMma3UFkQP

**Comment by spike-spb** [comment]
Now it crashes when you try to enter the battle (in battleroom).
Deleting ~/.spring/engine/* helps.

**Comment by spike-spb** [comment]
Bug happened after I had downloaded 104-dev.. engine.

**Comment by abma** [comment]
for cleaniness, see #846 (is very likely the same crash)

**Comment by spike-spb** [comment]
#846 is the same bug :)

**Comment by abma** [comment]
sorry, i meant #855

**Comment by spike-spb** [comment]
Yes, it looks like.
