### ISSUE TITLE
block usage of spring <=101.0

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#848]
see #707
https://springrts.com/mantis/view.php?id=5050 and https://github.com/springlobby/springlobby/commit/4a595bd821a93895d5eac5eebd7636d78c594854

**Comment by anmeldekram** [comment]
https://github.com/springlobby/springlobby/issues/707#issuecomment-231070665

> Hmm, problem occurs only if you use external repository, for example getdeb.

Is this true? The problem only occurs for users who mix installs with external unofficial sources?
Would be sad if all other users with no such problems will be blocked too, many are playing just fine.

**Comment by spike-spb** [comment]
I have downloaded only spring v103 and v104.0.1.... versions (and no 101.0).

**Comment by specing** [comment]
From my understanding, this whole issue is due to C++ ABI changes (101, 98,.. were compiled with old ABI, people try to use them on new systems)? If so, wouldn't a better choice be to recompile old major engine versions with the new ABI?

**Comment by abma** [comment]
>  If so, wouldn't a better choice be to recompile old major engine versions with the new ABI?

i'm pretty sure this won't happen :-|

**Comment by specing** [comment]
Who can make it happen?

**Comment by abma** [comment]
someone with to many computing power / memory / disk space and time and a lot of knowledge about gentoo/cross-compile/static-compile

its really not worth the time: old spring versions have A LOT more bugs.

a lot more useful stuff could be done with the resources.

**Comment by specing** [comment]
compiling those 5 major versions wouldn't take that much computing power / memory / disk space or time. Where are the builder docs? Can you force the existing machinery it to recompile those?

**Comment by specing** [comment]
Hmm, would it be possible to compile SL such that it can link with both ABIs? AFAIK the system C++ library should contain both symbol sets.

**Comment by abma** [comment]
please stop, its not worth the time.

**Comment by abma** [comment]
@specing: if you want really to fix this problem: make springlobby use lslextract via http/json and add missing functionality to lslextract.

**Comment by silentwings** [comment]
Fyi this will affect the hosts 
[loganberry]Autohost, [durian]Autohost, [semprini]Autohost (XTA) 
[ACE]Synchronous, [ACE]Embleur, [ACE]PitPot (Planet Annihilation/Defense)

It would be good to make an announcement if <=101 is going to be blocked, and give them time to react.

An (default off, perhaps text-file only) config param to "allow and try anyway" with <=101 could be useful for developers of games that get irregular updates.

**Comment by anmeldekram** [comment]
> I guess blocking at uberserver level is cleaner.

It is fault of one client, not server.
Also again: It is possible to use springlobby and engine versions <= 101 without crashes. Only some users are affected by the problem but the "solution" will prevent all users from playing.
A warning or entry in log or so would be better.

**Comment by silentwings** [comment]
This issue will be dealt with server side as part of https://github.com/spring/uberserver/issues/192, and can be closed.
