### ISSUE TITLE
SL crashing on registeration

### ISSUE THREAD

**Issue by PtaQQ** [springlobby/springlobby#853]
Hey, Ive just wanted to make another new account to use for a SL usage tutorial video and it seems to crash every time upon accepting the user agreement. I click accept and windows prompt goes up: Spring Lobby stopped working. 

I'm using Windows 8.1 Pro, 64 bit.
Dunno what else I can provide for you to close down on this issue, is there any logfile for SL?

**Comment by PtaQQ** [comment]
Ah, I forgot to note that it makes no issue with the account - it is created and works, but you have to run SL again.

**Comment by abma** [comment]
>  Dunno what else I can provide for you to close down on this issue, is there any logfile for SL?
https://springrts.com/wiki/Springlobby.log

atm it is overwritten every time you start springlobby: so it would be nice to get the file which contains logs before / the crash

**Comment by abma** [comment]
no feedback -> closing
