### ISSUE TITLE
impossible to watch a downloaded replay

### ISSUE THREAD

**Issue by triton13** [springlobby/springlobby#856]
![anotherbug](https://user-images.githubusercontent.com/28787431/38581304-c5da67b0-3d0c-11e8-853a-f32ef11c5b95.png)

**Comment by triton13** [comment]
I have all engines already, so it should work

**Comment by specing** [comment]
try to remove the uYinxi part (which I assume is not part of the map name. SL relies heavily (too much) on the file name being correct.

**Comment by abma** [comment]
no feedback -> closing
