### ISSUE TITLE
No Executable, No Files

### ISSUE THREAD

**Issue by devlman127** [springlobby/springlobby#861]
The Springlobby installation I got from the gamesdownloads page is completely broken - It does not have any files other than localization, info, and uninstall.

![aaargh](https://user-images.githubusercontent.com/39030234/39674919-09cfe542-5119-11e8-9905-390ef729b17c.png)

**Comment by abma** [comment]
i don't maintain this page / don't have contact ... please report the problem to "gamesdownload"

**Comment by devlman127** [comment]
Where is gamesdownload? I don't see it in the repositories.

**Comment by specing** [comment]
That is what we are wondering as well.
