### ISSUE TITLE
Flatpak distribution

### ISSUE THREAD

**Issue by leotada** [springlobby/springlobby#863]
Please make flatpak installation to distribute on https://flathub.org
https://flatpak.org

**Comment by specing** [comment]
https://xkcd.com/927/

**Comment by abma** [comment]
i don't see me doing this...

https://github.com/nsg/snap-springlobby

**Comment by baracoder** [comment]
It is easier then dealing with ubuntu PPAs. This works: https://github.com/baracoder/com.springrts.springlobby
Would need to rebase on https://github.com/flathub/flathub to get it to flathub.org
Using flatpak could help with "package in distro x is outdated" problems, as flatpaks can be installed on most distros.
