### ISSUE TITLE
"Failed to set up download"

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#867]
I get the following error with (almost) every engine/game download through SL. I can reproduce it on three different machines, one of which was a fresh install, on both Win 7 and 10.
![1](https://user-images.githubusercontent.com/3885930/40273260-f47c92b6-5bb4-11e8-8a3c-1c4fa3268926.png)

After producing this message, the download somtimes (but not always) turns out to work anyway, and trying to download a second time sometimes produces a download that does work.

https://springrts.com/phpbb/viewtopic.php?t=36760#p585875 - I don't know which log files you'd want, happy, let me know.

**Comment by abma** [comment]
already fixed in current development version via bdf3d61751ff29f58006d58ee45be76a447bae78
