### ISSUE TITLE
Make SpringLobby to save files in it's own directory by default instead of

### ISSUE THREAD

**Issue by quantuumsnot** [springlobby/springlobby#868]
... C:\Users\username\Documents\My Games\Spring

Because the directory grows too much on small SSDs

OS: Windows 7 x64

**Comment by specing** [comment]
Which files? You can use symlinks to point subdirectories elsewhere.

**Comment by quantuumsnot** [comment]
All downloaded files - maps, mods, engines

**Comment by abma** [comment]
often springlobby is installed as admin and doesn't have write-access to the install dir.

you can configure the download dir in settings.

IMHO its ok as it is.

**Comment by quantuumsnot** [comment]
So portable version is useless as variant? I always use it

imho hackish suggestions like symlinking directories breaks the user experience

**Comment by abma** [comment]
duplicate of #584:

to avoid future misunderstanding i renamed portable to zip:
https://github.com/springlobby/springlobby-website/commit/6813d9f46f44bddfc899820e39c4ba00d09ca693


(will be applied to the webpage, soon)
