### ISSUE TITLE
Game doesnt start from springlobby with spring version *477 or newer

### ISSUE THREAD

**Issue by fruehling76** [springlobby/springlobby#869]
After i have puplished the Problem here: https://springrts.com/phpbb/viewtopic.php?f=11&t=36864&p=585971#p585971, I was told to publish the following Problem also here on github:

Problem:
Game is not starting from springlobby when spring engine *477 or newer is used.  happend, just seeing the window clock for few second but never leaves the Lobby. spring engine gets not started and infolog not created

System :
- Windows 10 Laptop

i have tried: 
- with springlobby but without Firewall and antivir: no difference - spring not starting
- i tried starting from window cmd line - spring not starting
- i started spring from a file browser (free commander xe) **spring is starting** (also when i start it with the built in cmd line from free commander)

Can someone help me please?

**Comment by specing** [comment]
Please check and post https://springrts.com/wiki/Springlobby.log

**Comment by fruehling76** [comment]
[springlobby.log](https://github.com/springlobby/springlobby/files/2042833/springlobby.log)

**Comment by abma** [comment]
does "C:\Spiele\Spring\engine\104.0.1-151-g11de57d maintenance\spring.exe" exist?

can "C:\Spiele\Spring\engine\104.0.1-151-g11de57d maintenance\spring.exe" be started?

**Comment by abma** [comment]
from springlobby.log:

018-05-22 22:25:05.451 Message build/src/spring.cpp:135  spring call params: C:\Spiele\Spring\engine\104.0.1-151-g11de57d maintenance\spring.exe
2018-05-22 22:25:05.452 Message ld/src/tasserver.cpp:1048 sent: #18 MYSTATUS 17
2018-05-22 22:33:01.002 Message ld/src/tasserver.cpp:1048 sent: #36 MYSTATUS 16
2018-05-22 22:33:01.003 Info    build/src/gui/ui.cpp:652  Exiting with 0

spring was run without error (Exiting with 0)

**Comment by baracoder** [comment]
There could be something useful in `spring.log` or was it `engine.log`?

**Comment by abma** [comment]
https://springrts.com/wiki/Infolog.txt

**Comment by fruehling76** [comment]
Version 104.0.1-151xxx. spring.exe exist and start without Problems. The problems occur with Version 104.0.1-477 and anything that is newer. For every version is also an spring.exe. 

i can make a new springlobby.log because that one i have sent you was older but there should be inside some start fails if i am not wrong -  or does the the logfile only contain the last time when it starts a game?

**Comment by fruehling76** [comment]
this is the latest springlobby log. i tried to start Version 531 this morning
[springlobby.log](https://github.com/springlobby/springlobby/files/2046892/springlobby.log)
 which obviously doesnt work.

**Comment by abma** [comment]
springlobby.log / infolog.txt is always overwritten when you start spring / springlobby.

can you post infolog.txt when spring failed to start?

springlobby.log still doesn't contain an error :-|

**Comment by fruehling76** [comment]
i started Version 104.0.1-531xxx few minutes ago

[infolog.txt](https://github.com/springlobby/springlobby/files/2048115/infolog.txt)
[script.txt](https://github.com/springlobby/springlobby/files/2048116/script.txt)
[springlobby.log](https://github.com/springlobby/springlobby/files/2048117/springlobby.log)

i repeat: version 138 is not a Problem - the Problems start with Version 104.0.1-477 and every version later than that. for me it seams that infolog.txt is not even updated when i am trying to start game from the Lobby.

**Comment by fruehling76** [comment]
the thing with not downlaoding v138 is new. also if i doubt that it have something to do with the programm start i want to try to fix it. 

when i click in the Lobby on download if got following Messages: 
1. failed to download selected item
2. no mirrors found
3. error opening c:\*\* no such file or directory 

what could be the reason?

**Comment by fruehling76** [comment]
PS: infolog.txt is not getting overwritten when spring doesnt start

**Comment by fruehling76** [comment]
this morning i have installed latest spring version v541 from darke engery 7 Server. result is all the same but i got the error message "failed to Setup download" or something like this with that engine. is that error message kind of Standard message of the Lobby or something extraordinary?

**Comment by abma** [comment]
this is a known bug which is fixed in the current development version:
https://github.com/springlobby/springlobby/blob/master/ChangeLog#L6

#862 is a release blocker: i guess i'll disable tls when downloading on windows

**Comment by fruehling76** [comment]
Windows Report when starting spring.exe

Name der fehlerhaften Anwendung: spring.exe, Version: 0.0.0.0, Zeitstempel: 0x00000000
Name des fehlerhaften Moduls: spring.exe, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0x004f4cf3
ID des fehlerhaften Prozesses: 0x9f24
Startzeit der fehlerhaften Anwendung: 0x01d3fe8805ff0fb6
Pfad der fehlerhaften Anwendung: C:\Spiele\Spring\engine\104.0.1-531-gab3f84f maintenance\spring.exe
Pfad des fehlerhaften Moduls: C:\Spiele\Spring\engine\104.0.1-531-gab3f84f maintenance\spring.exe
Berichtskennung: bbd8bec4-4fdc-43cf-b2da-a1d9b4c9b92a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by abma** [comment]
please retest with springlobby 0.265: if it still fails, please reopen and with springlobby.log containing the problem.
