### ISSUE TITLE
Springlobby temporarily "forgot" I had 104.0 engine

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#870]
Springlobby 0.264

I log in, open the single player tab, had engine 99.something selected. I try to change to 104.0 and....couldn't find it?!

It was missing from the list. On the battle list, rooms with engine 104.0 were shown as having X on the engine column, as if I didn't have it.

After I joined the room to trigger its download, error popups show up: 

![imagem](https://user-images.githubusercontent.com/11828472/41886567-ce6ddfb4-78f4-11e8-8576-a87c35fdd749.png)

I couldn't remove the popups and a minute later, the lobby crashed.

After restarting the lobby it showed 104.0 again and worked normally.

**Comment by abma** [comment]
please retest with springlobby 0.265: if it still fails, please reopen and with springlobby.log containing the problem.
