### ISSUE TITLE
Typing bar doesnt scale with text size 

### ISSUE THREAD

**Issue by PtaQQ** [springlobby/springlobby#872]
Hey, I recently switched to a 4k display. It turns out the default font size in SL is a bit too small to be readable, therefore I scaled up the text size with ctrl+scroll, all good. The issue is that the chat bar doesn't scale up with new resolution, so I can only see top parts of the letters I type (see the attached screenie). 

<img width="1920" alt="text size 4k" src="https://user-images.githubusercontent.com/29601271/42641902-eb5dd800-85f5-11e8-95bf-a8f3f4ede596.png">

**Comment by specing** [comment]
I can change chat text size in preferences, but I cannot change input field text size ?_?

**Comment by specing** [comment]
Also an exact duplicate of #763
