### ISSUE TITLE
unable to register new user accounts

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#886]
tested with win 10, SL 0.265
trying to register a new user account on the official server
clicking yes does not allow me to create a new user account; instead i get disconnected

![untitled](https://user-images.githubusercontent.com/3885930/45112413-6af07680-b13f-11e8-980f-cabff9cd319b.png)
afaics the certificate is correct and there is no MITM happening
i can login with my existing accounts without any problems or errors

it was reported in #newbies, i tested it myself a recieved the same error, as above. i gave them a link to sl 0.264 install, and they said that worked fine.

**Comment by silentwings** [comment]
likely related to #828

**Comment by abma** [comment]
next try, thanks for reporting! :)
