### ISSUE TITLE
SL fails to display some minimaps (when map was compiled by SpringMapEdit)

### ISSUE THREAD

**Issue by Fx-Doo** [springlobby/springlobby#888]
The minimap displayed for such maps is all messy: 
https://cdn.discordapp.com/attachments/227361412047962112/488096440464310282/unknown.png
Seems to only happen on minimaps of maps compiled via springmapedit. The issue didnt exist on the other lobbies that i've used in the past (TASClient, WebLobby).
Setting up a minimap file (mini.dds) in mapinfo doesn't help.
Everything works as expected in engine.
One of the map on which this issue happens: https://springfiles.com/spring/spring-maps/two-continents-remake

**Comment by abma** [comment]
https://api.springfiles.com/?springname=Two+Continents+Remake+v3&filename=&tag=&sdp=&images=on&metadata=on&category=
->
https://api.springfiles.com/metadata/4eb4fe7d70711f57e3beafba67e164a4.jpg

not sure what springlobby does different. if i remember right it extracts images not at full resolution when springfiles does full resolution extract + scale.

**Comment by Fx-Doo** [comment]
The metalmaps/heightmaps show fine in springlobby. The issue only affects the texturemap.
Judging from the resulting minimap, it seems possible that the "extracts images not at full resolution" process might be faulty. I can only imagine that extracting not at full res means sampling certain coordinates. If the compiling process is different from the usual one (mother's mapconv vs SpringMapEdit conversion), maybe the sampling is off, giving this result of interlaced bands of textures, that seem to show a z-axis compression, and an alternance of bands from both lowerside and upperside of the map.
I guess the heightmap/metalmap don't go through that kind of sampling process, that would explain their integrity ?

**Comment by abma** [comment]
i have no clue. afaik a similar problem existed with a broken mapconv.

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=11&t=26172

**Comment by abma** [comment]
i have bad news for you:

recompiling the map fixes this.

-> bug in SpringMapEdit

to recompile i used SpringMapConvNG, for decompile:

smfdecompiler -directory . -mapfile Two_Continent.smf

compile:

springMapConvNG  -t texture.png -m metalmap.png  -z typemap.png  -h heightmap.png -minimap minimap.png -features features.txt -o test

**Comment by abma** [comment]
![bildschirmfoto von 2018-09-10 22-17-48](https://user-images.githubusercontent.com/301564/45322055-6a911a80-b547-11e8-8b9d-3dbff6bd5c6b.png)

**Comment by abma** [comment]
i guess it happens how the minimap is scaled, still IMHO the issue are the maps.
