### ISSUE TITLE
login windows not allways is shown correctly

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#889]
![imagen](https://user-images.githubusercontent.com/184088/45584566-58f89b80-b8d6-11e8-8ff1-e52cb46e4e25.png)

make it a bit bigger and it fixes itself

edit: on 0.267

**Comment by abma** [comment]
which desktop environment?

which version of gtk is used?

**Comment by TurBoss** [comment]
GNOME Shell 3.28.3

libgtk-3-0:amd 3.22.30-1ubu amd64
libgtk2.0-0:am 2.24.32-1ubu amd64


´´´
SpringLobby 0.267-10-g1fdbc0127 (unix x64)
Configuration file: /home/turboss/.springlobby/springlobby.conf (writable)
LobbyWriteDir (/home/turboss/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/turboss/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/usr/local/bin/)
	WX: no POSIX: no TRY: no
DownloadDir (/home/turboss/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/turboss/.spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /home/turboss/.spring/engine/104.0.1-743-g9e82927 maintenance/libunitsync.so
Current Spring engine executable: /home/turboss/.spring/engine/104.0.1-743-g9e82927 maintenance/spring
Portable mode: no
Compiled with wxWidgets 3.0.4.0
Global log level: 5 (up to and including Info)
PR-Downloader log level: 5 (up to and including Info)
Started with: 
springlobby 
```

**Comment by TurBoss** [comment]
this is no longer an issue
Thanks!
