### ISSUE TITLE
unhandled exception & other errors when typing LEAVE commands into the server window

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#894]
Trying to leave a channel you are not in, by typing eg. "LEAVE sy2" into the server window causes an unhandled exception.

Also, typing "LEAVE2 sy" into the server window causes SL to send a "LEAVE sy" command to the server, before is also sends the "LEAVE2 sy" command. The same happens for any command written in the form LEAVE***.

Neither should happen - commands typed into the server window should be passed directly on to the server without modification or reaction from SL.

(These bugs showed up while testing a LEAVEFROM command in my local uberserver.)

**Comment by abma** [comment]
without springlobby.log i can't fix the "other errors" as i don't get them

**Comment by silentwings** [comment]
Note sure there is anything useful there, but https://pastebin.com/NcPx6AGR
![untitled](https://user-images.githubusercontent.com/3885930/46583798-f36e7980-ca53-11e8-9c8e-feaa065d64a5.png)

**Comment by abma** [comment]
as this is a generic error message: no.
without springlobby.log, no clue

**Comment by abma** [comment]
OMG, i'm getting old, yes its useful.

maybe fixed by https://github.com/springlobby/springlobby/commit/73d18eaf940d312d9853d446e6d27fa7b6eec93f
