### ISSUE TITLE
ubuntus ppa is outdated

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#895]
http://ppa.launchpad.net/spring/ppa/ubuntu/

missing release for ubuntu 18.04 / bionic

**Comment by abma** [comment]
https://launchpad.net/~spring/+archive/ubuntu/ppa

**Comment by allanlegalstart** [comment]
note that the official repository of ubuntu have a not that old version :)

**Comment by halida** [comment]
ubuntu 18.04 / bionic package is still not there?

**Comment by abma** [comment]
basicly a duplicate of #964

(sorry, i don't maintain the ubuntu packages)
