### ISSUE TITLE
Springlobby accepts no more input after playing a game

### ISSUE THREAD

**Issue by borderbridge** [springlobby/springlobby#896]
Hello there,

i use windwos 10 as a OS.

Since i updated SpringLobby to 0.267 i have the following problem permanently:

SpringLobby works fine until i launch a Game. After returning to the SpringLobby the Lobby does not react to any input. However i can see that the chat is still working. The only solution is to close the lobby and start it again. Even the x (to close the Program in the top bar) is not accepting a mouseclick anymore. So i have to terminate the Lobby otherwhise. 

Is there anything i can do ? This is very annoying. 

Greetings.

**Comment by abma** [comment]
is the problem still present with 0.269?

**Comment by abma** [comment]
(sorry, for the delay, a much more important bug needed to be fixed first)
