### ISSUE TITLE
Map download bug

### ISSUE THREAD

**Issue by krash84** [springlobby/springlobby#901]
Downloads tab should show only one row for downloaded map with 100% and status = completed.

See the bug:
https://yadi.sk/i/XF51yqWtYS_8vg

Map is already downloaded but status < 100%.
And there are 2 rows in the table.

Version: SpringLobby 0.267-21-g1b68db7

**Comment by abma** [comment]
100% should be fixed by:
https://github.com/springlobby/springlobby/commit/91d36692282263221600d91567d5e0601e9af298

two rows basicly are fine, the first line is the access to https://api.springfiles.com/
