### ISSUE TITLE
merge https://framagit.org/specing/springlobby

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#903]
https://framagit.org/specing/springlobby
when its finished

**Comment by abma** [comment]
"<ThinkIRC> I will tell when it is finished."

**Comment by springraaar** [comment]
[19:57:26] <ThinkIRC> you could shorten it to "ThinkSome says its ready"
[19:58:56] <ThinkIRC> And invite him to pay us a visit in here

("here" is the springlobby chat channel on the official server)

**Comment by abma** [comment]
"Rename tabs: Battlelist->Multiplayer, Battleroom->Battle room,
Fedja Beader authored 10 hours ago

Singleplayer->Skirmish"

last commit 10 hours ago doesn't look like its "finished"?

**Comment by abma** [comment]
bah, this will take some time to review :-|

**Comment by abma** [comment]
done, i won't merge changes from there here any more.

still pull requests are mostly welcome.
