### ISSUE TITLE
No updated packages for Debian Stable

### ISSUE THREAD

**Issue by narcisgarcia** [springlobby/springlobby#904]
Today SpringLobby complains about being 0.255 version but 0.267 is available.
What can I do without having to compile software and not breaking other distribution packages?

**Comment by abma** [comment]
try if https://github.com/nsg/snap-springlobby works or upgrade to debian buster:

https://packages.debian.org/buster/springlobby

:-|

**Comment by abma** [comment]
basicly you're requesting something like a PPA for ubuntu. atm this is out of the scope due to lack of manpower. sorry.
(-> contributions welcome)
