### ISSUE TITLE
(springlobby:93): Gtk-CRITICAL **: IA__gtk_tree_view_set_fixed_height_mode: assertion 'gtk_tree_view_column_get_sizing (c) == GTK_TREE_VIEW_COLUMN_FIXED' failed

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#906]
whilst running self compiled SL on ubuntu bash for win10 via xming, so who knows if actually meant to work like that...

**Comment by silentwings** [comment]
SL log https://pastebin.com/YC007Efv

**Comment by neverwin** [comment]
it seems like bugs in wxgtk

**Comment by abma** [comment]
i never saw this error on debian10. i could swear i saw it on debian 9, too, so:

which version of wxgtk are you using?

debian uses wxWidgets 3.0.4.0

**Comment by abma** [comment]
springlobby.log:

"Compiled with wxWidgets 3.0.2.0"

**Comment by silentwings** [comment]
I was building on the Windows Subsystem for Linux, and I this build envir is now dead (it has gcc 7 & I don't want to upgrade gcc yet). So you can close it, likley no one else will ever have this error...

**Comment by abma** [comment]
maybe this message requires a debug build, too.
