### ISSUE TITLE
Springlobby RelayHosts are not working.

### ISSUE THREAD

**Issue by Hexxitfan111** [springlobby/springlobby#908]
![image](https://user-images.githubusercontent.com/35806451/52660114-95034d00-2ec4-11e9-9de0-b3e594a66383.png)
Whenever I try to host a battle with relayhost, the only two options are "chose automatically" and "manually enter manager name". In the past I have seen SLRelayMaster and SLRelaySlave as options as well, but currently neither of the two available options are working. When I try to start a battle with them, the dialog box just closes and nothing happens.

**Comment by silentwings** [comment]
https://github.com/spring/relayhost/issues/3

**Comment by abma** [comment]
fixed: https://github.com/spring/relayhost/issues/3
