### ISSUE TITLE
"Forgot password" option?

### ISSUE THREAD

**Issue by allentiak** [springlobby/springlobby#919]
Could this "forgot password" option be implemented?
Perhaps as an optional feature, only activated if the player provides an email (either when at registering or afterwards)...

**Comment by silentwings** [comment]
Functionality already exists within the server but - as you say - this has to wait until the live system forcibly collects emails

**Comment by abma** [comment]
this depends on #920

**Comment by abma** [comment]
#920 is fixed, so now it depends on https://github.com/spring/uberserver/issues/353

i close this report, as the springlobby part is done, if you want to follow progress, follow the issue https://github.com/spring/uberserver/issues/353
