### ISSUE TITLE
buildbot setup broken

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#920]
just for the reference:

due to an update of the host, buildbot broke it seems

http://buildbot.springlobby.info/

**Comment by renefritze** [comment]
Uhm, was this still supposed to run on my box?

**Comment by abma** [comment]
yeah, it suddenly broke after some os-update i guess.

**Comment by renefritze** [comment]
I'd be happy to look into re-creating the setup on azure pipelines in a week or two, if you're interested. 
I'd prefer not putting work into maintaining spring stuff on my box

**Comment by abma** [comment]
ok, when it can do the same?! idk much about azure pipelines...

**Comment by renefritze** [comment]
Well, part of "looking into" would be for me to learn what the buildbot currently does :wink: 
With azure pipeline you basically run everything, including native windows, macosx, and docker on linux. I'll have to see how we do binary upload, if that's configured on buildbot.

**Comment by abma** [comment]
> Well, part of "looking into" would be for me to learn what the buildbot currently does wink

poll this github repo and when changed compile a windows .exe  :)

there where two builders, one for development and one for releases.

when the build was finished,  springlobby.exe/installer/zip was uploaded to https://springlobby.info/temp/builds/develop/ or https://springlobby.info/windows/

thats basicly all. only two builds where used:

https://github.com/springlobby/springlobby/blob/master/buildbot/master.cfg#L343
class ReleaseFactory(BuildFactory):

and

https://github.com/springlobby/springlobby/blob/master/buildbot/master.cfg#L388
class WinTempBuildFactory()


maybe from time to time the MXEFactory, too, to update the build environment.

**Comment by abma** [comment]
todo:
- "libcurl 7.59.0 found but 7.60 is required!"
- https for http://springlobby.springrts.com
- fix upload
- change selfupdate link somewhere at springrts.com, i.e. https://springrts.com/springlobby/ ...
- create release from manual tag
- fix autostart of buildmaster / fix buildbot/Makefile

when that works:
- create release
- upload release to springlobby.info

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/commit/bfd7e842447403d5c2458548aa7b850fc0ad4acf

**Comment by abma** [comment]
done: https://springrts.com/phpbb/viewtopic.php?t=40447

(i'll fix autostart of buildmaster when it annoys me enough :-P )
