### ISSUE TITLE
Problem on Windows after installation

### ISSUE THREAD

**Issue by frju365** [springlobby/springlobby#922]
Hello,

There is a problem on windows, just after installation. See screenshot : 
![Capture](https://user-images.githubusercontent.com/19982894/57039016-c84faf80-6c5b-11e9-95ef-480b735d1d66.PNG)

Creating `C:\Users\frju365\AppData\Roaming\springlobby` and inside the folder an empty `springlobby.log` fixes it.

Something easy, I think. I don't have time this week, but perhaps I will se that next week if nobody fixes it.

**Comment by abma** [comment]
seems the dir is created after the error message: on next start the error is gone

**Comment by frju365** [comment]
For me it's was not the case because I had to create the folder... but perhaps I missed something.
