### ISSUE TITLE
You are allready logged in

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#927]
On windows 10 - Springlobby will log out and pretend im already logged in on automatic relogin.
After a short period (about 10 secs) a relogin will be allowed.
This lasts for about 20 minutes before a automatic logout is reoccuring.

**Comment by PicassoCT** [comment]
Still an issue in 0.267

**Comment by abma** [comment]
can you provide springlobby.log after this happend please?

**Comment by PicassoCT** [comment]
Eh, im sorry but i assume this has been somehow resolved. I can not reproduce the error. Only thing  i remember is that a reinstall  seemed to allow to circumvent it. Sorry.
