### ISSUE TITLE
Compile errors: incomplete classes wxBitmap and wxImage

### ISSUE THREAD

**Issue by hoijui** [springlobby/springlobby#931]
though CMake config ran fine, I failed to compile springlobby 0.267-42-g8f2d15af2 (current *master* as of 9. Nov. 2019) due to these errors:

```
lib/src/lsl/lslunitsync/image.cpp:414:36: error: return type ‘class wxBitmap’ is incomplete
lib/src/lsl/lslunitsync/image.cpp:416:26: error: invalid use of incomplete type ‘class wxImage’
lib/src/lsl/lslunitsync/image.cpp:416:27: error: invalid use of incomplete type ‘class wxBitmap’
lib/src/lsl/lslunitsync/image.cpp:419:34: error: return type ‘class wxImage’ is incomplete
lib/src/lsl/lslunitsync/image.cpp:422:22: error: invalid use of incomplete type ‘class wxImage’
lib/src/lsl/lslunitsync/image.cpp:424:14: error: variable ‘wxImage img’ has initializer but incomplete type
```

I am on latest Debian testing.

I added this line to the main CMakeLists.txt file:

```
find_package(wxWidgets COMPONENTS core base REQUIRED)
```

after which CMake config phase failed.

After installing package `libwxgtk3.0-gtk3-dev`, CMake config ran successful again, and so did `make`.

I think my `find_package (...)` is probably not the right way to do it, but figured you guys know better how to do it right.

**Comment by abma** [comment]
delete CMakeCache.txt should fix this issue / git clean -f -d -x.

very likely some wxwidget-notfound value was cached.
