### ISSUE TITLE
Nicknames column labels are incorrectly drawn

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#935]
Hello,

this is how it looks

![imagen](https://user-images.githubusercontent.com/184088/70747974-57ac5d80-1d29-11ea-92a4-38c1e3eccabf.png)

but if you try to resize a column to the left it goes wrong

![imagen](https://user-images.githubusercontent.com/184088/70748015-6b57c400-1d29-11ea-87eb-80b2b373a7dd.png)

only tested on windows 10

**Comment by TurBoss** [comment]
it only happends on chat user list

**Comment by silentwings** [comment]
Also, in the battle list the "player count" column has lost its label (and a few others too)

**Comment by abma** [comment]
duplicate of #942 ?

can you please test
https://github.com/springlobby/springlobby/issues/942#issuecomment-573470693
?

**Comment by TurBoss** [comment]
latest develop works like a charm!

**Comment by TurBoss** [comment]
this is from the devel channerl
![imagen](https://user-images.githubusercontent.com/184088/72959626-3e2c1600-3dab-11ea-9034-196e587c18de.png)

**Comment by TurBoss** [comment]
can this be closed?
