### ISSUE TITLE
0.268 fails to build from source on Debian

### ISSUE THREAD

**Issue by apoleon** [springlobby/springlobby#936]
Springlobby fails to build from source because tools/regen_config_header.sh doesn't exist. If I remove the llne 

add_custom_target(version ALL ${springlobby_SOURCE_DIR}/tools/regen_config_header.sh ${springlobby_SOURCE_DIR} ${springlobby_BINARY_DIR})

from src/CMakeLists.txt, the program compiles as expected.

**Comment by abma** [comment]
this commit broke it: https://github.com/springlobby/springlobby/commit/155ed735de3564f1a1b157fb49fcb4c086fb38c4

**Comment by abma** [comment]
thanks for reporting!

**Comment by apoleon** [comment]
Thanks for fixing. Unfortunately the missing file is also not present in the cmake directory. Do you intend to release a new tarball soon, which will contain this file?

**Comment by abma** [comment]
yeah, i guess a release will happen soon but first i want to wait a bit if the new release has some major bugs, too.

**Comment by abma** [comment]
reopening as release reminder

**Comment by abma** [comment]
i try to create a release 17.12.-19.12

**Comment by abma** [comment]
released 0.269
