### ISSUE TITLE
connection stall when tls 1.3 is used

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#940]
see https://github.com/spring/uberserver/issues/363

**Comment by abma** [comment]
hehe, delay can be reduced when "ping" is written into server chat :-)

**Comment by silentwings** [comment]
lol, perhaps because any data (including ping) triggers the command queue to be emptied, and a TASSERVER is waiting in the queu which then triggers a LOGIN

**Comment by abma** [comment]
atm it looks like openssl doesn't return the already received data: but after doing a send it returns it...
