### ISSUE TITLE
pressing enter declines ToS

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#941]
A user who enters their email verfication code and then simply presses enter will decline the ToS because the default button is the 'No' button. 

They aren't given any notification to tell them that they (accidentally) declined the ToS, and are just returned to the login screen. The server isn't told explicitly that this occurs. I guess it has caught a small percentage of new users out - I suggest making it so that pressing enter/return on the ToS dialogue does nothing at all, and requiring a mouseclick on yes/no.

Maybe didn't happen much before because users did not type into the ToS dialogue, although it leaves ~no trace in server logs so we wouldn't have known ayway!

**Comment by silentwings** [comment]
Perhaps the right way to handle this is to add DENIEDAGREEMENT to the protocol (to help record stats on registration outcomes) and for the server to respond with a DENIED a "You declined our terms of use. They must be accepted before you can login!"

**Comment by silentwings** [comment]
after https://github.com/springlobby/springlobby/commit/cbe85f6c0a23794d7f7a6bc4dfae84c523871ab4 & fallout my dev env is broken, and trying to fix would involve doing more complicated stuff to the WSL than i'm willing to try

so i'm afraid we can scratch that PR

**Comment by abma** [comment]
wrt the build env: sorry this was unavoidable, at same point we want std::filesystem which requires gcc9 it seems.

to upgrade "only" mxe has to be upgraded which takes maybe an hour to compile.

https://github.com/springlobby/springlobby/blob/master/tools/mxe_compile.sh
https://github.com/springlobby/springlobby/blob/master/tools/mxe_create_builddir.sh
