### ISSUE TITLE
Innocuous yet annoying map download errors

### ISSUE THREAD

**Issue by MaDDoXbr** [springlobby/springlobby#944]
After downloading some maps, a couple errors show up. They're innocuous, but I've also seen some new users believe the map download failed, trying to download it again etc. So maybe they should simply be suppressed and their messages only added to the log? Follows screenshots:

https://drive.google.com/open?id=1UqRuhKgRSL80g7HLLS2XIaIL5FuIxNQd
https://drive.google.com/open?id=1U3qMdiLclbvF7l46O_xOPdN3ttyAHUE4

**Comment by abma** [comment]
please try again with springlobby 0.270: i could swear this was changed, can't give a reference. if not, please reopen.

thank you!
