### ISSUE TITLE
When running springlobby: "Fatal Error: Mismatch between the program and library build versions detected."

### ISSUE THREAD

**Issue by pkillnine** [springlobby/springlobby#947]
After compiling from source with `cmake .. -DOPTION_SOUND=OFF -DOPTION_TRANSLATE_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/final
 && make` and installing with `make install`, when I run springlobby, I get the following error:

```
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.1.0 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 3.0),
and your program used 3.1.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 3.0).
```

**Comment by abma** [comment]
i guess your installation of wxwidgets is broken... do you have multiple versions installed?
