### ISSUE TITLE
Unitsync not initialized

### ISSUE THREAD

**Issue by springjools** [springlobby/springlobby#949]
Get an error that says:

Unitsync not initialized, when installing 0.269 on  fresh system. See picture.

I cannot download any games or maps at all.

**Comment by springjools** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/5911982/73595686-292a5200-4524-11ea-87ed-a8585208b402.png)

**Comment by springjools** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/5911982/73595787-00568c80-4525-11ea-9e21-0d6f8ba21e52.png)

**Comment by abma** [comment]
springlobby.log please!

**Comment by springjools** [comment]
[springlobby.log](https://github.com/springlobby/springlobby/files/4144093/springlobby.log)

**Comment by bcverdict** [comment]
I'm having the same issue. There is no unitsync.dll in any of the usual locations. Maps and games will download to the proper folders but will not be found since no unitsync file can sync them

**Comment by abma** [comment]
sorry, no clue, hopefully fixed with 0.271 which will be released "soon"
