### ISSUE TITLE
map downloads not working

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#950]
This has only been an issue for the past month or two. Players are no longer being able to download the maps they lack.

As an example, I moved a map file (lonely_oasis_v1.1.sd7) out of my maps directory and restarted the lobby.

here's what happens when I join the battle room and click to download the map, it fails, then click again on the map frame and it fails again:

> 2020-02-11 01:37:25.758 Message ld/src/tasserver.cpp:1093 sent: #34 JOINBATTLE 2793  11f57e33
> 2020-02-11 01:37:27.173 Message uild/src/chatlog.cpp:115  OpenLogFile( ) _BATTLE_nebula3
> 2020-02-11 01:37:27.173 Message uild/src/chatlog.cpp:300  ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\Rui\AppData\Roaming\springlobby\chatlog\Official server\_BATTLE_nebula3.txt.
> 2020-02-11 01:37:27.179 Debug   c/unitsync_cache.cpp:301  Loading from C:\Users\Rui\AppData\Roaming\springlobby\cache\Metal Factions v1.28-side-Random.png
> 2020-02-11 01:37:27.179 Debug   c/unitsync_cache.cpp:301  Loading from C:\Users\Rui\AppData\Roaming\springlobby\cache\Metal Factions v1.28-side-Aven.png
> 2020-02-11 01:37:27.179 Debug   c/unitsync_cache.cpp:301  Loading from C:\Users\Rui\AppData\Roaming\springlobby\cache\Metal Factions v1.28-side-Gear.png
> 2020-02-11 01:37:27.179 Debug   c/unitsync_cache.cpp:301  Loading from C:\Users\Rui\AppData\Roaming\springlobby\cache\Metal Factions v1.28-side-Claw.png
> 2020-02-11 01:37:27.180 Debug   c/unitsync_cache.cpp:301  Loading from C:\Users\Rui\AppData\Roaming\springlobby\cache\Metal Factions v1.28-side-Sphere.png
> 2020-02-11 01:37:28.535 Warning ng/battleroomtab.cpp:458  Tag 3_mapname not found in options list
> 2020-02-11 01:37:28.547 Message ui/customdialogs.cpp:82   Content is required to play. Should it be downloaded?
> 2020-02-11 01:37:28.547 Message ui/customdialogs.cpp:82  +- map Lonely Oasis v1.1
> 2020-02-11 01:37:28.552 Message ld/src/tasserver.cpp:1093 sent: #35 GETCHANNELMESSAGES __battle__968127 0
> 2020-02-11 01:37:28.568 Info    src/serverevents.cpp:544  detected SPADS autohost
> 2020-02-11 01:37:28.608 Warning uild/src/ibattle.cpp:73   Not synced: map name doesn't match host:'Lonely Oasis v1.1' local:''
> 2020-02-11 01:37:28.608 Message ld/src/tasserver.cpp:1093 sent: #36 MYBATTLESTATUS 41944200 16711680
> 2020-02-11 01:37:30.985 Info    der/prdownloader.cpp:56   Starting download of filename: , name: Lonely Oasis v1.1
> 2020-02-11 01:37:31.288 Message ld/src/tasserver.cpp:1093 sent: #37 MYBATTLESTATUS 41943176 16711680
> 2020-02-11 01:37:31.289 Message ui/customdialogs.cpp:82   Failed to download selected item.
> 2020-02-11 01:37:31.331 Info    der/prdownloader.cpp:81   Nothing found to download
> 2020-02-11 01:37:36.535 Info    der/prdownloader.cpp:56   Starting download of filename: , name: Lonely Oasis v1.1
> 2020-02-11 01:37:36.741 Message ld/src/tasserver.cpp:1093 sent: #38 MYBATTLESTATUS 41943176 16711680
> 2020-02-11 01:37:36.742 Message ui/customdialogs.cpp:82   Failed to download selected item.
> 2020-02-11 01:37:36.747 Info    der/prdownloader.cpp:81   Nothing found to download
> 2020-02-11 01:37:45.087 Warning c/gui/mainwindow.cpp:287  MainWindow::OnClose

this happens despite the map still being available to download on springfiles:
https://springfiles.com/spring/spring-maps/lonely-oasis-0

**Comment by springraaar** [comment]
This happened to some maps, but not others.

it happened too with my latest map
https://springfiles.com/spring/spring-maps/fifteen-platforms-0

but people have been able to download other maps.

the post on this thread indicates a related issue has been fixed on 21 february
https://springrts.com/phpbb/viewtopic.php?p=593384#p593384

but lonely oasis map is still not being downloaded, so it may not be fully fixed.

**Comment by abma** [comment]
please try again: https://github.com/springfiles/upq/commit/6f6a024d274dd92ba3831661e7c86aa4921d17d4

for some reason Lonley Oasis v1.1 got marked broken and the status never was updated.
now its there: https://api.springfiles.com/?springname=Lonely+Oasis+v1.1


fifteen-platforms was already there:

https://api.springfiles.com/?springname=Fifteen Platforms v2


please springlobby.log when it fails again?!

**Comment by abma** [comment]
i assume this is fixed with springlobby 0.270 / changes to api.springfiles.com
