### ISSUE TITLE
Build fails with new GCC 10

### ISSUE THREAD

**Issue by tim77** [springlobby/springlobby#951]
Hello. Common GCC 10 bugs
https://gcc.gnu.org/gcc-10/porting_to.html#common

[Full build log](https://gist.githubusercontent.com/tim77/4b42f7f3c5a0121ee38e713b1e0c3a70/raw/87c7437b00d7c187866b8f5d1d14979cb6499425/springlobby)
OS: `Fedora 32`
springlobby version: `0.269`

**Comment by abma** [comment]
as the log is very long, i hopefully found the first error:

```
/usr/include/minizip/mz_compat.h:65:9: error: 'uint64_t' does not name a type; did you mean 'u_int64_t'?
   65 | typedef uint64_t ZPOS64_T;

```

it looks more like the system installed minizip is either incompatible or broken.

**Comment by nametable** [comment]
I'm also having an issue compiling with GCC 10.
OS: `Arch`
SpringLobby version: master (5cc557549c11dd2f3a3c490169f36020c6580e39)
GCC version: `10.1.0`

[build_log.txt](https://github.com/springlobby/springlobby/files/4718452/build_log.txt)

Right off the bat, it looks like std::string is not being implicitly included. Adding `#include <string>` to `battlelist.h` and `sortutil.h` causes it to compile just fine it seems.

This is a quick to the issue for me. Would you like me to make a PR @abma ?

**Comment by abma** [comment]
yes, please!

its always difficult to fix stuff when you can't directly reproduce it :-|

**Comment by abma** [comment]
thank you!

does this fix compile at all with gcc 10 or does it still fail at a later stage?

**Comment by nametable** [comment]
For me, I can compile everything with GCC 10 and then am able to run it. I followed the most basic configuration. `cmake .` and `make`

I did find out I had to get the git submodule(s) but that was easy.

**Comment by tim77** [comment]
This is probably exactly the same issue which i have. TBH there was few of them. I'll try to test this very soon, sorry for some delay. And thanks a lot for fix @nametable

**Comment by abma** [comment]
@nametable :

nice, thank you!

@tim77 :
please report back if it works for you: i assume its fixed for now. thanks!

**Comment by tim77** [comment]
Compiles fine with this patch. I'll update and fix soon package in Fedora. Thank you guys.
