### ISSUE TITLE
Compiling Springlobby under Ubuntu 20.04

### ISSUE THREAD

**Issue by sammmuel** [springlobby/springlobby#953]
Hello alls,
The libwxgtk3.0-dev package seems not available under this new version of ubuntu.
[https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libwxgtk3.0-dev&searchon=names]
Is there a workaround? Should it be added in a near future?
Thanks a lot.
Samuel

**Comment by abma** [comment]
i'm not sure, but could it be that the package was renamed to libwxgtk3.0-gtk3-dev ?

**Comment by sammmuel** [comment]
Ok I try with this name and I tell you the result.

**Comment by sammmuel** [comment]
Perfect it's starting now.
For the complete story after upgrading to the new release of Ubuntu Springlobby was unable to start.
I have to reinstall different package until compilation start (until no more pakage asked) and installing libwxgtk3.0-gtk3-dev help to finish without error.
Thanks a lot for all!
