### ISSUE TITLE
Exception in ExecuteCommand (Windows)

### ISSUE THREAD

**Issue by andresmrm** [springlobby/springlobby#955]
Hello!

I'm having problems to run SpringLobby on Windows 10 (tested with 269 and then 268). On Linux it's fine.

After filling in username and password, the chat writes:

	[22:21:12] ** Server ** Connecting to server Official server...
	[22:21:15] ** Server ** Connected to Official server.

But all the other tabs are empty (no rooms list). And after some time the chat writes:

	[22:14:05] ** Server ** Disconnected from server, chat closed.
	### Session Closed at 2020-05-15 22:14
	[22:22:18] ** Server ** Connecting to server Official server...
	[22:22:20] ** Server ** Connected to Official server.

This repeats after a minute or so. Since it displays no rooms list, I can't play. =(

I'm not sure if it is related, but the registration process seems stuck. After registering a new user it sends a verification code to my e-mail, but there is no place to enter it in the SpringLobby.

The error reported above happened with a new registered user (without using the verification code) and with an old user (registered with an older version of SpringLobby on Linux).

Windows logs:
https://pastebin.com/raw/g2zpAgQL

**Comment by abma** [comment]
i've released springlobby 0.270: can you please try again with it and if it still fails provide springlobby.log again?

thank you!

**Comment by andresmrm** [comment]
It worked! (Windows10)
Huge thanks!
