### ISSUE TITLE
CMake errors with wxgtk while configuring

### ISSUE THREAD

**Issue by Enteneller2017** [springlobby/springlobby#957]
running: cmake . -DOPTION_TRANSLATION_SUPPORT=OFF -DOPTION_SOUND=OFF
on Solus Linux (Kernel 5.6.13-153.current) returns:

CMake Error at src/CMakeLists.txt:94 (message):
  Couldn't find wx/config.h, is wxgtk-dev installed?

wxgtk is not in the required list and is also not available in the Solus repo. 
Any chance to work around this?

tried to look at: 
http://buildbot.springlobby.info/waterfall
returns a bad gateway error for me.

Are there simple binaries available for Linux in a zipfile one could use distro-agnostic? Similar to the Spring portable zip version. That would be very helpful. 

more detailed log: 
> cmake . -DOPTION_TRANSLATION_SUPPORT=OFF -DOPTION_SOUND=OFF
> -- gcc 9.3.0 detected
> -- found wx-config: /usr/bin/wx-config
> -- found wxwidgets: 3.0.5.0
> -- Using WX_CXX_FLAGS: -I/usr/lib64/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__
> -- Using WX_C_FLAGS: -I/usr/lib64/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
> -- Using WX_LD_FLAGS: -L/usr/lib64 -pthread   -lwx_baseu_net-3.0 -lwx_gtk2u_qa-3.0 -lwx_gtk2u_richtext-3.0 -lwx_gtk2u_adv-3.0 -lwx_gtk2u_aui-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu-3.0
> CMake Error at src/CMakeLists.txt:94 (message):
>   Couldn't find wx/config.h, is wxgtk-dev installed?
> -- Configuring incomplete, errors occurred!
>

**Comment by abma** [comment]
what do you mean with "required list"?

IMHO it is there: https://github.com/springlobby/springlobby/wiki/InstallFromSource#Specific_OS_commands

**Comment by abma** [comment]
the buildbot migrated to a new url: https://springlobby.springrts.com/buildbot/

where did you find the old address?

**Comment by Enteneller2017** [comment]
> where did you find the old address?

https://github.com/springlobby/springlobby/wiki/InstallFromSource
bottom of the page.

> what do you mean with "required list"?

https://github.com/springlobby/springlobby/wiki/InstallFromSource#required

**Comment by abma** [comment]
i've fixed the wiki page.

wxgtk is a part of wxWidgets... so the error message basicly is correct.

**Comment by abma** [comment]
i have no clue about solus, but something like

sudo eopkg search wxwidgets
or 
sudo eopkg search wxgtk

hopefully shows the required package.

**Comment by Enteneller2017** [comment]
eopkg sf wx/config.h 
Searching for wx/config.h
Package wxwidgets-devel has file /usr/include/wx-3.0/wx/config.h
Package wxwidgets2.8-devel has file /usr/include/wx-2.8/wx/config.h
