### ISSUE TITLE
add / relase flatpak

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#964]
there would be a lot of issues solved by that

**Comment by baracoder** [comment]
Hi, I could take care of getting it into flathub, the flatpak app-store
I have a working build here https://github.com/baracoder/com.springrts.springlobby
just need to rebase on their official pull request template

**Comment by abma** [comment]
oh, i didn't know that.

can you cherry-pick the best of both please before doing so?


https://github.com/springlobby/springlobby/blob/master/flatpak/com.springrts.SpringLobby.json

isn't finished, but i.e. the build args for boost should lead to a smaller build.

is "glu" really required or is it just required because springlobby launches spring and so spring uses the same environment?

**Comment by abma** [comment]
i guess it makes sense to add a config switch to disable the autoupdater for springlobby for the flatpak build

**Comment by baracoder** [comment]
Thank you for the suggestions, I will include those.
glu is included to run spring. It should also be possible to package spring on its own, and launch that package explicitly from springlobby.

**Comment by baracoder** [comment]
I prepared the repo here https://github.com/baracoder/flathub
Anything I should change before submitting it?

Next step would be to create a pull request to the flathub repo to start the review process.

> Once your pull request has been approved, a new repository will be created for your application, containing your app’s Flatpak manifest. You will have write access for the repository. The Flathub service then uses the manifest from your repository to continuously build and distribute your application on every commit.

**Comment by abma** [comment]
app-id should be IMHO "com.springrts.SpringLobby" + can you please use https://github.com/springlobby/flathub/ for that?

i have no clue how the permissions are made for the new repo, but it would be good, if the "springlobby" organization would have access, so multiple people can create a new release.

**Comment by baracoder** [comment]
:tada: https://flathub.org/apps/details/com.springrts.SpringLobby

The repository was created:
https://github.com/flathub/com.springrts.SpringLobby
@abma and @renefritze should get an invite to edit the repository.
Releases are made available to flathub 24h after a successful build by default, but can be published manually from the build bot. (login through github) 
Buildbot info is available here https://flathub.org/builds/#/apps/com.springrts.SpringLobby
A guide on flathub app maintenance is here: https://github.com/flathub/flathub/wiki/App-Maintenance

I added an [updated version](https://github.com/flathub/com.springrts.SpringLobby/blob/master/springlobby.appdata.xml) of the `appdata.xml` file with some changes:
There are required fields like release, open age rating https://hughsie.github.io/oars/ and changed dimensions for the screenshots. We can update the original file and patch-in release tags on the fly.

Also we should add a `flathub.json` file to restrict the architectures, as I think there are no arm builds of spring

Also when testing, I had some crashes when downloading an engine :thinking: 

And a note on sandboxing:
The home directory and directories `~/.spring` and `~/.springlobby` are not visible inside the sanbox. Instead they mapped from an per-app data directory.
```
ls -a ~/.var/app/com.springrts.SpringLobby/
./  ../  cache/  config/  data/  .ld.so/  .spring/  .springlobby/
```
This could lead to some confusion, when switching from another form of distribution

**Comment by renefritze** [comment]
Do I rightly assume I was added to increase the bus factor? That would be fine.

**Comment by baracoder** [comment]
@renefritze sorry and yes, I have added you as you are one of the owners of the springlobby/ group :bus:

**Comment by abma** [comment]
so i would say this issue is solved, i've created some issues wrt flatpak:

https://github.com/springlobby/springlobby/labels/flatpak
