### ISSUE TITLE
[flatpack] there is no desktop icon

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#967]
hello,

just installed the flatpak on ubuntu 20.04 and works fantastic

i only noticed that there is no desktop launcher

thanks

**Comment by baracoder** [comment]
:thinking: works on an ubuntu 20.04 virtual machine, as well as on NixOS 20.03. Did you install the flatpak version? There are two other versions in ubuntu software.
![Screenshot from 2020-06-29 23-32-35](https://user-images.githubusercontent.com/127523/86058364-12e7da00-ba61-11ea-9100-fc31aa802c0c.png)
![Screenshot from 2020-06-29 23-31-54](https://user-images.githubusercontent.com/127523/86058365-13807080-ba61-11ea-8315-5644ba3ee346.png)

**Comment by TurBoss** [comment]
hello, it started to show now that i have restarted the computer
thanks
