### ISSUE TITLE
restrict architectures of flatpak

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#968]
"Also we should add a flathub.json file to restrict the architectures, as I think there are no arm builds of spring."

when doing this,  i386 should be removed as well as its mostly "deprecated".

**Comment by abma** [comment]
https://github.com/flathub/flathub/wiki/App-Maintenance

{
  "only-arches": ["x86_64"]
}

**Comment by baracoder** [comment]
Fixed in https://github.com/flathub/com.springrts.SpringLobby/commit/ddf9186be993ea8b6056f501a205ac5950ef60fb
