### ISSUE TITLE
flatpak sandboxing makes it ignore existing ~/.spring ~/.springlobby

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#969]
The home directory and directories ~/.spring and ~/.springlobby are not visible inside the sanbox. Instead they mapped from an per-app data directory.

ls -a ~/.var/app/com.springrts.SpringLobby/
./  ../  cache/  config/  data/  .ld.so/  .spring/  .springlobby/

This could lead to some confusion, when switching from another form of distribution

**Comment by baracoder** [comment]
Fixed in https://github.com/flathub/com.springrts.SpringLobby/commit/1fc94a8ff87c6e328a0eccda73686fab9c86eb40
