### ISSUE TITLE
spring makes gnome-shell crashing when run from flatpak

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#970]
no clue why for now

**Comment by baracoder** [comment]
Which distribution & release? Works on my machine with gnome 3.36.1

**Comment by abma** [comment]
debian 10 + gnome-shell 3.30.2-11~deb10u1 with xorg

**Comment by abma** [comment]
with wayland it seems to work

**Comment by baracoder** [comment]
Debian 10 has in my case gnome shell 3.30.2
I did not manage to reproduce it today with Debian 10 in a VM and spring engine `104.0.1-1482-gc4e1654`

**Comment by abma** [comment]
ok, as it works for you i guess its something specific to my computer: also the shell shouldn't crash at all.
