### ISSUE TITLE
0xc000007b when staring x64 springlobby

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#977]
https://stackoverflow.com/questions/10492037/the-application-was-unable-to-start-correctly-0xc000007b

https://springrts.com/phpbb/viewtopic.php?p=595625#p595625

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/97113069-445b7400-16e8-11eb-81e1-f6360dbdf246.png)
Dependency walker showing me the following.
WINRT sounds suspicious...

**Comment by TurBoss** [comment]
under wine runs fine :-/

**Comment by abma** [comment]
can you please test again with https://springlobby.springrts.com/dl/develop/springlobby-0.270-30-g26b08aa6a-win32.zip please?

**Comment by Beherith** [comment]
About api-ms-win-core : "They're part of architectural changes to Windows to support multiple devices and system architectures. They shouldn't be used or linked to directly and should not themselves be distributed. Rather apps and programs should make use of MinCore.lib or MinCore_Downlevel.lib."

![image](https://user-images.githubusercontent.com/109391/97302853-e484da80-1859-11eb-885c-63b8e04a4372.png)

**Comment by abma** [comment]
is comctl32.dll x64 or x86 (column cpu)? thats not visible in the second screenshot.  api-ms-win-core is not directly linked which can be seen in the first screenshot already.

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/97308579-4f85df80-1861-11eb-9898-9f3529aea809.png)

x86

**Comment by abma** [comment]
ugh, for some reason, the buildsystem cached the old .manifest.

new build: https://springlobby.springrts.com/dl/develop/springlobby-0.270-31-g107c87300-win32.zip

please try again!

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/97481744-89d0a900-1955-11eb-94c0-de0d797998bc.png)

**Comment by abma** [comment]
next try: https://springlobby.springrts.com/dl/develop/springlobby-0.270-32-gbc361888f-win32.zip

**Comment by Beherith** [comment]
Excellent! It loaded up, but failed to load both 32bit and 64bit engine unitsync.ddls, and showed 3 messages for each engine unitsync it was unable to load. 
![image](https://user-images.githubusercontent.com/109391/97553075-4b7ace80-19d5-11eb-9e72-00a17a56375b.png)

**Comment by abma** [comment]
can you paste springlobby.log please?

**Comment by psarkozy** [comment]
Sure thing, anything you need :)
[unitsync.log](https://github.com/springlobby/springlobby/files/5458608/unitsync.log)



[20201029_142451-springlobby.log.txt](https://github.com/springlobby/springlobby/files/5458606/20201029_142451-springlobby.log.txt)

**Comment by Beherith** [comment]
Just a side note, I have a large set of engine 32 and 64bit, and none of them show up in Springlobby x64. Btw above poster is me.

**Comment by abma** [comment]
please try again:
https://springlobby.springrts.com/dl/develop/springlobby-0.270-37-g85d6d3be6-win32.zip

this version works loads unitsync with wine and downloading seems to work, too.

only thing that fails in my short test is extracting the engine: not sure if the used 7zip lib is just to old.

**Comment by Beherith** [comment]
Unfortunately still cant load neither 32, nor 64 bit unitsyncs.

![image](https://user-images.githubusercontent.com/109391/97781924-d18e4500-1b8e-11eb-894a-c605464d8853.png)

[unitsync.log](https://github.com/springlobby/springlobby/files/5469249/unitsync.log)
[20201031_153434-springlobby.log](https://github.com/springlobby/springlobby/files/5469253/20201031_153434-springlobby.log)
[springlobby.log](https://github.com/springlobby/springlobby/files/5469254/springlobby.log)

**Comment by abma** [comment]
does C:\Users\Peti\Documents\My Games\Spring\engine\spring_{maintenance}104.0.1-1554-gf775ea1470_win64-minimal-portable\unitsync.dll exist?

**Comment by abma** [comment]
if so, can you please load it with Dependency walker again?

**Comment by JackCarterSmith** [comment]
> 
> 
> please try again:
> https://springlobby.springrts.com/dl/develop/springlobby-0.270-39-g97cf3a2bc-win32.zip
> 
> this version works loads unitsync with wine and downloading seems to work, too.
> 
> only thing that fails in my short test is extracting the engine: not sure if the used 7zip lib is just to old.

I've tried to use it with the 64bits version (spring-{maintenance}104.0.1-1553-gd3c0012_win64), but I can't load 32bits version now.
How I can help?

![image](https://user-images.githubusercontent.com/2466196/97800062-53837a00-1c32-11eb-9394-c625467c0bd1.png)

**Comment by abma** [comment]
> I've tried to use it with the 64bits version (spring-{maintenance}104.0.1-1553-gd3c0012_win64), but I can't load 32bits version now. How I can help?

without large changes to springlobby (see https://github.com/springlobby/springlobby/issues/48 ) the engine platform must be the same platform as the lobby.

to avoid to mixing of architectures pr-downloader and springlobby will download the spring engine in dedicated folders per architecture, i.e. its now downloaded to engine/windows64/spring version (before it was engine/springversion).

**Comment by abma** [comment]
wrt extracting:

Path = spring-{maintenance}104.0.1-1553-gd3c0012_win64/AI/Interfaces/Java/0.1/AIInterface.dll
Size = 254897
Packed Size = 
Modified = 2020-08-04 20:04:07
Attributes = A_ -rw-r--r--
CRC = 77626BDF
Encrypted = -
Method = BCJ2 LZMA:26 LZMA:20:lc0:lp2 LZMA:20:lc0:lp2
Block = 1

vs win32:

Path = AI/Interfaces/Java/0.1/AIInterface.dll
Size = 241602
Packed Size = 
Modified = 2020-08-04 20:21:06
Attributes = A_ -rwxr-xr-x
CRC = A1D76779
Encrypted = -
Method = BCJ2 LZMA:25 LZMA:20 LZMA:20
Block = 1

**Comment by abma** [comment]
next try:
https://springlobby.springrts.com/dl/develop/springlobby-0.270-45-g5819a7918-win32.zip

changelog: https://github.com/springlobby/springlobby/blob/master/ChangeLog

i had to update the 7zip lib. for some reason the win64 buildbot worker compresses in a newer format, i had to update the used 7z sdk. now download / join works with wine, i'm synced. 

Can you please test again?

**Comment by JackCarterSmith** [comment]
> 
> 
> next try:
> https://springlobby.springrts.com/dl/develop/springlobby-0.270-45-g5819a7918-win32.zip
> 
> changelog: https://github.com/springlobby/springlobby/blob/master/ChangeLog
> 
> i had to update the 7zip lib. for some reason the win64 buildbot worker compresses in a newer format, i had to update the used 7z sdk. now download / join works with wine, i'm synced.
> 
> Can you please test again?

I've tested your new version, :
maintenance x64 engine (104.0.1-1553-gd3c0012 maintenance) -> OK
latest x64 engine DL -> OK
latest x64 engine (104.0.1-2128-g73c3ed1 develop) -> NOK

![image](https://user-images.githubusercontent.com/2466196/97838087-c5fe6380-1cdf-11eb-8ce8-16dc9309535e.png)

![image](https://user-images.githubusercontent.com/2466196/97838224-05c54b00-1ce0-11eb-992e-fab0fd3c9f8a.png)

**Comment by abma** [comment]
ok, found one bug at least:

https://github.com/springlobby/springlobby/commit/ab254fe7d9179f52af42a05a8dbc654610cf13bc


but it seems unrelated to your error.

regardless of that, can you please try again:

https://springlobby.springrts.com/dl/develop/springlobby-0.270-49-gab254fe7d-win32.zip

**Comment by JackCarterSmith** [comment]
I got the same error (couldn't load unitsync.dll on last develop version) and same result for "depends"

**Comment by abma** [comment]
can you make a screenshot of depends loaded the broking unitsync.dll + provide springlobby.log?

thats weird as for me it works with wine and
C:\users\abma\Meine Dokumente\My Games\Spring\engine\windows64\104.0.1-2128-g73c3ed1 develop\unitsync.dll

**Comment by JackCarterSmith** [comment]
I've scanned unitsync.dll but I can't found the springlobby.log... It's in MyGames/Spring folder?

![image](https://user-images.githubusercontent.com/2466196/97922571-fb956200-1d5c-11eb-8b2a-527b13998b6e.png)

I've found this information about API-MS-WIN dll. Do you see it?
https://stackoverflow.com/a/36244483
Maybe your Wine config is set for Windows XP or 7?

**Comment by abma** [comment]
https://springrts.com/wiki/Springlobby.log

these errors are from indirect dependencies which shouldn't matter at all, only the direct dependencies matter: but these are not visible in the screenshot.

thats from wine with windows 10 config + depends x64 loaded unitsync 104.0.1-2128-g73c3ed1 develop
![Bildschirmfoto von 2020-11-02 23-23-53](https://user-images.githubusercontent.com/301564/97925932-87f65380-1d62-11eb-84cc-c4b4c0184a5e.png)

**Comment by JackCarterSmith** [comment]
[20201102_223754-springlobby.log](https://github.com/springlobby/springlobby/files/5479579/20201102_223754-springlobby.log)

Hopefully there will be some informations inside the log file. He was in a logs subfolder with a different format but it's it

**Comment by abma** [comment]
> Otw, I was thinking of a compatibility problem between mingw compiler... I've the same trouble with 2 differents versions of mingw, the lib has been compiled with mingw64 and my program has been compiled with mingw32, resulting in a program that can't correctly "parse" lib in memory.

the compiler version used to compile springlobby x64 and unitsync 104.0.1-2128-g73c3ed1 develop x64 is the same. (gcc 10.2)
sadly there is no more info in springlobby.log: for some reason the error message of LoadLibrary is empty, i guess i need to check out why its empty and fix that.

whats with the screenshot of depends x64 of  D:\JCS\Documents\My Games\Spring\engine\windows64\104.0.1-2128-g73c3ed1 develop\unitsync.dll ?

**Comment by abma** [comment]
ok, i've tested with some real windows 7: there it works.

can you please test with some clean installation? i'm pretty sure some file/config is broken in your setup.

**Comment by JackCarterSmith** [comment]
That's curious... I've cleaned all MyGames/spring folder, relaunch, redownload engine (develop and maintenance) and added without problems.
It seem to work, good work!

**Comment by abma** [comment]
thanks, great! :-)


now the hard part comes: "migrate" users from 32 bit to 64 bit :-|

**Comment by abma** [comment]
also a lot thanks for your help!

**Comment by JackCarterSmith** [comment]
A lot of machine run on a x64 arch, it's necessary to upgrade to 64bits!
