### ISSUE TITLE
Download engine not possible due to expired SSL certificate of api.springfiles.com

### ISSUE THREAD

**Issue by Progman2002** [springlobby/springlobby#978]
The SSL certificate on https://api.springfiles.com/ expired on Oct 24:
![certifcate](https://user-images.githubusercontent.com/18059362/97175263-868dbf80-1793-11eb-8659-8f2bec668b56.png)

This means you cannot download any files from this server with the springlobby:
![downloadError](https://user-images.githubusercontent.com/18059362/97175413-c2c12000-1793-11eb-8853-6ed1cf4b82b6.png)

**Comment by abma** [comment]
thanks, should be fixed. "certbot renew" failed because some dns entries were deleted.
