### ISSUE TITLE
Crash when trying to start self-hosted battle

### ISSUE THREAD

**Issue by nametable** [springlobby/springlobby#985]
OS: Arch Linux
Kernel: 5.9.12-arch1-1
SpringLobby Version: 0.271

I clicked to host a new battle. Selected tech annihilation, picked a map. When I tried to start a game, the lobby crashed. I have included the log below:

[20201222_184656-springlobby.log](https://github.com/springlobby/springlobby/files/5732488/20201222_184656-springlobby.log)

**Comment by nametable** [comment]
I think the problem is in spring.cpp:561

```cpp
	unsigned int maxiter = std::max(NumUsers, battle.GetLastRectIdx() + 1);
	std::set<int> parsedallys;
	for (unsigned int i = 0; i < maxiter; i++) {

		User& usr = battle.GetUser(i);
		UserBattleStatus& status = usr.BattleStatus();
		BattleStartRect sr = battle.GetStartRect(i);
		if (status.spectator && !sr.IsOk()) // This line crashes
			continue;
```
My guess is that the crash is due to `status` being a null-ptr. `maxiter` get's set to 4 for me even though there is only one user (me). When reading the `status.spectator` from an undefined user, springlobby segfaults. I'm investigating further. If I come up with a fix, I may make a pull request.

@abma Why does `maxiter` get set to a value other than `NumUsers`? What does GetLastRectIdx mean ("key of last start rect in the map")?

**Comment by abma** [comment]
very likely this is caused by a invalid battle setup: # of battle start rects doesn't match # of users.

**Comment by abma** [comment]
thanks for reporting!

it looks this crash bug exists since a very long time.

the fix isn't this nice, it would be better when springlobby would warn about the invalid # of  battle start rectangles before the battle starts.
