### ISSUE TITLE
Download link does not work

### ISSUE THREAD

**Issue by hugoam** [springlobby/springlobby#989]
The download link for windows lobby does not work... It complains a certificate, and even if you try to bypass that (which no one in their right mind should) it still yields nothing
https://github.com/springlobby/springlobby/wiki/Install#windows-binary

**Comment by abma** [comment]
thanks, i've fixed the link:

https://github.com/springlobby/springlobby/wiki/Install/_compare/859f0519e424e431ca154090c6e97c756ef0d9d3
