### ISSUE TITLE
libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by fwong13** [springlobby/springlobby#993]
"Couldn't load the library /home/fw/.spring/engine/linux64/105.0/libunitsync.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/fw/.spring/engine/linux64/105.0/libunitsync.so)"

This message appears when trying to download engine "spring 105.0" from "multiplater" tab ..
Thanks !

**Comment by fwong13** [comment]
Oups ! I'm using Debian 10 (Buster)

**Comment by abma** [comment]
can you paste [springlobby.log](https://springrts.com/wiki/Springlobby.log) please?

are you using the springlobby flatpak?

**Comment by fwong13** [comment]
Le 18/05/2021 à 17:17, abma a écrit :
>
> /can you paste //springlobby.log 
> <https://springrts.com/wiki/Springlobby.log>//please?/
>
- Yes, where please ? :)
>
> /are you using the springlobby flatpak?/
>
- No, the packages from Debian 10 (Buster) :
     spring, spring-common, springlobby

Thanks !
Francis

**Comment by abma** [comment]
here or https://paste.springfiles.com/

**Comment by fwong13** [comment]
Ok, the log content is in :

https://paste.springfiles.com/view/224df8af 
<https://paste.springfiles.com/view/224df8af>

Sayonara :))

Francis

**Comment by adamryczkowski** [comment]
I understand the problem has not been resolved. I have the same problem on two machines running Ubuntu 20.04.

Can anyone tell me, what Linux distributions are compatible with springlobby and spring engine right now?

**Comment by adamryczkowski** [comment]
Update: this is the error that only sounds scary. I ignored it, tried downloading stuff several times, and after some patience, everything started to work.

**Comment by abma** [comment]
> I understand the problem has not been resolved. I have the same problem on two machines running Ubuntu 20.04 with springlobby-nsg downloaded by snap.
> 
> Can anyone tell me, what Linux distributions are compatible with springlobby and spring engine right now?

the stable snap seems outdated, only 0.270 is available but 0.271 was released 

please report issuses related to the snap to https://github.com/nsg/snap-springlobby/issues

thank you!
