### ISSUE TITLE
CURL error on downloading archives

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#998]
![Bildschirmfoto vom 2021-10-18 20-49-03](https://user-images.githubusercontent.com/1271047/137789406-1874249d-4897-4858-9316-2046502f3504.png)

**Comment by abma** [comment]
which version of springlobby are you using and can you paste springlobby.log please?

**Comment by abma** [comment]
from springlobby.log:

0.269 (unix x64) started

**Comment by PicassoCT** [comment]
Sorry to have bugged you.. seems its my game.. doing something with the repo..

**Comment by abma** [comment]
i've never tested pr-downloader with curl/gnutls backend, so could be an error.

**Comment by abma** [comment]
my guess is either the cert-store is outdated or gnutls doesn't use it at all (because of some bug in pr-downloader)

**Comment by PicassoCT** [comment]
> https://springlobby.springrts.com/dl/stable/version.txt
Yes it does. I shall investigate when i have some free time on my hand

**Comment by abma** [comment]
can you provide the latest springlobby.log with the error(s) please?

**Comment by PicassoCT** [comment]
[20220313_215241-springlobby.log](https://github.com/springlobby/springlobby/files/8240671/20220313_215241-springlobby.log)

**Comment by PicassoCT** [comment]
so i fixed this with
` sudo apt-get upgrade `

- turns out i had old systemsoftware.. after i uninstalled another piece of software.
