### ISSUE TITLE
Gentoo package & documentation outdated

### ISSUE THREAD

**Issue by mfld-fr** [springlobby/springlobby#999]
Hello,
- the Gentoo package looks like outdated (https://packages.gentoo.org/packages/games-util/springlobby),
- does not compile on the current Gentoo version (https://bugs.gentoo.org/756715),
- and the Wiki (https://github.com/springlobby/springlobby/wiki/Install#Gentoo) refers `layman` but as stated in the Gentoo Wiki, `layman` is now superseded by `eselect repository` (https://wiki.gentoo.org/wiki/Layman) [**FIXED**]

Edit: the build from the latest `master` in this repository completes well on current Gentoo (updated 2021-12-18).

Maybe the solution is just to update the `ebuild` in https://github.com/springlobby/overlay/tree/master/games-util/springlobby [**DONE**] and remove the obsolete package from the Gentoo mainstream ?

**Comment by mfld-fr** [comment]
Wiki fixed in acd0db1: https://github.com/springlobby/springlobby/wiki/Install#Gentoo (revision 21).

**Comment by mfld-fr** [comment]
Update proposal of `ebuild` in 'spring' overlay : https://github.com/springlobby/overlay/pull/32

**Comment by mfld-fr** [comment]
By the way the following wiki page is outdated : https://springrts.com/wiki/Gentoo_install. I suggest to redirect from that page to https://github.com/springlobby/springlobby/wiki/Install#Gentoo, in order to avoid duplication.

**Comment by abma** [comment]
thanks, i've updated the springrts.com wiki.

**Comment by mfld-fr** [comment]
Simplification in Wiki after overlay registration: https://github.com/springlobby/springlobby/wiki/Install#Gentoo.
All remaining actions tracked in springlobby/overlay#25.
Closing this one.
